import {
  boolean,
  date,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const items = pgTable("items", {
  id: serial("id").primaryKey(),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  foreignName: text("foreign_name"),
  itemGroupCode: integer("item_group_code"),
  inventoryUom: text("inventory_uom"),
  purchaseItem: boolean("purchase_item").default(false),
  salesItem: boolean("sales_item").default(false),
  inventoryItem: boolean("inventory_item").default(false),
  defaultWarehouse: text("default_warehouse"),
  avgPrice: numeric("avg_price", { precision: 19, scale: 6 }),
  lastPurchasePrice: numeric("last_purchase_price", { precision: 19, scale: 6 }),
  lastPurchaseDate: date("last_purchase_date"),
  barcode: text("barcode"),
  frozen: boolean("frozen").default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
