export type StatusMap = Record<string, string>;

export const STATUS_MAP: StatusMap = {
  C: "Closed",
  D: "Draft",
  O: "Open",
  P: "Partial",
};

// Common field maps for document tables
export const DOC_FIELD_MAP: Record<string, string> = {
  address: "Address",
  address2: "Address2",
  attachmentEntry: "attachmentEntry",
  attachments: "Attachments",
  balanceDue: "BalanceDue",
  canceled: "canceled",
  cardCode: "CardCode",
  cardName: "CardName",
  comments: "Comments",
  counterRef: "CounterRef",
  createdAt: "createdAt",
  docCurrency: "DocCurr",
  docDate: "DocDate",
  docDueDate: "DocDueDate",
  docEntry: "DocEntry",
  docNum: "DocNum",
  docNumEnd: "DocNumEnd",
  docNumStart: "DocNumStart",
  docStatus: "DocStatus",
  docTotal: "DocTotal",
  filler: "Filler",
  jrnlMemo: "JrnlMemo",
  lines: "DocumentLines",
  numAtCard: "NumAtCard",
  paidToDate: "paidToDate",
  paymentMode: "PaymentMode",
  priceList: "PriceList",
  salesPersonCode: "SalesPersonCode",
  taxDate: "TaxDate",
  toWarehouseCode: "ToWhsCode",
  updatedAt: "updatedAt",
};

// Line item field maps
export const LINE_FIELD_MAP: Record<string, string> = {
  acctCode: "AcctCode",
  baseEntry: "BaseEntry",
  baseLine: "BaseLine",
  baseType: "BaseType",
  binAllocations: "DocumentLinesBinAllocations",
  costingCode: "CostingCode",
  discountPercent: "DiscountPercent",
  docEntry: "DocEntry",
  dscription: "Dscription",
  fromWarehouseCode: "FromWarehouseCode",
  grossTotal: "GrossTotal",
  itemCode: "ItemCode",
  itemDescription: "ItemDescription",
  lineNum: "LineNum",
  lineStatus: "LineStatus",
  lineTotal: "LineTotal",
  netTotal: "NetTotal",
  ocrCode: "OcrCode",
  openQty: "OpenQty",
  openQuantity: "OpenQuantity",
  price: "Price",
  quantity: "Quantity",
  remainingOpenQuantity: "RemainingOpenQuantity",
  requiredDate: "ReqDate",
  requiredQuantity: "RequiredQuantity",
  taxAmount: "TaxAmount",
  taxCode: "TaxCode",
  unitMsr: "unitMsr",
  unitPrice: "UnitPrice",
  uomCode: "UoMCode",
  uomEntry: "UoMEntry",
  vatGroup: "VatGroup",
  vatPercent: "VatPrcnt",
  warehouseCode: "WarehouseCode",
};

// Item master field maps
export const ITEM_FIELD_MAP: Record<string, string> = {
  avgPrice: "AvgPrice",
  barcode: "CodeBars",
  code: "ItemCode",
  defaultWarehouse: "DfltWH",
  foreignName: "FrgnName",
  frozen: "frozenFor",
  inventoryItem: "InvntItem",
  inventoryUom: "InvntryUom",
  isCommitted: "IsCommited",
  itemGroupCode: "ItmsGrpCod",
  lastPurchaseDate: "LastPurDat",
  lastPurchasePrice: "LastPurPrc",
  name: "ItemName",
  onHand: "OnHand",
  onOrder: "OnOrder",
  purchaseItem: "purchaseItem",
  salesItem: "salesItem",
};

// Fields that should be parsed to numbers
export const NUMERIC_FIELDS = new Set([
  "id",
  "DocNum",
  "DocEntry",
  "Quantity",
  "UnitPrice",
  "Price",
  "LineTotal",
  "DiscountPercent",
  "VatPrcnt",
  "OnHand",
  "IsCommited",
  "OnOrder",
  "AvgPrice",
  "LastPurPrc",
  "ItmsGrpCod",
  "LineNum",
  "BaseEntry",
  "BaseLine",
  "BaseType",
  "OpenQty",
  "RequiredQuantity",
  "UoMEntry",
  "SalesPersonCode",
  "attachmentEntry",
  "DocTotal",
  "paidToDate",
  "BalanceDue",
  "PriceList",
]);

export const DOC_STATUS_FIELDS = new Set(["DocStatus", "LineStatus"]);

// Fields that should remain camelCase even in PascalCase responses
export const KEEP_CAMELCASE = new Set([
  "paidToDate",
  "attachmentEntry",
  "canceled",
  "createdAt",
  "updatedAt",
]);
