/** usePOLookups: Manages specialized vendor and product lookups for the PO flow. */
import { useQuery } from "@tanstack/react-query";
import { useCallback, useEffect, useMemo, useState } from "react";

import { createSharedQueries as purchaseOrderCreateQueries } from "@/features/create-pages/create-shared/api/create-shared.queries";
import type { ProductLookupItem } from "@/features/create-pages/create-shared/api/create-shared.types";
import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import type { LookupOption } from "@/features/create-pages/create-shared/utils/create-order.types";
import { formatWarehouseDisplay } from "@/features/create-pages/create-shared/utils/create-order.utils";
import { rankAndLimitLookupOptions } from "@/features/create-pages/create-shared/utils/rank-lookup-options";
import type { ProductSearchFieldError } from "@/features/create-pages/purchase-order-create/utils/po-create.utils";
import type { POHeaderState } from "@/store/create/po-create.store";

import { stripAutoGeneratedReferences } from "../../create-shared/utils/auto-reference";

interface UsePoLookupsProps {
  headerWarehouseCode: string;
  setHeader: (patch: Partial<POHeaderState>) => void;
  clearFieldError: (field: keyof ProductSearchFieldError) => void;
  closeModal: () => void;
  onWarehouseSelected?: (warehouseCode: string) => void;
  productRows: any[];
  setProductRows: React.Dispatch<React.SetStateAction<any[]>>;
  headerRemarks: string;
}

export function usePoLookups({
  headerWarehouseCode,
  setHeader,
  clearFieldError,
  closeModal,
  onWarehouseSelected,
  productRows,
  setProductRows,
  headerRemarks,
}: UsePoLookupsProps) {
  const normalizeCodeForCompare = (value: unknown) => {
    const raw = String(value ?? "").trim();
    if (!raw) {
      return "";
    }
    const parsed = Number(raw);
    return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
  };

  // Master Data Queries: Backing lookups for vendors, warehouses, and sales employees.
  // Errors here are surface-propagated to the orchestrator for UI-level display.
  const vendorsQuery = useQuery(purchaseOrderCreateQueries.vendors());
  const warehousesQuery = useQuery(purchaseOrderCreateQueries.warehouses());
  const salesEmployeesQuery = useQuery(purchaseOrderCreateQueries.salesEmployees());

  const [nameInput, setNameInput] = useState("");
  const [codeInput, setCodeInput] = useState("");
  const [pendingVendorChange, setPendingVendorChange] = useState<{ vendor: LookupOption } | null>(
    null,
  );
  const [warehouseInput, setWarehouseInput] = useState("");
  const [salesEmployeeInput, setSalesEmployeeInput] = useState("");

  const [billToAddress, setBillToAddressRaw] = useState("");
  const [shipToAddress, setShipToAddressRaw] = useState("");

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value));
  }, []);
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value));
  }, []);

  const [nameFocused, setNameFocused] = useState(false);
  const [codeFocused, setCodeFocused] = useState(false);
  const [warehouseFocused, setWarehouseFocused] = useState(false);
  const [salesEmployeeFocused, setSalesEmployeeFocused] = useState(false);

  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data]);
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data]);
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data]);

  const findVendorByCode = (value: string) =>
    (vendors as ProductLookupItem[]).find(
      (vendor) => vendor.code.toLowerCase() === value.trim().toLowerCase(),
    );
  const findVendorByName = (value: string) =>
    (vendors as ProductLookupItem[]).find(
      (vendor) => vendor.name.toLowerCase() === value.trim().toLowerCase(),
    );
  const findWarehouseByCode = (value: string) =>
    (warehouses as ProductLookupItem[]).find(
      (item) => item.code.toLowerCase() === value.trim().toLowerCase(),
    );
  const findWarehouseByName = (value: string) =>
    (warehouses as ProductLookupItem[]).find(
      (item) => item.name.toLowerCase() === value.trim().toLowerCase(),
    );
  const findSalesEmployeeByCode = (value: string) =>
    (salesEmployees as ProductLookupItem[]).find(
      (item) => normalizeCodeForCompare(item.code) === normalizeCodeForCompare(value),
    );
  const findSalesEmployeeByName = (value: string) =>
    (salesEmployees as ProductLookupItem[]).find(
      (item) => item.name.toLowerCase() === value.trim().toLowerCase(),
    );

  const effectiveWarehouseCode = useMemo(() => {
    const lookup = warehouseInput.trim().toLowerCase();
    const match = lookup.match(/\[([^\]]+)\]$/) || lookup.match(/^\[([^\]]+)\]/);
    const codeOrName = match ? match[1]!.trim() : lookup;
    const matched = (warehouses as ProductLookupItem[]).find(
      (item: ProductLookupItem) =>
        item.name.toLowerCase() === codeOrName || item.code.toLowerCase() === codeOrName,
    );
    if (matched?.code) {
      return matched.code;
    }
    return (headerWarehouseCode ?? "").trim();
  }, [warehouseInput, warehouses, headerWarehouseCode]);

  const resolveVendorSalesEmployeeName = (vendor: LookupOption) => {
    const targetCode = normalizeCodeForCompare(vendor.salesEmployeeCode);
    const nameByCode =
      targetCode === ""
        ? ""
        : ((salesEmployees as ProductLookupItem[]).find(
            (item) => normalizeCodeForCompare(item.code) === targetCode,
          )?.name ?? "");
    if (nameByCode) {
      return nameByCode;
    }

    return vendor.salesEmployeeName?.trim() ?? "";
  };

  const hasCopiedRows = useMemo(() => {
    return productRows.some((row) => row.baseEntry || row.baseType);
  }, [productRows]);

  const selectVendor = (vendor: LookupOption) => {
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor });
      return;
    }
    applyVendorChange(vendor);
  };

  const applyVendorChange = (vendor: LookupOption) => {
    const nextBillToAddress = vendor.billToAddress ?? "";
    const nextShipToAddress = vendor.shipToAddress ?? "";
    const associatedSalesEmployeeName = resolveVendorSalesEmployeeName(vendor);
    setHeader({ vendorCode: vendor.code, vendorName: vendor.name });
    setNameInput(vendor.name);
    setCodeInput(vendor.code);
    setSalesEmployeeInput(associatedSalesEmployeeName);

    clearFieldError("vendorName");
    clearFieldError("vendorCode");
    if (associatedSalesEmployeeName) {
      clearFieldError("salesEmployee");
    }
    if (nextBillToAddress.trim()) {
      clearFieldError("billToAddress");
    }
    if (nextShipToAddress.trim()) {
      clearFieldError("shipToAddress");
    }

    setBillToAddress(nextBillToAddress);
    setShipToAddress(nextShipToAddress);
    setNameFocused(false);
    setCodeFocused(false);
    closeModal();
  };

  const confirmVendorChange = () => {
    const pending = pendingVendorChange;
    if (!pending) return;
    setPendingVendorChange(null);

    const cleanedRemarks = stripAutoGeneratedReferences(headerRemarks);
    setHeader({ comments: cleanedRemarks });

    setProductRows((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row;
        return rest;
      }),
    );

    applyVendorChange(pending.vendor);
  };

  const cancelVendorChange = () => {
    setPendingVendorChange(null);
  };

  const selectWarehouse = (item: { code: string; name: string }) => {
    setWarehouseInput(formatWarehouseDisplay(item.name, item.code));
    setHeader({ warehouseCode: item.code });
    clearFieldError("warehouseCode");
    // Do not prefetch full OITM — products load only after vendor CardCode (OSCN).
    setWarehouseFocused(false);
    onWarehouseSelected?.(item.code);
    closeModal();
  };

  const selectSalesEmployee = (item: { code: string; name: string }) => {
    setSalesEmployeeInput(item.name);
    clearFieldError("salesEmployee");
    setSalesEmployeeFocused(false);
    closeModal();
  };

  // Handlers
  const handleVendorNameChange = (value: string) => {
    setNameInput(value);
    clearFieldError("vendorName");
    if (value.trim() === "") {
      setNameFocused(true);
      setHeader({ vendorCode: "", vendorName: "" });
      setSalesEmployeeInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = findVendorByName(value);
    if (matched) {
      selectVendor(matched);
      return;
    }
    setSalesEmployeeInput("");
    setBillToAddress("");
    setShipToAddress("");
    setNameFocused(true);
    setHeader({ vendorCode: "", vendorName: value });
  };

  const handleVendorCodeChange = (value: string) => {
    setCodeInput(value);
    clearFieldError("vendorCode");
    if (value.trim() === "") {
      setCodeFocused(true);
      setHeader({ vendorCode: "", vendorName: "" });
      setSalesEmployeeInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = findVendorByCode(value);
    if (matched) {
      selectVendor(matched);
      return;
    }
    setSalesEmployeeInput("");
    setBillToAddress("");
    setShipToAddress("");
    setCodeFocused(true);
    setHeader({ vendorCode: value, vendorName: "" });
  };

  const handleWarehouseChange = (value: string) => {
    setWarehouseInput(value);
    clearFieldError("warehouseCode");
    if (value.trim() === "") {
      setWarehouseFocused(true);
      setHeader({ warehouseCode: "" });
      return;
    }
    const matched = findWarehouseByName(value) ?? findWarehouseByCode(value);
    if (matched) {
      selectWarehouse(matched);
      return;
    }
    setHeader({ warehouseCode: "" });
  };

  const handleSalesEmployeeChange = (value: string) => {
    setSalesEmployeeInput(value);
    clearFieldError("salesEmployee");
    if (!value.trim()) {
      setSalesEmployeeFocused(true);
      return;
    }
    const matched = findSalesEmployeeByName(value) ?? findSalesEmployeeByCode(value);
    if (matched) {
      selectSalesEmployee(matched);
      return;
    }
    setSalesEmployeeFocused(true);
  };

  const nameSuggestions = useMemo(() => {
    return rankAndLimitLookupOptions(vendors as ProductLookupItem[], nameInput);
  }, [vendors, nameInput]);

  const codeSuggestions = useMemo(() => {
    return rankAndLimitLookupOptions(vendors as ProductLookupItem[], codeInput);
  }, [vendors, codeInput]);

  const warehouseSuggestions = useMemo(() => {
    return rankAndLimitLookupOptions(warehouses as ProductLookupItem[], warehouseInput);
  }, [warehouses, warehouseInput]);

  const salesEmployeeSuggestions = useMemo(() => {
    return rankAndLimitLookupOptions(salesEmployees as ProductLookupItem[], salesEmployeeInput);
  }, [salesEmployees, salesEmployeeInput]);

  // Robust Name Resolver for Hydration & Copy-From flows
  useEffect(() => {
    if (headerWarehouseCode && warehouses.length > 0) {
      const matched = warehouses.find(
        (w) => String(w.code).trim() === String(headerWarehouseCode).trim(),
      );
      if (matched && warehouseInput !== formatWarehouseDisplay(matched.name, matched.code)) {
        setWarehouseInput(formatWarehouseDisplay(matched.name, matched.code));
      }
    }
  }, [headerWarehouseCode, warehouses, warehouseInput]);

  const resetWarehouse = useCallback(() => {
    setWarehouseInput("");
    setHeader({ warehouseCode: "" });
    setWarehouseFocused(false);
    clearFieldError("warehouseCode");
  }, [setHeader, clearFieldError]);

  return {
    billToAddress,
    codeFocused,
    codeInput,
    codeSuggestions,
    effectiveWarehouseCode,
    findVendorByCode,
    findVendorByName,
    findWarehouseByCode,
    findWarehouseByName,
    handleSalesEmployeeChange,
    handleVendorCodeChange,
    handleVendorNameChange,
    handleWarehouseChange,
    nameFocused,
    nameInput,
    nameSuggestions,
    salesEmployeeFocused,
    salesEmployeeInput,
    salesEmployeeSuggestions,
    salesEmployees,
    salesEmployeesQuery,
    selectSalesEmployee,
    selectVendor,
    selectWarehouse,
    setBillToAddress,
    setCodeFocused,
    setCodeInput,
    setNameFocused,
    setNameInput,
    setSalesEmployeeFocused,
    setSalesEmployeeInput,
    setShipToAddress,
    setWarehouseFocused,
    setWarehouseInput,
    shipToAddress,
    vendors,
    vendorsQuery,
    warehouseFocused,
    warehouseInput,
    warehouseSuggestions,
    warehouses,
    warehousesQuery,
    resetWarehouse,
    pendingVendorChange,
    confirmVendorChange,
    cancelVendorChange,
  };
}
