/** usePurchaseOrderCreate: State and logic for creating/updating purchase orders. */
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { AttachmentItem } from "@/features/create-pages/create-shared/components/grids/upload-grid";

import type { ProductLookupItem } from "@/features/create-pages/create-shared/api/create-shared.types";
import {
  getMissingMandatoryCreateFieldsTyped,
  PURCHASE_ORDER_MANDATORY_FIELDS,
} from "@/features/create-pages/create-shared/config/create-mandatory-fields";
import {
  calculateOrderTotals,
  calculateSummaryCurrency,
} from "@/features/create-pages/create-shared/utils/create-order.calculations";
import { resolveDocumentLineDiscount } from "@/features/create-pages/create-shared/utils/resolve-document-line-discount";
import {
  resolveHydrateProductMeta,
  scheduleHydrateWarehouseStocks,
} from "@/features/create-pages/create-shared/utils/hydrate-product-meta";
import {
  clipSapText,
  SAP_FIELD_MAX,
  sapCommentsField,
} from "@/features/create-pages/create-shared/utils/sap-document-fields";
import { parseDocumentHeaderNotes } from "@/features/create-pages/create-shared/utils/parse-header-notes";
import type {
  ActiveDatePicker,
  PopupMode,
  ProductRow,
} from "@/features/create-pages/create-shared/utils/create-order.types";
import {
  formatWarehouseDisplay,
  normalizeCreateOrderErrorMessage,
} from "@/features/create-pages/create-shared/utils/create-order.utils";
import {
  dismissDocumentHydrating,
  notifyCreateApiError,
  notifyDocumentHydrateError,
  notifyDocumentHydrating,
  notifyEditRestrictedField,
} from "@/features/create-pages/create-shared/utils/create-feedback-toast";
import {
  isPqRfqCopyAllowed,
  PQ_RFQ_COPY_BLOCKED_MESSAGE,
} from "@/features/create-pages/create-shared/utils/pq-rfq-copy";
import { useDocumentSaveActions } from "@/features/create-pages/create-shared/hooks/use-document-save-actions";
import { useDocumentBranchField } from "@/features/create-pages/create-shared/hooks/use-document-branch-field";
import { useDocumentSeriesField } from "@/features/create-pages/create-shared/hooks/use-document-series-field";
import { documentBranchPayload } from "@/features/create-pages/create-shared/utils/document-branch";
import {
  documentSeriesPayload,
  SAP_SERIES_OBJECT,
  toPositiveSeries,
} from "@/features/create-pages/create-shared/utils/document-series";
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from "@/features/create-pages/create-shared/utils/lookup-search-sync";
import {
  useCreatePurchaseOrder,
  useUpdatePurchaseOrder,
} from "@/features/create-pages/purchase-order-create/api/purchase-order-create.mutations";
import {
  EMPTY_PRODUCT_SEARCH_FIELD_ERRORS,
  MANDATORY_ERROR_TEXT,
  REQUIRED_FIELD_LABEL_TEXT,
} from "@/features/create-pages/purchase-order-create/utils/po-create.utils";
import type { ProductSearchFieldError } from "@/features/create-pages/purchase-order-create/utils/po-create.utils";
import {
  purchaseOrderKeys,
  purchaseOrderQueries,
} from "@/features/table-pages/purchase-orders/api/purchase-order.queries";
import type { PurchaseOrderDetailLine } from "@/features/table-pages/purchase-orders/api/purchase-order.service";
import {
  purchaseQuotationKeys,
  purchaseQuotationQueries,
} from "@/features/table-pages/purchase-quotations/api/purchase-quotation.queries";
import {
  usePOHeader,
  useResetPOCreateAction,
  useSetPOHeaderAction,
} from "@/store/create/po-create.store";

import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import {
  generateSingleSourceReference,
  isAutoGeneratedRemarkLine,
} from "../../create-shared/utils/auto-reference";
import { usePoLookups } from "./use-po-lookups";
import { usePoModals } from "./use-po-modals";
import { usePoProducts } from "./use-po-products";

type PurchaseOrderCreateMode = "create" | "edit";

interface UsePurchaseOrderCreateOptions {
  mode?: PurchaseOrderCreateMode;
  docNum?: string;
  sourceDocNum?: string | undefined;
  sourceDocType?: "PurchaseQuotation" | undefined;
  draftDocNum?: string | undefined;
  draftDocEntry?: string | undefined;
  onCreateSuccess?: () => void;
}

export function usePurchaseOrderCreate(options?: UsePurchaseOrderCreateOptions) {
  const sourceDocNum = options?.sourceDocNum;
  const sourceDocType = options?.sourceDocType;
  const [sourceHydrationComplete, setSourceHydrationComplete] = useState(false);
  const normalizeCodeForCompare = (value: unknown) => {
    const raw = String(value ?? "").trim();
    if (!raw) {
      return "";
    }
    const parsed = Number(raw);
    return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
  };

  const parsePurchaseOrderHeaderNotes = parseDocumentHeaderNotes;

  const mode = options?.mode ?? "create";
  const isEditMode = mode === "edit";
  const header = usePOHeader();
  const resetPOCreate = useResetPOCreateAction();
  const setHeader = useSetPOHeaderAction();
  const queryClient = useQueryClient();
  const [productRows, setProductRows] = useState<ProductRow[]>([]);
  const createPurchaseOrderMutation = useCreatePurchaseOrder();
  const updatePurchaseOrderMutation = useUpdatePurchaseOrder();

  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);

  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null);
  const [formSnapshot, setFormSnapshot] = useState<any>(null);
  const [productSearchFieldErrors, setProductSearchFieldErrors] = useState<ProductSearchFieldError>(
    EMPTY_PRODUCT_SEARCH_FIELD_ERRORS,
  );
  const [createError, setCreateError] = useState<string | null>(null);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [attachments, setAttachments] = useState<AttachmentItem[]>([]);
  const hydratedDocNumRef = useRef<string | null>(null);
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null);

  const editDocNum = (options?.docNum ?? "").trim();
  const draftDocNum = (options?.draftDocNum ?? "").trim();
  const draftDocEntry = (options?.draftDocEntry ?? "").trim();
  const fetchDocNum = isEditMode ? editDocNum : draftDocNum;

  const docDateContainerRef = useRef<HTMLDivElement>(null);
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null);

  const modals = usePoModals();

  const notifyRestricted = (fieldName = "Field") => {
    notifyEditRestrictedField(fieldName);
  };

  const clearFieldError = useCallback((field: keyof ProductSearchFieldError) => {
    setProductSearchFieldErrors((prev) => ({ ...prev, [field]: undefined }));
  }, []);

  const lookups = usePoLookups({
    clearFieldError,
    closeModal: () => modals.setModalOpen(false),
    headerWarehouseCode: header.warehouseCode ?? "",
    setHeader,
    onWarehouseSelected: (warehouseCode: string) => {
      setProductRows((prev) =>
        prev.map((row) => ({
          ...row,
          warehouseCode,
        })),
      );
    },
    productRows,
    setProductRows,
    headerRemarks: header.comments ?? "",
  });

  const setBranchId = useCallback(
    (branchId: number | null) => {
      setHeader({ branchId });
    },
    [setHeader],
  );

  const branchField = useDocumentBranchField({
    warehouses: lookups.warehouses as Array<{
      code: string;
      name?: string;
      branchId?: number | null;
    }>,
    warehouseCode: header.warehouseCode ?? lookups.effectiveWarehouseCode,
    branchId: header.branchId,
    setBranchId,
    disabled: false,
  });

  const setSeries = useCallback(
    (series: number | null) => {
      setHeader({ series });
    },
    [setHeader],
  );

  const seriesField = useDocumentSeriesField({
    objectCode: SAP_SERIES_OBJECT.purchaseOrder,
    branchId: header.branchId ?? branchField.effectiveBranchId,
    series: header.series,
    setSeries,
    disabled: isEditMode,
    lockSuggestion: isEditMode,
  });

  const productsHook = usePoProducts({
    effectiveWarehouseCode: lookups.effectiveWarehouseCode,
    isEditMode,
    productPopupOpen: modals.productPopupOpen,
    productSearch: modals.productSearch,
    setProductPopupOpen: modals.setProductPopupOpen,
    setProductSearch: modals.setProductSearch,
    stockPreviewProductCode: modals.stockPreviewProduct?.code,
    vendorCardCode: header.vendorCode || lookups.codeInput.trim() || undefined,
    vendorLookupToken: `${lookups.codeInput.trim().toLowerCase()}::${lookups.nameInput.trim().toLowerCase()}`,
    vendorSelected: Boolean(lookups.codeInput || lookups.nameInput),
    productRows,
    setProductRows,
  });

  useEffect(() => {
    if (!isEditMode && !draftDocNum) {
      resetPOCreate();
      hydratedDocNumRef.current = null;
      setHydratedDocNum(null);
    }
    return () => {
      resetPOCreate();
      lookups.resetWarehouse();
    };
  }, [isEditMode, draftDocNum, resetPOCreate, lookups.resetWarehouse]);

  const resetForm = useCallback(() => {
    resetPOCreate();
    setSubmitAttempted(false);
    lookups.setNameInput("");
    lookups.setCodeInput("");
    lookups.resetWarehouse();
    lookups.setSalesEmployeeInput("");
    lookups.setBillToAddress("");
    lookups.setShipToAddress("");
    lookups.setNameFocused(false);
    lookups.setCodeFocused(false);
    lookups.setSalesEmployeeFocused(false);
    setActiveDatePicker(null);
    modals.setModalOpen(false);
    modals.setModalMode("vendor-name");
    modals.setModalSearch("");
    productsHook.setProductRows([]);
    productsHook.setProductRowDrafts({});
    setProductSearchFieldErrors(EMPTY_PRODUCT_SEARCH_FIELD_ERRORS);
    modals.setProductSearch("");
    productsHook.setDebouncedProductSearch("");
    productsHook.setActiveProductRowId(null);
    modals.setProductPopupOpen(false);
    modals.setStockPreviewProduct(null);
    setCreateError(null);
    setHydratedDocNum(null);
    setFormSnapshot(null);
    setAttachments([]);
  }, [
    resetPOCreate,
    lookups,
    modals,
    productsHook,
    setSubmitAttempted,
    setActiveDatePicker,
    setProductSearchFieldErrors,
    setCreateError,
    setHydratedDocNum,
  ]);

  const editDetailQuery = useQuery({
    ...purchaseOrderQueries.detailByDocNum(fetchDocNum, isEditMode ? undefined : draftDocEntry),
    enabled: (isEditMode && Boolean(editDocNum)) || Boolean(draftDocNum),
  });

  useEffect(() => {
    if (!isEditMode && !draftDocNum) {
      return;
    }
    const hydrationKey = isEditMode ? editDocNum : `${draftDocNum}_${draftDocEntry ?? ""}`;
    const currentDocNum = fetchDocNum;
    if (!hydrationKey || hydratedDocNumRef.current === hydrationKey) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    const vendorCode = String(detail.CardCode ?? "").trim();
    const vendorName = String(detail.CardName ?? "").trim();
    const matchedVendor = lookups.vendors.find((vendor) => String(vendor.code) === vendorCode);
    const warehouseCode = String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
    const matchedWarehouse = lookups.warehouses.find((item) => String(item.code) === warehouseCode);
    const salesEmployeeNameFromDocCode =
      detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
        ? lookups.salesEmployees.find(
            (item) =>
              normalizeCodeForCompare(item.code) ===
              normalizeCodeForCompare(detail.SalesPersonCode),
          )?.name
        : "";
    const associatedSalesEmployeeName =
      salesEmployeeNameFromDocCode ||
      (matchedVendor?.salesEmployeeCode !== undefined
        ? lookups.salesEmployees.find(
            (item) =>
              normalizeCodeForCompare(item.code) ===
              normalizeCodeForCompare(matchedVendor.salesEmployeeCode),
          )?.name
        : "") ||
      matchedVendor?.salesEmployeeName?.trim() ||
      "";

    const { comments, referenceNo } = parsePurchaseOrderHeaderNotes(detail);

    const docDate = String(detail.DocDate ?? "").slice(0, 10);
    const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);
    const billToAddress = String(detail.Address ?? "").trim();
    const shipToAddress = String((detail as Record<string, unknown>).Address2 ?? "").trim();

    notifyDocumentHydrating("purchase-order", "Loading purchase order…");
    void (async () => {
      try {
        const detailLines = detail.DocumentLines ?? [];
        const uniqueItemCodes = [
          ...new Set(detailLines.map((line) => String(line.ItemCode ?? "").trim())),
        ].filter(Boolean);

        const vendorCode = String(detail.CardCode ?? "").trim();
        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          uniqueItemCodes,
          "purchase",
          { cardCode: vendorCode || undefined },
        );
        const stockByItemCode = new Map<string, number>();

        const mappedRows = detailLines.map((line: PurchaseOrderDetailLine, index) => {
          const lineData = line as Record<string, unknown>;
          const itemCode = String(line.ItemCode ?? "").trim();
          const productMeta = productByCode.get(itemCode);
          const quantity = Number(line.Quantity ?? 1);
          const openQty = Number(line.OpenQty ?? quantity);
          const price = Number(line.Price ?? line.UnitPrice ?? productMeta?.price ?? 0);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount: Math.max(0, price * quantity),
            headerDiscountPercent: Number((detail as Record<string, unknown>).DiscountPercent ?? 0),
            line: line as Record<string, unknown>,
          });
          // SAP line VatPrcnt is authoritative; fall back to product master only when missing
          const sapVatPrcnt = Number(line.VatPrcnt ?? 0);

          return {
            comment: "",
            currency: String(detail.DocCurr ?? productMeta?.currency ?? ""),
            discountAmount,
            discountPercent,
            id: `row-${currentDocNum}-${index}`,
            lineNum: typeof line.LineNum === "number" ? line.LineNum : index,
            openQty,
            price,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? productMeta?.name ?? "").trim(),
            quantity,
            selected: false,
            stock: Number(stockByItemCode.get(itemCode) ?? productMeta?.stock ?? 0),
            taxRate: sapVatPrcnt > 0 ? sapVatPrcnt : Number(productMeta?.taxRate ?? 0),
            uomCode: (() => {
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) return code;
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) {
                const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                if (match?.code) return match.code;
              }
              return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
            })(),
            uomEntry: (() => {
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) return entry;
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) {
                const match = productMeta?.uomList?.find((u) => u.code === code);
                if (match?.uomEntry !== undefined) return match.uomEntry;
              }
              return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
            })(),
            purchaseUomCode: productMeta?.purchaseUomCode,
            purchaseUomEntry: productMeta?.purchaseUomEntry,
            salesUomCode: productMeta?.uomCode,
            salesUomEntry: productMeta?.uomEntry,
            uomList: productMeta?.uomList,
            vatGroup: String(line.VatGroup ?? line.TaxCode ?? productMeta?.vatGroup ?? "").trim(),
            warehouseCode: String(line.WarehouseCode ?? "").trim(),
          };
        });

        setHeader({
          comments,
          docDate: docDate || header.docDate,
          docDueDate,
          referenceNo,
          series: toPositiveSeries((detail as Record<string, unknown>).Series),
          vendorCode,
          vendorName,
          warehouseCode,
        });
        lookups.setNameInput(vendorName);
        lookups.setCodeInput(vendorCode);
        lookups.setWarehouseInput(
          formatWarehouseDisplay(matchedWarehouse?.name ?? warehouseCode, warehouseCode),
        );
        lookups.setSalesEmployeeInput(associatedSalesEmployeeName);
        lookups.setBillToAddress(billToAddress);
        lookups.setShipToAddress(shipToAddress);
        productsHook.setProductRows(mappedRows);
        productsHook.setProductRowDrafts({});

        scheduleHydrateWarehouseStocks(queryClient, uniqueItemCodes, warehouseCode, (stocks) => {
          productsHook.setProductRows((prev) =>
            prev.map((row) => {
              const nextStock = stocks.get(row.productCode);
              return nextStock === undefined || nextStock === row.stock
                ? row
                : { ...row, stock: nextStock };
            }),
          );
        });

        const rawAttachments = detail.attachments || [];
        setAttachments(
          rawAttachments.map((item: any, idx: number) => ({
            id: `loaded-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );

        setFormSnapshot({
          comments: comments.trim(),
          referenceNo: referenceNo.trim(),
          docDueDate: docDueDate,
          salesEmployee: associatedSalesEmployeeName.trim(),
          warehouseCode: warehouseCode.trim(),
          billToAddress: formatAddressForDisplay(billToAddress).trim(),
          shipToAddress: formatAddressForDisplay(shipToAddress).trim(),
          attachments: rawAttachments.map((item: any) => ({
            fileName: item.fileName,
            freeText: item.freeText || item.remarks || "",
          })),
          productRows: mappedRows
            .filter((row) => row.productCode.trim() && row.quantity > 0)
            .map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
        });

        hydratedDocNumRef.current = hydrationKey;
        setHydratedDocNum(hydrationKey);
      } finally {
        dismissDocumentHydrating("purchase-order");
      }
    })();
  }, [
    queryClient,
    editDetailQuery.data,
    header.docDate,
    isEditMode,
    draftDocNum,
    draftDocEntry,
    lookups,
    editDocNum,
    fetchDocNum,
    productsHook,
    setHeader,
  ]);

  // Copy-From Hydration (Purchase Quotation as source)
  useEffect(() => {
    if (isEditMode || draftDocNum) {
      return;
    }
    if (!sourceDocNum || !sourceDocType || sourceDocType !== "PurchaseQuotation") {
      hydratedDocNumRef.current = null;
      setSourceHydrationComplete(false);
      return;
    }
    const sourceDocNums = sourceDocNum
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (sourceDocNums.length === 0) {
      return;
    }
    const isMetadataLoaded = lookups.vendors.length > 0 && lookups.salesEmployees.length > 0;
    const hydrationKey = `${sourceDocType}-${sourceDocNum}`;
    if (hydratedDocNumRef.current === hydrationKey && isMetadataLoaded) {
      return;
    }
    const fetchAllSources = async () => {
      try {
        const details = await Promise.all(
          sourceDocNums.map(async (num) => {
            const res = await queryClient.fetchQuery(purchaseQuotationQueries.detailByDocNum(num));
            return res.data;
          }),
        );
        const allowedDetails = details.filter((detail) => isPqRfqCopyAllowed(detail));
        if (allowedDetails.length === 0) {
          if (isMetadataLoaded) {
            hydratedDocNumRef.current = hydrationKey;
          }
          notifyDocumentHydrateError("po", PQ_RFQ_COPY_BLOCKED_MESSAGE);
          return;
        }

        const primaryDetail = allowedDetails[0]!;
        const vendorCode = String(primaryDetail.CardCode ?? "").trim();
        const vendorName = String(primaryDetail.CardName ?? "").trim();
        const matchedVendor = lookups.vendors.find((v) => String(v.code).trim() === vendorCode);
        const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
        const matchedWarehouse = lookups.warehouses.find(
          (w) => String(w.code).trim() === warehouseCode,
        );

        const buyerFromDocCode =
          primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
            ? lookups.salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(primaryDetail.SalesPersonCode),
              )?.name
            : "";
        const buyerName = buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "";

        const sourceComments = String(primaryDetail.Comments ?? "").trim();
        // Auto remarks: "Based on PQ <DocNum>" (source PQ number always included)
        const refs = sourceDocNums.map((num) =>
          generateSingleSourceReference(sourceDocType, String(num).trim(), vendorCode),
        );
        const autoReference = refs.length === 1 ? refs[0]! : refs.join("\n");
        const commentLines = sourceComments
          .split("\n")
          .map((l) => l.trim())
          .filter(Boolean);
        const refLinesFromComments = commentLines.filter((line) => isAutoGeneratedRemarkLine(line));
        const userRemarks = commentLines
          .filter((line) => !isAutoGeneratedRemarkLine(line))
          .join("\n")
          .trim();
        // Prefer new Based on PQ lines; drop older auto lines that already name the same source PQ(s)
        const sourceNums = new Set(sourceDocNums.map((n) => String(n).trim()).filter(Boolean));
        const keptChain = refLinesFromComments.filter((line) => {
          const m = line.match(/(?:^|\bbased on\s+)(PQD|PQ|RFQ|SQ|PO|AR)\s*:?\s+(\S+)/i);
          if (!m?.[1] || !m[2]) {
            return true;
          }
          const key = m[1].toUpperCase() === "PQD" ? "PQ" : m[1].toUpperCase();
          if (key === "PQ" && sourceNums.has(m[2].trim())) {
            return false;
          }
          return true;
        });
        const remarksParts = [keptChain.join("\n"), autoReference, userRemarks]
          .filter(Boolean)
          .join("\n")
          .trim();

        const sourceNumAtCard = String(
          (primaryDetail as { NumAtCard?: string }).NumAtCard ?? "",
        ).trim();
        const docDueDate = String(primaryDetail.DocDueDate ?? "").slice(0, 10);
        const resolvedHeaderDiscountPercent = Number(
          (primaryDetail as Record<string, unknown>).DiscountPercent ?? 0,
        );

        const allDetailLines = allowedDetails.flatMap((d) => d.DocumentLines ?? []);
        const uniqueItemCodes = [
          ...new Set(allDetailLines.map((line) => String(line.ItemCode ?? "").trim())),
        ].filter(Boolean);

        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          uniqueItemCodes,
          "purchase",
          { cardCode: vendorCode || undefined },
        );
        const stockByItemCode = new Map<string, number>();

        const baseType = 540000006;
        let lineIndex = 0;
        const mappedRows = allowedDetails.flatMap((detail, docIdx) => {
          const detailLines = detail.DocumentLines ?? [];
          return detailLines.map((line: PurchaseOrderDetailLine) => {
            const idx = lineIndex++;
            const itemCode = String(line.ItemCode ?? "").trim();
            const lineWarehouseCode = String(line.WarehouseCode ?? "").trim();
            const lineData = line as Record<string, unknown>;
            // For Purchase Quotation sources (baseType 540000006), the user-entered
            // quantity lives in PQT1.PQTReqQty (Service Layer: RequiredQuantity),
            // while PQT1.Quantity stays 0. Prefer RequiredQuantity as a fallback
            // so the copied-to PO receives the same quantity the user requested.
            const openQty = Number(
              (line as { OpenQty?: number }).OpenQty ??
                (line as { RemainingOpenQuantity?: number }).RemainingOpenQuantity ??
                lineData.RequiredQuantity ??
                lineData.requiredQuantity ??
                line.Quantity ??
                1,
            );
            const quantity = openQty;
            const price = Number(line.Price ?? line.UnitPrice ?? 0);
            const grossAmount = Math.max(0, price * quantity);
            const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
              grossAmount,
              headerDiscountPercent: resolvedHeaderDiscountPercent,
              line: line as unknown as Record<string, unknown>,
            });
            const sapVatPrcnt = Number(line.VatPrcnt ?? 0);
            const productMeta = productByCode.get(itemCode);

            return {
              baseEntry: detail.DocEntry ?? (detail as { id?: number }).id,
              baseLine: line.LineNum ?? idx,
              baseQuantity: quantity,
              baseType,
              comment: "",
              currency: String(primaryDetail.DocCurr ?? productMeta?.currency ?? ""),
              discountAmount,
              discountPercent,
              id: `row-copy-${sourceDocNums[docIdx] ?? "unknown"}-${idx}`,
              lineNum: typeof line.LineNum === "number" ? line.LineNum : idx,
              openQty,
              price,
              productCode: itemCode,
              productName: String(line.ItemDescription ?? productMeta?.name ?? itemCode).trim(),
              quantity,
              selected: false,
              stock: Number(stockByItemCode.get(itemCode) ?? productMeta?.stock ?? 0),
              taxRate: sapVatPrcnt > 0 ? sapVatPrcnt : Number(productMeta?.taxRate ?? 0),
              uomCode: (() => {
                const code = String(
                  lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
                ).trim();
                if (code) return code;
                const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
                if (Number.isFinite(entry) && entry > 0) {
                  const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                  if (match?.code) return match.code;
                }
                return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
              })(),
              uomEntry: (() => {
                const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
                if (Number.isFinite(entry) && entry > 0) return entry;
                const code = String(
                  lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
                ).trim();
                if (code) {
                  const match = productMeta?.uomList?.find((u) => u.code === code);
                  if (match?.uomEntry !== undefined) return match.uomEntry;
                }
                return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
              })(),
              purchaseUomCode: productMeta?.purchaseUomCode,
              purchaseUomEntry: productMeta?.purchaseUomEntry,
              salesUomCode: productMeta?.uomCode,
              salesUomEntry: productMeta?.uomEntry,
              uomList: productMeta?.uomList,
              vatGroup: String(line.VatGroup ?? line.TaxCode ?? productMeta?.vatGroup ?? "").trim(),
              warehouseCode: lineWarehouseCode,
            };
          });
        });

        setHeader({
          comments: clipSapText(remarksParts, SAP_FIELD_MAX.comments),
          docDate: header.docDate,
          docDueDate,
          referenceNo: sourceNumAtCard,
          vendorCode,
          vendorName,
          warehouseCode: matchedWarehouse?.code ?? warehouseCode,
        });
        lookups.setNameInput(vendorName);
        lookups.setCodeInput(vendorCode);
        lookups.setWarehouseInput(
          formatWarehouseDisplay(matchedWarehouse?.name ?? warehouseCode, warehouseCode),
        );
        lookups.setSalesEmployeeInput(buyerName);
        const targetBillTo =
          String(primaryDetail.Address ?? "").trim() || matchedVendor?.billToAddress || "";
        const targetShipTo =
          String((primaryDetail as Record<string, unknown>).Address2 ?? "").trim() ||
          matchedVendor?.shipToAddress ||
          matchedVendor?.billToAddress ||
          "";
        lookups.setBillToAddress(targetBillTo);
        lookups.setShipToAddress(targetShipTo);
        productsHook.setProductRows(mappedRows);
        productsHook.setProductRowDrafts({});

        scheduleHydrateWarehouseStocks(queryClient, uniqueItemCodes, warehouseCode, (stocks) => {
          productsHook.setProductRows((prev) =>
            prev.map((row) => {
              const nextStock = stocks.get(row.productCode);
              return nextStock === undefined || nextStock === row.stock
                ? row
                : { ...row, stock: nextStock };
            }),
          );
        });

        const sourceAttachments = primaryDetail.attachments || [];
        setAttachments(
          sourceAttachments.map((item: any, idx: number) => ({
            id: `copy-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );

        if (isMetadataLoaded) {
          hydratedDocNumRef.current = hydrationKey;
        }
        setSourceHydrationComplete(true);
      } catch {
      } finally {
      }
    };

    void fetchAllSources();
  }, [
    isEditMode,
    sourceDocNum,
    sourceDocType,
    queryClient,
    lookups,
    header.docDate,
    productsHook,
    setHeader,
  ]);

  const popupResults = useMemo(() => {
    const term = modals.modalSearch.trim().toLowerCase();
    const source = (
      modals.modalMode === "vendor-name" || modals.modalMode === "vendor-code"
        ? lookups.vendors
        : modals.modalMode === "warehouse"
          ? lookups.warehouses
          : modals.modalMode === "branch"
            ? branchField.branches
            : modals.modalMode === "series"
              ? seriesField.seriesList
              : lookups.salesEmployees
    ) as ProductLookupItem[];
    if (!term) {
      return source;
    }
    const score = (item: ProductLookupItem) => {
      const code = (item.code || "").toLowerCase();
      const name = (item.name || "").toLowerCase();
      if (code === term || name === term) {
        return 0;
      }
      if (code.startsWith(term) || name.startsWith(term)) {
        return 1;
      }
      if (code.includes(term) || name.includes(term)) {
        return 2;
      }
      return 3;
    };
    return [...source].toSorted((a, b) => {
      const byScore = score(a) - score(b);
      if (byScore !== 0) {
        return byScore;
      }
      return a.code.localeCompare(b.code, undefined, {
        numeric: true,
        sensitivity: "base",
      });
    });
  }, [
    lookups.vendors,
    lookups.warehouses,
    lookups.salesEmployees,
    branchField.branches,
    seriesField.seriesList,
    modals.modalSearch,
    modals.modalMode,
  ]);

  const openPopupWithContext = (mode: PopupMode) => {
    modals.openPopup(mode, {
      branchInput: branchField.branchInput,
      codeInput: lookups.codeInput,
      nameInput: lookups.nameInput,
      salesEmployeeInput: lookups.salesEmployeeInput,
      seriesInput: seriesField.seriesInput,
      warehouseInput: lookups.warehouseInput,
    });
  };

  useEffect(() => {
    if (!modals.modalOpen) {
      return;
    }
    const nextSearch = getLookupInlineSearchByMode(modals.modalMode, {
      branch: branchField.branchInput,
      salesEmployee: lookups.salesEmployeeInput,
      series: seriesField.seriesInput,
      vendorCode: lookups.codeInput,
      vendorName: lookups.nameInput,
      warehouse: lookups.warehouseInput,
    });
    if (nextSearch !== modals.modalSearch) {
      modals.setModalSearch(nextSearch);
    }
  }, [
    branchField.branchInput,
    seriesField.seriesInput,
    lookups.codeInput,
    lookups.nameInput,
    lookups.salesEmployeeInput,
    lookups.warehouseInput,
    modals,
  ]);

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onBranch: branchField.handleBranchChange,
      onSalesEmployee: lookups.handleSalesEmployeeChange,
      onSeries: seriesField.handleSeriesChange,
      onVendorCode: lookups.handleVendorCodeChange,
      onVendorName: lookups.handleVendorNameChange,
      onWarehouse: lookups.handleWarehouseChange,
    });

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (!activeDatePicker) {
        return;
      }
      const target = event.target as Node;
      const insideDoc = docDateContainerRef.current?.contains(target);
      const insideDelivery = deliveryDateContainerRef.current?.contains(target);
      if (!insideDoc && !insideDelivery) {
        setActiveDatePicker(null);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [activeDatePicker]);

  const handleOpenProductPopup = (rowId: string | null = null) => {
    const existingRow = rowId ? productsHook.productRows.find((r) => r.id === rowId) : null;
    const initialSearch = existingRow ? existingRow.productName : "";

    productsHook.openProductPopup(rowId, initialSearch, {
      onValidateBeforeOpen: () => {
        const nextErrors: ProductSearchFieldError = {
          ...EMPTY_PRODUCT_SEARCH_FIELD_ERRORS,
        };
        if (!lookups.nameInput.trim()) {
          nextErrors.vendorName = "Vendor Name is required.";
        }
        if (!lookups.codeInput.trim()) {
          nextErrors.vendorCode = "Vendor Code is required.";
        }
        return nextErrors;
      },
      onValidationFailed: (errors) => setProductSearchFieldErrors(errors),
    });
  };

  // Create & Validation computations
  const createMandatoryValues = useMemo(
    () => ({
      vendorCode: lookups.codeInput.trim() || header.vendorCode.trim(),
      vendorName: lookups.nameInput.trim() || header.vendorName.trim(),
      // Check if ANY row has a warehouseCode selected (row-level warehouse)
      warehouseCode: productsHook.productRows.some((row) => row.warehouseCode?.trim())
        ? lookups.effectiveWarehouseCode.trim() || "selected"
        : lookups.effectiveWarehouseCode.trim(),
      docDueDate: header.docDueDate,
      salesEmployee: lookups.salesEmployeeInput.trim(),
      billToAddress: lookups.billToAddress.trim(),
      shipToAddress: lookups.shipToAddress.trim(),
      referenceNo: header.referenceNo.trim(),
      comments: header.comments.trim(),
    }),
    [
      lookups.codeInput,
      header.vendorCode,
      lookups.nameInput,
      header.vendorName,
      lookups.effectiveWarehouseCode,
      header.docDueDate,
      lookups.salesEmployeeInput,
      lookups.billToAddress,
      lookups.shipToAddress,
      header.referenceNo,
      header.comments,
      productsHook.productRows,
    ],
  );

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) {
      return [];
    }
    return getMissingMandatoryCreateFieldsTyped(
      createMandatoryValues,
      PURCHASE_ORDER_MANDATORY_FIELDS,
    );
  }, [isEditMode, createMandatoryValues]);

  const searchMandatoryFields = useMemo(() => ["vendorName", "vendorCode"] as const, []);
  const missingSearchMandatoryFields = useMemo(
    () =>
      searchMandatoryFields.filter((field) => !String(createMandatoryValues[field] ?? "").trim()),
    [createMandatoryValues, searchMandatoryFields],
  );

  const resolvedSalesEmployeeCode = useMemo(() => {
    const byName = lookups.salesEmployees.find(
      (item) => item.name.trim().toLowerCase() === lookups.salesEmployeeInput.trim().toLowerCase(),
    );
    if (byName) {
      return Number(normalizeCodeForCompare(byName.code));
    }

    const byCode = lookups.salesEmployees.find(
      (item) =>
        normalizeCodeForCompare(item.code) === normalizeCodeForCompare(lookups.salesEmployeeInput),
    );
    if (byCode) {
      return Number(normalizeCodeForCompare(byCode.code));
    }

    return;
  }, [lookups.salesEmployeeInput, lookups.salesEmployees]);

  const searchRequiredCompletionPercent =
    ((searchMandatoryFields.length - missingSearchMandatoryFields.length) /
      searchMandatoryFields.length) *
    100;
  const validRows = useMemo(
    () => productsHook.productRows.filter((row) => row.productCode.trim() && row.quantity > 0),
    [productsHook.productRows],
  );

  const isDirty = useMemo(() => {
    if ((!isEditMode && !draftDocNum) || !formSnapshot) {
      return false;
    }
    const current = {
      comments: header.comments.trim(),
      referenceNo: header.referenceNo.trim(),
      docDueDate: header.docDueDate,
      salesEmployee: lookups.salesEmployeeInput.trim(),
      warehouseCode: lookups.effectiveWarehouseCode.trim(),
      billToAddress: formatAddressForDisplay(lookups.billToAddress).trim(),
      shipToAddress: formatAddressForDisplay(lookups.shipToAddress).trim(),
      attachments: attachments.map((att) => ({
        fileName: att.fileName,
        freeText: att.freeText || "",
      })),
      productRows: validRows.map((row) => ({
        productCode: row.productCode,
        quantity: row.quantity,
        price: row.price,
        discountPercent: row.discountPercent,
        warehouseCode: row.warehouseCode,
        uomCode: row.uomCode,
        uomEntry: row.uomEntry,
      })),
    };
    return JSON.stringify(current) !== JSON.stringify(formSnapshot);
  }, [
    isEditMode,
    draftDocNum,
    formSnapshot,
    header.comments,
    header.referenceNo,
    header.docDueDate,
    lookups.salesEmployeeInput,
    lookups.effectiveWarehouseCode,
    lookups.billToAddress,
    lookups.shipToAddress,
    validRows,
    attachments,
  ]);

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === "Closed" ||
    editDetailQuery.data?.data?.DocStatus === "C";

  const submitDisabled = isEditMode || Boolean(draftDocNum) ? !isDirty : false;

  const hasValidRowsForCreate = validRows.length > 0;

  const createDisabledReason =
    missingMandatoryFields.length > 0
      ? `Complete required fields: ${missingMandatoryFields.map((field) => REQUIRED_FIELD_LABEL_TEXT[field]).join(", ")}.`
      : !hasValidRowsForCreate
        ? `Add at least one product row before ${isEditMode ? "updating" : "creating"} purchase order.`
        : null;

  const requiredCompletionPercent =
    ((PURCHASE_ORDER_MANDATORY_FIELDS.length - missingMandatoryFields.length) /
      PURCHASE_ORDER_MANDATORY_FIELDS.length) *
    100;

  const requiredFieldsErrorText = `Fill required fields before ${isEditMode ? "updating" : "creating"} purchase order.`;
  const rowsErrorText = `Add at least one product row before ${isEditMode ? "updating" : "creating"} purchase order.`;

  const visibleCreateError =
    createError === requiredFieldsErrorText && !createDisabledReason
      ? null
      : createError === rowsErrorText && hasValidRowsForCreate
        ? null
        : createError;

  const warehouseErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!submitAttempted) return errors;

    productsHook.productRows.forEach((row) => {
      if (row.productCode.trim() && !row.warehouseCode.trim()) {
        errors[row.id] = "Warehouse is required.";
      }
    });
    return errors;
  }, [submitAttempted, productsHook.productRows]);

  const saveActions = useDocumentSaveActions({
    documentName: "Purchase Order",
    moduleType: "purchase",
    defaultUrl: "/purchase/create-order",
    tableUrl: "/purchase/orders",
    resetForm,
    getPayloadString: () => {
      const validRows = productsHook.productRows.filter(
        (row) => row.productCode.trim() && row.quantity > 0,
      );
      const branchFields = documentBranchPayload(header.branchId ?? branchField.effectiveBranchId);
      const seriesFields = documentSeriesPayload(header.series ?? seriesField.effectiveSeries);
      const payload = isEditMode
        ? {
            Address: lookups.billToAddress.trim() || undefined,
            Address2: lookups.shipToAddress.trim() || undefined,
            ...sapCommentsField(header.comments),
            DocDate: header.docDate,
            DocDueDate: header.docDueDate || header.docDate,
            NumAtCard: header.referenceNo.trim() || undefined,
            DocumentLines: validRows.map((row) => ({
              DiscountPercent: row.discountPercent,
              ItemCode: row.productCode,
              LineNum: row.lineNum,
              Quantity: row.quantity,
              UnitPrice: row.price,
              UoMCode: row.uomCode || undefined,
              UoMEntry: row.uomEntry ?? undefined,
              VatGroup: row.vatGroup || undefined,
              WarehouseCode: row.warehouseCode || undefined,
              BaseType: typeof row.baseType === "number" ? row.baseType : undefined,
              BaseEntry: typeof row.baseEntry === "number" ? row.baseEntry : undefined,
              BaseLine: typeof row.baseLine === "number" ? row.baseLine : undefined,
            })),
            SalesPersonCode: resolvedSalesEmployeeCode,
            ...branchFields,
          }
        : {
            Address: lookups.billToAddress.trim() || undefined,
            Address2: lookups.shipToAddress.trim() || undefined,
            CardCode: (header.vendorCode || lookups.codeInput).trim(),
            ...sapCommentsField(header.comments),
            DocDate: header.docDate,
            DocDueDate: header.docDueDate || header.docDate,
            NumAtCard: header.referenceNo.trim() || undefined,
            DocumentLines: (() => {
              const lines: Record<string, unknown>[] = [];
              for (const row of validRows) {
                const hasCompleteBaseLink =
                  Number.isFinite(row.baseEntry) &&
                  Number.isFinite(row.baseLine) &&
                  Number.isFinite(row.baseType);

                if (!hasCompleteBaseLink) {
                  lines.push({
                    DiscountPercent: row.discountPercent,
                    ItemCode: row.productCode,
                    Quantity: row.quantity,
                    UnitPrice: row.price,
                    UoMCode: row.uomCode || undefined,
                    UoMEntry: row.uomEntry ?? undefined,
                    VatGroup: row.vatGroup || undefined,
                    WarehouseCode: row.warehouseCode || undefined,
                  });
                  continue;
                }

                const baseQty = row.baseQuantity ?? 0;
                const linkedQty = Math.min(row.quantity, baseQty);

                if (linkedQty > 0) {
                  lines.push({
                    BaseEntry: row.baseEntry,
                    BaseLine: row.baseLine,
                    BaseType: row.baseType,
                    DiscountPercent: row.discountPercent,
                    ItemCode: row.productCode,
                    Quantity: linkedQty,
                    UnitPrice: row.price,
                    UoMCode: row.uomCode || undefined,
                    UoMEntry: row.uomEntry ?? undefined,
                    VatGroup: row.vatGroup || undefined,
                    WarehouseCode: row.warehouseCode || undefined,
                  });
                }

                const excessQty = row.quantity - baseQty;
                if (excessQty > 0) {
                  lines.push({
                    DiscountPercent: row.discountPercent,
                    ItemCode: row.productCode,
                    Quantity: excessQty,
                    UnitPrice: row.price,
                    UoMCode: row.uomCode || undefined,
                    UoMEntry: row.uomEntry ?? undefined,
                    VatGroup: row.vatGroup || undefined,
                    WarehouseCode: row.warehouseCode || undefined,
                  });
                }
              }
              return lines;
            })(),
            SalesPersonCode: resolvedSalesEmployeeCode,
            ...branchFields,
            ...seriesFields,
          };
      return JSON.stringify(payload);
    },
    isEditMode,
  });

  function handleCreateOrderAction(action: "save-new" | "view" | "close" | "draft" = "save-new") {
    void handleCreateOrder(action);
  }

  const handleCreateOrder = async (
    action: "save-new" | "view" | "close" | "draft" = "save-new",
  ) => {
    const isDraftAction = action === "draft";
    const draftCardCode = (header.vendorCode || lookups.codeInput).trim();

    if (isDraftAction) {
      if (!draftCardCode) {
        setSubmitAttempted(true);
        const nextErrors: ProductSearchFieldError = {
          ...EMPTY_PRODUCT_SEARCH_FIELD_ERRORS,
          vendorCode: "Vendor Code is required.",
          vendorName: "Vendor Name is required.",
        };
        setProductSearchFieldErrors(nextErrors);
        setCreateError("Vendor is required to save as draft.");
        return;
      }
    } else {
      setSubmitAttempted(true);
      const nextErrors: ProductSearchFieldError = {
        ...EMPTY_PRODUCT_SEARCH_FIELD_ERRORS,
      };
      missingMandatoryFields.forEach((field) => {
        nextErrors[field] = MANDATORY_ERROR_TEXT[field];
      });

      if (Object.values(nextErrors).some(Boolean)) {
        setProductSearchFieldErrors(nextErrors);
        setCreateError(requiredFieldsErrorText);
        return;
      }

      if (validRows.length === 0) {
        setCreateError(rowsErrorText);
        return;
      }

      if (isEditMode && !isDirty) {
        const noChangeMessage = "Change at least one field before update.";
        setCreateError(noChangeMessage);
        return;
      }
    }

    setCreateError(null);

    const loadedDraftDocEntry =
      editDetailQuery.data?.data?.DocEntry ?? editDetailQuery.data?.data?.id;

    const branchFields = documentBranchPayload(header.branchId ?? branchField.effectiveBranchId);
    const seriesFields = documentSeriesPayload(header.series ?? seriesField.effectiveSeries);

    const payload = isDraftAction
      ? {
          Address: lookups.billToAddress.trim() || undefined,
          Address2: lookups.shipToAddress.trim() || undefined,
          CardCode: draftCardCode,
          ...sapCommentsField(header.comments),
          DocDate: header.docDate,
          DocDueDate: header.docDueDate || header.docDate,
          NumAtCard: header.referenceNo.trim() || undefined,
          DocumentLines: validRows.map((row) => ({
            DiscountPercent: row.discountPercent,
            ItemCode: row.productCode,
            Quantity: row.quantity,
            UnitPrice: row.price,
            UoMCode: row.uomCode || undefined,
            UoMEntry: row.uomEntry ?? undefined,
            VatGroup: row.vatGroup || undefined,
            WarehouseCode: row.warehouseCode || undefined,
          })),
          SalesPersonCode: resolvedSalesEmployeeCode,
          attachments: attachments.map((att) => ({
            sourcePath: att.sourcePath || "",
            fileName: att.fileName,
            fileExtension: att.fileExtension || "",
            freeText: att.freeText || "",
            attachmentDate: att.attachmentDate || "",
          })),
          isDraft: true,
          ...branchFields,
        }
      : isEditMode
        ? {
            Address: lookups.billToAddress.trim() || undefined,
            Address2: lookups.shipToAddress.trim() || undefined,
            ...sapCommentsField(header.comments),
            DocDate: header.docDate,
            DocDueDate: header.docDueDate || header.docDate,
            NumAtCard: header.referenceNo.trim() || undefined,
            DocumentLines: validRows.map((row) => ({
              DiscountPercent: row.discountPercent,
              ItemCode: row.productCode,
              LineNum: row.lineNum,
              Quantity: row.quantity,
              UnitPrice: row.price,
              UoMCode: row.uomCode || undefined,
              UoMEntry: row.uomEntry ?? undefined,
              VatGroup: row.vatGroup || undefined,
              WarehouseCode: row.warehouseCode || undefined,
              BaseType: typeof row.baseType === "number" ? row.baseType : undefined,
              BaseEntry: typeof row.baseEntry === "number" ? row.baseEntry : undefined,
              BaseLine: typeof row.baseLine === "number" ? row.baseLine : undefined,
            })),
            SalesPersonCode: resolvedSalesEmployeeCode,
            attachments: attachments.map((att) => ({
              sourcePath: att.sourcePath || "",
              fileName: att.fileName,
              fileExtension: att.fileExtension || "",
              freeText: att.freeText || "",
              attachmentDate: att.attachmentDate || "",
            })),
            ...branchFields,
            ...seriesFields,
          }
        : {
            Address: lookups.billToAddress.trim() || undefined,
            Address2: lookups.shipToAddress.trim() || undefined,
            CardCode: (header.vendorCode || lookups.codeInput).trim(),
            ...sapCommentsField(header.comments),
            DocDate: header.docDate,
            DocDueDate: header.docDueDate || header.docDate,
            NumAtCard: header.referenceNo.trim() || undefined,
            DocumentLines: (() => {
              const lines: Record<string, unknown>[] = [];
              for (const row of validRows) {
                const hasCompleteBaseLink =
                  Number.isFinite(row.baseEntry) &&
                  Number.isFinite(row.baseLine) &&
                  Number.isFinite(row.baseType);

                if (!hasCompleteBaseLink) {
                  lines.push({
                    DiscountPercent: row.discountPercent,
                    ItemCode: row.productCode,
                    Quantity: row.quantity,
                    UnitPrice: row.price,
                    UoMCode: row.uomCode || undefined,
                    UoMEntry: row.uomEntry ?? undefined,
                    VatGroup: row.vatGroup || undefined,
                    WarehouseCode: row.warehouseCode || undefined,
                  });
                  continue;
                }

                const baseQty = row.baseQuantity ?? 0;
                const linkedQty = Math.min(row.quantity, baseQty);

                if (linkedQty > 0) {
                  lines.push({
                    BaseEntry: row.baseEntry,
                    BaseLine: row.baseLine,
                    BaseType: row.baseType,
                    DiscountPercent: row.discountPercent,
                    ItemCode: row.productCode,
                    Quantity: linkedQty,
                    UnitPrice: row.price,
                    UoMCode: row.uomCode || undefined,
                    UoMEntry: row.uomEntry ?? undefined,
                    VatGroup: row.vatGroup || undefined,
                    WarehouseCode: row.warehouseCode || undefined,
                  });
                }

                const excessQty = row.quantity - baseQty;
                if (excessQty > 0) {
                  lines.push({
                    DiscountPercent: row.discountPercent,
                    ItemCode: row.productCode,
                    Quantity: excessQty,
                    UnitPrice: row.price,
                    UoMCode: row.uomCode || undefined,
                    UoMEntry: row.uomEntry ?? undefined,
                    VatGroup: row.vatGroup || undefined,
                    WarehouseCode: row.warehouseCode || undefined,
                  });
                }
              }
              return lines;
            })(),
            SalesPersonCode: resolvedSalesEmployeeCode,
            attachments: attachments.map((att) => ({
              sourcePath: att.sourcePath || "",
              fileName: att.fileName,
              fileExtension: att.fileExtension || "",
              freeText: att.freeText || "",
              attachmentDate: att.attachmentDate || "",
            })),
            draftDocEntry: loadedDraftDocEntry ? Number(loadedDraftDocEntry) : undefined,
            ...branchFields,
            ...seriesFields,
          };

    const isDraftUpdate = isDraftAction && loadedDraftDocEntry !== undefined;
    const isUpdating = isEditMode || isDraftUpdate;
    const trackingAction = isDraftUpdate ? "draft-update" : isEditMode ? "update" : action;

    saveActions.startSaveTracking(trackingAction);
    try {
      let createdDocNum: string | number | undefined;
      if (isUpdating) {
        const docEntry = isEditMode
          ? (editDetailQuery.data?.data?.DocEntry ?? editDetailQuery.data?.data?.id)
          : loadedDraftDocEntry;
        if (docEntry === undefined || docEntry === null) {
          setCreateError("Unable to update purchase order. Document id is missing.");
          return;
        }
        await updatePurchaseOrderMutation.mutateAsync({
          id: docEntry,
          payload,
        });
        createdDocNum = isEditMode
          ? editDetailQuery.data?.data?.DocNum
          : (editDetailQuery.data?.data?.DocNum ?? draftDocNum);

        // Fetch the updated detail from the API/cache to sync the local states (like attachments) immediately without page refresh
        const updatedDetailRes = await queryClient.fetchQuery(
          purchaseOrderQueries.detailByDocNum(
            String(createdDocNum),
            isEditMode ? undefined : String(loadedDraftDocEntry),
          ),
        );
        const updatedDetail = updatedDetailRes?.data;
        if (updatedDetail) {
          const rawAttachments = updatedDetail.attachments || [];
          setAttachments(
            rawAttachments.map((item: any, idx: number) => ({
              id: `loaded-${idx}-${item.fileName}`,
              fileName: item.fileName,
              fileExtension: item.fileExtension,
              sourcePath: item.sourcePath,
              attachmentDate: item.attachmentDate,
              freeText: item.freeText || "",
              targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
            })),
          );

          const vendorCode = String(updatedDetail.CardCode ?? "").trim();
          const matchedVendor = lookups.vendors.find(
            (vendor) => String(vendor.code) === vendorCode,
          );
          const warehouseCode = String(
            updatedDetail.DocumentLines?.[0]?.WarehouseCode ?? "",
          ).trim();
          const salesEmployeeNameFromDocCode =
            updatedDetail.SalesPersonCode !== undefined && updatedDetail.SalesPersonCode !== null
              ? lookups.salesEmployees.find(
                  (item) =>
                    normalizeCodeForCompare(item.code) ===
                    normalizeCodeForCompare(updatedDetail.SalesPersonCode),
                )?.name
              : "";
          const associatedSalesEmployeeName =
            salesEmployeeNameFromDocCode ||
            (matchedVendor?.salesEmployeeCode !== undefined
              ? lookups.salesEmployees.find(
                  (item) =>
                    normalizeCodeForCompare(item.code) ===
                    normalizeCodeForCompare(matchedVendor.salesEmployeeCode),
                )?.name
              : "") ||
            matchedVendor?.salesEmployeeName?.trim() ||
            "";

          const { comments, referenceNo } = parsePurchaseOrderHeaderNotes(updatedDetail);
          const docDueDate = String(updatedDetail.DocDueDate ?? "").slice(0, 10);
          const billToAddress = String(updatedDetail.Address ?? "").trim();
          const shipToAddress = String(
            (updatedDetail as Record<string, unknown>).Address2 ?? "",
          ).trim();

          const detailLines = updatedDetail.DocumentLines ?? [];
          const mappedRows = detailLines.map((line: PurchaseOrderDetailLine, index) => {
            const lineData = line as Record<string, unknown>;
            const itemCode = String(line.ItemCode ?? "").trim();
            const quantity = Number(line.Quantity ?? 1);
            const openQty = Number(line.OpenQty ?? quantity);
            const price = Number(line.Price ?? line.UnitPrice ?? 0);
            const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
              grossAmount: Math.max(0, price * quantity),
              headerDiscountPercent: Number(
                (updatedDetail as Record<string, unknown>).DiscountPercent ?? 0,
              ),
              line: line as Record<string, unknown>,
            });
            const sapVatPrcnt = Number(line.VatPrcnt ?? 0);

            return {
              comment: "",
              currency: String(updatedDetail.DocCurr ?? ""),
              discountAmount,
              discountPercent,
              id: `row-${createdDocNum}-${index}`,
              lineNum: typeof line.LineNum === "number" ? line.LineNum : index,
              openQty,
              price,
              productCode: itemCode,
              productName: String(line.ItemDescription ?? "").trim(),
              quantity,
              selected: false,
              stock: Number(line.Quantity ?? 0),
              taxRate: sapVatPrcnt,
              uomCode: String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim(),
              uomEntry: Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry),
              vatGroup: String(line.VatGroup ?? line.TaxCode ?? "").trim(),
              warehouseCode: String(line.WarehouseCode ?? "").trim(),
            };
          });

          setFormSnapshot({
            comments: comments.trim(),
            referenceNo: referenceNo.trim(),
            docDueDate: docDueDate,
            salesEmployee: associatedSalesEmployeeName.trim(),
            warehouseCode: warehouseCode.trim(),
            billToAddress: formatAddressForDisplay(billToAddress).trim(),
            shipToAddress: formatAddressForDisplay(shipToAddress).trim(),
            attachments: rawAttachments.map((item: any) => ({
              fileName: item.fileName,
              freeText: item.freeText || item.remarks || "",
            })),
            productRows: mappedRows
              .filter((row) => row.productCode.trim() && row.quantity > 0)
              .map((row) => ({
                productCode: row.productCode,
                quantity: row.quantity,
                price: row.price,
                discountPercent: row.discountPercent,
                warehouseCode: row.warehouseCode,
                uomCode: row.uomCode,
                uomEntry: row.uomEntry,
              })),
          });
        }
      } else {
        const result = await createPurchaseOrderMutation.mutateAsync({
          payload,
        });
        createdDocNum = result?.data?.DocNum;
      }

      saveActions.trackMutationSuccess();

      // Proactive Cache Revalidation
      void queryClient.invalidateQueries({ queryKey: purchaseOrderKeys.all });
      void Promise.allSettled([
        queryClient.prefetchQuery(purchaseOrderQueries.list({ limit: 10, page: 1 })),
        queryClient.prefetchQuery(purchaseOrderQueries.docNumSuggestions(undefined, 10)),
        queryClient.prefetchQuery(purchaseOrderQueries.docNumSuggestions(undefined, 100)),
      ]);

      // Invalidate specific PurchaseQuotation detail and list queries used by copy-from hydration
      if (sourceDocNum && sourceDocType === "PurchaseQuotation") {
        sourceDocNum.split(",").forEach((num) => {
          const trimmed = num.trim();
          if (trimmed) {
            void queryClient.invalidateQueries({
              queryKey: purchaseQuotationQueries.detailByDocNum(trimmed).queryKey,
            });
          }
        });
        void queryClient.invalidateQueries({ queryKey: purchaseQuotationKeys.all });
      }

      await saveActions.handleActionSuccess(isEditMode ? "update" : action, createdDocNum);

      if (!isEditMode && action === "save-new") {
        options?.onCreateSuccess?.();
      }

      if (isEditMode || loadedDraftDocEntry) {
        const currentDocNum = isEditMode ? (options?.docNum ?? "").trim() : draftDocNum;
        if (currentDocNum) {
          void queryClient.invalidateQueries(
            purchaseOrderQueries.detailByDocNum(
              currentDocNum,
              isEditMode ? undefined : String(loadedDraftDocEntry),
            ),
          );
        }
      }
    } catch (error) {
      const errorMessage = normalizeCreateOrderErrorMessage(
        error,
        `Failed to ${isEditMode ? "update" : "create"} purchase order. Try again.`,
      );
      setCreateError(errorMessage);
      notifyCreateApiError(errorMessage, "purchase-order");
    }
  };

  const submitPurchaseOrderMutation = isEditMode
    ? updatePurchaseOrderMutation
    : createPurchaseOrderMutation;

  const totals = useMemo(
    () => calculateOrderTotals(productsHook.productRows),
    [productsHook.productRows],
  );
  const summaryCurrency = useMemo(
    () => calculateSummaryCurrency(productsHook.productRows),
    [productsHook.productRows],
  );
  const summaryCurrencyLabel = summaryCurrency === "MULTI" ? "MULTI" : summaryCurrency;
  const isEditHydrated = !isEditMode || !editDocNum || hydratedDocNum === editDocNum;
  const isSourceHydrating =
    !isEditMode &&
    Boolean(sourceDocNum) &&
    sourceDocType === "PurchaseQuotation" &&
    !sourceHydrationComplete;

  // Derive the product code of the currently active row for seeding modal selection
  const activeRowProductCode = useMemo(() => {
    if (!productsHook.activeProductRowId) {
      return null;
    }
    const activeRow = productsHook.productRows.find(
      (r) => r.id === productsHook.activeProductRowId,
    );
    return activeRow?.productCode ?? null;
  }, [productsHook.activeProductRowId, productsHook.productRows]);

  const selectBranch = useCallback(
    (item: { code: string; name: string }) => {
      branchField.selectBranch(item);
      modals.setModalOpen(false);
    },
    [branchField, modals],
  );

  const selectSeries = useCallback(
    (item: { code: string; name: string; nextNumber?: number | null | undefined }) => {
      if (isEditMode) {
        notifyRestricted("Series");
        return;
      }
      seriesField.selectSeries(item);
      modals.setModalOpen(false);
    },
    [isEditMode, seriesField, modals],
  );

  return {
    ...lookups,
    ...modals,
    ...productsHook,
    ...branchField,
    ...seriesField,
    selectBranch,
    selectSeries,
    activeDatePicker,
    activeRowProductCode,
    applyProductToRow: (product: ProductLookupItem) =>
      productsHook.applyProductToRow(product, {
        closeProductPopup: () => modals.setProductPopupOpen(false),
      }),
    applyProductsToRows: (products: ProductLookupItem[]) =>
      productsHook.applyProductsToRows(products, {
        closeProductPopup: () => modals.setProductPopupOpen(false),
      }),
    isDirty,
    submitDisabled,
    createDisabledReason,
    createError: visibleCreateError,
    submitAttempted,
    warehouseErrors,
    createPurchaseOrderMutation: submitPurchaseOrderMutation,
    deliveryDateContainerRef,
    docDateContainerRef,
    docStatus:
      editDetailQuery.data?.data?.DocStatus === "O"
        ? "Open"
        : editDetailQuery.data?.data?.DocStatus === "C"
          ? "Closed"
          : (editDetailQuery.data?.data?.DocStatus ?? "Open"),
    editDetailQuery,
    handleCreateOrder: handleCreateOrderAction,
    handleLookupModalSearchSync,
    header,
    isClosed,
    isEditHydrated,
    isEditMode,
    draftDocNum,
    isSourceHydrating,
    isSaved: saveActions.isSaved,
    savedDocNum: saveActions.savedDocNum,
    missingMandatoryFields,
    missingSearchMandatoryFields,
    openPopup: openPopupWithContext,
    openProductPopup: handleOpenProductPopup,
    popupResults,
    productSearchFieldErrors,
    requiredCompletionPercent,
    resetForm: saveActions.handleReset,
    searchMandatoryFields,
    searchRequiredCompletionPercent,
    setActiveDatePicker,
    setHeader,
    setProductSearchFieldErrors,
    showEditRestrictedToast: (fieldName = "Field") => notifyRestricted(fieldName),
    summaryCurrencyLabel,
    today,
    totals,
    trackerDocType:
      isEditMode && editDetailQuery.data?.data?.DocStatus !== "Draft"
        ? ("purchase-order" as const)
        : null,
    trackerDocEntry:
      isEditMode && editDetailQuery.data?.data?.DocStatus !== "Draft"
        ? (editDetailQuery.data?.data?.DocEntry ?? editDetailQuery.data?.data?.id)
        : null,
    updatePurchaseOrderMutation,
    attachments,
    setAttachments,
  };
}
