/**
 * Auto-reference utilities for document copy operations.
 * Provides consistent reference string formatting for traceability.
 */

/**
 * Document type display names for reference strings.
 */
const DOC_TYPE_DISPLAY_NAMES: Record<string, string> = {
  APCreditMemo: "A/P Credit Memo",
  APInvoice: "A/P Invoice",
  GoodsReceiptPO: "GRPO",
  OutgoingPayment: "Outgoing Payment",
  PurchaseOrder: "Purchase Order",
  PurchaseQuotation: "Purchase Quotation",
};

/**
 * Plural forms of document types for multi-document references.
 */
const DOC_TYPE_PLURALS: Record<string, string> = {
  APCreditMemo: "A/P Credit Memos",
  APInvoice: "A/P Invoices",
  GoodsReceiptPO: "GRPOs",
  OutgoingPayment: "Outgoing Payments",
  PurchaseOrder: "Purchase Orders",
  PurchaseQuotation: "Purchase Quotations",
};

/**
 * Generates a reference string for a single source document.
 * Format: "Based on <Source Document Type> <Doc Num>"
 */
export function generateSingleSourceReference(docType: string, docNum: string): string {
  const displayName = DOC_TYPE_DISPLAY_NAMES[docType] || docType;
  return `Based on ${displayName} ${docNum}`;
}

/**
 * Generates a reference string for multiple source documents.
 * Format: "Based on <count> <Document Type Plural>"
 * If mixed types: "Based on <count> Documents"
 */
export function generateMultiSourceReference(
  documents: { docType: string; docNum: string }[],
): string {
  const count = documents.length;
  if (count === 0) {
    return "";
  }
  if (count === 1) {
    return generateSingleSourceReference(documents[0]!.docType, documents[0]!.docNum);
  }

  // Check if all documents are the same type
  const firstType = documents[0]!.docType;
  const allSameType = documents.every((doc) => doc.docType === firstType);

  if (allSameType) {
    const pluralName = DOC_TYPE_PLURALS[firstType] || "Documents";
    return `Based on ${count} ${pluralName}`;
  }

  // Mixed document types
  return `Based on ${count} Documents`;
}

/**
 * Generates a short summary of source documents for reference.
 * Shows up to 3 document numbers, then ellipsis if more.
 * Format: "Based on <DocType> <Num1>, <Num2>..."
 */
export function generateShortDocListSummary(
  documents: { docType: string; docNum: string }[],
): string {
  const count = documents.length;
  if (count === 0) {
    return "";
  }
  if (count === 1) {
    return generateSingleSourceReference(documents[0]!.docType, documents[0]!.docNum);
  }

  // Check if all documents are the same type
  const firstType = documents[0]!.docType;
  const allSameType = documents.every((doc) => doc.docType === firstType);

  const displayName = allSameType ? DOC_TYPE_DISPLAY_NAMES[firstType] || firstType : "Documents";

  if (count <= 3) {
    const docNums = documents.map((doc) => doc.docNum).join(", ");
    return `Based on ${displayName} ${docNums}`;
  }

  // More than 3 documents - show count and first few numbers
  const shownNums = documents
    .slice(0, 3)
    .map((doc) => doc.docNum)
    .join(", ");
  const remaining = count - 3;
  return `Based on ${displayName} ${shownNums} (+${remaining} more)`;
}

/**
 * Extracts source document metadata from a reference string.
 * Returns null if the reference doesn't match expected format.
 */
export function parseReferenceToSourceDocs(
  reference: string,
): { docType: string; docNum: string }[] | null {
  if (!reference.startsWith("Based on ")) {
    return null;
  }

  // This is a simplified parser - in production you might want more robust parsing
  // For now, we store source metadata separately, so this is mainly for validation
  return null;
}

/**
 * Strips auto-generated "Based on..." reference lines from remarks
 * while preserving user-entered text.
 *
 * During copy-to vendor change confirmation (Yes), only the system-generated
 * reference lines are removed; any manual remarks typed by the user remain.
 */
export function stripAutoGeneratedReferences(remarks: string): string {
  if (!remarks) {
    return "";
  }

  const lines = remarks.split("\n");
  const userLines = lines.filter((line) => {
    const trimmed = line.trim();
    // Skip auto-generated reference lines (they always start with "Based on ")
    if (/^based on /i.test(trimmed)) {
      return false;
    }
    return true;
  });

  return userLines.join("\n").trim();
}
