/**
 * Auto-reference utilities for document copy operations.
 * Short "Based on {TYPE} {num}" lines for SAP Comments (254 max).
 */

/** @deprecated Old long-form prefix; new lines use Based on PQ 123. */
export const AUTO_GENERATED_PREFIX = "Auto Generated";

/** Short type codes written into remarks. */
const DOC_TYPE_SHORT: Record<string, string> = {
  APCreditMemo: "CM",
  APInvoice: "AP",
  GoodsReceiptPO: "GRPO",
  OutgoingPayment: "OP",
  PurchaseOrder: "PO",
  PurchaseQuotation: "PQ",
};

const DOC_TYPE_SHORT_PLURAL: Record<string, string> = {
  APCreditMemo: "CM",
  APInvoice: "AP",
  GoodsReceiptPO: "GRPO",
  OutgoingPayment: "OP",
  PurchaseOrder: "PO",
  PurchaseQuotation: "PQ",
};

const SHORT_CODES = "PQD|PQ|RFQ|SQ|PO|AR|GRPO|AP|CM|OP";

/** Short auto-ref: `Based on PQ 132424`, legacy `PQ 132424`, … */
const SHORT_AUTO_REF_LINE_RE = new RegExp(`^(${SHORT_CODES})\\s*:?\\s+\\S+`, "i");

/**
 * True for system reference lines (new Based on TYPE + legacy forms).
 */
export const isAutoGeneratedRemarkLine = (line: string): boolean => {
  const trimmed = line.trim();
  if (!trimmed) {
    return false;
  }
  if (/^(?:auto\s+generated\s+)?based on\s+/i.test(trimmed)) {
    return true;
  }
  if (/^IC\s*\|/i.test(trimmed)) {
    return true;
  }
  return SHORT_AUTO_REF_LINE_RE.test(trimmed);
};

const shortCodeFor = (docType: string): string => DOC_TYPE_SHORT[docType] || docType;

/**
 * Single source: `Based on PQ 132424` (no company name).
 */
export function generateSingleSourceReference(
  docType: string,
  docNum: string,
  _companyCode?: string | null,
): string {
  const code = shortCodeFor(docType);
  const num = String(docNum).trim();
  return num ? `Based on ${code} ${num}` : `Based on ${code}`;
}

/**
 * Multiple sources, same type: `Based on PO 1, 2, 3` or `Based on 3 PO` when mixed nums not listed.
 * Mixed types: `Based on 3 docs`.
 */
export function generateMultiSourceReference(
  documents: { docType: string; docNum: string; companyCode?: string | null }[],
): string {
  const count = documents.length;
  if (count === 0) {
    return "";
  }
  if (count === 1) {
    return generateSingleSourceReference(
      documents[0]!.docType,
      documents[0]!.docNum,
      documents[0]!.companyCode,
    );
  }

  const firstType = documents[0]!.docType;
  const allSameType = documents.every((doc) => doc.docType === firstType);

  if (allSameType) {
    const code = DOC_TYPE_SHORT_PLURAL[firstType] || shortCodeFor(firstType);
    if (count <= 5) {
      const nums = documents.map((doc) => String(doc.docNum).trim()).filter(Boolean);
      if (nums.length === count) {
        return `Based on ${code} ${nums.join(", ")}`;
      }
    }
    return `Based on ${count} ${code}`;
  }

  return `Based on ${count} docs`;
}

/**
 * Short list summary for many sources.
 */
export function generateShortDocListSummary(
  documents: { docType: string; docNum: string; companyCode?: string | null }[],
): string {
  const count = documents.length;
  if (count === 0) {
    return "";
  }
  if (count === 1) {
    return generateSingleSourceReference(
      documents[0]!.docType,
      documents[0]!.docNum,
      documents[0]!.companyCode,
    );
  }

  const firstType = documents[0]!.docType;
  const allSameType = documents.every((doc) => doc.docType === firstType);
  const code = allSameType ? shortCodeFor(firstType) : "doc";

  if (count <= 3) {
    const docNums = documents.map((doc) => String(doc.docNum).trim()).join(", ");
    return `Based on ${code} ${docNums}`;
  }

  const shownNums = documents
    .slice(0, 3)
    .map((doc) => String(doc.docNum).trim())
    .join(", ");
  const remaining = count - 3;
  return `Based on ${code} ${shownNums} (+${remaining})`;
}

/**
 * Extracts source document metadata from a reference string.
 * Returns null if the reference doesn't match expected format.
 */
export function parseReferenceToSourceDocs(
  reference: string,
): { docType: string; docNum: string }[] | null {
  if (!isAutoGeneratedRemarkLine(reference)) {
    return null;
  }
  return null;
}

/**
 * Strips auto-generated reference lines from remarks while preserving user text.
 * Matches `Based on PQ 123`, short `PQ 123`, and legacy long forms.
 */
export function stripAutoGeneratedReferences(remarks: string): string {
  if (!remarks) {
    return "";
  }

  const lines = remarks.split("\n");
  const userLines = lines.filter((line) => !isAutoGeneratedRemarkLine(line));

  return userLines.join("\n").trim();
}
