import {
  getProducts,
  getProductWarehouseStocks,
  getVendors,
  getCustomers,
  getTaxCodes,
  getUOMs,
  getPriceLists,
  getSeries,
  getWarehouses,
  getWarehouseBins,
  getSalesEmployees,
  getWarehouseBranch,
  getDefaultBranch,
} from "./master-data.queries";

export {
  getProducts,
  getProductWarehouseStocks,
  getVendors,
  getCustomers,
  getTaxCodes,
  getUOMs,
  getPriceLists,
  getSeries,
  getWarehouses,
  getWarehouseBins,
  getSalesEmployees,
  getWarehouseBranch,
  getDefaultBranch,
};

export const masterDataService = {
  getProducts,
  getProductWarehouseStocks,
  getVendors,
  getCustomers,
  getTaxCodes,
  getUOMs,
  getPriceLists,
  getSeries,
  getWarehouses,
  getWarehouseBins,
  getSalesEmployees,
  getWarehouseBranch,
  getDefaultBranch,
};
