import {
  getProducts,
  getProductsByCodes,
  getProductWarehouseStocks,
  getProductWarehouseStocksBatch,
  getVendors,
  getCustomers,
  getTaxCodes,
  getUOMs,
  getPriceLists,
  getSeries,
  getWarehouses,
  getBusinessPlaces,
  getWarehouseBins,
  getSalesEmployees,
  getWarehouseBranch,
  getDefaultBranch,
  resolveDocumentSeries,
  resolveItemSalesUom,
  getBusinessPartnerAddresses,
} from "./master-data.queries";

export {
  getProducts,
  getProductsByCodes,
  getProductWarehouseStocks,
  getProductWarehouseStocksBatch,
  getVendors,
  getCustomers,
  getTaxCodes,
  getUOMs,
  getPriceLists,
  getSeries,
  getWarehouses,
  getBusinessPlaces,
  getWarehouseBins,
  getSalesEmployees,
  getWarehouseBranch,
  getDefaultBranch,
  resolveDocumentSeries,
  resolveItemSalesUom,
  getBusinessPartnerAddresses,
};

export const masterDataService = {
  getProducts,
  getProductsByCodes,
  getProductWarehouseStocks,
  getProductWarehouseStocksBatch,
  getVendors,
  getCustomers,
  getTaxCodes,
  getUOMs,
  getPriceLists,
  getSeries,
  getWarehouses,
  getBusinessPlaces,
  getWarehouseBins,
  getSalesEmployees,
  getWarehouseBranch,
  getDefaultBranch,
  resolveDocumentSeries,
  resolveItemSalesUom,
  getBusinessPartnerAddresses,
};
