/** Global IC configuration keys (IC_CONFIGURATION). */
export const IC_CONFIG_KEY = {
  DETECT_DRAFT_CRON_MINUTES: "DETECT_DRAFT_CRON_MINUTES",
  ENABLE_FLOW1_RFQ_CHAIN: "ENABLE_FLOW1_RFQ_CHAIN",
  ENABLE_FLOW2_DIRECT_PO: "ENABLE_FLOW2_DIRECT_PO",
  MAX_RETRY_COUNT: "MAX_RETRY_COUNT",
  REMARKS_PREFIX: "REMARKS_PREFIX",
  RETRY_DELAY_MINUTES: "RETRY_DELAY_MINUTES",
  SL_SESSION_TIMEOUT_MINUTES: "SL_SESSION_TIMEOUT_MINUTES",
} as const;

export type IcConfigKey = (typeof IC_CONFIG_KEY)[keyof typeof IC_CONFIG_KEY];

export const IC_DOC_MAP_STATUS = {
  ERROR: "ERROR",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
} as const;

export const IC_RFQ_STATUS = {
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
} as const;

export const IC_RETRY_STATUS = {
  DEAD: "DEAD",
  PROCESSING: "PROCESSING",
  SUCCESS: "SUCCESS",
  WAITING: "WAITING",
} as const;

export const DEFAULT_MAX_RETRY = 2;
