import { useQuery, useQueryClient } from "@tanstack/react-query";
import { goeyToast } from "goey-toast";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import {
  useCreateAPInvoice,
  useUpdateAPInvoice,
} from "@/features/create-pages/ap-invoice-create/api/ap-invoice-create.mutations";
import { useAPInvoiceLookups } from "@/features/create-pages/ap-invoice-create/hooks/use-ap-invoice-lookups";
import {
  AP_INVOICE_FIELD_ERROR_TEXT,
  AP_INVOICE_FIELD_LABEL_TEXT,
  AP_INVOICE_MANDATORY_FIELDS,
  filterAndRankLookups,
  getTodayISO,
} from "@/features/create-pages/ap-invoice-create/utils/ap-invoice-create.utils";
import type { APInvoiceMandatoryField } from "@/features/create-pages/ap-invoice-create/utils/ap-invoice-create.utils";
import { createSharedQueries } from "@/features/create-pages/create-shared/api/create-shared.queries";
import type {
  LookupItem,
  ProductLookupItem,
} from "@/features/create-pages/create-shared/api/create-shared.types";
import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import type {
  ActiveDatePicker,
  PopupMode,
  ProductRowDraft,
  StockPreviewProduct,
} from "@/features/create-pages/create-shared/utils/create-order.types";
import {
  formatWarehouseDisplay,
  normalizeCreateOrderErrorMessage,
} from "@/features/create-pages/create-shared/utils/create-order.utils";
import { documentActionToast } from "@/features/create-pages/create-shared/utils/document-action-toast";
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from "@/features/create-pages/create-shared/utils/lookup-search-sync";
import { pageLoadingToast } from "@/features/create-pages/create-shared/utils/page-loading-toast";
import { resolveProductTaxRates } from "@/features/create-pages/create-shared/utils/product-tax-rate";
import { resolveDocumentLineDiscount } from "@/features/create-pages/create-shared/utils/resolve-document-line-discount";
import { apInvoiceQueries } from "@/features/table-pages/ap-invoices/api/ap-invoice.queries";
import type { CreateAPInvoiceInput } from "@/features/table-pages/ap-invoices/api/ap-invoice.service";
import { grpoKeys, grpoQueries } from "@/features/table-pages/grpo/api/grpo.queries";
import {
  purchaseOrderKeys,
  purchaseOrderQueries,
} from "@/features/table-pages/purchase-orders/api/purchase-order.queries";
import {
  purchaseQuotationKeys,
  purchaseQuotationQueries,
} from "@/features/table-pages/purchase-quotations/api/purchase-quotation.queries";
import {
  useAPInvoiceHeader,
  useAPInvoiceLines,
  useResetAPInvoiceCreateAction,
  useSetAPInvoiceHeaderAction,
  useSetAPInvoiceLinesAction,
} from "@/store/create/ap-invoice-create.store";

import {
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from "../../create-shared/utils/auto-reference";

export interface APInvoiceCreateLine {
  id: string;
  productCode: string;
  productName: string;
  stock: number;
  currency: string;
  vatGroup: string;
  taxRate: number;
  uomCode?: string | undefined;
  uomEntry?: number | undefined;
  baseQuantity?: number | undefined;
  quantity: number;
  discountPercent: number;
  discountAmount: number;
  comment: string;
  price: number;
  warehouseCode: string;
  baseLine?: number | undefined;
  baseEntry?: number | undefined;
  baseType?: number | undefined;
}
type APInvoiceFieldErrors = Record<APInvoiceMandatoryField, string | undefined> & {
  warehouseCode?: string | undefined;
};
const QUICK_PRODUCT_LIMIT = 10;

const EMPTY_AP_INVOICE_FIELD_ERRORS: APInvoiceFieldErrors = {
  vendorCode: undefined,
  vendorName: undefined,
};

interface UseAPInvoiceCreateOptions {
  mode?: "create" | "edit";
  docNum?: string;
  sourceDocNum?: string | undefined;
  sourceDocType?: "PurchaseOrder" | "GoodsReceiptPO" | "PurchaseQuotation" | undefined;
  onCreateSuccess?: () => void;
}

const normalizeCodeForCompare = (value: unknown) => {
  const raw = String(value ?? "").trim();
  if (!raw) {
    return "";
  }
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
};

export function useAPInvoiceCreate({
  mode = "create",
  docNum,
  sourceDocNum,
  sourceDocType,
  onCreateSuccess,
}: UseAPInvoiceCreateOptions) {
  const parseAPInvoiceHeaderNotes = (detail: { Comments?: unknown; NumAtCard?: unknown }) => {
    const referenceNo = String(detail.NumAtCard ?? "").trim();
    const rawComments = String(detail.Comments ?? "").trim();

    if (referenceNo) {
      const legacyReferencePrefix = `${referenceNo} | `;
      return {
        comments: rawComments.startsWith(legacyReferencePrefix)
          ? rawComments.slice(legacyReferencePrefix.length).trim()
          : rawComments,
        referenceNo,
      };
    }

    const splitComments = rawComments.split(" | ").map((part) => part.trim());
    if (splitComments.length > 1) {
      return {
        comments: splitComments.slice(1).join(" | "),
        referenceNo: splitComments[0] ?? "",
      };
    }

    return {
      comments: rawComments,
      referenceNo,
    };
  };
  const isEditMode = mode === "edit";
  const editDocNum = (docNum ?? "").trim();
  const queryClient = useQueryClient();
  const header = useAPInvoiceHeader();
  const setHeader = useSetAPInvoiceHeaderAction();
  const rows = useAPInvoiceLines();
  const filteredRows = useMemo(() => rows.filter((r) => r.quantity > 0), [rows]);
  const setLines = useSetAPInvoiceLinesAction();
  const resetAPInvoiceCreate = useResetAPInvoiceCreateAction();
  const createMutation = useCreateAPInvoice();
  const updateMutation = useUpdateAPInvoice();
  const hydratedDocNumRef = useRef<string | null>(null);
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null);
  const lastRestrictedToastAtRef = useRef(0);
  const loadingToastRef = useRef<ReturnType<typeof pageLoadingToast> | null>(null);

  const [vendorNameInput, setVendorNameInput] = useState("");
  const [vendorCodeInput, setVendorCodeInput] = useState("");
  const [vendorNameFocused, setVendorNameFocused] = useState(false);
  const [vendorCodeFocused, setVendorCodeFocused] = useState(false);
  const [buyerInput, setBuyerInput] = useState("");
  const [buyerFocused, setBuyerFocused] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<PopupMode>("vendor-name");
  const [modalSearch, setModalSearch] = useState("");
  const [productPopupOpen, setProductPopupOpen] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [debouncedProductSearch, setDebouncedProductSearch] = useState("");
  const [productQueryLimit, setProductQueryLimit] = useState(QUICK_PRODUCT_LIMIT);
  const [activeProductRowId, setActiveProductRowId] = useState<string | null>(null);
  const [warehouseInput, setWarehouseInput] = useState("");
  const [warehouseFocused, setWarehouseFocused] = useState(false);

  const [billToAddress, setBillToAddressRaw] = useState("");
  const [shipToAddress, setShipToAddressRaw] = useState("");

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value));
  }, []);
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value));
  }, []);

  const [productRowDrafts, setProductRowDrafts] = useState<Record<string, ProductRowDraft>>({});
  const [stockPreviewProduct, setStockPreviewProduct] = useState<StockPreviewProduct | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<APInvoiceFieldErrors>(
    EMPTY_AP_INVOICE_FIELD_ERRORS,
  );
  const [headerDiscountPercent, setHeaderDiscountPercent] = useState(0);

  /* ---------- vendor-change confirmation (copy-from guard) ---------- */
  const [pendingVendorChange, setPendingVendorChange] = useState<{
    vendor: LookupItem;
  } | null>(null);
  const hasCopiedRows = useMemo(
    () => rows.some((r) => r.baseEntry != null && r.baseType != null),
    [rows],
  );

  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);

  const warehouseErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!submitAttempted) return errors;

    filteredRows.forEach((row) => {
      if (!row.warehouseCode.trim()) {
        errors[row.id] = "Warehouse is required.";
      }
    });
    return errors;
  }, [submitAttempted, filteredRows]);
  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null);
  const docDateContainerRef = useRef<HTMLDivElement>(null);
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null);

  const notifyRestricted = (fieldName: string) => {
    const now = Date.now();
    if (now - lastRestrictedToastAtRef.current < 2500) {
      return;
    }
    lastRestrictedToastAtRef.current = now;
    goeyToast.error(`${fieldName} is locked for edit`, {
      id: "restricted-edit-toast",
    });
  };

  const vendorsQuery = useQuery(createSharedQueries.vendors());
  const warehousesQuery = useQuery(createSharedQueries.warehouses());
  const salesEmployeesQuery = useQuery(createSharedQueries.salesEmployees());
  const financialPeriodQuery = useQuery(createSharedQueries.financialPeriod());
  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data]);
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data]);
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data]);
  const effectiveWarehouseCode = useMemo(() => {
    const lookup = warehouseInput.trim().toLowerCase();
    const match = lookup.match(/^\[(.*?)\]/);
    const codeOrName = match ? match[1]!.trim() : lookup;
    const matched = warehouses.find(
      (item) => item.name.toLowerCase() === codeOrName || item.code.toLowerCase() === codeOrName,
    );
    return matched?.code ?? lookup;
  }, [warehouseInput, warehouses]);

  const vendorSelected = Boolean(vendorCodeInput) || Boolean(vendorNameInput);
  const vendorLookupToken = `${vendorCodeInput.trim().toLowerCase()}::${vendorNameInput.trim().toLowerCase()}`;

  const productsQuery = useQuery({
    ...createSharedQueries.products(
      effectiveWarehouseCode || undefined,
      debouncedProductSearch.trim() || undefined,
      debouncedProductSearch.trim() ? undefined : productQueryLimit,
      "purchase",
    ),
    enabled: productPopupOpen && vendorSelected,
  });

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDebouncedProductSearch(productSearch.trim());
    }, 180);
    return () => window.clearTimeout(timer);
  }, [productSearch]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setProductQueryLimit(QUICK_PRODUCT_LIMIT);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [debouncedProductSearch, vendorSelected, productPopupOpen]);

  const prefetchProducts = useCallback(() => {
    if (!vendorSelected) {
      return;
    }
    void queryClient.prefetchQuery(
      createSharedQueries.products(
        effectiveWarehouseCode || undefined,
        productSearch.trim() || undefined,
        QUICK_PRODUCT_LIMIT,
        "purchase",
      ),
    );
  }, [vendorSelected, effectiveWarehouseCode, productSearch, queryClient]);

  useEffect(() => {
    if (!vendorSelected) {
      return;
    }
    prefetchProducts();
  }, [vendorLookupToken, vendorSelected, prefetchProducts]);

  const productWarehouseStocksQuery = useQuery({
    ...createSharedQueries.productWarehouseStocks(stockPreviewProduct?.code),
    enabled: Boolean(stockPreviewProduct?.code),
  });

  const editDetailQuery = useQuery({
    ...apInvoiceQueries.detailByDocNum(editDocNum),
    enabled: isEditMode && Boolean(editDocNum),
  });

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === "Closed" ||
    editDetailQuery.data?.data?.DocStatus === "C";
  const docStatus =
    editDetailQuery.data?.data?.DocStatus === "O"
      ? "Open"
      : editDetailQuery.data?.data?.DocStatus === "C"
        ? "Closed"
        : (editDetailQuery.data?.data?.DocStatus ?? "Open");

  useEffect(() => {
    if (!isEditMode) {
      resetAPInvoiceCreate();
      hydratedDocNumRef.current = null;
    }
    return () => {
      resetAPInvoiceCreate();
    };
  }, [isEditMode, resetAPInvoiceCreate]);

  useEffect(() => {
    if (header.warehouseCode && warehouses.length > 0) {
      const matched = warehouses.find(
        (w) => String(w.code).trim() === String(header.warehouseCode).trim(),
      );
      if (matched && warehouseInput !== formatWarehouseDisplay(matched.name, matched.code)) {
        setWarehouseInput(formatWarehouseDisplay(matched.name, matched.code));
      }
    }
  }, [header.warehouseCode, warehouses, warehouseInput]);

  // Edit Mode Hydration
  useEffect(() => {
    if (!isEditMode) {
      return;
    }
    const currentDocNum = editDocNum;
    if (!currentDocNum) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    if (hydratedDocNumRef.current === currentDocNum && isMetadataLoaded) {
      return;
    }

    // Show loading toast when starting edit hydration
    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast("A/P Invoice", "edit");
    }

    void (async () => {
      setVendorCodeInput(String(detail.CardCode ?? "").trim());
      setVendorNameInput(String(detail.CardName ?? "").trim());
      const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
      const { comments: remarks, referenceNo } = parseAPInvoiceHeaderNotes(detail);

      const matchedVendor = vendors.find(
        (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
      );
      const buyerFromDocCode =
        detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(detail.SalesPersonCode),
            )?.name
          : "";

      setBuyerInput(buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "");
      const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);
      const resolvedHeaderDiscountPercent = Number(
        (detail as Record<string, unknown>).DiscountPercent ?? 0,
      );
      setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

      setHeader({
        docDate: loadedDocDate,
        docDueDate,
        referenceNo,
        remarks,
      });
      // Set addresses from document: Address = Bill To, Address2 = Ship To
      setBillToAddress(String(detail.Address ?? "").trim());
      setShipToAddress(String((detail as Record<string, unknown>).Address2 ?? "").trim());
      const detailLines = detail.DocumentLines ?? [];

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        detailLines.map((line) => String(line.ItemCode ?? "").trim()),
        "purchase",
      );

      const mappedLines = (detail.DocumentLines ?? []).map((line, index) => {
        const quantity = Math.max(0, Number(line.Quantity ?? 0));
        const price = Number(line.Price ?? line.UnitPrice ?? 0);
        const grossAmount = Math.max(0, price * quantity);
        const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
          grossAmount,
          headerDiscountPercent: resolvedHeaderDiscountPercent,
          line: line as unknown as Record<string, unknown>,
        });
        const itemCode = String(line.ItemCode ?? "").trim();

        return {
          id: `${currentDocNum}-${index}`,
          productCode: String(line.ItemCode ?? "").trim(),
          productName: String(line.ItemDescription ?? line.ItemCode ?? "").trim(),
          stock: 0, // In edit mode, stock is less relevant for invoices
          currency: String(detail.DocCurr ?? "").trim(),
          vatGroup: String(line.TaxCode ?? "").trim(),
          // SAP line tax is authoritative; fall back to product master only when missing
          taxRate:
            (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
            taxRateByItemCode.get(itemCode) ||
            0,
          uomCode: String(line.UoMCode ?? "").trim(),
          uomEntry: typeof line.UoMEntry === "number" ? line.UoMEntry : undefined,
          baseQuantity: quantity,
          quantity,
          discountPercent,
          discountAmount,
          comment: "",
          price,
          warehouseCode: String(line.WarehouseCode ?? "").trim(),
          baseEntry: typeof line.BaseEntry === "number" ? line.BaseEntry : undefined,
          baseLine: typeof line.BaseLine === "number" ? line.BaseLine : undefined,
          baseType: typeof line.BaseType === "number" ? line.BaseType : undefined,
          selected: false,
        };
      });
      setLines(mappedLines);
      const warehouseCode = String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
      const matchedWarehouse = warehouses.find((w) => String(w.code).trim() === warehouseCode);
      setWarehouseInput(
        formatWarehouseDisplay(matchedWarehouse?.name ?? warehouseCode, warehouseCode),
      );

      if (isMetadataLoaded) {
        hydratedDocNumRef.current = currentDocNum;
      }
      setHydratedDocNum(currentDocNum);
      // Dismiss loading toast when edit hydration is complete
      loadingToastRef.current?.dismiss();
      loadingToastRef.current = null;
    })();
  }, [
    editDocNum,
    editDetailQuery.data,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
  ]);

  // Copy-From Hydration (GRPO or PO) — supports multi-doc, single type
  useEffect(() => {
    if (mode !== "create") {
      return;
    }
    const currentSourceDocNum = sourceDocNum;
    const currentSourceDocType = sourceDocType;
    if (!currentSourceDocNum || !currentSourceDocType) {
      return;
    }

    const sourceDocNums = currentSourceDocNum
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (sourceDocNums.length === 0) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    const hydrationKey = `${currentSourceDocType}-${currentSourceDocNum}`;
    if (hydratedDocNumRef.current === hydrationKey && isMetadataLoaded) {
      return;
    }

    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast("A/P Invoice", "create");
    }

    const fetchAllSources = async () => {
      const details = await Promise.all(
        sourceDocNums.map(async (num) => {
          if (currentSourceDocType === "GoodsReceiptPO") {
            const res = await queryClient.fetchQuery(grpoQueries.detailByDocNum(num));
            return res.data;
          }
          if (currentSourceDocType === "PurchaseQuotation") {
            const res = await queryClient.fetchQuery(purchaseQuotationQueries.detailByDocNum(num));
            return res.data;
          }
          const res = await queryClient.fetchQuery(purchaseOrderQueries.detailByDocNum(num));
          return res.data;
        }),
      );

      const primaryDetail = details[0]!;
      const vendorCode = String(primaryDetail.CardCode ?? "").trim();
      const vendorName = String(primaryDetail.CardName ?? "").trim();
      const matchedVendor = vendors.find((v) => String(v.code).trim() === vendorCode);

      const buyerFromDocCode =
        primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(primaryDetail.SalesPersonCode),
            )?.name
          : "";
      const buyerName = buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "";

      const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
      const sourceComments = String(primaryDetail.Comments ?? "").trim();

      const refs = sourceDocNums.map((num) =>
        generateSingleSourceReference(currentSourceDocType, num),
      );
      const autoReference = refs.length === 1 ? refs[0]! : refs.join("\n");

      // Extract existing "Based on" chain from source comments
      const commentLines = sourceComments
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean);
      const refLinesFromComments = commentLines.filter((line) => /^based on /i.test(line));

      // Build remarks: existing ref chain + new auto-ref + user remarks from source
      const userRemarks = commentLines
        .filter((line) => !/^based on /i.test(line))
        .join("\n")
        .trim();
      const remarksParts = [refLinesFromComments.join("\n"), autoReference, userRemarks]
        .filter(Boolean)
        .join("\n")
        .trim();

      const referenceWasAutoFilled = true;
      const docDueDate = String(primaryDetail.DocDueDate ?? "").slice(0, 10);

      const allDetailLines = details.flatMap((d) => d.DocumentLines ?? []);
      const baseType =
        currentSourceDocType === "GoodsReceiptPO"
          ? 20
          : currentSourceDocType === "PurchaseQuotation"
            ? 540000006
            : 22;
      const currency = String(primaryDetail.DocCurr ?? "").trim();

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        allDetailLines.map((line) => String(line.ItemCode ?? "").trim()),
        "purchase",
      );
      const resolvedHeaderDiscountPercent = Number(
        (primaryDetail as Record<string, unknown>).DiscountPercent ?? 0,
      );
      setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

      let lineIndex = 0;
      const mappedLines = details.flatMap((detail) => {
        const detailLines = detail.DocumentLines ?? [];
        return detailLines.map((line) => {
          const idx = lineIndex++;
          const lineData = line as Record<string, unknown>;
          // For Purchase Quotation sources (baseType 540000006), the user-entered
          // quantity lives in PQT1.PQTReqQty (Service Layer: RequiredQuantity),
          // while PQT1.Quantity stays 0. Prefer RequiredQuantity as a fallback
          // so the copied-to AP Invoice receives the same quantity the user requested.
          const openQty = Number(
            lineData.OpenQty ??
              lineData.OpenQuantity ??
              lineData.RequiredQuantity ??
              lineData.requiredQuantity ??
              line.Quantity ??
              1,
          );
          const quantity = openQty;
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line: line as unknown as Record<string, unknown>,
          });
          const itemCode = String(line.ItemCode ?? "").trim();

          return {
            id: `row-copy-${detail.DocEntry ?? detail.id ?? "unknown"}-${idx}`,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? line.ItemCode ?? "").trim(),
            stock: 0,
            currency,
            vatGroup: String(line.TaxCode ?? "").trim(),
            // SAP line tax is authoritative; fall back to product master only when missing
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? "").trim(),
            uomEntry: typeof line.UoMEntry === "number" ? line.UoMEntry : undefined,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: String(line.WarehouseCode ?? warehouseCode).trim(),
            baseEntry: detail.DocEntry ?? (detail as { id?: number }).id,
            baseLine: line.LineNum ?? idx,
            baseType,
            selected: false,
          };
        });
      });

      const sourceNumAtCard = String(
        (primaryDetail as { NumAtCard?: string }).NumAtCard ?? "",
      ).trim();
      setVendorCodeInput(vendorCode);
      setVendorNameInput(vendorName);
      setBuyerInput(buyerName);
      const matchedWarehouseCopy = warehouses.find((w) => String(w.code).trim() === warehouseCode);
      setWarehouseInput(
        formatWarehouseDisplay(matchedWarehouseCopy?.name ?? warehouseCode, warehouseCode),
      );
      setBillToAddress(
        String(primaryDetail.Address ?? "").trim() || matchedVendor?.billToAddress || "",
      );
      setShipToAddress(
        String((primaryDetail as Record<string, unknown>).Address2 ?? "").trim() ||
          matchedVendor?.shipToAddress ||
          matchedVendor?.billToAddress ||
          "",
      );
      setHeader({
        docDate: getTodayISO(),
        docDueDate,
        referenceAutoFilled: referenceWasAutoFilled,
        referenceNo: sourceNumAtCard,
        remarks: remarksParts,
      });
      setLines(mappedLines);
      setProductRowDrafts({});
      if (isMetadataLoaded) {
        hydratedDocNumRef.current = hydrationKey;
      }
      loadingToastRef.current?.dismiss();
      loadingToastRef.current = null;
    };

    void fetchAllSources();
  }, [
    mode,
    sourceDocNum,
    sourceDocType,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    setProductRowDrafts,
    vendors,
  ]);

  const { vendorNameSuggestions, vendorCodeSuggestions, warehouseSuggestions, buyerSuggestions } =
    useAPInvoiceLookups({
      buyerInput,
      buyers: salesEmployees,
      vendorCodeInput,
      vendorNameInput,
      vendors,
      warehouseInput,
      warehouses,
    });

  const openPopupByMode = (mode: PopupMode) => {
    const searchVal =
      mode === "vendor-name" || mode === "vendor-code"
        ? mode === "vendor-name"
          ? vendorNameInput
          : vendorCodeInput
        : mode === "warehouse"
          ? warehouseInput
          : buyerInput;

    setModalMode(mode);
    setModalSearch(searchVal);
    setModalOpen(true);
  };

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onSalesEmployee: handleBuyerChange,
      onVendorCode: handleVendorCodeChange,
      onVendorName: handleVendorNameChange,
      onWarehouse: handleWarehouseInputChange,
    });

  useEffect(() => {
    if (!modalOpen) {
      return;
    }
    const nextSearch = getLookupInlineSearchByMode(modalMode, {
      salesEmployee: buyerInput,
      vendorCode: vendorCodeInput,
      vendorName: vendorNameInput,
      warehouse: warehouseInput,
    });
    if (nextSearch !== modalSearch) {
      setModalSearch(nextSearch);
    }
  }, [
    buyerInput,
    modalMode,
    modalOpen,
    modalSearch,
    setModalSearch,
    vendorCodeInput,
    vendorNameInput,
    warehouseInput,
  ]);

  const selectVendor = (vendor: LookupItem) => {
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor });
      return;
    }
    applyVendorChange(vendor);
  };

  const applyVendorChange = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);

    setWarehouseInput("");
    setLines([]);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
  };

  const handleVendorNameChange = (value: string) => {
    setVendorNameInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined }));
    if (value.trim() === "") {
      setVendorNameFocused(true);
      setVendorCodeInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.name.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      setVendorCodeInput(matched.code);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorCodeInput("");
    setBuyerInput("");
    setLines([]);
    setVendorNameFocused(true);
  };

  const handleVendorCodeChange = (value: string) => {
    setVendorCodeInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorCode: undefined }));
    if (value.trim() === "") {
      setVendorCodeFocused(true);
      setVendorNameInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.code.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      if (hasCopiedRows) {
        setPendingVendorChange({ vendor: matched });
        return;
      }
      setVendorNameInput(matched.name);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorNameInput("");
    setBuyerInput("");
    setLines([]);
    setVendorCodeFocused(true);
  };

  /* ---------- vendor-change confirmation handlers ---------- */
  const confirmVendorChange = () => {
    const pending = pendingVendorChange;
    if (!pending) {
      return;
    }
    setPendingVendorChange(null);

    // Strip only auto-generated "Based on..." references from remarks, keep user remarks
    const cleanedRemarks = stripAutoGeneratedReferences(header.remarks);
    setHeader({ remarks: cleanedRemarks });

    // Clear base linkage from all rows (break copy-from link) but keep row data
    setLines((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row;
        return rest;
      }),
    );

    // Apply the new vendor (without clearing lines/warehouse)
    applyVendorChangeForConfirmation(pending.vendor);
  };

  const cancelVendorChange = () => {
    setPendingVendorChange(null);
  };

  /** Apply vendor without clearing lines/warehouse — used only during vendor-change confirmation. */
  const applyVendorChangeForConfirmation = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
  };

  const handleWarehouseInputChange = (value: string) => {
    setWarehouseInput(value);
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }));
    if (value.trim() === "") {
      setWarehouseFocused(true);
      setHeader({ warehouseCode: "" });
      return;
    }
    const matched = warehouses.find(
      (w) =>
        w.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        w.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      selectWarehouse(matched);
      return;
    }
    setHeader({ warehouseCode: "" });
  };

  const handleBuyerChange = (value: string) => {
    setBuyerInput(value);
    setFieldErrors((prev) => ({ ...prev, salesEmployee: undefined }));
    const matched = salesEmployees.find(
      (s) =>
        s.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        s.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      setBuyerFocused(false);
    }
  };

  const openProductPopup = (rowId: string | null = null) => {
    setActiveProductRowId(rowId);
    if (!vendorNameInput.trim() || !vendorCodeInput.trim()) {
      setFieldErrors((prev) => ({
        ...prev,
        vendorCode: !vendorCodeInput.trim() ? AP_INVOICE_FIELD_ERROR_TEXT.vendorCode : undefined,
        vendorName: !vendorNameInput.trim() ? AP_INVOICE_FIELD_ERROR_TEXT.vendorName : undefined,
      }));
      return;
    }

    setProductPopupOpen(true);
  };

  const selectWarehouse = (warehouse: LookupItem) => {
    setWarehouseInput(formatWarehouseDisplay(warehouse.name, warehouse.code));
    setHeader({ warehouseCode: warehouse.code });
    setLines((prev) => prev.map((row) => ({ ...row, warehouseCode: warehouse.code })));
    setWarehouseFocused(false);
  };

  const selectBuyer = (item: LookupItem) => {
    setBuyerInput(item.name);
    setBuyerFocused(false);
  };

  const applyProductToRow = (product: ProductLookupItem) => {
    setLines((prev) => {
      if (activeProductRowId) {
        // Updating an existing row: leave the user-chosen warehouse untouched.
        return prev.map((row) =>
          row.id === activeProductRowId
            ? {
                ...row,
                price: Number(product.price ?? 0),
                productCode: product.code,
                productName: product.name,
                quantity: 1,
                stock: Number(product.stock ?? 0),
                uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
                uomEntry: product.purchaseUomEntry ?? product.uomEntry,
                warehouseCode: effectiveWarehouseCode || "",
              }
            : row,
        );
      }
      // New row: force user to pick a warehouse explicitly.
      return [
        ...prev,
        {
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: Number(product.stock ?? 0),
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: effectiveWarehouseCode || "",
        },
      ];
    });
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const applyProductsToRows = (products: ProductLookupItem[]) => {
    setLines((prev) => [
      ...prev,
      ...products.map((product) => ({
        comment: "",
        currency: String(product.currency ?? ""),
        discountAmount: 0,
        discountPercent: 0,
        id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        price: Number(product.price ?? 0),
        productCode: product.code,
        productName: product.name,
        quantity: 1,
        selected: false,
        stock: Number(product.stock ?? 0),
        taxRate: Number(product.taxRate ?? 0),
        uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
        uomEntry: product.purchaseUomEntry ?? product.uomEntry,
        vatGroup: String(product.vatGroup ?? ""),
        warehouseCode: effectiveWarehouseCode || "",
      })),
    ]);
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const handleCreateAPInvoice = async () => {
    setSubmitAttempted(true);
    if (!isEditMode) {
      const missing = AP_INVOICE_MANDATORY_FIELDS.filter((field) => {
        if (field === "vendorName") {
          return !vendorNameInput.trim();
        }
        if (field === "vendorCode") {
          return !vendorCodeInput.trim();
        }
        return false;
      });

      if (missing.length > 0) {
        const nextErrors = { ...EMPTY_AP_INVOICE_FIELD_ERRORS };
        missing.forEach((field) => {
          nextErrors[field] = AP_INVOICE_FIELD_ERROR_TEXT[field];
        });
        setFieldErrors(nextErrors);
        setCreateError("Fill required fields before creating A/P Invoice.");
        return;
      }
    }

    if (filteredRows.length === 0) {
      setCreateError("Set at least one line quantity greater than 0.");
      return;
    }


    const toastHandle = documentActionToast("A/P Invoice", isEditMode ? "update" : "create");
    try {
      let createdDocNum: number | undefined;
      if (isEditMode) {
        const detail = editDetailQuery.data?.data;
        const existingDocDueDate = String(detail?.DocDueDate ?? "")
          .slice(0, 10)
          .trim();
        const { comments: existingComments, referenceNo: existingReferenceNo } = detail
          ? parseAPInvoiceHeaderNotes(detail)
          : { comments: "", referenceNo: "" };
        const currentDocDueDate = String(header.docDueDate ?? "").trim();
        const currentComments = String(header.remarks ?? "").trim();
        const currentReferenceNo = String(header.referenceNo ?? "").trim();

        if (
          currentDocDueDate === existingDocDueDate &&
          currentComments === existingComments.trim() &&
          currentReferenceNo === existingReferenceNo
        ) {
          const noChangeMessage = "Change at least one field before update.";
          setCreateError(noChangeMessage);
          goeyToast.error(noChangeMessage, { id: "no-change-update-toast" });
          return;
        }

        const id = editDetailQuery.data?.data?.id ?? editDetailQuery.data?.data?.DocEntry;
        const updatePayload = {
          Comments: header.remarks.trim() || undefined,
          DocDueDate: header.docDueDate || undefined,
          NumAtCard: header.referenceNo.trim() || undefined,
        };
        await updateMutation.mutateAsync({ id: id!, payload: updatePayload });
      } else {
        const buildDocumentLines = (): CreateAPInvoiceInput["DocumentLines"] => {
          const lines: CreateAPInvoiceInput["DocumentLines"] = [];
          for (const row of filteredRows) {
            // Guard: never send zero-quantity lines
            if (row.quantity <= 0) {
              continue;
            }

            const hasCompleteBaseLink =
              Number.isFinite(row.baseEntry) &&
              Number.isFinite(row.baseLine) &&
              Number.isFinite(row.baseType);

            // Manual rows (no base link): send single line with actual quantity
            if (!hasCompleteBaseLink) {
              lines.push({
                DiscountPercent: row.discountPercent,
                ItemCode: row.productCode,
                Quantity: row.quantity,
                UnitPrice: row.price,
                UoMCode: row.uomCode || undefined,
                VatGroup: row.vatGroup || undefined,
                WarehouseCode: row.warehouseCode || undefined,
              });
              continue;
            }

            // Base-linked rows: split into base qty and excess portions
            const baseQty = row.baseQuantity ?? 0;
            const linkedQty = Math.min(row.quantity, baseQty);

            // Only push base-linked portion if quantity is positive
            if (linkedQty > 0) {
              lines.push({
                BaseEntry: row.baseEntry,
                BaseLine: row.baseLine,
                BaseType: row.baseType,
                DiscountPercent: row.discountPercent,
                ItemCode: row.productCode,
                Quantity: linkedQty,
                UnitPrice: row.price,
                UoMCode: row.uomCode || undefined,
                VatGroup: row.vatGroup || undefined,
                WarehouseCode: row.warehouseCode || undefined,
              });
            }

            // Excess portion: manual line without base linkage
            const excessQty = row.quantity - baseQty;
            if (excessQty > 0) {
              lines.push({
                DiscountPercent: row.discountPercent,
                ItemCode: row.productCode,
                Quantity: excessQty,
                UnitPrice: row.price,
                UoMCode: row.uomCode || undefined,
                VatGroup: row.vatGroup || undefined,
                WarehouseCode: row.warehouseCode || undefined,
              });
            }
          }
          return lines;
        };

        const createPayload = {
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          CardCode: vendorCodeInput.trim(),
          Comments: header.remarks.trim() || undefined,
          DocDate: header.docDate || undefined,
          DocDueDate: header.docDueDate || undefined,
          DocumentLines: buildDocumentLines(),
          NumAtCard: header.referenceNo.trim() || undefined,
        };
        const result = await createMutation.mutateAsync({
          payload: createPayload,
        });
        createdDocNum = result?.data?.DocNum;
      }
      toastHandle.success(createdDocNum);
      if (isEditMode) {
        setWarehouseInput("");
        setHeader({ warehouseCode: "" });
      }
      if (!isEditMode) {
        resetAPInvoiceCreate();
        setVendorNameInput("");
        setVendorCodeInput("");
        setBuyerInput("");
        setWarehouseInput("");
        setBillToAddress("");
        setShipToAddress("");
        setVendorNameFocused(false);
        setVendorCodeFocused(false);
        setBuyerFocused(false);
        setWarehouseFocused(false);
        setActiveDatePicker(null);
        setModalOpen(false);
        setModalMode("vendor-name");
        setModalSearch("");
        setProductSearch("");
        setDebouncedProductSearch("");
        setActiveProductRowId(null);
        setProductPopupOpen(false);
        setProductRowDrafts({});
        setStockPreviewProduct(null);
        setFieldErrors(EMPTY_AP_INVOICE_FIELD_ERRORS);
        setCreateError(null);
        hydratedDocNumRef.current = null;
        setHydratedDocNum(null);

        // Invalidate the specific source document detail queries used by copy-from hydration
        // so the next AP Invoice copy reads fresh OpenQty / status from the backend
        if (sourceDocNum) {
          if (sourceDocType === "PurchaseOrder") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: purchaseOrderQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
            void queryClient.invalidateQueries({ queryKey: purchaseOrderKeys.all });
          } else if (sourceDocType === "GoodsReceiptPO") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: grpoQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
            void queryClient.invalidateQueries({ queryKey: grpoKeys.all });
          } else if (sourceDocType === "PurchaseQuotation") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: purchaseQuotationQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
            void queryClient.invalidateQueries({ queryKey: purchaseQuotationKeys.all });
          }
        }
      }
      setSubmitAttempted(false);

      // Scroll to top after successful save
      window.scrollTo({ behavior: "smooth", top: 0 });

      // Notify parent to navigate away after successful create
      if (!isEditMode) {
        onCreateSuccess?.();
      }
    } catch (error) {
      toastHandle.error();
      const errorMsg = normalizeCreateOrderErrorMessage(error, "Failed to process A/P Invoice.");
      setCreateError(errorMsg);
    }
  };

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) {
      return [];
    }
    return AP_INVOICE_MANDATORY_FIELDS.filter((field) => {
      if (field === "vendorName") {
        return !vendorNameInput.trim();
      }
      if (field === "vendorCode") {
        return !vendorCodeInput.trim();
      }
      return false;
    });
  }, [isEditMode, vendorNameInput, vendorCodeInput, rows]);

  const requiredCompletionPercent = useMemo(
    () =>
      ((AP_INVOICE_MANDATORY_FIELDS.length - missingMandatoryFields.length) /
        AP_INVOICE_MANDATORY_FIELDS.length) *
      100,
    [missingMandatoryFields],
  );

  return {
    isEditMode,
    isEditHydrated: !isEditMode || hydratedDocNum === editDocNum,
    isSourceHydrating: mode === "create" && Boolean(sourceDocNum) && !hydratedDocNumRef.current,
    today,
    activeDatePicker,
    setActiveDatePicker,
    docDateContainerRef,
    deliveryDateContainerRef,
    handleDocDateChange: (val: string) => setHeader({ docDate: val }),
    handleDocDueDateChange: (val: string) => setHeader({ docDueDate: val }),
    showEditRestrictedToast: notifyRestricted,

    vendorsQuery,
    warehousesQuery,
    salesEmployeesQuery,
    financialPeriodQuery,
    productsQuery,
    productWarehouseStocksQuery,
    editDetailQuery,
    createMutation,
    updateMutation,

    vendorNameSuggestions,
    vendorCodeSuggestions,
    warehouseSuggestions,
    buyerSuggestions,
    vendors,
    warehouses,
    salesEmployees,

    vendorNameInput,
    vendorCodeInput,
    warehouseInput,
    buyerInput,
    vendorNameFocused,
    setVendorNameFocused,
    vendorCodeFocused,
    setVendorCodeFocused,
    buyerFocused,
    setBuyerFocused,
    warehouseFocused,
    setWarehouseFocused,
    docDate: header.docDate,
    docDueDate: header.docDueDate,
    referenceNo: header.referenceNo,
    referenceAutoFilled: header.referenceAutoFilled,
    remarks: header.remarks,
    headerDiscountPercent,
    billToAddress,
    shipToAddress,
    isClosed,
    docStatus,
    products: productsQuery.data ?? [],

    modalOpen,
    modalMode,
    modalSearch,
    setModalOpen,
    setModalSearch,
    openPopup: openPopupByMode,
    handleLookupModalSearchSync,
    popupResults: useMemo(
      () =>
        filterAndRankLookups(
          modalMode.includes("vendor")
            ? vendors
            : modalMode === "warehouse"
              ? warehouses
              : salesEmployees,
          modalSearch,
        ),
      [vendors, warehouses, salesEmployees, modalSearch, modalMode],
    ),

    productPopupOpen,
    productSearch,
    setProductPopupOpen,
    setProductSearch,
    activeProductRowId,
    openProductPopup,
    loadMoreProducts: () => {
      if (!productPopupOpen) {
        return;
      }
      if (productsQuery.isFetching) {
        return;
      }
      const currentCount = productsQuery.data?.length ?? 0;
      if (currentCount < productQueryLimit) {
        return;
      }
      if (debouncedProductSearch.trim().length > 0) {
        return;
      }
      if (productQueryLimit >= 50) {
        return;
      }
      setProductQueryLimit((prev) => Math.min(prev + 10, 50));
    },
    applyProductToRow,
    applyProductsToRows,
    prefetchProducts: isEditMode ? () => {} : prefetchProducts,
    // Derive the product code of the currently active row for seeding modal selection
    activeRowProductCode: (() => {
      if (!activeProductRowId) {
        return null;
      }
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      return activeRow?.productCode ?? null;
    })(),
    isLookupLoading: modalMode.includes("vendor")
      ? vendorsQuery.isLoading
      : modalMode === "warehouse"
        ? warehousesQuery.isLoading
        : salesEmployeesQuery.isLoading,
    lookupError:
      (modalMode.includes("vendor")
        ? vendorsQuery.error
        : modalMode === "warehouse"
          ? warehousesQuery.error
          : salesEmployeesQuery.error
      )?.message ?? null,
    isProductsLoading: productsQuery.isLoading,
    productsError: productsQuery.error?.message ?? null,
    warehouseCode: effectiveWarehouseCode,

    rows,
    productRowDrafts,
    setProductRowDraft: (id: string, field: string, value: string) =>
      setProductRowDrafts((prev) => ({
        ...prev,
        [id]: { ...prev[id], [field]: value },
      })),
    clearProductRowDraft: (id: string, field: string) =>
      setProductRowDrafts((prev) => {
        const next = { ...prev[id] };
        delete next[field as keyof typeof next];
        return { ...prev, [id]: next };
      }),
    updateProductRow: (id: string, patch: Partial<APInvoiceCreateLine>) =>
      setLines((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r))),
    removeProductRow: (id: string) => setLines((prev) => prev.filter((r) => r.id !== id)),

    stockPreviewProduct,
    setStockPreviewProduct,
    openStockPreview: setStockPreviewProduct,

    fieldErrors,
    createError,
    createDisabledReason:
      missingMandatoryFields.length > 0
        ? "Mandatory fields missing"
        : rows.length === 0
          ? "No lines"
          : null,
    searchMandatoryFields: useMemo(() => ["vendorName", "vendorCode"] as const, []),
    missingSearchMandatoryFields: useMemo(
      () =>
        ["vendorName", "vendorCode"].filter(
          (field) =>
            !String(field === "vendorName" ? vendorNameInput : (vendorCodeInput ?? "")).trim(),
        ),
      [vendorNameInput, vendorCodeInput],
    ),
    searchRequiredCompletionPercent: useMemo(() => {
      const filled = (vendorNameInput.trim() ? 1 : 0) + (vendorCodeInput.trim() ? 1 : 0);
      return (filled / 2) * 100;
    }, [vendorNameInput, vendorCodeInput]),
    missingMandatoryFields,
    requiredCompletionPercent,
    requiredFieldsTotal: AP_INVOICE_MANDATORY_FIELDS.length,
    requiredFieldLabelText: AP_INVOICE_FIELD_LABEL_TEXT,
    handleCreateOrder: handleCreateAPInvoice,
    submitAttempted,
    warehouseErrors,

    setDocDate: (val: string) => setHeader({ docDate: val }),
    setDocDueDate: (val: string) =>
      isClosed ? notifyRestricted("Due Date") : setHeader({ docDueDate: val }),
    setBuyerInput: (val: string) =>
      isEditMode ? notifyRestricted("Buyer") : handleBuyerChange(val),
    setWarehouseInput: (val: string) =>
      isEditMode ? notifyRestricted("Warehouse") : handleWarehouseInputChange(val),
    setReferenceNo: (val: string) => setHeader({ referenceNo: val }),
    setRemarks: (val: string) => setHeader({ remarks: val }),
    setBillToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Bill To Address") : setBillToAddress(val),
    setShipToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Ship To Address") : setShipToAddress(val),
    selectVendor: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Vendor") : selectVendor(val),
    selectWarehouse: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Warehouse") : selectWarehouse(val),
    selectSalesEmployee: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Sales Employee") : selectBuyer(val),
    handleVendorNameChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Name") : handleVendorNameChange(val),
    handleVendorCodeChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Code") : handleVendorCodeChange(val),

    // Vendor-change confirmation (copy-from guard)
    pendingVendorChange,
    hasCopiedRows,
    confirmVendorChange,
    cancelVendorChange,
  };
}
