import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { AttachmentItem } from "@/features/create-pages/create-shared/components/grids/upload-grid";

import {
  useCreateAPInvoice,
  useUpdateAPInvoice,
} from "@/features/create-pages/ap-invoice-create/api/ap-invoice-create.mutations";
import { useAPInvoiceLookups } from "@/features/create-pages/ap-invoice-create/hooks/use-ap-invoice-lookups";
import {
  AP_INVOICE_FIELD_ERROR_TEXT,
  AP_INVOICE_FIELD_LABEL_TEXT,
  AP_INVOICE_MANDATORY_FIELDS,
  EMPTY_AP_INVOICE_FIELD_ERRORS,
  filterAndRankLookups,
  getTodayISO,
} from "@/features/create-pages/ap-invoice-create/utils/ap-invoice-create.utils";
import type { APInvoiceFieldErrors } from "@/features/create-pages/ap-invoice-create/utils/ap-invoice-create.utils";
import { createSharedQueries } from "@/features/create-pages/create-shared/api/create-shared.queries";
import type {
  LookupItem,
  ProductLookupItem,
  ProductWarehouseStockItem,
} from "@/features/create-pages/create-shared/api/create-shared.types";
import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import { parseDocumentHeaderNotes } from "@/features/create-pages/create-shared/utils/parse-header-notes";
import type {
  ActiveDatePicker,
  PopupMode,
  ProductRowDraft,
  StockPreviewProduct,
} from "@/features/create-pages/create-shared/utils/create-order.types";
import {
  formatWarehouseDisplay,
  normalizeCreateOrderErrorMessage,
} from "@/features/create-pages/create-shared/utils/create-order.utils";
import {
  notifyCreateApiError,
  notifyEditRestrictedField,
} from "@/features/create-pages/create-shared/utils/create-feedback-toast";
import { useDocumentSaveActions } from "@/features/create-pages/create-shared/hooks/use-document-save-actions";
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from "@/features/create-pages/create-shared/utils/lookup-search-sync";
import {
  firstRequiredLotError,
  lotFieldsFromProduct,
  sapLotFieldsFromRow,
} from "@/features/create-pages/create-shared/utils/product-lot-allocations";
import {
  resolveHydrateProductMeta,
  taxRatesFromProductMeta,
} from "@/features/create-pages/create-shared/utils/hydrate-product-meta";
import { resolveDocumentLineDiscount } from "@/features/create-pages/create-shared/utils/resolve-document-line-discount";
import { apInvoiceQueries } from "@/features/table-pages/ap-invoices/api/ap-invoice.queries";
import type { CreateAPInvoiceInput } from "@/features/table-pages/ap-invoices/api/ap-invoice.service";
import { grpoKeys, grpoQueries } from "@/features/table-pages/grpo/api/grpo.queries";
import {
  purchaseOrderKeys,
  purchaseOrderQueries,
} from "@/features/table-pages/purchase-orders/api/purchase-order.queries";
import {
  purchaseQuotationKeys,
  purchaseQuotationQueries,
} from "@/features/table-pages/purchase-quotations/api/purchase-quotation.queries";
import {
  useAPInvoiceHeader,
  useAPInvoiceLines,
  useResetAPInvoiceCreateAction,
  useSetAPInvoiceHeaderAction,
  useSetAPInvoiceLinesAction,
} from "@/store/create/ap-invoice-create.store";

import {
  generateSingleSourceReference,
  isAutoGeneratedRemarkLine,
  stripAutoGeneratedReferences,
} from "../../create-shared/utils/auto-reference";

export interface APInvoiceCreateLine {
  id: string;
  productCode: string;
  productName: string;
  stock: number;
  currency: string;
  vatGroup: string;
  taxRate: number;
  uomCode?: string | undefined;
  uomEntry?: number | undefined;
  baseQuantity?: number | undefined;
  quantity: number;
  discountPercent: number;
  discountAmount: number;
  comment: string;
  price: number;
  warehouseCode: string;
  baseLine?: number | undefined;
  baseEntry?: number | undefined;
  baseType?: number | undefined;
}
const QUICK_PRODUCT_LIMIT = 10;
const BROWSE_PRODUCT_LIMIT = 50;

interface UseAPInvoiceCreateOptions {
  mode?: "create" | "edit";
  docNum?: string;
  sourceDocNum?: string | undefined;
  sourceDocType?: "PurchaseOrder" | "GoodsReceiptPO" | "PurchaseQuotation" | undefined;
  draftDocNum?: string | undefined;
  draftDocEntry?: string | undefined;
  onCreateSuccess?: () => void;
}

const normalizeCodeForCompare = (value: unknown) => {
  const raw = String(value ?? "").trim();
  if (!raw) {
    return "";
  }
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
};

export function useAPInvoiceCreate({
  mode = "create",
  docNum,
  sourceDocNum,
  sourceDocType,
  draftDocNum,
  draftDocEntry,
  onCreateSuccess,
}: UseAPInvoiceCreateOptions) {
  const parseAPInvoiceHeaderNotes = parseDocumentHeaderNotes;
  const isEditMode = mode === "edit";
  const editDocNum = (docNum ?? "").trim();
  const queryClient = useQueryClient();
  const header = useAPInvoiceHeader();
  const setHeader = useSetAPInvoiceHeaderAction();
  const rows = useAPInvoiceLines();
  const filteredRows = useMemo(() => rows.filter((r) => r.quantity > 0), [rows]);
  const setLines = useSetAPInvoiceLinesAction();
  const resetAPInvoiceCreate = useResetAPInvoiceCreateAction();
  const createMutation = useCreateAPInvoice();
  const updateMutation = useUpdateAPInvoice();
  const hydratedDocNumRef = useRef<string | null>(null);
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null);
  const [formSnapshot, setFormSnapshot] = useState<any>(null);
  const [vendorNameInput, setVendorNameInput] = useState("");
  const [vendorCodeInput, setVendorCodeInput] = useState("");
  const [vendorNameFocused, setVendorNameFocused] = useState(false);
  const [vendorCodeFocused, setVendorCodeFocused] = useState(false);
  const [buyerInput, setBuyerInput] = useState("");
  const [buyerFocused, setBuyerFocused] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<PopupMode>("vendor-name");
  const [modalSearch, setModalSearch] = useState("");
  const [productPopupOpen, setProductPopupOpen] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [debouncedProductSearch, setDebouncedProductSearch] = useState("");
  const [productQueryLimit, setProductQueryLimit] = useState(QUICK_PRODUCT_LIMIT);
  const [activeProductRowId, setActiveProductRowId] = useState<string | null>(null);
  const [warehouseInput, setWarehouseInput] = useState("");
  const [warehouseFocused, setWarehouseFocused] = useState(false);

  const resetWarehouse = useCallback(() => {
    setWarehouseInput("");
    setHeader({ warehouseCode: "" });
    setWarehouseFocused(false);
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }));
  }, [setHeader]);

  const [billToAddress, setBillToAddressRaw] = useState("");
  const [shipToAddress, setShipToAddressRaw] = useState("");

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value));
  }, []);
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value));
  }, []);

  const [productRowDrafts, setProductRowDrafts] = useState<Record<string, ProductRowDraft>>({});
  const [stockPreviewProduct, setStockPreviewProduct] = useState<StockPreviewProduct | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<APInvoiceFieldErrors>(
    EMPTY_AP_INVOICE_FIELD_ERRORS,
  );
  const [headerDiscountPercent, setHeaderDiscountPercent] = useState(0);
  const [attachments, setAttachments] = useState<AttachmentItem[]>([]);

  /* ---------- vendor-change confirmation (copy-from guard) ---------- */
  const [pendingVendorChange, setPendingVendorChange] = useState<{
    vendor: LookupItem;
  } | null>(null);
  const hasCopiedRows = useMemo(
    () => rows.some((r) => r.baseEntry != null && r.baseType != null),
    [rows],
  );

  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);

  const warehouseErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!submitAttempted) return errors;

    filteredRows.forEach((row) => {
      if (!row.warehouseCode.trim()) {
        errors[row.id] = "Warehouse is required.";
      }
    });
    return errors;
  }, [submitAttempted, filteredRows]);
  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null);
  const docDateContainerRef = useRef<HTMLDivElement>(null);
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null);

  const notifyRestricted = (fieldName = "Field") => {
    notifyEditRestrictedField(fieldName);
  };

  const vendorsQuery = useQuery(createSharedQueries.vendors());
  const warehousesQuery = useQuery(createSharedQueries.warehouses());
  const salesEmployeesQuery = useQuery(createSharedQueries.salesEmployees());
  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data]);
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data]);
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data]);
  const effectiveWarehouseCode = useMemo(() => {
    const lookup = warehouseInput.trim().toLowerCase();
    const match = lookup.match(/\[([^\]]+)\]$/) || lookup.match(/^\[([^\]]+)\]/);
    const codeOrName = match ? match[1]!.trim() : lookup;
    const matched = warehouses.find(
      (item) => item.name.toLowerCase() === codeOrName || item.code.toLowerCase() === codeOrName,
    );
    return matched?.code ?? lookup;
  }, [warehouseInput, warehouses]);

  const searchWarehouseCode = useMemo(() => {
    if (activeProductRowId) {
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      if (activeRow?.warehouseCode) {
        return activeRow.warehouseCode;
      }
    }
    return effectiveWarehouseCode || undefined;
  }, [activeProductRowId, rows, effectiveWarehouseCode]);

  const vendorSelected = Boolean(vendorCodeInput) || Boolean(vendorNameInput);
  const vendorLookupToken = `${vendorCodeInput.trim().toLowerCase()}::${vendorNameInput.trim().toLowerCase()}`;

  const productsQuery = useQuery({
    ...createSharedQueries.products(
      undefined, // Pass undefined to keep search warehouse-agnostic
      debouncedProductSearch.trim() || undefined,
      debouncedProductSearch.trim() ? BROWSE_PRODUCT_LIMIT : productQueryLimit,
      "purchase",
    ),
    enabled: productPopupOpen && vendorSelected,
  });

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDebouncedProductSearch(productSearch.trim());
    }, 180);
    return () => window.clearTimeout(timer);
  }, [productSearch]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setProductQueryLimit(QUICK_PRODUCT_LIMIT);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [debouncedProductSearch, vendorSelected, productPopupOpen]);

  const prefetchProducts = useCallback(() => {
    if (!vendorSelected) {
      return;
    }
    void queryClient.prefetchQuery(
      createSharedQueries.products(
        undefined, // Pass undefined to keep search warehouse-agnostic
        productSearch.trim() || undefined,
        QUICK_PRODUCT_LIMIT,
        "purchase",
      ),
    );
  }, [vendorSelected, productSearch, queryClient]);

  useEffect(() => {
    if (!vendorSelected) {
      return;
    }
    prefetchProducts();
  }, [vendorLookupToken, vendorSelected, prefetchProducts]);

  // After the quick first page settles, warm the full browse page so scroll load-more is instant.
  useEffect(() => {
    if (!productPopupOpen || !vendorSelected) {
      return;
    }
    if (debouncedProductSearch.trim()) {
      return;
    }
    if (productsQuery.isFetching || productsQuery.isError) {
      return;
    }
    if ((productsQuery.data?.length ?? 0) === 0) {
      return;
    }
    if (productQueryLimit >= BROWSE_PRODUCT_LIMIT) {
      return;
    }
    void queryClient.prefetchQuery(
      createSharedQueries.products(undefined, undefined, BROWSE_PRODUCT_LIMIT, "purchase"),
    );
  }, [
    productPopupOpen,
    vendorSelected,
    debouncedProductSearch,
    productsQuery.isFetching,
    productsQuery.isError,
    productsQuery.data,
    productQueryLimit,
    queryClient,
  ]);

  const productWarehouseStocksQuery = useQuery({
    ...createSharedQueries.productWarehouseStocks(stockPreviewProduct?.code),
    enabled: Boolean(stockPreviewProduct?.code),
  });

  const isDraftUpdate = !isEditMode && Boolean(draftDocNum);
  const fetchDocNum = isEditMode ? editDocNum : (draftDocNum ?? "");

  const editDetailQuery = useQuery({
    ...apInvoiceQueries.detailByDocNum(fetchDocNum, isEditMode ? undefined : draftDocEntry),
    enabled: (isEditMode && Boolean(editDocNum)) || (isDraftUpdate && Boolean(draftDocEntry)),
  });

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === "Closed" ||
    editDetailQuery.data?.data?.DocStatus === "C";

  const isDirty = useMemo(() => {
    if ((!isEditMode && !draftDocNum) || !formSnapshot) {
      return false;
    }
    const current = {
      remarks: (header.remarks || "").trim(),
      referenceNo: (header.referenceNo || "").trim(),
      docDueDate: header.docDueDate,
      billToAddress: formatAddressForDisplay(billToAddress).trim(),
      shipToAddress: formatAddressForDisplay(shipToAddress).trim(),
      attachments: attachments.map((att) => ({
        fileName: att.fileName,
        freeText: att.freeText || "",
      })),
      productRows: rows
        .filter((row) => row.productCode.trim() && row.quantity > 0)
        .map((row) => ({
          productCode: row.productCode,
          quantity: row.quantity,
          price: row.price,
          discountPercent: row.discountPercent,
          warehouseCode: row.warehouseCode,
          uomCode: row.uomCode,
          uomEntry: row.uomEntry,
        })),
    };
    return JSON.stringify(current) !== JSON.stringify(formSnapshot);
  }, [
    isEditMode,
    draftDocNum,
    formSnapshot,
    header.remarks,
    header.referenceNo,
    header.docDueDate,
    billToAddress,
    shipToAddress,
    attachments,
    rows,
  ]);

  const submitDisabled = isEditMode || Boolean(draftDocNum) ? !isDirty : false;
  const docStatus =
    editDetailQuery.data?.data?.DocStatus === "O"
      ? "Open"
      : editDetailQuery.data?.data?.DocStatus === "C"
        ? "Closed"
        : (editDetailQuery.data?.data?.DocStatus ?? "Open");

  useEffect(() => {
    if (!isEditMode) {
      resetAPInvoiceCreate();
      hydratedDocNumRef.current = null;
    }
    return () => {
      resetAPInvoiceCreate();
      resetWarehouse();
    };
  }, [isEditMode, resetAPInvoiceCreate, resetWarehouse]);

  useEffect(() => {
    if (header.warehouseCode && warehouses.length > 0) {
      const matched = warehouses.find(
        (w) => String(w.code).trim() === String(header.warehouseCode).trim(),
      );
      if (matched && warehouseInput !== formatWarehouseDisplay(matched.name, matched.code)) {
        setWarehouseInput(formatWarehouseDisplay(matched.name, matched.code));
      }
    }
  }, [header.warehouseCode, warehouses, warehouseInput]);

  // Edit Mode Hydration
  useEffect(() => {
    if (!isEditMode) {
      return;
    }
    const currentDocNum = editDocNum;
    if (!currentDocNum) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    if (hydratedDocNumRef.current === currentDocNum) {
      return;
    }

    void (async () => {
      try {
        setVendorCodeInput(String(detail.CardCode ?? "").trim());
        setVendorNameInput(String(detail.CardName ?? "").trim());
        const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
        const { comments: remarks, referenceNo } = parseAPInvoiceHeaderNotes(detail);

        const matchedVendor = vendors.find(
          (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
        );
        const buyerFromDocCode =
          detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(detail.SalesPersonCode),
              )?.name
            : "";

        setBuyerInput(buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "");
        const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);
        const resolvedHeaderDiscountPercent = Number(
          (detail as Record<string, unknown>).DiscountPercent ?? 0,
        );
        setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

        setHeader({
          docDate: loadedDocDate,
          docDueDate,
          referenceNo,
          remarks,
        });
        // Set addresses from document: Address = Bill To, Address2 = Ship To
        setBillToAddress(String(detail.Address ?? "").trim());
        setShipToAddress(String((detail as Record<string, unknown>).Address2 ?? "").trim());
        const detailLines = detail.DocumentLines ?? [];
        const uniqueItemCodes = [
          ...new Set(detailLines.map((line) => String(line.ItemCode ?? "").trim())),
        ].filter(Boolean);

        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          uniqueItemCodes,
          "purchase",
          { cardCode: String(detail.CardCode ?? "").trim() || undefined },
        );
        const taxRateByItemCode = taxRatesFromProductMeta(productByCode);

        const mappedLines = (detail.DocumentLines ?? []).map((line, index) => {
          const lineData = line as Record<string, unknown>;
          const quantity = Math.max(0, Number(line.Quantity ?? 0));
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line: line as unknown as Record<string, unknown>,
          });
          const itemCode = String(line.ItemCode ?? "").trim();
          const productMeta = productByCode.get(itemCode);

          return {
            id: `${currentDocNum}-${index}`,
            productCode: itemCode,
            productName: String(
              line.ItemDescription ?? productMeta?.name ?? line.ItemCode ?? "",
            ).trim(),
            stock: 0, // In edit mode, stock is less relevant for invoices
            currency: String(detail.DocCurr ?? productMeta?.currency ?? "").trim(),
            vatGroup: String(lineData.VatGroup ?? line.TaxCode ?? "").trim(),
            // SAP line tax is authoritative; fall back to product master only when missing
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: (() => {
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) return code;
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) {
                const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                if (match?.code) return match.code;
              }
              return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
            })(),
            uomEntry: (() => {
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) return entry;
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) {
                const match = productMeta?.uomList?.find((u) => u.code === code);
                if (match?.uomEntry !== undefined) return match.uomEntry;
              }
              return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
            })(),
            purchaseUomCode: productMeta?.purchaseUomCode,
            purchaseUomEntry: productMeta?.purchaseUomEntry,
            salesUomCode: productMeta?.uomCode,
            salesUomEntry: productMeta?.uomEntry,
            uomList: productMeta?.uomList,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: String(line.WarehouseCode ?? "").trim(),
            baseEntry: typeof line.BaseEntry === "number" ? line.BaseEntry : undefined,
            baseLine: typeof line.BaseLine === "number" ? line.BaseLine : undefined,
            baseType: typeof line.BaseType === "number" ? line.BaseType : undefined,
            selected: false,
          };
        });
        setLines(mappedLines);

        const rawAttachments = detail.attachments || [];
        setAttachments(
          rawAttachments.map((item: any, idx: number) => ({
            id: `loaded-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );

        const warehouseCode = String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
        const matchedWarehouse = warehouses.find((w) => String(w.code).trim() === warehouseCode);
        setWarehouseInput(
          formatWarehouseDisplay(matchedWarehouse?.name ?? warehouseCode, warehouseCode),
        );

        hydratedDocNumRef.current = currentDocNum;
        setFormSnapshot({
          remarks: (remarks || "").trim(),
          referenceNo: (referenceNo || "").trim(),
          docDueDate: docDueDate,
          billToAddress: formatAddressForDisplay(String(detail.Address ?? "")).trim(),
          shipToAddress: formatAddressForDisplay(
            String((detail as Record<string, unknown>).Address2 ?? ""),
          ).trim(),
          attachments: rawAttachments.map((item: any) => ({
            fileName: item.fileName,
            freeText: item.freeText || item.remarks || "",
          })),
          productRows: mappedLines
            .filter((row) => row.productCode.trim() && row.quantity > 0)
            .map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
        });
        setHydratedDocNum(currentDocNum);
      } finally {
        // no-op
      }
    })();
  }, [
    editDocNum,
    editDetailQuery.data,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
  ]);

  // Draft Hydration — loads existing draft data into form when draftDocNum is present
  useEffect(() => {
    if (isEditMode || !draftDocNum) {
      return;
    }
    const currentDocNum = fetchDocNum;
    if (!currentDocNum) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    const hydrationKey = `${draftDocNum}_${draftDocEntry ?? ""}`;
    if (hydratedDocNumRef.current === hydrationKey) {
      return;
    }

    void (async () => {
      try {
        setVendorCodeInput(String(detail.CardCode ?? "").trim());
        setVendorNameInput(String(detail.CardName ?? "").trim());
        const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
        const { comments: remarks, referenceNo } = parseAPInvoiceHeaderNotes(detail);

        const matchedVendor = vendors.find(
          (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
        );
        const buyerFromDocCode =
          detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(detail.SalesPersonCode),
              )?.name
            : "";
        const buyerFromVendorCode =
          matchedVendor?.salesEmployeeCode !== undefined && matchedVendor.salesEmployeeCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(matchedVendor.salesEmployeeCode),
              )?.name
            : "";

        setBuyerInput(
          buyerFromDocCode || buyerFromVendorCode || matchedVendor?.salesEmployeeName?.trim() || "",
        );
        const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);

        setHeader({
          docDate: loadedDocDate,
          docDueDate,
          referenceNo,
          remarks,
        });

        const billAddr = String(detail.Address ?? "").trim() || matchedVendor?.billToAddress || "";
        const shipAddr =
          String(detail.Address2 ?? "").trim() ||
          matchedVendor?.shipToAddress ||
          matchedVendor?.billToAddress ||
          "";
        setBillToAddress(billAddr);
        setShipToAddress(shipAddr);

        const productCodes = (detail.DocumentLines ?? [])
          .map((line) => String(line.ItemCode ?? "").trim())
          .filter(Boolean);
        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          productCodes,
          "purchase",
          { cardCode: String(detail.CardCode ?? "").trim() || undefined },
        );
        const taxRateByItemCode = taxRatesFromProductMeta(productByCode);

        let lineIndex = 0;
        const mappedLines = (detail.DocumentLines ?? []).map((line) => {
          const idx = lineIndex++;
          const lineData = line as Record<string, unknown>;
          const openQty = Number(lineData.OpenQty ?? lineData.OpenQuantity ?? line.Quantity ?? 1);
          const quantity = openQty;
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const resolvedHeaderDiscountPercent = Number(
            (detail as Record<string, unknown>).DiscountPercent ?? 0,
          );
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line: line as unknown as Record<string, unknown>,
          });
          const itemCode = String(line.ItemCode ?? "").trim();
          const productMeta = productByCode.get(itemCode);

          return {
            id: `row-draft-${idx}`,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? productMeta?.name ?? itemCode).trim(),
            stock: 0,
            currency: String(productMeta?.currency ?? "").trim(),
            vatGroup: String(lineData.VatGroup ?? line.TaxCode ?? "").trim(),
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: (() => {
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) return code;
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) {
                const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                if (match?.code) return match.code;
              }
              return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
            })(),
            uomEntry: (() => {
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) return entry;
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) {
                const match = productMeta?.uomList?.find((u) => u.code === code);
                if (match?.uomEntry !== undefined) return match.uomEntry;
              }
              return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
            })(),
            purchaseUomCode: productMeta?.purchaseUomCode,
            purchaseUomEntry: productMeta?.purchaseUomEntry,
            salesUomCode: productMeta?.uomCode,
            salesUomEntry: productMeta?.uomEntry,
            uomList: productMeta?.uomList,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: String(line.WarehouseCode ?? "").trim(),
            baseEntry: typeof line.BaseEntry === "number" ? line.BaseEntry : undefined,
            baseLine: typeof line.BaseLine === "number" ? line.BaseLine : undefined,
            baseType: typeof line.BaseType === "number" ? line.BaseType : undefined,
            selected: false,
          };
        });
        setLines(mappedLines);

        const editWarehouseCode = String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
        const matchedWarehouseEdit = warehouses.find(
          (w) => String(w.code).trim() === editWarehouseCode,
        );
        setWarehouseInput(
          formatWarehouseDisplay(
            matchedWarehouseEdit?.name ?? editWarehouseCode,
            editWarehouseCode,
          ),
        );

        const rawAttachments = detail.attachments || [];
        setAttachments(
          rawAttachments.map((item: any, idx: number) => ({
            id: `loaded-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );

        setFormSnapshot({
          remarks: (remarks || "").trim(),
          referenceNo: (referenceNo || "").trim(),
          docDueDate: docDueDate,
          billToAddress: formatAddressForDisplay(billAddr).trim(),
          shipToAddress: formatAddressForDisplay(shipAddr).trim(),
          attachments: rawAttachments.map((item: any) => ({
            fileName: item.fileName,
            freeText: item.freeText || "",
          })),
          productRows: mappedLines
            .filter((row) => row.productCode.trim() && row.quantity > 0)
            .map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
        });

        hydratedDocNumRef.current = hydrationKey;
        setHydratedDocNum(hydrationKey);
      } finally {
        // no-op
      }
    })();
  }, [
    draftDocNum,
    draftDocEntry,
    isEditMode,
    editDetailQuery.data,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
  ]);

  // Copy-From Hydration (GRPO or PO) — supports multi-doc, single type
  useEffect(() => {
    if (mode !== "create") {
      return;
    }
    const currentSourceDocNum = sourceDocNum;
    const currentSourceDocType = sourceDocType;
    if (!currentSourceDocNum || !currentSourceDocType) {
      hydratedDocNumRef.current = null;
      return;
    }

    const sourceDocNums = currentSourceDocNum
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (sourceDocNums.length === 0) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    const hydrationKey = `${currentSourceDocType}-${currentSourceDocNum}`;
    if (hydratedDocNumRef.current === hydrationKey && isMetadataLoaded) {
      return;
    }
    if (isMetadataLoaded) {
      hydratedDocNumRef.current = hydrationKey;
    }

    const fetchAllSources = async () => {
      const details = await Promise.all(
        sourceDocNums.map(async (num) => {
          if (currentSourceDocType === "GoodsReceiptPO") {
            const res = await queryClient.fetchQuery(grpoQueries.detailByDocNum(num));
            return res.data;
          }
          if (currentSourceDocType === "PurchaseQuotation") {
            const res = await queryClient.fetchQuery(purchaseQuotationQueries.detailByDocNum(num));
            return res.data;
          }
          const res = await queryClient.fetchQuery(purchaseOrderQueries.detailByDocNum(num));
          return res.data;
        }),
      );

      const primaryDetail = details[0]!;
      const vendorCode = String(primaryDetail.CardCode ?? "").trim();
      const vendorName = String(primaryDetail.CardName ?? "").trim();
      const matchedVendor = vendors.find((v) => String(v.code).trim() === vendorCode);

      const buyerFromDocCode =
        primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(primaryDetail.SalesPersonCode),
            )?.name
          : "";
      const buyerName = buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "";

      const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
      const sourceComments = String(primaryDetail.Comments ?? "").trim();

      // Format: "Based on <company/BP code> <DocType> <DocNum>"
      const refs = sourceDocNums.map((num) =>
        generateSingleSourceReference(currentSourceDocType, num, vendorCode),
      );
      const autoReference = refs.length === 1 ? refs[0]! : refs.join("\n");

      // Extract existing "Based on" chain from source comments
      const commentLines = sourceComments
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean);
      const refLinesFromComments = commentLines.filter((line) => isAutoGeneratedRemarkLine(line));

      // Build remarks: existing ref chain + new auto-ref + user remarks from source
      const userRemarks = commentLines
        .filter((line) => !isAutoGeneratedRemarkLine(line))
        .join("\n")
        .trim();
      const remarksParts = [refLinesFromComments.join("\n"), autoReference, userRemarks]
        .filter(Boolean)
        .join("\n")
        .trim();

      const referenceWasAutoFilled = true;
      const docDueDate = String(primaryDetail.DocDueDate ?? "").slice(0, 10);

      const allDetailLines = details.flatMap((d) => d.DocumentLines ?? []);
      const uniqueItemCodes = [
        ...new Set(allDetailLines.map((line) => String(line.ItemCode ?? "").trim())),
      ].filter(Boolean);

      const productByCode = await resolveHydrateProductMeta(
        queryClient,
        uniqueItemCodes,
        "purchase",
        {
          cardCode: String(primaryDetail.CardCode ?? header.vendorCode ?? "").trim() || undefined,
        },
      );

      const baseType =
        currentSourceDocType === "GoodsReceiptPO"
          ? 20
          : currentSourceDocType === "PurchaseQuotation"
            ? 540000006
            : 22;
      const currency = String(primaryDetail.DocCurr ?? "").trim();

      const taxRateByItemCode = taxRatesFromProductMeta(productByCode);
      const resolvedHeaderDiscountPercent = Number(
        (primaryDetail as Record<string, unknown>).DiscountPercent ?? 0,
      );
      setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

      let lineIndex = 0;
      const mappedLines = details.flatMap((detail) => {
        const detailLines = detail.DocumentLines ?? [];
        return detailLines.map((line) => {
          const idx = lineIndex++;
          const lineData = line as Record<string, unknown>;
          // For Purchase Quotation sources (baseType 540000006), the user-entered
          // quantity lives in PQT1.PQTReqQty (Service Layer: RequiredQuantity),
          // while PQT1.Quantity stays 0. Prefer RequiredQuantity as a fallback
          // so the copied-to AP Invoice receives the same quantity the user requested.
          const openQty = Number(
            lineData.OpenQty ??
              lineData.OpenQuantity ??
              lineData.RequiredQuantity ??
              lineData.requiredQuantity ??
              line.Quantity ??
              1,
          );
          const quantity = openQty;
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line: line as unknown as Record<string, unknown>,
          });
          const itemCode = String(line.ItemCode ?? "").trim();
          const productMeta = productByCode.get(itemCode);

          return {
            id: `row-copy-${detail.DocEntry ?? detail.id ?? "unknown"}-${idx}`,
            productCode: itemCode,
            productName: String(
              line.ItemDescription ?? productMeta?.name ?? line.ItemCode ?? "",
            ).trim(),
            stock: 0,
            currency: currency || String(productMeta?.currency ?? "").trim(),
            vatGroup: String(lineData.VatGroup ?? line.TaxCode ?? "").trim(),
            // SAP line tax is authoritative; fall back to product master only when missing
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: (() => {
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) return code;
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) {
                const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                if (match?.code) return match.code;
              }
              return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
            })(),
            uomEntry: (() => {
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) return entry;
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) {
                const match = productMeta?.uomList?.find((u) => u.code === code);
                if (match?.uomEntry !== undefined) return match.uomEntry;
              }
              return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
            })(),
            purchaseUomCode: productMeta?.purchaseUomCode,
            purchaseUomEntry: productMeta?.purchaseUomEntry,
            salesUomCode: productMeta?.uomCode,
            salesUomEntry: productMeta?.uomEntry,
            uomList: productMeta?.uomList,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: String(line.WarehouseCode ?? warehouseCode).trim(),
            baseEntry: detail.DocEntry ?? (detail as { id?: number }).id,
            baseLine: line.LineNum ?? idx,
            baseType,
            selected: false,
          };
        });
      });

      const sourceNumAtCard = String(
        (primaryDetail as { NumAtCard?: string }).NumAtCard ?? "",
      ).trim();
      setVendorCodeInput(vendorCode);
      setVendorNameInput(vendorName);
      setBuyerInput(buyerName);
      const matchedWarehouseCopy = warehouses.find((w) => String(w.code).trim() === warehouseCode);
      setWarehouseInput(
        formatWarehouseDisplay(matchedWarehouseCopy?.name ?? warehouseCode, warehouseCode),
      );
      setBillToAddress(
        String(primaryDetail.Address ?? "").trim() || matchedVendor?.billToAddress || "",
      );
      setShipToAddress(
        String((primaryDetail as Record<string, unknown>).Address2 ?? "").trim() ||
          matchedVendor?.shipToAddress ||
          matchedVendor?.billToAddress ||
          "",
      );
      setHeader({
        docDate: getTodayISO(),
        docDueDate,
        referenceAutoFilled: referenceWasAutoFilled,
        referenceNo: sourceNumAtCard,
        remarks: remarksParts,
      });
      setLines(mappedLines);
      setProductRowDrafts({});

      const sourceAttachments = primaryDetail.attachments || [];
      setAttachments(
        sourceAttachments.map((item: any, idx: number) => ({
          id: `copy-${idx}-${item.fileName}`,
          fileName: item.fileName,
          fileExtension: item.fileExtension,
          sourcePath: item.sourcePath,
          attachmentDate: item.attachmentDate,
          freeText: item.freeText || "",
          targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
        })),
      );
      if (isMetadataLoaded) {
        hydratedDocNumRef.current = hydrationKey;
      }
    };

    void fetchAllSources();
  }, [
    mode,
    sourceDocNum,
    sourceDocType,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    setProductRowDrafts,
    vendors,
  ]);

  const { vendorNameSuggestions, vendorCodeSuggestions, warehouseSuggestions, buyerSuggestions } =
    useAPInvoiceLookups({
      buyerInput,
      buyers: salesEmployees,
      vendorCodeInput,
      vendorNameInput,
      vendors,
      warehouseInput,
      warehouses,
    });

  const openPopupByMode = (mode: PopupMode) => {
    const searchVal =
      mode === "vendor-name" || mode === "vendor-code"
        ? mode === "vendor-name"
          ? vendorNameInput
          : vendorCodeInput
        : mode === "warehouse"
          ? warehouseInput
          : buyerInput;

    setModalMode(mode);
    setModalSearch(searchVal);
    setModalOpen(true);
  };

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onSalesEmployee: handleBuyerChange,
      onVendorCode: handleVendorCodeChange,
      onVendorName: handleVendorNameChange,
      onWarehouse: handleWarehouseInputChange,
    });

  useEffect(() => {
    if (!modalOpen) {
      return;
    }
    const nextSearch = getLookupInlineSearchByMode(modalMode, {
      salesEmployee: buyerInput,
      vendorCode: vendorCodeInput,
      vendorName: vendorNameInput,
      warehouse: warehouseInput,
    });
    if (nextSearch !== modalSearch) {
      setModalSearch(nextSearch);
    }
  }, [
    buyerInput,
    modalMode,
    modalOpen,
    modalSearch,
    setModalSearch,
    vendorCodeInput,
    vendorNameInput,
    warehouseInput,
  ]);

  const selectVendor = (vendor: LookupItem) => {
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor });
      return;
    }
    applyVendorChange(vendor);
  };

  const applyVendorChange = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);

    setWarehouseInput("");
    setLines([]);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
  };

  const handleVendorNameChange = (value: string) => {
    setVendorNameInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined }));
    if (value.trim() === "") {
      setVendorNameFocused(true);
      setVendorCodeInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.name.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      setVendorCodeInput(matched.code);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorCodeInput("");
    setBuyerInput("");
    setLines([]);
    setVendorNameFocused(true);
  };

  const handleVendorCodeChange = (value: string) => {
    setVendorCodeInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorCode: undefined }));
    if (value.trim() === "") {
      setVendorCodeFocused(true);
      setVendorNameInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.code.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      if (hasCopiedRows) {
        setPendingVendorChange({ vendor: matched });
        return;
      }
      setVendorNameInput(matched.name);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorNameInput("");
    setBuyerInput("");
    setLines([]);
    setVendorCodeFocused(true);
  };

  /* ---------- vendor-change confirmation handlers ---------- */
  const confirmVendorChange = () => {
    const pending = pendingVendorChange;
    if (!pending) {
      return;
    }
    setPendingVendorChange(null);

    // Strip only auto-generated "Based on..." references from remarks, keep user remarks
    const cleanedRemarks = stripAutoGeneratedReferences(header.remarks);
    setHeader({ remarks: cleanedRemarks });

    // Clear base linkage from all rows (break copy-from link) but keep row data
    setLines((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row;
        return rest;
      }),
    );

    // Apply the new vendor (without clearing lines/warehouse)
    applyVendorChangeForConfirmation(pending.vendor);
  };

  const cancelVendorChange = () => {
    setPendingVendorChange(null);
  };

  /** Apply vendor without clearing lines/warehouse — used only during vendor-change confirmation. */
  const applyVendorChangeForConfirmation = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
  };

  const handleWarehouseInputChange = (value: string) => {
    setWarehouseInput(value);
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }));
    if (value.trim() === "") {
      setWarehouseFocused(true);
      setHeader({ warehouseCode: "" });
      return;
    }
    const matched = warehouses.find(
      (w) =>
        w.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        w.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      selectWarehouse(matched);
      return;
    }
    setHeader({ warehouseCode: "" });
  };

  const handleBuyerChange = (value: string) => {
    setBuyerInput(value);
    setFieldErrors((prev) => ({ ...prev, salesEmployee: undefined }));
    const matched = salesEmployees.find(
      (s) =>
        s.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        s.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      setBuyerFocused(false);
    }
  };

  const openProductPopup = (rowId: string | null = null) => {
    setActiveProductRowId(rowId);
    if (!vendorNameInput.trim() || !vendorCodeInput.trim()) {
      setFieldErrors((prev) => ({
        ...prev,
        vendorCode: !vendorCodeInput.trim() ? AP_INVOICE_FIELD_ERROR_TEXT.vendorCode : undefined,
        vendorName: !vendorNameInput.trim() ? AP_INVOICE_FIELD_ERROR_TEXT.vendorName : undefined,
      }));
      return;
    }

    setProductPopupOpen(true);
  };

  const selectWarehouse = (warehouse: LookupItem) => {
    setWarehouseInput(formatWarehouseDisplay(warehouse.name, warehouse.code));
    setHeader({ warehouseCode: warehouse.code });
    setLines((prev) => prev.map((row) => ({ ...row, warehouseCode: warehouse.code })));
    setWarehouseFocused(false);
  };

  const selectBuyer = (item: LookupItem) => {
    setBuyerInput(item.name);
    setBuyerFocused(false);
  };

  const applyProductToRow = (product: ProductLookupItem) => {
    void queryClient.prefetchQuery(createSharedQueries.productWarehouseStocks(product.code));
    setLines((prev) => {
      if (activeProductRowId) {
        const activeRow = prev.find((r) => r.id === activeProductRowId);
        const targetWhs = activeRow?.warehouseCode || effectiveWarehouseCode || "";
        const stocksData = queryClient.getQueryData<ProductWarehouseStockItem[]>(
          createSharedQueries.productWarehouseStocks(product.code).queryKey,
        );
        const matchedStock = stocksData?.find(
          (s) => String(s.code).trim() === String(targetWhs).trim(),
        );
        const resolvedStock = matchedStock ? Number(matchedStock.stock ?? 0) : 0;

        return prev.map((row) =>
          row.id === activeProductRowId
            ? {
                ...row,
                price: Number(product.price ?? 0),
                productCode: product.code,
                productName: product.name,
                quantity: 1,
                stock: resolvedStock,
                uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
                uomEntry: product.purchaseUomEntry ?? product.uomEntry,
                warehouseCode: targetWhs,
                ...lotFieldsFromProduct(product),
              }
            : row,
        );
      }
      const targetWhs = effectiveWarehouseCode || "";
      const stocksData = queryClient.getQueryData<ProductWarehouseStockItem[]>(
        createSharedQueries.productWarehouseStocks(product.code).queryKey,
      );
      const matchedStock = stocksData?.find(
        (s) => String(s.code).trim() === String(targetWhs).trim(),
      );
      const resolvedStock = matchedStock ? Number(matchedStock.stock ?? 0) : 0;

      return [
        ...prev,
        {
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: resolvedStock,
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: targetWhs,
          ...lotFieldsFromProduct(product),
        },
      ];
    });
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const resolvedBuyerCode = useMemo(() => {
    const normalize = (val: unknown) =>
      String(val ?? "")
        .trim()
        .toLowerCase();
    const input = normalize(buyerInput);
    if (!input) return undefined;

    const byName = salesEmployees.find((item) => normalize(item.name) === input);
    if (byName) return Number(byName.code);

    const byCode = salesEmployees.find((item) => normalize(item.code) === input);
    if (byCode) return Number(byCode.code);

    return undefined;
  }, [buyerInput, salesEmployees]);

  const resetForm = useCallback(() => {
    resetAPInvoiceCreate();
    setVendorNameInput("");
    setVendorCodeInput("");
    setBuyerInput("");
    resetWarehouse();
    setBillToAddress("");
    setShipToAddress("");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
    setBuyerFocused(false);
    setActiveDatePicker(null);
    setModalOpen(false);
    setModalMode("vendor-name");
    setModalSearch("");
    setProductSearch("");
    setDebouncedProductSearch("");
    setActiveProductRowId(null);
    setProductPopupOpen(false);
    setProductRowDrafts({});
    setStockPreviewProduct(null);
    setFieldErrors(EMPTY_AP_INVOICE_FIELD_ERRORS);
    setCreateError(null);
    setHydratedDocNum(null);
    setFormSnapshot(null);
    setAttachments([]);
  }, [resetAPInvoiceCreate, resetWarehouse, setBillToAddress, setShipToAddress]);

  const saveActions = useDocumentSaveActions({
    documentName: "AP Invoice",
    moduleType: "purchase",
    defaultUrl: "/purchase/create-ap-invoice",
    tableUrl: "/purchase/ap-invoice",
    resetForm,
    getPayloadString: () => {
      const buildDocumentLines = () => {
        const lines = [];
        for (const row of filteredRows) {
          if (row.quantity <= 0) {
            continue;
          }

          const hasCompleteBaseLink =
            Number.isFinite(row.baseEntry) &&
            Number.isFinite(row.baseLine) &&
            Number.isFinite(row.baseType);

          if (!hasCompleteBaseLink) {
            lines.push({
              DiscountPercent: row.discountPercent,
              ItemCode: row.productCode,
              Quantity: row.quantity,
              UnitPrice: row.price,
              UoMCode: row.uomCode || undefined,
              VatGroup: row.vatGroup || undefined,
              ...sapLotFieldsFromRow(row),
              WarehouseCode: row.warehouseCode || undefined,
            });
            continue;
          }

          const baseQty = row.baseQuantity ?? 0;
          const linkedQty = Math.min(row.quantity, baseQty);

          if (linkedQty > 0) {
            lines.push({
              BaseEntry: row.baseEntry,
              BaseLine: row.baseLine,
              BaseType: row.baseType,
              DiscountPercent: row.discountPercent,
              ItemCode: row.productCode,
              Quantity: linkedQty,
              UnitPrice: row.price,
              UoMCode: row.uomCode || undefined,
              VatGroup: row.vatGroup || undefined,
              ...sapLotFieldsFromRow(row),
              WarehouseCode: row.warehouseCode || undefined,
            });
          }

          const excessQty = row.quantity - baseQty;
          if (excessQty > 0) {
            lines.push({
              DiscountPercent: row.discountPercent,
              ItemCode: row.productCode,
              Quantity: excessQty,
              UnitPrice: row.price,
              UoMCode: row.uomCode || undefined,
              VatGroup: row.vatGroup || undefined,
              ...sapLotFieldsFromRow(row),
              WarehouseCode: row.warehouseCode || undefined,
            });
          }
        }
        return lines;
      };

      const payload = isEditMode
        ? {
            Comments: header.remarks.trim() || undefined,
            DocDueDate: header.docDueDate || undefined,
            NumAtCard: header.referenceNo.trim() || undefined,
            SalesPersonCode: resolvedBuyerCode,
            attachments: attachments.map((att) => ({
              sourcePath: att.sourcePath || "",
              fileName: att.fileName,
              fileExtension: att.fileExtension || "",
              freeText: att.freeText || "",
              attachmentDate: att.attachmentDate || "",
            })),
          }
        : {
            Address: billToAddress.trim() || undefined,
            Address2: shipToAddress.trim() || undefined,
            CardCode: vendorCodeInput.trim(),
            ...(header.docDate ? { DocDate: header.docDate } : {}),
            ...(header.docDueDate ? { DocDueDate: header.docDueDate } : {}),
            ...(header.remarks.trim() ? { Comments: header.remarks.trim() } : {}),
            ...(header.referenceNo.trim() ? { NumAtCard: header.referenceNo.trim() } : {}),
            DocumentLines: buildDocumentLines(),
            SalesPersonCode: resolvedBuyerCode,
            attachments: attachments.map((att) => ({
              sourcePath: att.sourcePath || "",
              fileName: att.fileName,
              fileExtension: att.fileExtension || "",
              freeText: att.freeText || "",
              attachmentDate: att.attachmentDate || "",
            })),
          };
      return JSON.stringify(payload);
    },
    isEditMode,
  });

  const applyProductsToRows = (products: ProductLookupItem[]) => {
    products.forEach((product) => {
      void queryClient.prefetchQuery(createSharedQueries.productWarehouseStocks(product.code));
    });

    setLines((prev) => [
      ...prev,
      ...products.map((product) => {
        const targetWhs = effectiveWarehouseCode || "";
        const stocksData = queryClient.getQueryData<ProductWarehouseStockItem[]>(
          createSharedQueries.productWarehouseStocks(product.code).queryKey,
        );
        const matchedStock = stocksData?.find(
          (s) => String(s.code).trim() === String(targetWhs).trim(),
        );
        const resolvedStock = matchedStock ? Number(matchedStock.stock ?? 0) : 0;

        return {
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: resolvedStock,
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: targetWhs,
          ...lotFieldsFromProduct(product),
        };
      }),
    ]);
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const handleCreateAPInvoice = async (
    action: "save-new" | "view" | "close" | "draft" = "save-new",
  ) => {
    const isDraftAction = action === "draft";
    const isUpdating = isEditMode || (isDraftAction && isDraftUpdate);
    const trackingAction =
      isDraftAction && isDraftUpdate ? "draft-update" : isEditMode ? "update" : action;

    setSubmitAttempted(true);

    if (isDraftAction) {
      if (!vendorCodeInput.trim() || !vendorNameInput.trim()) {
        const nextErrors = { ...EMPTY_AP_INVOICE_FIELD_ERRORS };
        if (!vendorCodeInput.trim()) {
          nextErrors.vendorCode = AP_INVOICE_FIELD_ERROR_TEXT.vendorCode;
        }
        if (!vendorNameInput.trim()) {
          nextErrors.vendorName = AP_INVOICE_FIELD_ERROR_TEXT.vendorName;
        }
        setFieldErrors(nextErrors);
        setCreateError("Vendor is required to save as draft.");
        return;
      }
    } else {
      if (!isEditMode) {
        const missing = AP_INVOICE_MANDATORY_FIELDS.filter((field) => {
          if (field === "vendorName") {
            return !vendorNameInput.trim();
          }
          if (field === "vendorCode") {
            return !vendorCodeInput.trim();
          }
          return false;
        });

        if (missing.length > 0) {
          const nextErrors = { ...EMPTY_AP_INVOICE_FIELD_ERRORS };
          missing.forEach((field) => {
            nextErrors[field] = AP_INVOICE_FIELD_ERROR_TEXT[field];
          });
          setFieldErrors(nextErrors);
          setCreateError("Fill required fields before creating A/P Invoice.");
          return;
        }
      }

      if (filteredRows.length === 0) {
        setCreateError("Set at least one line quantity greater than 0.");
        return;
      }

      const lotError = firstRequiredLotError(filteredRows);
      if (lotError) {
        setCreateError(lotError);
        return;
      }

      if (isEditMode && !isDirty) {
        const noChangeMessage = "Change at least one field before update.";
        setCreateError(noChangeMessage);
        return;
      }
    }

    const buildDocumentLines = (): CreateAPInvoiceInput["DocumentLines"] => {
      const lines: CreateAPInvoiceInput["DocumentLines"] = [];
      for (const row of filteredRows) {
        // Guard: never send zero-quantity lines
        if (row.quantity <= 0) {
          continue;
        }

        const hasCompleteBaseLink =
          Number.isFinite(row.baseEntry) &&
          Number.isFinite(row.baseLine) &&
          Number.isFinite(row.baseType);

        // Manual rows (no base link): send single line with actual quantity
        if (!hasCompleteBaseLink) {
          lines.push({
            DiscountPercent: row.discountPercent,
            ItemCode: row.productCode,
            Quantity: row.quantity,
            UnitPrice: row.price,
            UoMCode: row.uomCode || undefined,
            VatGroup: row.vatGroup || undefined,
            ...sapLotFieldsFromRow(row),
            WarehouseCode: row.warehouseCode || undefined,
          });
          continue;
        }

        // Base-linked rows: split into base qty and excess portions
        const baseQty = row.baseQuantity ?? 0;
        const linkedQty = Math.min(row.quantity, baseQty);

        // Only push base-linked portion if quantity is positive
        if (linkedQty > 0) {
          lines.push({
            BaseEntry: row.baseEntry,
            BaseLine: row.baseLine,
            BaseType: row.baseType,
            DiscountPercent: row.discountPercent,
            ItemCode: row.productCode,
            Quantity: linkedQty,
            UnitPrice: row.price,
            UoMCode: row.uomCode || undefined,
            VatGroup: row.vatGroup || undefined,
            ...sapLotFieldsFromRow(row),
            WarehouseCode: row.warehouseCode || undefined,
          });
        }

        // Excess portion: manual line without base linkage
        const excessQty = row.quantity - baseQty;
        if (excessQty > 0) {
          lines.push({
            DiscountPercent: row.discountPercent,
            ItemCode: row.productCode,
            Quantity: excessQty,
            UnitPrice: row.price,
            UoMCode: row.uomCode || undefined,
            VatGroup: row.vatGroup || undefined,
            ...sapLotFieldsFromRow(row),
            WarehouseCode: row.warehouseCode || undefined,
          });
        }
      }
      return lines;
    };

    saveActions.startSaveTracking(trackingAction);
    try {
      let createdDocNum: number | undefined;
      const loadedDraftDocEntry = isDraftUpdate ? draftDocEntry : undefined;

      if (isUpdating) {
        const id =
          editDetailQuery.data?.data?.id ??
          editDetailQuery.data?.data?.DocEntry ??
          (loadedDraftDocEntry ? Number(loadedDraftDocEntry) : undefined);
        if (id === undefined || id === null) {
          setCreateError("Unable to update A/P Invoice. Document id is missing.");
          return;
        }

        const updatePayload =
          isDraftAction && isDraftUpdate
            ? {
                Address: billToAddress.trim() || undefined,
                Address2: shipToAddress.trim() || undefined,
                CardCode: vendorCodeInput.trim(),
                Comments: header.remarks.trim() || undefined,
                DocDate: header.docDate,
                DocDueDate: header.docDueDate || header.docDate,
                NumAtCard: header.referenceNo.trim() || undefined,
                DocumentLines: buildDocumentLines(),
                SalesPersonCode: resolvedBuyerCode,
                attachments: attachments.map((att) => ({
                  sourcePath: att.sourcePath || "",
                  fileName: att.fileName,
                  fileExtension: att.fileExtension || "",
                  freeText: att.freeText || "",
                  attachmentDate: att.attachmentDate || "",
                })),
                isDraft: true,
                draftDocEntry: Number(loadedDraftDocEntry),
              }
            : {
                Comments: header.remarks.trim() || undefined,
                DocDueDate: header.docDueDate || undefined,
                NumAtCard: header.referenceNo.trim() || undefined,
                SalesPersonCode: resolvedBuyerCode,
                attachments: attachments.map((att) => ({
                  sourcePath: att.sourcePath || "",
                  fileName: att.fileName,
                  fileExtension: att.fileExtension || "",
                  freeText: att.freeText || "",
                  attachmentDate: att.attachmentDate || "",
                })),
              };

        await updateMutation.mutateAsync({ id, payload: updatePayload });
        createdDocNum = isEditMode
          ? editDetailQuery.data?.data?.DocNum
          : (editDetailQuery.data?.data?.DocNum ?? Number(draftDocNum));

        // Fetch the updated detail from the API/cache to sync the local states (like attachments) immediately without page refresh
        const updatedDetailRes = await queryClient.fetchQuery(
          apInvoiceQueries.detailByDocNum(
            String(createdDocNum),
            isEditMode ? undefined : String(loadedDraftDocEntry),
          ),
        );
        const updatedDetail = updatedDetailRes?.data;
        if (updatedDetail) {
          const rawAttachments = updatedDetail.attachments || [];
          setAttachments(
            rawAttachments.map((item: any, idx: number) => ({
              id: `loaded-${idx}-${item.fileName}`,
              fileName: item.fileName,
              fileExtension: item.fileExtension,
              sourcePath: item.sourcePath,
              attachmentDate: item.attachmentDate,
              freeText: item.freeText || "",
              targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
            })),
          );

          const { comments: remarks, referenceNo } = parseAPInvoiceHeaderNotes(updatedDetail);
          const docDueDate = String(updatedDetail.DocDueDate ?? "").slice(0, 10);
          const billAddr = String(updatedDetail.Address ?? "").trim();
          const shipAddr = String((updatedDetail as Record<string, unknown>).Address2 ?? "").trim();

          setFormSnapshot({
            remarks: (remarks || "").trim(),
            referenceNo: (referenceNo || "").trim(),
            docDueDate: docDueDate,
            billToAddress: formatAddressForDisplay(billAddr).trim(),
            shipToAddress: formatAddressForDisplay(shipAddr).trim(),
            attachments: rawAttachments.map((item: any) => ({
              fileName: item.fileName,
              freeText: item.freeText || item.remarks || "",
            })),
            productRows: filteredRows.map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
          });
        }
      } else {
        const createPayload: CreateAPInvoiceInput & { draftDocEntry?: number } = {
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          CardCode: vendorCodeInput.trim(),
          ...(header.docDate ? { DocDate: header.docDate } : {}),
          ...(header.docDueDate ? { DocDueDate: header.docDueDate } : {}),
          ...(header.remarks.trim() ? { Comments: header.remarks.trim() } : {}),
          ...(header.referenceNo.trim() ? { NumAtCard: header.referenceNo.trim() } : {}),
          DocumentLines: buildDocumentLines(),
          SalesPersonCode: resolvedBuyerCode,
          attachments: attachments.map((att) => ({
            sourcePath: att.sourcePath || "",
            fileName: att.fileName,
            fileExtension: att.fileExtension || "",
            freeText: att.freeText || "",
            attachmentDate: att.attachmentDate || "",
          })),
          ...(isDraftAction ? { isDraft: true } : {}),
          ...(loadedDraftDocEntry ? { draftDocEntry: Number(loadedDraftDocEntry) } : {}),
        };
        const result = await createMutation.mutateAsync({
          payload: createPayload,
        });
        createdDocNum = result?.data?.DocNum;
      }

      saveActions.trackMutationSuccess();

      // Proactive Cache Revalidation / Invalidation
      if (!isEditMode) {
        // Invalidate the specific source document detail queries used by copy-from hydration
        // so the next AP Invoice copy reads fresh OpenQty / status from the backend
        if (sourceDocNum) {
          if (sourceDocType === "PurchaseOrder") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: purchaseOrderQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
            void queryClient.invalidateQueries({ queryKey: purchaseOrderKeys.all });
          } else if (sourceDocType === "GoodsReceiptPO") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: grpoQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
            void queryClient.invalidateQueries({ queryKey: grpoKeys.all });
          } else if (sourceDocType === "PurchaseQuotation") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: purchaseQuotationQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
            void queryClient.invalidateQueries({ queryKey: purchaseQuotationKeys.all });
          }
        }
      }

      if (isEditMode || isDraftUpdate) {
        const currentDocNum = isEditMode ? editDocNum : draftDocNum;
        if (currentDocNum) {
          void queryClient.invalidateQueries(
            apInvoiceQueries.detailByDocNum(
              currentDocNum,
              isEditMode ? undefined : String(loadedDraftDocEntry),
            ),
          );
        }
      }
      await saveActions.handleActionSuccess(isEditMode ? "update" : trackingAction, createdDocNum);
      if (isEditMode) {
        resetWarehouse();
      }
      setSubmitAttempted(false);

      if (!isEditMode && action === "save-new") {
        onCreateSuccess?.();
      }
    } catch (error) {
      const errorMessage = normalizeCreateOrderErrorMessage(
        error,
        "Failed to process A/P Invoice.",
      );
      setCreateError(errorMessage);
      notifyCreateApiError(errorMessage, "ap-invoice");
    }
  };

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) {
      return [];
    }
    return AP_INVOICE_MANDATORY_FIELDS.filter((field) => {
      if (field === "vendorName") {
        return !vendorNameInput.trim();
      }
      if (field === "vendorCode") {
        return !vendorCodeInput.trim();
      }
      return false;
    });
  }, [isEditMode, vendorNameInput, vendorCodeInput, rows]);

  const requiredCompletionPercent = useMemo(
    () =>
      ((AP_INVOICE_MANDATORY_FIELDS.length - missingMandatoryFields.length) /
        AP_INVOICE_MANDATORY_FIELDS.length) *
      100,
    [missingMandatoryFields],
  );

  return {
    isEditMode,
    isDirty,
    isEditHydrated: !isEditMode || hydratedDocNum === editDocNum,
    isSourceHydrating: mode === "create" && Boolean(sourceDocNum) && !hydratedDocNumRef.current,
    today,
    activeDatePicker,
    setActiveDatePicker,
    docDateContainerRef,
    deliveryDateContainerRef,
    handleDocDateChange: (val: string) => setHeader({ docDate: val }),
    handleDocDueDateChange: (val: string) => setHeader({ docDueDate: val }),
    showEditRestrictedToast: notifyRestricted,

    vendorsQuery,
    warehousesQuery,
    salesEmployeesQuery,
    productsQuery,
    productWarehouseStocksQuery,
    editDetailQuery,
    createMutation,
    updateMutation,

    vendorNameSuggestions,
    vendorCodeSuggestions,
    warehouseSuggestions,
    buyerSuggestions,
    vendors,
    warehouses,
    salesEmployees,

    vendorNameInput,
    vendorCodeInput,
    warehouseInput,
    buyerInput,
    vendorNameFocused,
    setVendorNameFocused,
    vendorCodeFocused,
    setVendorCodeFocused,
    buyerFocused,
    setBuyerFocused,
    warehouseFocused,
    setWarehouseFocused,
    resetWarehouse,
    clearLines: () => setLines([]),
    clearProductRowDrafts: () => setProductRowDrafts({}),
    docDate: header.docDate,
    docDueDate: header.docDueDate,
    referenceNo: header.referenceNo,
    referenceAutoFilled: header.referenceAutoFilled,
    remarks: header.remarks,
    headerDiscountPercent,
    billToAddress,
    shipToAddress,
    isClosed,
    docStatus,
    products: productsQuery.data ?? [],

    modalOpen,
    modalMode,
    modalSearch,
    setModalOpen,
    setModalSearch,
    openPopup: openPopupByMode,
    handleLookupModalSearchSync,
    popupResults: useMemo(
      () =>
        filterAndRankLookups(
          modalMode.includes("vendor")
            ? vendors
            : modalMode === "warehouse"
              ? warehouses
              : salesEmployees,
          modalSearch,
        ),
      [vendors, warehouses, salesEmployees, modalSearch, modalMode],
    ),

    productPopupOpen,
    productSearch,
    setProductPopupOpen,
    setProductSearch,
    activeProductRowId,
    openProductPopup,
    loadMoreProducts: () => {
      if (!productPopupOpen) {
        return;
      }
      if (productsQuery.isFetching) {
        return;
      }
      const currentCount = productsQuery.data?.length ?? 0;
      if (currentCount < productQueryLimit) {
        return;
      }
      if (debouncedProductSearch.trim().length > 0) {
        return;
      }
      if (productQueryLimit >= BROWSE_PRODUCT_LIMIT) {
        return;
      }
      setProductQueryLimit(BROWSE_PRODUCT_LIMIT);
    },
    applyProductToRow,
    applyProductsToRows,
    prefetchProducts: isEditMode ? () => {} : prefetchProducts,
    // Derive the product code of the currently active row for seeding modal selection
    activeRowProductCode: (() => {
      if (!activeProductRowId) {
        return null;
      }
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      return activeRow?.productCode ?? null;
    })(),
    isLookupLoading: modalMode.includes("vendor")
      ? vendorsQuery.isLoading
      : modalMode === "warehouse"
        ? warehousesQuery.isLoading
        : salesEmployeesQuery.isLoading,
    lookupError:
      (modalMode.includes("vendor")
        ? vendorsQuery.error
        : modalMode === "warehouse"
          ? warehousesQuery.error
          : salesEmployeesQuery.error
      )?.message ?? null,
    isProductsLoading: productsQuery.isLoading,
    productsError: productsQuery.error?.message ?? null,
    warehouseCode: effectiveWarehouseCode,
    searchWarehouseCode,

    rows,
    productRowDrafts,
    setProductRowDraft: (id: string, field: string, value: string) =>
      setProductRowDrafts((prev) => ({
        ...prev,
        [id]: { ...prev[id], [field]: value },
      })),
    clearProductRowDraft: (id: string, field: string) =>
      setProductRowDrafts((prev) => {
        const next = { ...prev[id] };
        delete next[field as keyof typeof next];
        return { ...prev, [id]: next };
      }),
    updateProductRow: (id: string, patch: Partial<APInvoiceCreateLine>) =>
      setLines((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r))),
    removeProductRow: (id: string) => setLines((prev) => prev.filter((r) => r.id !== id)),
    setProductRows: setLines,

    stockPreviewProduct,
    setStockPreviewProduct,
    openStockPreview: setStockPreviewProduct,

    submitDisabled,
    fieldErrors,
    createError,
    createDisabledReason:
      missingMandatoryFields.length > 0
        ? "Mandatory fields missing"
        : rows.length === 0
          ? "No lines"
          : null,
    searchMandatoryFields: useMemo(() => ["vendorName", "vendorCode"] as const, []),
    missingSearchMandatoryFields: useMemo(
      () =>
        ["vendorName", "vendorCode"].filter(
          (field) =>
            !String(field === "vendorName" ? vendorNameInput : (vendorCodeInput ?? "")).trim(),
        ),
      [vendorNameInput, vendorCodeInput],
    ),
    searchRequiredCompletionPercent: useMemo(() => {
      const filled = (vendorNameInput.trim() ? 1 : 0) + (vendorCodeInput.trim() ? 1 : 0);
      return (filled / 2) * 100;
    }, [vendorNameInput, vendorCodeInput]),
    missingMandatoryFields,
    requiredCompletionPercent,
    requiredFieldsTotal: AP_INVOICE_MANDATORY_FIELDS.length,
    requiredFieldLabelText: AP_INVOICE_FIELD_LABEL_TEXT,
    handleCreateOrder: handleCreateAPInvoice,
    submitAttempted,
    warehouseErrors,
    isSaved: saveActions.isSaved,
    savedDocNum: saveActions.savedDocNum,
    resetForm: saveActions.handleReset,

    setDocDate: (val: string) => setHeader({ docDate: val }),
    setDocDueDate: (val: string) =>
      isClosed ? notifyRestricted("Due Date") : setHeader({ docDueDate: val }),
    setBuyerInput: (val: string) =>
      isEditMode ? notifyRestricted("Buyer") : handleBuyerChange(val),
    setWarehouseInput: (val: string) =>
      isEditMode ? notifyRestricted("Warehouse") : handleWarehouseInputChange(val),
    setReferenceNo: (val: string) => {
      setHeader({ referenceNo: val });
      setFieldErrors((prev) => ({ ...prev, referenceNo: undefined }));
    },
    setRemarks: (val: string) => {
      setHeader({ remarks: val });
      setFieldErrors((prev) => ({ ...prev, comments: undefined }));
    },
    setBillToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Pay To Address") : setBillToAddress(val),
    setShipToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Ship To Address") : setShipToAddress(val),
    selectVendor: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Vendor") : selectVendor(val),
    selectWarehouse: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Warehouse") : selectWarehouse(val),
    selectSalesEmployee: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Sales Employee") : selectBuyer(val),
    handleVendorNameChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Name") : handleVendorNameChange(val),
    handleVendorCodeChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Code") : handleVendorCodeChange(val),

    // Vendor-change confirmation (copy-from guard)
    pendingVendorChange,
    hasCopiedRows,
    confirmVendorChange,
    cancelVendorChange,
    trackerDocType: isEditMode ? ("ap-invoice" as const) : null,
    trackerDocEntry: isEditMode
      ? (editDetailQuery.data?.data?.DocEntry ?? editDetailQuery.data?.data?.id)
      : null,
    attachments,
    setAttachments,
  };
}
