/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutDashboardRouteRouteImport } from './routes/_layout/dashboard/route'
import { Route as LayoutIntercompanyRouteRouteImport } from './routes/_layout/intercompany/route'
import { Route as LayoutDashboardPurchaseRouteImport } from './routes/_layout/dashboard/purchase'
import { Route as LayoutDashboardSalesRouteImport } from './routes/_layout/dashboard/sales'
import { Route as LayoutIntercompanyIndexRouteImport } from './routes/_layout/intercompany/index'
import { Route as LayoutIntercompanyNotificationsRouteImport } from './routes/_layout/intercompany/notifications'
import { Route as LayoutIntercompanyRetriesRouteImport } from './routes/_layout/intercompany/retries'
import { Route as LayoutPurchaseApCreditMemoRouteRouteImport } from './routes/_layout/purchase/ap-credit-memo/route'
import { Route as LayoutPurchaseApInvoiceRouteRouteImport } from './routes/_layout/purchase/ap-invoice/route'
import { Route as LayoutPurchaseCreateApCreditMemoRouteImport } from './routes/_layout/purchase/create-ap-credit-memo'
import { Route as LayoutPurchaseCreateApInvoiceRouteImport } from './routes/_layout/purchase/create-ap-invoice'
import { Route as LayoutPurchaseCreateGrpoRouteImport } from './routes/_layout/purchase/create-grpo'
import { Route as LayoutPurchaseCreateOrderRouteImport } from './routes/_layout/purchase/create-order'
import { Route as LayoutPurchaseCreateOutgoingPaymentRouteImport } from './routes/_layout/purchase/create-outgoing-payment'
import { Route as LayoutPurchaseCreateQuotationRouteImport } from './routes/_layout/purchase/create-quotation'
import { Route as LayoutPurchaseGrpoRouteRouteImport } from './routes/_layout/purchase/grpo/route'
import { Route as LayoutPurchaseOrdersRouteRouteImport } from './routes/_layout/purchase/orders/route'
import { Route as LayoutPurchaseOutgoingPaymentRouteRouteImport } from './routes/_layout/purchase/outgoing-payment/route'
import { Route as LayoutPurchaseQuotationsRouteRouteImport } from './routes/_layout/purchase/quotations/route'
import { Route as LayoutSalesCreateQuotationRouteImport } from './routes/_layout/sales/create-quotation'
import { Route as LayoutSalesQuotationsRouteRouteImport } from './routes/_layout/sales/quotations/route'
import { Route as LayoutPurchaseApCreditMemoDocNumUpdateRouteImport } from './routes/_layout/purchase/ap-credit-memo/$docNum.update'
import { Route as LayoutPurchaseApInvoiceDocNumUpdateRouteImport } from './routes/_layout/purchase/ap-invoice/$docNum.update'
import { Route as LayoutPurchaseGrpoDocNumUpdateRouteImport } from './routes/_layout/purchase/grpo/$docNum.update'
import { Route as LayoutPurchaseOrdersDocNumUpdateRouteImport } from './routes/_layout/purchase/orders/$docNum.update'
import { Route as LayoutPurchaseOutgoingPaymentDocNumUpdateRouteImport } from './routes/_layout/purchase/outgoing-payment/$docNum.update'
import { Route as LayoutPurchaseQuotationsDocNumUpdateRouteImport } from './routes/_layout/purchase/quotations/$docNum.update'
import { Route as LayoutSalesQuotationsDocNumUpdateRouteImport } from './routes/_layout/sales/quotations/$docNum.update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardRouteRoute = LayoutDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIntercompanyRouteRoute = LayoutIntercompanyRouteRouteImport.update({
  id: '/intercompany',
  path: '/intercompany',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardPurchaseRoute = LayoutDashboardPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => LayoutDashboardRouteRoute,
} as any)
const LayoutDashboardSalesRoute = LayoutDashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutDashboardRouteRoute,
} as any)
const LayoutIntercompanyIndexRoute = LayoutIntercompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutIntercompanyRouteRoute,
} as any)
const LayoutIntercompanyNotificationsRoute =
  LayoutIntercompanyNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutIntercompanyRouteRoute,
  } as any)
const LayoutIntercompanyRetriesRoute =
  LayoutIntercompanyRetriesRouteImport.update({
    id: '/retries',
    path: '/retries',
    getParentRoute: () => LayoutIntercompanyRouteRoute,
  } as any)
const LayoutPurchaseApCreditMemoRouteRoute =
  LayoutPurchaseApCreditMemoRouteRouteImport.update({
    id: '/purchase/ap-credit-memo',
    path: '/purchase/ap-credit-memo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseApInvoiceRouteRoute =
  LayoutPurchaseApInvoiceRouteRouteImport.update({
    id: '/purchase/ap-invoice',
    path: '/purchase/ap-invoice',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateApCreditMemoRoute =
  LayoutPurchaseCreateApCreditMemoRouteImport.update({
    id: '/purchase/create-ap-credit-memo',
    path: '/purchase/create-ap-credit-memo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateApInvoiceRoute =
  LayoutPurchaseCreateApInvoiceRouteImport.update({
    id: '/purchase/create-ap-invoice',
    path: '/purchase/create-ap-invoice',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateGrpoRoute =
  LayoutPurchaseCreateGrpoRouteImport.update({
    id: '/purchase/create-grpo',
    path: '/purchase/create-grpo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateOrderRoute =
  LayoutPurchaseCreateOrderRouteImport.update({
    id: '/purchase/create-order',
    path: '/purchase/create-order',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateOutgoingPaymentRoute =
  LayoutPurchaseCreateOutgoingPaymentRouteImport.update({
    id: '/purchase/create-outgoing-payment',
    path: '/purchase/create-outgoing-payment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateQuotationRoute =
  LayoutPurchaseCreateQuotationRouteImport.update({
    id: '/purchase/create-quotation',
    path: '/purchase/create-quotation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseGrpoRouteRoute = LayoutPurchaseGrpoRouteRouteImport.update({
  id: '/purchase/grpo',
  path: '/purchase/grpo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseOrdersRouteRoute =
  LayoutPurchaseOrdersRouteRouteImport.update({
    id: '/purchase/orders',
    path: '/purchase/orders',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseOutgoingPaymentRouteRoute =
  LayoutPurchaseOutgoingPaymentRouteRouteImport.update({
    id: '/purchase/outgoing-payment',
    path: '/purchase/outgoing-payment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseQuotationsRouteRoute =
  LayoutPurchaseQuotationsRouteRouteImport.update({
    id: '/purchase/quotations',
    path: '/purchase/quotations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesCreateQuotationRoute =
  LayoutSalesCreateQuotationRouteImport.update({
    id: '/sales/create-quotation',
    path: '/sales/create-quotation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesQuotationsRouteRoute =
  LayoutSalesQuotationsRouteRouteImport.update({
    id: '/sales/quotations',
    path: '/sales/quotations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseApCreditMemoDocNumUpdateRoute =
  LayoutPurchaseApCreditMemoDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutPurchaseApCreditMemoRouteRoute,
  } as any)
const LayoutPurchaseApInvoiceDocNumUpdateRoute =
  LayoutPurchaseApInvoiceDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutPurchaseApInvoiceRouteRoute,
  } as any)
const LayoutPurchaseGrpoDocNumUpdateRoute =
  LayoutPurchaseGrpoDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutPurchaseGrpoRouteRoute,
  } as any)
const LayoutPurchaseOrdersDocNumUpdateRoute =
  LayoutPurchaseOrdersDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutPurchaseOrdersRouteRoute,
  } as any)
const LayoutPurchaseOutgoingPaymentDocNumUpdateRoute =
  LayoutPurchaseOutgoingPaymentDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutPurchaseOutgoingPaymentRouteRoute,
  } as any)
const LayoutPurchaseQuotationsDocNumUpdateRoute =
  LayoutPurchaseQuotationsDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutPurchaseQuotationsRouteRoute,
  } as any)
const LayoutSalesQuotationsDocNumUpdateRoute =
  LayoutSalesQuotationsDocNumUpdateRouteImport.update({
    id: '/$docNum/update',
    path: '/$docNum/update',
    getParentRoute: () => LayoutSalesQuotationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRouteRouteWithChildren
  '/intercompany': typeof LayoutIntercompanyRouteRouteWithChildren
  '/purchase/ap-credit-memo': typeof LayoutPurchaseApCreditMemoRouteRouteWithChildren
  '/purchase/ap-invoice': typeof LayoutPurchaseApInvoiceRouteRouteWithChildren
  '/purchase/grpo': typeof LayoutPurchaseGrpoRouteRouteWithChildren
  '/purchase/orders': typeof LayoutPurchaseOrdersRouteRouteWithChildren
  '/purchase/outgoing-payment': typeof LayoutPurchaseOutgoingPaymentRouteRouteWithChildren
  '/purchase/quotations': typeof LayoutPurchaseQuotationsRouteRouteWithChildren
  '/sales/quotations': typeof LayoutSalesQuotationsRouteRouteWithChildren
  '/dashboard/purchase': typeof LayoutDashboardPurchaseRoute
  '/dashboard/sales': typeof LayoutDashboardSalesRoute
  '/intercompany/notifications': typeof LayoutIntercompanyNotificationsRoute
  '/intercompany/retries': typeof LayoutIntercompanyRetriesRoute
  '/purchase/create-ap-credit-memo': typeof LayoutPurchaseCreateApCreditMemoRoute
  '/purchase/create-ap-invoice': typeof LayoutPurchaseCreateApInvoiceRoute
  '/purchase/create-grpo': typeof LayoutPurchaseCreateGrpoRoute
  '/purchase/create-order': typeof LayoutPurchaseCreateOrderRoute
  '/purchase/create-outgoing-payment': typeof LayoutPurchaseCreateOutgoingPaymentRoute
  '/purchase/create-quotation': typeof LayoutPurchaseCreateQuotationRoute
  '/sales/create-quotation': typeof LayoutSalesCreateQuotationRoute
  '/intercompany/': typeof LayoutIntercompanyIndexRoute
  '/purchase/ap-credit-memo/$docNum/update': typeof LayoutPurchaseApCreditMemoDocNumUpdateRoute
  '/purchase/ap-invoice/$docNum/update': typeof LayoutPurchaseApInvoiceDocNumUpdateRoute
  '/purchase/grpo/$docNum/update': typeof LayoutPurchaseGrpoDocNumUpdateRoute
  '/purchase/orders/$docNum/update': typeof LayoutPurchaseOrdersDocNumUpdateRoute
  '/purchase/outgoing-payment/$docNum/update': typeof LayoutPurchaseOutgoingPaymentDocNumUpdateRoute
  '/purchase/quotations/$docNum/update': typeof LayoutPurchaseQuotationsDocNumUpdateRoute
  '/sales/quotations/$docNum/update': typeof LayoutSalesQuotationsDocNumUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRouteRouteWithChildren
  '/purchase/ap-credit-memo': typeof LayoutPurchaseApCreditMemoRouteRouteWithChildren
  '/purchase/ap-invoice': typeof LayoutPurchaseApInvoiceRouteRouteWithChildren
  '/purchase/grpo': typeof LayoutPurchaseGrpoRouteRouteWithChildren
  '/purchase/orders': typeof LayoutPurchaseOrdersRouteRouteWithChildren
  '/purchase/outgoing-payment': typeof LayoutPurchaseOutgoingPaymentRouteRouteWithChildren
  '/purchase/quotations': typeof LayoutPurchaseQuotationsRouteRouteWithChildren
  '/sales/quotations': typeof LayoutSalesQuotationsRouteRouteWithChildren
  '/dashboard/purchase': typeof LayoutDashboardPurchaseRoute
  '/dashboard/sales': typeof LayoutDashboardSalesRoute
  '/intercompany/notifications': typeof LayoutIntercompanyNotificationsRoute
  '/intercompany/retries': typeof LayoutIntercompanyRetriesRoute
  '/purchase/create-ap-credit-memo': typeof LayoutPurchaseCreateApCreditMemoRoute
  '/purchase/create-ap-invoice': typeof LayoutPurchaseCreateApInvoiceRoute
  '/purchase/create-grpo': typeof LayoutPurchaseCreateGrpoRoute
  '/purchase/create-order': typeof LayoutPurchaseCreateOrderRoute
  '/purchase/create-outgoing-payment': typeof LayoutPurchaseCreateOutgoingPaymentRoute
  '/purchase/create-quotation': typeof LayoutPurchaseCreateQuotationRoute
  '/sales/create-quotation': typeof LayoutSalesCreateQuotationRoute
  '/intercompany': typeof LayoutIntercompanyIndexRoute
  '/purchase/ap-credit-memo/$docNum/update': typeof LayoutPurchaseApCreditMemoDocNumUpdateRoute
  '/purchase/ap-invoice/$docNum/update': typeof LayoutPurchaseApInvoiceDocNumUpdateRoute
  '/purchase/grpo/$docNum/update': typeof LayoutPurchaseGrpoDocNumUpdateRoute
  '/purchase/orders/$docNum/update': typeof LayoutPurchaseOrdersDocNumUpdateRoute
  '/purchase/outgoing-payment/$docNum/update': typeof LayoutPurchaseOutgoingPaymentDocNumUpdateRoute
  '/purchase/quotations/$docNum/update': typeof LayoutPurchaseQuotationsDocNumUpdateRoute
  '/sales/quotations/$docNum/update': typeof LayoutSalesQuotationsDocNumUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRouteRouteWithChildren
  '/_layout/intercompany': typeof LayoutIntercompanyRouteRouteWithChildren
  '/_layout/purchase/ap-credit-memo': typeof LayoutPurchaseApCreditMemoRouteRouteWithChildren
  '/_layout/purchase/ap-invoice': typeof LayoutPurchaseApInvoiceRouteRouteWithChildren
  '/_layout/purchase/grpo': typeof LayoutPurchaseGrpoRouteRouteWithChildren
  '/_layout/purchase/orders': typeof LayoutPurchaseOrdersRouteRouteWithChildren
  '/_layout/purchase/outgoing-payment': typeof LayoutPurchaseOutgoingPaymentRouteRouteWithChildren
  '/_layout/purchase/quotations': typeof LayoutPurchaseQuotationsRouteRouteWithChildren
  '/_layout/sales/quotations': typeof LayoutSalesQuotationsRouteRouteWithChildren
  '/_layout/dashboard/purchase': typeof LayoutDashboardPurchaseRoute
  '/_layout/dashboard/sales': typeof LayoutDashboardSalesRoute
  '/_layout/intercompany/notifications': typeof LayoutIntercompanyNotificationsRoute
  '/_layout/intercompany/retries': typeof LayoutIntercompanyRetriesRoute
  '/_layout/purchase/create-ap-credit-memo': typeof LayoutPurchaseCreateApCreditMemoRoute
  '/_layout/purchase/create-ap-invoice': typeof LayoutPurchaseCreateApInvoiceRoute
  '/_layout/purchase/create-grpo': typeof LayoutPurchaseCreateGrpoRoute
  '/_layout/purchase/create-order': typeof LayoutPurchaseCreateOrderRoute
  '/_layout/purchase/create-outgoing-payment': typeof LayoutPurchaseCreateOutgoingPaymentRoute
  '/_layout/purchase/create-quotation': typeof LayoutPurchaseCreateQuotationRoute
  '/_layout/sales/create-quotation': typeof LayoutSalesCreateQuotationRoute
  '/_layout/intercompany/': typeof LayoutIntercompanyIndexRoute
  '/_layout/purchase/ap-credit-memo/$docNum/update': typeof LayoutPurchaseApCreditMemoDocNumUpdateRoute
  '/_layout/purchase/ap-invoice/$docNum/update': typeof LayoutPurchaseApInvoiceDocNumUpdateRoute
  '/_layout/purchase/grpo/$docNum/update': typeof LayoutPurchaseGrpoDocNumUpdateRoute
  '/_layout/purchase/orders/$docNum/update': typeof LayoutPurchaseOrdersDocNumUpdateRoute
  '/_layout/purchase/outgoing-payment/$docNum/update': typeof LayoutPurchaseOutgoingPaymentDocNumUpdateRoute
  '/_layout/purchase/quotations/$docNum/update': typeof LayoutPurchaseQuotationsDocNumUpdateRoute
  '/_layout/sales/quotations/$docNum/update': typeof LayoutSalesQuotationsDocNumUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/intercompany'
    | '/purchase/ap-credit-memo'
    | '/purchase/ap-invoice'
    | '/purchase/grpo'
    | '/purchase/orders'
    | '/purchase/outgoing-payment'
    | '/purchase/quotations'
    | '/sales/quotations'
    | '/dashboard/purchase'
    | '/dashboard/sales'
    | '/intercompany/notifications'
    | '/intercompany/retries'
    | '/purchase/create-ap-credit-memo'
    | '/purchase/create-ap-invoice'
    | '/purchase/create-grpo'
    | '/purchase/create-order'
    | '/purchase/create-outgoing-payment'
    | '/purchase/create-quotation'
    | '/sales/create-quotation'
    | '/intercompany/'
    | '/purchase/ap-credit-memo/$docNum/update'
    | '/purchase/ap-invoice/$docNum/update'
    | '/purchase/grpo/$docNum/update'
    | '/purchase/orders/$docNum/update'
    | '/purchase/outgoing-payment/$docNum/update'
    | '/purchase/quotations/$docNum/update'
    | '/sales/quotations/$docNum/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/purchase/ap-credit-memo'
    | '/purchase/ap-invoice'
    | '/purchase/grpo'
    | '/purchase/orders'
    | '/purchase/outgoing-payment'
    | '/purchase/quotations'
    | '/sales/quotations'
    | '/dashboard/purchase'
    | '/dashboard/sales'
    | '/intercompany/notifications'
    | '/intercompany/retries'
    | '/purchase/create-ap-credit-memo'
    | '/purchase/create-ap-invoice'
    | '/purchase/create-grpo'
    | '/purchase/create-order'
    | '/purchase/create-outgoing-payment'
    | '/purchase/create-quotation'
    | '/sales/create-quotation'
    | '/intercompany'
    | '/purchase/ap-credit-memo/$docNum/update'
    | '/purchase/ap-invoice/$docNum/update'
    | '/purchase/grpo/$docNum/update'
    | '/purchase/orders/$docNum/update'
    | '/purchase/outgoing-payment/$docNum/update'
    | '/purchase/quotations/$docNum/update'
    | '/sales/quotations/$docNum/update'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/_layout/intercompany'
    | '/_layout/purchase/ap-credit-memo'
    | '/_layout/purchase/ap-invoice'
    | '/_layout/purchase/grpo'
    | '/_layout/purchase/orders'
    | '/_layout/purchase/outgoing-payment'
    | '/_layout/purchase/quotations'
    | '/_layout/sales/quotations'
    | '/_layout/dashboard/purchase'
    | '/_layout/dashboard/sales'
    | '/_layout/intercompany/notifications'
    | '/_layout/intercompany/retries'
    | '/_layout/purchase/create-ap-credit-memo'
    | '/_layout/purchase/create-ap-invoice'
    | '/_layout/purchase/create-grpo'
    | '/_layout/purchase/create-order'
    | '/_layout/purchase/create-outgoing-payment'
    | '/_layout/purchase/create-quotation'
    | '/_layout/sales/create-quotation'
    | '/_layout/intercompany/'
    | '/_layout/purchase/ap-credit-memo/$docNum/update'
    | '/_layout/purchase/ap-invoice/$docNum/update'
    | '/_layout/purchase/grpo/$docNum/update'
    | '/_layout/purchase/orders/$docNum/update'
    | '/_layout/purchase/outgoing-payment/$docNum/update'
    | '/_layout/purchase/quotations/$docNum/update'
    | '/_layout/sales/quotations/$docNum/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/intercompany': {
      id: '/_layout/intercompany'
      path: '/intercompany'
      fullPath: '/intercompany'
      preLoaderRoute: typeof LayoutIntercompanyRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/purchase': {
      id: '/_layout/dashboard/purchase'
      path: '/purchase'
      fullPath: '/dashboard/purchase'
      preLoaderRoute: typeof LayoutDashboardPurchaseRouteImport
      parentRoute: typeof LayoutDashboardRouteRoute
    }
    '/_layout/dashboard/sales': {
      id: '/_layout/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof LayoutDashboardSalesRouteImport
      parentRoute: typeof LayoutDashboardRouteRoute
    }
    '/_layout/intercompany/': {
      id: '/_layout/intercompany/'
      path: '/'
      fullPath: '/intercompany/'
      preLoaderRoute: typeof LayoutIntercompanyIndexRouteImport
      parentRoute: typeof LayoutIntercompanyRouteRoute
    }
    '/_layout/intercompany/notifications': {
      id: '/_layout/intercompany/notifications'
      path: '/notifications'
      fullPath: '/intercompany/notifications'
      preLoaderRoute: typeof LayoutIntercompanyNotificationsRouteImport
      parentRoute: typeof LayoutIntercompanyRouteRoute
    }
    '/_layout/intercompany/retries': {
      id: '/_layout/intercompany/retries'
      path: '/retries'
      fullPath: '/intercompany/retries'
      preLoaderRoute: typeof LayoutIntercompanyRetriesRouteImport
      parentRoute: typeof LayoutIntercompanyRouteRoute
    }
    '/_layout/purchase/ap-credit-memo': {
      id: '/_layout/purchase/ap-credit-memo'
      path: '/purchase/ap-credit-memo'
      fullPath: '/purchase/ap-credit-memo'
      preLoaderRoute: typeof LayoutPurchaseApCreditMemoRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/ap-invoice': {
      id: '/_layout/purchase/ap-invoice'
      path: '/purchase/ap-invoice'
      fullPath: '/purchase/ap-invoice'
      preLoaderRoute: typeof LayoutPurchaseApInvoiceRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-ap-credit-memo': {
      id: '/_layout/purchase/create-ap-credit-memo'
      path: '/purchase/create-ap-credit-memo'
      fullPath: '/purchase/create-ap-credit-memo'
      preLoaderRoute: typeof LayoutPurchaseCreateApCreditMemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-ap-invoice': {
      id: '/_layout/purchase/create-ap-invoice'
      path: '/purchase/create-ap-invoice'
      fullPath: '/purchase/create-ap-invoice'
      preLoaderRoute: typeof LayoutPurchaseCreateApInvoiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-grpo': {
      id: '/_layout/purchase/create-grpo'
      path: '/purchase/create-grpo'
      fullPath: '/purchase/create-grpo'
      preLoaderRoute: typeof LayoutPurchaseCreateGrpoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-order': {
      id: '/_layout/purchase/create-order'
      path: '/purchase/create-order'
      fullPath: '/purchase/create-order'
      preLoaderRoute: typeof LayoutPurchaseCreateOrderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-outgoing-payment': {
      id: '/_layout/purchase/create-outgoing-payment'
      path: '/purchase/create-outgoing-payment'
      fullPath: '/purchase/create-outgoing-payment'
      preLoaderRoute: typeof LayoutPurchaseCreateOutgoingPaymentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-quotation': {
      id: '/_layout/purchase/create-quotation'
      path: '/purchase/create-quotation'
      fullPath: '/purchase/create-quotation'
      preLoaderRoute: typeof LayoutPurchaseCreateQuotationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/grpo': {
      id: '/_layout/purchase/grpo'
      path: '/purchase/grpo'
      fullPath: '/purchase/grpo'
      preLoaderRoute: typeof LayoutPurchaseGrpoRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/orders': {
      id: '/_layout/purchase/orders'
      path: '/purchase/orders'
      fullPath: '/purchase/orders'
      preLoaderRoute: typeof LayoutPurchaseOrdersRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/outgoing-payment': {
      id: '/_layout/purchase/outgoing-payment'
      path: '/purchase/outgoing-payment'
      fullPath: '/purchase/outgoing-payment'
      preLoaderRoute: typeof LayoutPurchaseOutgoingPaymentRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/quotations': {
      id: '/_layout/purchase/quotations'
      path: '/purchase/quotations'
      fullPath: '/purchase/quotations'
      preLoaderRoute: typeof LayoutPurchaseQuotationsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/create-quotation': {
      id: '/_layout/sales/create-quotation'
      path: '/sales/create-quotation'
      fullPath: '/sales/create-quotation'
      preLoaderRoute: typeof LayoutSalesCreateQuotationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/quotations': {
      id: '/_layout/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof LayoutSalesQuotationsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/ap-credit-memo/$docNum/update': {
      id: '/_layout/purchase/ap-credit-memo/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/purchase/ap-credit-memo/$docNum/update'
      preLoaderRoute: typeof LayoutPurchaseApCreditMemoDocNumUpdateRouteImport
      parentRoute: typeof LayoutPurchaseApCreditMemoRouteRoute
    }
    '/_layout/purchase/ap-invoice/$docNum/update': {
      id: '/_layout/purchase/ap-invoice/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/purchase/ap-invoice/$docNum/update'
      preLoaderRoute: typeof LayoutPurchaseApInvoiceDocNumUpdateRouteImport
      parentRoute: typeof LayoutPurchaseApInvoiceRouteRoute
    }
    '/_layout/purchase/grpo/$docNum/update': {
      id: '/_layout/purchase/grpo/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/purchase/grpo/$docNum/update'
      preLoaderRoute: typeof LayoutPurchaseGrpoDocNumUpdateRouteImport
      parentRoute: typeof LayoutPurchaseGrpoRouteRoute
    }
    '/_layout/purchase/orders/$docNum/update': {
      id: '/_layout/purchase/orders/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/purchase/orders/$docNum/update'
      preLoaderRoute: typeof LayoutPurchaseOrdersDocNumUpdateRouteImport
      parentRoute: typeof LayoutPurchaseOrdersRouteRoute
    }
    '/_layout/purchase/outgoing-payment/$docNum/update': {
      id: '/_layout/purchase/outgoing-payment/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/purchase/outgoing-payment/$docNum/update'
      preLoaderRoute: typeof LayoutPurchaseOutgoingPaymentDocNumUpdateRouteImport
      parentRoute: typeof LayoutPurchaseOutgoingPaymentRouteRoute
    }
    '/_layout/purchase/quotations/$docNum/update': {
      id: '/_layout/purchase/quotations/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/purchase/quotations/$docNum/update'
      preLoaderRoute: typeof LayoutPurchaseQuotationsDocNumUpdateRouteImport
      parentRoute: typeof LayoutPurchaseQuotationsRouteRoute
    }
    '/_layout/sales/quotations/$docNum/update': {
      id: '/_layout/sales/quotations/$docNum/update'
      path: '/$docNum/update'
      fullPath: '/sales/quotations/$docNum/update'
      preLoaderRoute: typeof LayoutSalesQuotationsDocNumUpdateRouteImport
      parentRoute: typeof LayoutSalesQuotationsRouteRoute
    }
  }
}

interface LayoutDashboardRouteRouteChildren {
  LayoutDashboardPurchaseRoute: typeof LayoutDashboardPurchaseRoute
  LayoutDashboardSalesRoute: typeof LayoutDashboardSalesRoute
}

const LayoutDashboardRouteRouteChildren: LayoutDashboardRouteRouteChildren = {
  LayoutDashboardPurchaseRoute: LayoutDashboardPurchaseRoute,
  LayoutDashboardSalesRoute: LayoutDashboardSalesRoute,
}

const LayoutDashboardRouteRouteWithChildren =
  LayoutDashboardRouteRoute._addFileChildren(LayoutDashboardRouteRouteChildren)

interface LayoutIntercompanyRouteRouteChildren {
  LayoutIntercompanyNotificationsRoute: typeof LayoutIntercompanyNotificationsRoute
  LayoutIntercompanyRetriesRoute: typeof LayoutIntercompanyRetriesRoute
  LayoutIntercompanyIndexRoute: typeof LayoutIntercompanyIndexRoute
}

const LayoutIntercompanyRouteRouteChildren: LayoutIntercompanyRouteRouteChildren =
  {
    LayoutIntercompanyNotificationsRoute: LayoutIntercompanyNotificationsRoute,
    LayoutIntercompanyRetriesRoute: LayoutIntercompanyRetriesRoute,
    LayoutIntercompanyIndexRoute: LayoutIntercompanyIndexRoute,
  }

const LayoutIntercompanyRouteRouteWithChildren =
  LayoutIntercompanyRouteRoute._addFileChildren(
    LayoutIntercompanyRouteRouteChildren,
  )

interface LayoutPurchaseApCreditMemoRouteRouteChildren {
  LayoutPurchaseApCreditMemoDocNumUpdateRoute: typeof LayoutPurchaseApCreditMemoDocNumUpdateRoute
}

const LayoutPurchaseApCreditMemoRouteRouteChildren: LayoutPurchaseApCreditMemoRouteRouteChildren =
  {
    LayoutPurchaseApCreditMemoDocNumUpdateRoute:
      LayoutPurchaseApCreditMemoDocNumUpdateRoute,
  }

const LayoutPurchaseApCreditMemoRouteRouteWithChildren =
  LayoutPurchaseApCreditMemoRouteRoute._addFileChildren(
    LayoutPurchaseApCreditMemoRouteRouteChildren,
  )

interface LayoutPurchaseApInvoiceRouteRouteChildren {
  LayoutPurchaseApInvoiceDocNumUpdateRoute: typeof LayoutPurchaseApInvoiceDocNumUpdateRoute
}

const LayoutPurchaseApInvoiceRouteRouteChildren: LayoutPurchaseApInvoiceRouteRouteChildren =
  {
    LayoutPurchaseApInvoiceDocNumUpdateRoute:
      LayoutPurchaseApInvoiceDocNumUpdateRoute,
  }

const LayoutPurchaseApInvoiceRouteRouteWithChildren =
  LayoutPurchaseApInvoiceRouteRoute._addFileChildren(
    LayoutPurchaseApInvoiceRouteRouteChildren,
  )

interface LayoutPurchaseGrpoRouteRouteChildren {
  LayoutPurchaseGrpoDocNumUpdateRoute: typeof LayoutPurchaseGrpoDocNumUpdateRoute
}

const LayoutPurchaseGrpoRouteRouteChildren: LayoutPurchaseGrpoRouteRouteChildren =
  {
    LayoutPurchaseGrpoDocNumUpdateRoute: LayoutPurchaseGrpoDocNumUpdateRoute,
  }

const LayoutPurchaseGrpoRouteRouteWithChildren =
  LayoutPurchaseGrpoRouteRoute._addFileChildren(
    LayoutPurchaseGrpoRouteRouteChildren,
  )

interface LayoutPurchaseOrdersRouteRouteChildren {
  LayoutPurchaseOrdersDocNumUpdateRoute: typeof LayoutPurchaseOrdersDocNumUpdateRoute
}

const LayoutPurchaseOrdersRouteRouteChildren: LayoutPurchaseOrdersRouteRouteChildren =
  {
    LayoutPurchaseOrdersDocNumUpdateRoute:
      LayoutPurchaseOrdersDocNumUpdateRoute,
  }

const LayoutPurchaseOrdersRouteRouteWithChildren =
  LayoutPurchaseOrdersRouteRoute._addFileChildren(
    LayoutPurchaseOrdersRouteRouteChildren,
  )

interface LayoutPurchaseOutgoingPaymentRouteRouteChildren {
  LayoutPurchaseOutgoingPaymentDocNumUpdateRoute: typeof LayoutPurchaseOutgoingPaymentDocNumUpdateRoute
}

const LayoutPurchaseOutgoingPaymentRouteRouteChildren: LayoutPurchaseOutgoingPaymentRouteRouteChildren =
  {
    LayoutPurchaseOutgoingPaymentDocNumUpdateRoute:
      LayoutPurchaseOutgoingPaymentDocNumUpdateRoute,
  }

const LayoutPurchaseOutgoingPaymentRouteRouteWithChildren =
  LayoutPurchaseOutgoingPaymentRouteRoute._addFileChildren(
    LayoutPurchaseOutgoingPaymentRouteRouteChildren,
  )

interface LayoutPurchaseQuotationsRouteRouteChildren {
  LayoutPurchaseQuotationsDocNumUpdateRoute: typeof LayoutPurchaseQuotationsDocNumUpdateRoute
}

const LayoutPurchaseQuotationsRouteRouteChildren: LayoutPurchaseQuotationsRouteRouteChildren =
  {
    LayoutPurchaseQuotationsDocNumUpdateRoute:
      LayoutPurchaseQuotationsDocNumUpdateRoute,
  }

const LayoutPurchaseQuotationsRouteRouteWithChildren =
  LayoutPurchaseQuotationsRouteRoute._addFileChildren(
    LayoutPurchaseQuotationsRouteRouteChildren,
  )

interface LayoutSalesQuotationsRouteRouteChildren {
  LayoutSalesQuotationsDocNumUpdateRoute: typeof LayoutSalesQuotationsDocNumUpdateRoute
}

const LayoutSalesQuotationsRouteRouteChildren: LayoutSalesQuotationsRouteRouteChildren =
  {
    LayoutSalesQuotationsDocNumUpdateRoute:
      LayoutSalesQuotationsDocNumUpdateRoute,
  }

const LayoutSalesQuotationsRouteRouteWithChildren =
  LayoutSalesQuotationsRouteRoute._addFileChildren(
    LayoutSalesQuotationsRouteRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutDashboardRouteRoute: typeof LayoutDashboardRouteRouteWithChildren
  LayoutIntercompanyRouteRoute: typeof LayoutIntercompanyRouteRouteWithChildren
  LayoutPurchaseApCreditMemoRouteRoute: typeof LayoutPurchaseApCreditMemoRouteRouteWithChildren
  LayoutPurchaseApInvoiceRouteRoute: typeof LayoutPurchaseApInvoiceRouteRouteWithChildren
  LayoutPurchaseGrpoRouteRoute: typeof LayoutPurchaseGrpoRouteRouteWithChildren
  LayoutPurchaseOrdersRouteRoute: typeof LayoutPurchaseOrdersRouteRouteWithChildren
  LayoutPurchaseOutgoingPaymentRouteRoute: typeof LayoutPurchaseOutgoingPaymentRouteRouteWithChildren
  LayoutPurchaseQuotationsRouteRoute: typeof LayoutPurchaseQuotationsRouteRouteWithChildren
  LayoutSalesQuotationsRouteRoute: typeof LayoutSalesQuotationsRouteRouteWithChildren
  LayoutPurchaseCreateApCreditMemoRoute: typeof LayoutPurchaseCreateApCreditMemoRoute
  LayoutPurchaseCreateApInvoiceRoute: typeof LayoutPurchaseCreateApInvoiceRoute
  LayoutPurchaseCreateGrpoRoute: typeof LayoutPurchaseCreateGrpoRoute
  LayoutPurchaseCreateOrderRoute: typeof LayoutPurchaseCreateOrderRoute
  LayoutPurchaseCreateOutgoingPaymentRoute: typeof LayoutPurchaseCreateOutgoingPaymentRoute
  LayoutPurchaseCreateQuotationRoute: typeof LayoutPurchaseCreateQuotationRoute
  LayoutSalesCreateQuotationRoute: typeof LayoutSalesCreateQuotationRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRouteRoute: LayoutDashboardRouteRouteWithChildren,
  LayoutIntercompanyRouteRoute: LayoutIntercompanyRouteRouteWithChildren,
  LayoutPurchaseApCreditMemoRouteRoute:
    LayoutPurchaseApCreditMemoRouteRouteWithChildren,
  LayoutPurchaseApInvoiceRouteRoute:
    LayoutPurchaseApInvoiceRouteRouteWithChildren,
  LayoutPurchaseGrpoRouteRoute: LayoutPurchaseGrpoRouteRouteWithChildren,
  LayoutPurchaseOrdersRouteRoute: LayoutPurchaseOrdersRouteRouteWithChildren,
  LayoutPurchaseOutgoingPaymentRouteRoute:
    LayoutPurchaseOutgoingPaymentRouteRouteWithChildren,
  LayoutPurchaseQuotationsRouteRoute:
    LayoutPurchaseQuotationsRouteRouteWithChildren,
  LayoutSalesQuotationsRouteRoute: LayoutSalesQuotationsRouteRouteWithChildren,
  LayoutPurchaseCreateApCreditMemoRoute: LayoutPurchaseCreateApCreditMemoRoute,
  LayoutPurchaseCreateApInvoiceRoute: LayoutPurchaseCreateApInvoiceRoute,
  LayoutPurchaseCreateGrpoRoute: LayoutPurchaseCreateGrpoRoute,
  LayoutPurchaseCreateOrderRoute: LayoutPurchaseCreateOrderRoute,
  LayoutPurchaseCreateOutgoingPaymentRoute:
    LayoutPurchaseCreateOutgoingPaymentRoute,
  LayoutPurchaseCreateQuotationRoute: LayoutPurchaseCreateQuotationRoute,
  LayoutSalesCreateQuotationRoute: LayoutSalesCreateQuotationRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
