/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutSalesQuotationsRouteImport } from './routes/_layout.sales.quotations'
import { Route as LayoutSalesOrdersRouteImport } from './routes/_layout.sales.orders'
import { Route as LayoutSalesIncomingPaymentRouteImport } from './routes/_layout.sales.incoming-payment'
import { Route as LayoutSalesCreateQuotationRouteImport } from './routes/_layout.sales.create-quotation'
import { Route as LayoutSalesCreateOrderRouteImport } from './routes/_layout.sales.create-order'
import { Route as LayoutSalesCreateIncomingPaymentRouteImport } from './routes/_layout.sales.create-incoming-payment'
import { Route as LayoutSalesCreateArInvoiceRouteImport } from './routes/_layout.sales.create-ar-invoice'
import { Route as LayoutSalesArInvoiceRouteImport } from './routes/_layout.sales.ar-invoice'
import { Route as LayoutSalesArCreditMemoRouteImport } from './routes/_layout.sales.ar-credit-memo'
import { Route as LayoutPurchaseQuotationsRouteImport } from './routes/_layout.purchase.quotations'
import { Route as LayoutPurchaseOutgoingPaymentRouteImport } from './routes/_layout.purchase.outgoing-payment'
import { Route as LayoutPurchaseOrdersRouteImport } from './routes/_layout.purchase.orders'
import { Route as LayoutPurchaseGrpoRouteImport } from './routes/_layout.purchase.grpo'
import { Route as LayoutPurchaseCreateQuotationRouteImport } from './routes/_layout.purchase.create-quotation'
import { Route as LayoutPurchaseCreateOutgoingPaymentRouteImport } from './routes/_layout.purchase.create-outgoing-payment'
import { Route as LayoutPurchaseCreateOrderRouteImport } from './routes/_layout.purchase.create-order'
import { Route as LayoutPurchaseCreateGrpoRouteImport } from './routes/_layout.purchase.create-grpo'
import { Route as LayoutPurchaseCreateApInvoiceRouteImport } from './routes/_layout.purchase.create-ap-invoice'
import { Route as LayoutPurchaseCreateApCreditMemoRouteImport } from './routes/_layout.purchase.create-ap-credit-memo'
import { Route as LayoutPurchaseApInvoiceRouteImport } from './routes/_layout.purchase.ap-invoice'
import { Route as LayoutPurchaseApCreditMemoRouteImport } from './routes/_layout.purchase.ap-credit-memo'
import { Route as LayoutInventoryTransferRequestRouteImport } from './routes/_layout.inventory.transfer-request'
import { Route as LayoutInventoryTransferRouteImport } from './routes/_layout.inventory.transfer'
import { Route as LayoutInventoryItemMasterRouteImport } from './routes/_layout.inventory.item-master'
import { Route as LayoutInventoryGoodsReceiptRouteImport } from './routes/_layout.inventory.goods-receipt'
import { Route as LayoutInventoryGoodsIssueRouteImport } from './routes/_layout.inventory.goods-issue'
import { Route as LayoutDashboardSalesRouteImport } from './routes/_layout.dashboard.sales'
import { Route as LayoutDashboardPurchaseRouteImport } from './routes/_layout.dashboard.purchase'
import { Route as LayoutDashboardInventoryRouteImport } from './routes/_layout.dashboard.inventory'
import { Route as LayoutSalesArCreditMemoSelectInvoiceRouteImport } from './routes/_layout.sales.ar-credit-memo.select-invoice'
import { Route as LayoutSalesArCreditMemoCreateRouteImport } from './routes/_layout.sales.ar-credit-memo.create'
import { Route as LayoutInventoryTransferCreateRouteImport } from './routes/_layout.inventory.transfer.create'
import { Route as LayoutInventoryTransferRequestCreateRouteImport } from './routes/_layout.inventory.transfer-request.create'
import { Route as LayoutInventoryItemMasterCreateRouteImport } from './routes/_layout.inventory.item-master.create'
import { Route as LayoutInventoryGoodsReceiptCreateRouteImport } from './routes/_layout.inventory.goods-receipt.create'
import { Route as LayoutInventoryGoodsIssueCreateRouteImport } from './routes/_layout.inventory.goods-issue.create'
import { Route as LayoutSalesQuotationsDocNumEditRouteImport } from './routes/_layout.sales.quotations.$docNum.edit'
import { Route as LayoutSalesOrdersDocNumEditRouteImport } from './routes/_layout.sales.orders.$docNum.edit'
import { Route as LayoutSalesIncomingPaymentDocNumEditRouteImport } from './routes/_layout.sales.incoming-payment.$docNum.edit'
import { Route as LayoutSalesArInvoiceDocNumEditRouteImport } from './routes/_layout.sales.ar-invoice.$docNum.edit'
import { Route as LayoutSalesArCreditMemoDocNumEditRouteImport } from './routes/_layout.sales.ar-credit-memo.$docNum.edit'
import { Route as LayoutPurchaseQuotationsDocNumEditRouteImport } from './routes/_layout.purchase.quotations.$docNum.edit'
import { Route as LayoutPurchaseOutgoingPaymentDocNumEditRouteImport } from './routes/_layout.purchase.outgoing-payment.$docNum.edit'
import { Route as LayoutPurchaseOrdersDocNumEditRouteImport } from './routes/_layout.purchase.orders.$docNum.edit'
import { Route as LayoutPurchaseGrpoDocNumEditRouteImport } from './routes/_layout.purchase.grpo.$docNum.edit'
import { Route as LayoutPurchaseApInvoiceDocNumEditRouteImport } from './routes/_layout.purchase.ap-invoice.$docNum.edit'
import { Route as LayoutPurchaseApCreditMemoDocNumEditRouteImport } from './routes/_layout.purchase.ap-credit-memo.$docNum.edit'
import { Route as LayoutInventoryGoodsReceiptDocNumEditRouteImport } from './routes/_layout.inventory.goods-receipt.$docNum.edit'
import { Route as LayoutInventoryGoodsIssueDocNumEditRouteImport } from './routes/_layout.inventory.goods-issue.$docNum.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesQuotationsRoute = LayoutSalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesOrdersRoute = LayoutSalesOrdersRouteImport.update({
  id: '/sales/orders',
  path: '/sales/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesIncomingPaymentRoute =
  LayoutSalesIncomingPaymentRouteImport.update({
    id: '/sales/incoming-payment',
    path: '/sales/incoming-payment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesCreateQuotationRoute =
  LayoutSalesCreateQuotationRouteImport.update({
    id: '/sales/create-quotation',
    path: '/sales/create-quotation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesCreateOrderRoute = LayoutSalesCreateOrderRouteImport.update({
  id: '/sales/create-order',
  path: '/sales/create-order',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesCreateIncomingPaymentRoute =
  LayoutSalesCreateIncomingPaymentRouteImport.update({
    id: '/sales/create-incoming-payment',
    path: '/sales/create-incoming-payment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesCreateArInvoiceRoute =
  LayoutSalesCreateArInvoiceRouteImport.update({
    id: '/sales/create-ar-invoice',
    path: '/sales/create-ar-invoice',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesArInvoiceRoute = LayoutSalesArInvoiceRouteImport.update({
  id: '/sales/ar-invoice',
  path: '/sales/ar-invoice',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesArCreditMemoRoute = LayoutSalesArCreditMemoRouteImport.update({
  id: '/sales/ar-credit-memo',
  path: '/sales/ar-credit-memo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseQuotationsRoute =
  LayoutPurchaseQuotationsRouteImport.update({
    id: '/purchase/quotations',
    path: '/purchase/quotations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseOutgoingPaymentRoute =
  LayoutPurchaseOutgoingPaymentRouteImport.update({
    id: '/purchase/outgoing-payment',
    path: '/purchase/outgoing-payment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseOrdersRoute = LayoutPurchaseOrdersRouteImport.update({
  id: '/purchase/orders',
  path: '/purchase/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseGrpoRoute = LayoutPurchaseGrpoRouteImport.update({
  id: '/purchase/grpo',
  path: '/purchase/grpo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseCreateQuotationRoute =
  LayoutPurchaseCreateQuotationRouteImport.update({
    id: '/purchase/create-quotation',
    path: '/purchase/create-quotation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateOutgoingPaymentRoute =
  LayoutPurchaseCreateOutgoingPaymentRouteImport.update({
    id: '/purchase/create-outgoing-payment',
    path: '/purchase/create-outgoing-payment',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateOrderRoute =
  LayoutPurchaseCreateOrderRouteImport.update({
    id: '/purchase/create-order',
    path: '/purchase/create-order',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateGrpoRoute =
  LayoutPurchaseCreateGrpoRouteImport.update({
    id: '/purchase/create-grpo',
    path: '/purchase/create-grpo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateApInvoiceRoute =
  LayoutPurchaseCreateApInvoiceRouteImport.update({
    id: '/purchase/create-ap-invoice',
    path: '/purchase/create-ap-invoice',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseCreateApCreditMemoRoute =
  LayoutPurchaseCreateApCreditMemoRouteImport.update({
    id: '/purchase/create-ap-credit-memo',
    path: '/purchase/create-ap-credit-memo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPurchaseApInvoiceRoute = LayoutPurchaseApInvoiceRouteImport.update({
  id: '/purchase/ap-invoice',
  path: '/purchase/ap-invoice',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseApCreditMemoRoute =
  LayoutPurchaseApCreditMemoRouteImport.update({
    id: '/purchase/ap-credit-memo',
    path: '/purchase/ap-credit-memo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryTransferRequestRoute =
  LayoutInventoryTransferRequestRouteImport.update({
    id: '/inventory/transfer-request',
    path: '/inventory/transfer-request',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryTransferRoute = LayoutInventoryTransferRouteImport.update({
  id: '/inventory/transfer',
  path: '/inventory/transfer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInventoryItemMasterRoute =
  LayoutInventoryItemMasterRouteImport.update({
    id: '/inventory/item-master',
    path: '/inventory/item-master',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryGoodsReceiptRoute =
  LayoutInventoryGoodsReceiptRouteImport.update({
    id: '/inventory/goods-receipt',
    path: '/inventory/goods-receipt',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInventoryGoodsIssueRoute =
  LayoutInventoryGoodsIssueRouteImport.update({
    id: '/inventory/goods-issue',
    path: '/inventory/goods-issue',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardSalesRoute = LayoutDashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardPurchaseRoute = LayoutDashboardPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardInventoryRoute =
  LayoutDashboardInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutSalesArCreditMemoSelectInvoiceRoute =
  LayoutSalesArCreditMemoSelectInvoiceRouteImport.update({
    id: '/select-invoice',
    path: '/select-invoice',
    getParentRoute: () => LayoutSalesArCreditMemoRoute,
  } as any)
const LayoutSalesArCreditMemoCreateRoute =
  LayoutSalesArCreditMemoCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => LayoutSalesArCreditMemoRoute,
  } as any)
const LayoutInventoryTransferCreateRoute =
  LayoutInventoryTransferCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => LayoutInventoryTransferRoute,
  } as any)
const LayoutInventoryTransferRequestCreateRoute =
  LayoutInventoryTransferRequestCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => LayoutInventoryTransferRequestRoute,
  } as any)
const LayoutInventoryItemMasterCreateRoute =
  LayoutInventoryItemMasterCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => LayoutInventoryItemMasterRoute,
  } as any)
const LayoutInventoryGoodsReceiptCreateRoute =
  LayoutInventoryGoodsReceiptCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => LayoutInventoryGoodsReceiptRoute,
  } as any)
const LayoutInventoryGoodsIssueCreateRoute =
  LayoutInventoryGoodsIssueCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => LayoutInventoryGoodsIssueRoute,
  } as any)
const LayoutSalesQuotationsDocNumEditRoute =
  LayoutSalesQuotationsDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutSalesQuotationsRoute,
  } as any)
const LayoutSalesOrdersDocNumEditRoute =
  LayoutSalesOrdersDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutSalesOrdersRoute,
  } as any)
const LayoutSalesIncomingPaymentDocNumEditRoute =
  LayoutSalesIncomingPaymentDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutSalesIncomingPaymentRoute,
  } as any)
const LayoutSalesArInvoiceDocNumEditRoute =
  LayoutSalesArInvoiceDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutSalesArInvoiceRoute,
  } as any)
const LayoutSalesArCreditMemoDocNumEditRoute =
  LayoutSalesArCreditMemoDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutSalesArCreditMemoRoute,
  } as any)
const LayoutPurchaseQuotationsDocNumEditRoute =
  LayoutPurchaseQuotationsDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutPurchaseQuotationsRoute,
  } as any)
const LayoutPurchaseOutgoingPaymentDocNumEditRoute =
  LayoutPurchaseOutgoingPaymentDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutPurchaseOutgoingPaymentRoute,
  } as any)
const LayoutPurchaseOrdersDocNumEditRoute =
  LayoutPurchaseOrdersDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutPurchaseOrdersRoute,
  } as any)
const LayoutPurchaseGrpoDocNumEditRoute =
  LayoutPurchaseGrpoDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutPurchaseGrpoRoute,
  } as any)
const LayoutPurchaseApInvoiceDocNumEditRoute =
  LayoutPurchaseApInvoiceDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutPurchaseApInvoiceRoute,
  } as any)
const LayoutPurchaseApCreditMemoDocNumEditRoute =
  LayoutPurchaseApCreditMemoDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutPurchaseApCreditMemoRoute,
  } as any)
const LayoutInventoryGoodsReceiptDocNumEditRoute =
  LayoutInventoryGoodsReceiptDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutInventoryGoodsReceiptRoute,
  } as any)
const LayoutInventoryGoodsIssueDocNumEditRoute =
  LayoutInventoryGoodsIssueDocNumEditRouteImport.update({
    id: '/$docNum/edit',
    path: '/$docNum/edit',
    getParentRoute: () => LayoutInventoryGoodsIssueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/dashboard/inventory': typeof LayoutDashboardInventoryRoute
  '/dashboard/purchase': typeof LayoutDashboardPurchaseRoute
  '/dashboard/sales': typeof LayoutDashboardSalesRoute
  '/inventory/goods-issue': typeof LayoutInventoryGoodsIssueRouteWithChildren
  '/inventory/goods-receipt': typeof LayoutInventoryGoodsReceiptRouteWithChildren
  '/inventory/item-master': typeof LayoutInventoryItemMasterRouteWithChildren
  '/inventory/transfer': typeof LayoutInventoryTransferRouteWithChildren
  '/inventory/transfer-request': typeof LayoutInventoryTransferRequestRouteWithChildren
  '/purchase/ap-credit-memo': typeof LayoutPurchaseApCreditMemoRouteWithChildren
  '/purchase/ap-invoice': typeof LayoutPurchaseApInvoiceRouteWithChildren
  '/purchase/create-ap-credit-memo': typeof LayoutPurchaseCreateApCreditMemoRoute
  '/purchase/create-ap-invoice': typeof LayoutPurchaseCreateApInvoiceRoute
  '/purchase/create-grpo': typeof LayoutPurchaseCreateGrpoRoute
  '/purchase/create-order': typeof LayoutPurchaseCreateOrderRoute
  '/purchase/create-outgoing-payment': typeof LayoutPurchaseCreateOutgoingPaymentRoute
  '/purchase/create-quotation': typeof LayoutPurchaseCreateQuotationRoute
  '/purchase/grpo': typeof LayoutPurchaseGrpoRouteWithChildren
  '/purchase/orders': typeof LayoutPurchaseOrdersRouteWithChildren
  '/purchase/outgoing-payment': typeof LayoutPurchaseOutgoingPaymentRouteWithChildren
  '/purchase/quotations': typeof LayoutPurchaseQuotationsRouteWithChildren
  '/sales/ar-credit-memo': typeof LayoutSalesArCreditMemoRouteWithChildren
  '/sales/ar-invoice': typeof LayoutSalesArInvoiceRouteWithChildren
  '/sales/create-ar-invoice': typeof LayoutSalesCreateArInvoiceRoute
  '/sales/create-incoming-payment': typeof LayoutSalesCreateIncomingPaymentRoute
  '/sales/create-order': typeof LayoutSalesCreateOrderRoute
  '/sales/create-quotation': typeof LayoutSalesCreateQuotationRoute
  '/sales/incoming-payment': typeof LayoutSalesIncomingPaymentRouteWithChildren
  '/sales/orders': typeof LayoutSalesOrdersRouteWithChildren
  '/sales/quotations': typeof LayoutSalesQuotationsRouteWithChildren
  '/inventory/goods-issue/create': typeof LayoutInventoryGoodsIssueCreateRoute
  '/inventory/goods-receipt/create': typeof LayoutInventoryGoodsReceiptCreateRoute
  '/inventory/item-master/create': typeof LayoutInventoryItemMasterCreateRoute
  '/inventory/transfer-request/create': typeof LayoutInventoryTransferRequestCreateRoute
  '/inventory/transfer/create': typeof LayoutInventoryTransferCreateRoute
  '/sales/ar-credit-memo/create': typeof LayoutSalesArCreditMemoCreateRoute
  '/sales/ar-credit-memo/select-invoice': typeof LayoutSalesArCreditMemoSelectInvoiceRoute
  '/inventory/goods-issue/$docNum/edit': typeof LayoutInventoryGoodsIssueDocNumEditRoute
  '/inventory/goods-receipt/$docNum/edit': typeof LayoutInventoryGoodsReceiptDocNumEditRoute
  '/purchase/ap-credit-memo/$docNum/edit': typeof LayoutPurchaseApCreditMemoDocNumEditRoute
  '/purchase/ap-invoice/$docNum/edit': typeof LayoutPurchaseApInvoiceDocNumEditRoute
  '/purchase/grpo/$docNum/edit': typeof LayoutPurchaseGrpoDocNumEditRoute
  '/purchase/orders/$docNum/edit': typeof LayoutPurchaseOrdersDocNumEditRoute
  '/purchase/outgoing-payment/$docNum/edit': typeof LayoutPurchaseOutgoingPaymentDocNumEditRoute
  '/purchase/quotations/$docNum/edit': typeof LayoutPurchaseQuotationsDocNumEditRoute
  '/sales/ar-credit-memo/$docNum/edit': typeof LayoutSalesArCreditMemoDocNumEditRoute
  '/sales/ar-invoice/$docNum/edit': typeof LayoutSalesArInvoiceDocNumEditRoute
  '/sales/incoming-payment/$docNum/edit': typeof LayoutSalesIncomingPaymentDocNumEditRoute
  '/sales/orders/$docNum/edit': typeof LayoutSalesOrdersDocNumEditRoute
  '/sales/quotations/$docNum/edit': typeof LayoutSalesQuotationsDocNumEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/dashboard/inventory': typeof LayoutDashboardInventoryRoute
  '/dashboard/purchase': typeof LayoutDashboardPurchaseRoute
  '/dashboard/sales': typeof LayoutDashboardSalesRoute
  '/inventory/goods-issue': typeof LayoutInventoryGoodsIssueRouteWithChildren
  '/inventory/goods-receipt': typeof LayoutInventoryGoodsReceiptRouteWithChildren
  '/inventory/item-master': typeof LayoutInventoryItemMasterRouteWithChildren
  '/inventory/transfer': typeof LayoutInventoryTransferRouteWithChildren
  '/inventory/transfer-request': typeof LayoutInventoryTransferRequestRouteWithChildren
  '/purchase/ap-credit-memo': typeof LayoutPurchaseApCreditMemoRouteWithChildren
  '/purchase/ap-invoice': typeof LayoutPurchaseApInvoiceRouteWithChildren
  '/purchase/create-ap-credit-memo': typeof LayoutPurchaseCreateApCreditMemoRoute
  '/purchase/create-ap-invoice': typeof LayoutPurchaseCreateApInvoiceRoute
  '/purchase/create-grpo': typeof LayoutPurchaseCreateGrpoRoute
  '/purchase/create-order': typeof LayoutPurchaseCreateOrderRoute
  '/purchase/create-outgoing-payment': typeof LayoutPurchaseCreateOutgoingPaymentRoute
  '/purchase/create-quotation': typeof LayoutPurchaseCreateQuotationRoute
  '/purchase/grpo': typeof LayoutPurchaseGrpoRouteWithChildren
  '/purchase/orders': typeof LayoutPurchaseOrdersRouteWithChildren
  '/purchase/outgoing-payment': typeof LayoutPurchaseOutgoingPaymentRouteWithChildren
  '/purchase/quotations': typeof LayoutPurchaseQuotationsRouteWithChildren
  '/sales/ar-credit-memo': typeof LayoutSalesArCreditMemoRouteWithChildren
  '/sales/ar-invoice': typeof LayoutSalesArInvoiceRouteWithChildren
  '/sales/create-ar-invoice': typeof LayoutSalesCreateArInvoiceRoute
  '/sales/create-incoming-payment': typeof LayoutSalesCreateIncomingPaymentRoute
  '/sales/create-order': typeof LayoutSalesCreateOrderRoute
  '/sales/create-quotation': typeof LayoutSalesCreateQuotationRoute
  '/sales/incoming-payment': typeof LayoutSalesIncomingPaymentRouteWithChildren
  '/sales/orders': typeof LayoutSalesOrdersRouteWithChildren
  '/sales/quotations': typeof LayoutSalesQuotationsRouteWithChildren
  '/inventory/goods-issue/create': typeof LayoutInventoryGoodsIssueCreateRoute
  '/inventory/goods-receipt/create': typeof LayoutInventoryGoodsReceiptCreateRoute
  '/inventory/item-master/create': typeof LayoutInventoryItemMasterCreateRoute
  '/inventory/transfer-request/create': typeof LayoutInventoryTransferRequestCreateRoute
  '/inventory/transfer/create': typeof LayoutInventoryTransferCreateRoute
  '/sales/ar-credit-memo/create': typeof LayoutSalesArCreditMemoCreateRoute
  '/sales/ar-credit-memo/select-invoice': typeof LayoutSalesArCreditMemoSelectInvoiceRoute
  '/inventory/goods-issue/$docNum/edit': typeof LayoutInventoryGoodsIssueDocNumEditRoute
  '/inventory/goods-receipt/$docNum/edit': typeof LayoutInventoryGoodsReceiptDocNumEditRoute
  '/purchase/ap-credit-memo/$docNum/edit': typeof LayoutPurchaseApCreditMemoDocNumEditRoute
  '/purchase/ap-invoice/$docNum/edit': typeof LayoutPurchaseApInvoiceDocNumEditRoute
  '/purchase/grpo/$docNum/edit': typeof LayoutPurchaseGrpoDocNumEditRoute
  '/purchase/orders/$docNum/edit': typeof LayoutPurchaseOrdersDocNumEditRoute
  '/purchase/outgoing-payment/$docNum/edit': typeof LayoutPurchaseOutgoingPaymentDocNumEditRoute
  '/purchase/quotations/$docNum/edit': typeof LayoutPurchaseQuotationsDocNumEditRoute
  '/sales/ar-credit-memo/$docNum/edit': typeof LayoutSalesArCreditMemoDocNumEditRoute
  '/sales/ar-invoice/$docNum/edit': typeof LayoutSalesArInvoiceDocNumEditRoute
  '/sales/incoming-payment/$docNum/edit': typeof LayoutSalesIncomingPaymentDocNumEditRoute
  '/sales/orders/$docNum/edit': typeof LayoutSalesOrdersDocNumEditRoute
  '/sales/quotations/$docNum/edit': typeof LayoutSalesQuotationsDocNumEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/dashboard/inventory': typeof LayoutDashboardInventoryRoute
  '/_layout/dashboard/purchase': typeof LayoutDashboardPurchaseRoute
  '/_layout/dashboard/sales': typeof LayoutDashboardSalesRoute
  '/_layout/inventory/goods-issue': typeof LayoutInventoryGoodsIssueRouteWithChildren
  '/_layout/inventory/goods-receipt': typeof LayoutInventoryGoodsReceiptRouteWithChildren
  '/_layout/inventory/item-master': typeof LayoutInventoryItemMasterRouteWithChildren
  '/_layout/inventory/transfer': typeof LayoutInventoryTransferRouteWithChildren
  '/_layout/inventory/transfer-request': typeof LayoutInventoryTransferRequestRouteWithChildren
  '/_layout/purchase/ap-credit-memo': typeof LayoutPurchaseApCreditMemoRouteWithChildren
  '/_layout/purchase/ap-invoice': typeof LayoutPurchaseApInvoiceRouteWithChildren
  '/_layout/purchase/create-ap-credit-memo': typeof LayoutPurchaseCreateApCreditMemoRoute
  '/_layout/purchase/create-ap-invoice': typeof LayoutPurchaseCreateApInvoiceRoute
  '/_layout/purchase/create-grpo': typeof LayoutPurchaseCreateGrpoRoute
  '/_layout/purchase/create-order': typeof LayoutPurchaseCreateOrderRoute
  '/_layout/purchase/create-outgoing-payment': typeof LayoutPurchaseCreateOutgoingPaymentRoute
  '/_layout/purchase/create-quotation': typeof LayoutPurchaseCreateQuotationRoute
  '/_layout/purchase/grpo': typeof LayoutPurchaseGrpoRouteWithChildren
  '/_layout/purchase/orders': typeof LayoutPurchaseOrdersRouteWithChildren
  '/_layout/purchase/outgoing-payment': typeof LayoutPurchaseOutgoingPaymentRouteWithChildren
  '/_layout/purchase/quotations': typeof LayoutPurchaseQuotationsRouteWithChildren
  '/_layout/sales/ar-credit-memo': typeof LayoutSalesArCreditMemoRouteWithChildren
  '/_layout/sales/ar-invoice': typeof LayoutSalesArInvoiceRouteWithChildren
  '/_layout/sales/create-ar-invoice': typeof LayoutSalesCreateArInvoiceRoute
  '/_layout/sales/create-incoming-payment': typeof LayoutSalesCreateIncomingPaymentRoute
  '/_layout/sales/create-order': typeof LayoutSalesCreateOrderRoute
  '/_layout/sales/create-quotation': typeof LayoutSalesCreateQuotationRoute
  '/_layout/sales/incoming-payment': typeof LayoutSalesIncomingPaymentRouteWithChildren
  '/_layout/sales/orders': typeof LayoutSalesOrdersRouteWithChildren
  '/_layout/sales/quotations': typeof LayoutSalesQuotationsRouteWithChildren
  '/_layout/inventory/goods-issue/create': typeof LayoutInventoryGoodsIssueCreateRoute
  '/_layout/inventory/goods-receipt/create': typeof LayoutInventoryGoodsReceiptCreateRoute
  '/_layout/inventory/item-master/create': typeof LayoutInventoryItemMasterCreateRoute
  '/_layout/inventory/transfer-request/create': typeof LayoutInventoryTransferRequestCreateRoute
  '/_layout/inventory/transfer/create': typeof LayoutInventoryTransferCreateRoute
  '/_layout/sales/ar-credit-memo/create': typeof LayoutSalesArCreditMemoCreateRoute
  '/_layout/sales/ar-credit-memo/select-invoice': typeof LayoutSalesArCreditMemoSelectInvoiceRoute
  '/_layout/inventory/goods-issue/$docNum/edit': typeof LayoutInventoryGoodsIssueDocNumEditRoute
  '/_layout/inventory/goods-receipt/$docNum/edit': typeof LayoutInventoryGoodsReceiptDocNumEditRoute
  '/_layout/purchase/ap-credit-memo/$docNum/edit': typeof LayoutPurchaseApCreditMemoDocNumEditRoute
  '/_layout/purchase/ap-invoice/$docNum/edit': typeof LayoutPurchaseApInvoiceDocNumEditRoute
  '/_layout/purchase/grpo/$docNum/edit': typeof LayoutPurchaseGrpoDocNumEditRoute
  '/_layout/purchase/orders/$docNum/edit': typeof LayoutPurchaseOrdersDocNumEditRoute
  '/_layout/purchase/outgoing-payment/$docNum/edit': typeof LayoutPurchaseOutgoingPaymentDocNumEditRoute
  '/_layout/purchase/quotations/$docNum/edit': typeof LayoutPurchaseQuotationsDocNumEditRoute
  '/_layout/sales/ar-credit-memo/$docNum/edit': typeof LayoutSalesArCreditMemoDocNumEditRoute
  '/_layout/sales/ar-invoice/$docNum/edit': typeof LayoutSalesArInvoiceDocNumEditRoute
  '/_layout/sales/incoming-payment/$docNum/edit': typeof LayoutSalesIncomingPaymentDocNumEditRoute
  '/_layout/sales/orders/$docNum/edit': typeof LayoutSalesOrdersDocNumEditRoute
  '/_layout/sales/quotations/$docNum/edit': typeof LayoutSalesQuotationsDocNumEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/inventory'
    | '/dashboard/purchase'
    | '/dashboard/sales'
    | '/inventory/goods-issue'
    | '/inventory/goods-receipt'
    | '/inventory/item-master'
    | '/inventory/transfer'
    | '/inventory/transfer-request'
    | '/purchase/ap-credit-memo'
    | '/purchase/ap-invoice'
    | '/purchase/create-ap-credit-memo'
    | '/purchase/create-ap-invoice'
    | '/purchase/create-grpo'
    | '/purchase/create-order'
    | '/purchase/create-outgoing-payment'
    | '/purchase/create-quotation'
    | '/purchase/grpo'
    | '/purchase/orders'
    | '/purchase/outgoing-payment'
    | '/purchase/quotations'
    | '/sales/ar-credit-memo'
    | '/sales/ar-invoice'
    | '/sales/create-ar-invoice'
    | '/sales/create-incoming-payment'
    | '/sales/create-order'
    | '/sales/create-quotation'
    | '/sales/incoming-payment'
    | '/sales/orders'
    | '/sales/quotations'
    | '/inventory/goods-issue/create'
    | '/inventory/goods-receipt/create'
    | '/inventory/item-master/create'
    | '/inventory/transfer-request/create'
    | '/inventory/transfer/create'
    | '/sales/ar-credit-memo/create'
    | '/sales/ar-credit-memo/select-invoice'
    | '/inventory/goods-issue/$docNum/edit'
    | '/inventory/goods-receipt/$docNum/edit'
    | '/purchase/ap-credit-memo/$docNum/edit'
    | '/purchase/ap-invoice/$docNum/edit'
    | '/purchase/grpo/$docNum/edit'
    | '/purchase/orders/$docNum/edit'
    | '/purchase/outgoing-payment/$docNum/edit'
    | '/purchase/quotations/$docNum/edit'
    | '/sales/ar-credit-memo/$docNum/edit'
    | '/sales/ar-invoice/$docNum/edit'
    | '/sales/incoming-payment/$docNum/edit'
    | '/sales/orders/$docNum/edit'
    | '/sales/quotations/$docNum/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/inventory'
    | '/dashboard/purchase'
    | '/dashboard/sales'
    | '/inventory/goods-issue'
    | '/inventory/goods-receipt'
    | '/inventory/item-master'
    | '/inventory/transfer'
    | '/inventory/transfer-request'
    | '/purchase/ap-credit-memo'
    | '/purchase/ap-invoice'
    | '/purchase/create-ap-credit-memo'
    | '/purchase/create-ap-invoice'
    | '/purchase/create-grpo'
    | '/purchase/create-order'
    | '/purchase/create-outgoing-payment'
    | '/purchase/create-quotation'
    | '/purchase/grpo'
    | '/purchase/orders'
    | '/purchase/outgoing-payment'
    | '/purchase/quotations'
    | '/sales/ar-credit-memo'
    | '/sales/ar-invoice'
    | '/sales/create-ar-invoice'
    | '/sales/create-incoming-payment'
    | '/sales/create-order'
    | '/sales/create-quotation'
    | '/sales/incoming-payment'
    | '/sales/orders'
    | '/sales/quotations'
    | '/inventory/goods-issue/create'
    | '/inventory/goods-receipt/create'
    | '/inventory/item-master/create'
    | '/inventory/transfer-request/create'
    | '/inventory/transfer/create'
    | '/sales/ar-credit-memo/create'
    | '/sales/ar-credit-memo/select-invoice'
    | '/inventory/goods-issue/$docNum/edit'
    | '/inventory/goods-receipt/$docNum/edit'
    | '/purchase/ap-credit-memo/$docNum/edit'
    | '/purchase/ap-invoice/$docNum/edit'
    | '/purchase/grpo/$docNum/edit'
    | '/purchase/orders/$docNum/edit'
    | '/purchase/outgoing-payment/$docNum/edit'
    | '/purchase/quotations/$docNum/edit'
    | '/sales/ar-credit-memo/$docNum/edit'
    | '/sales/ar-invoice/$docNum/edit'
    | '/sales/incoming-payment/$docNum/edit'
    | '/sales/orders/$docNum/edit'
    | '/sales/quotations/$docNum/edit'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/dashboard'
    | '/_layout/dashboard/inventory'
    | '/_layout/dashboard/purchase'
    | '/_layout/dashboard/sales'
    | '/_layout/inventory/goods-issue'
    | '/_layout/inventory/goods-receipt'
    | '/_layout/inventory/item-master'
    | '/_layout/inventory/transfer'
    | '/_layout/inventory/transfer-request'
    | '/_layout/purchase/ap-credit-memo'
    | '/_layout/purchase/ap-invoice'
    | '/_layout/purchase/create-ap-credit-memo'
    | '/_layout/purchase/create-ap-invoice'
    | '/_layout/purchase/create-grpo'
    | '/_layout/purchase/create-order'
    | '/_layout/purchase/create-outgoing-payment'
    | '/_layout/purchase/create-quotation'
    | '/_layout/purchase/grpo'
    | '/_layout/purchase/orders'
    | '/_layout/purchase/outgoing-payment'
    | '/_layout/purchase/quotations'
    | '/_layout/sales/ar-credit-memo'
    | '/_layout/sales/ar-invoice'
    | '/_layout/sales/create-ar-invoice'
    | '/_layout/sales/create-incoming-payment'
    | '/_layout/sales/create-order'
    | '/_layout/sales/create-quotation'
    | '/_layout/sales/incoming-payment'
    | '/_layout/sales/orders'
    | '/_layout/sales/quotations'
    | '/_layout/inventory/goods-issue/create'
    | '/_layout/inventory/goods-receipt/create'
    | '/_layout/inventory/item-master/create'
    | '/_layout/inventory/transfer-request/create'
    | '/_layout/inventory/transfer/create'
    | '/_layout/sales/ar-credit-memo/create'
    | '/_layout/sales/ar-credit-memo/select-invoice'
    | '/_layout/inventory/goods-issue/$docNum/edit'
    | '/_layout/inventory/goods-receipt/$docNum/edit'
    | '/_layout/purchase/ap-credit-memo/$docNum/edit'
    | '/_layout/purchase/ap-invoice/$docNum/edit'
    | '/_layout/purchase/grpo/$docNum/edit'
    | '/_layout/purchase/orders/$docNum/edit'
    | '/_layout/purchase/outgoing-payment/$docNum/edit'
    | '/_layout/purchase/quotations/$docNum/edit'
    | '/_layout/sales/ar-credit-memo/$docNum/edit'
    | '/_layout/sales/ar-invoice/$docNum/edit'
    | '/_layout/sales/incoming-payment/$docNum/edit'
    | '/_layout/sales/orders/$docNum/edit'
    | '/_layout/sales/quotations/$docNum/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/quotations': {
      id: '/_layout/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof LayoutSalesQuotationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/orders': {
      id: '/_layout/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof LayoutSalesOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/incoming-payment': {
      id: '/_layout/sales/incoming-payment'
      path: '/sales/incoming-payment'
      fullPath: '/sales/incoming-payment'
      preLoaderRoute: typeof LayoutSalesIncomingPaymentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/create-quotation': {
      id: '/_layout/sales/create-quotation'
      path: '/sales/create-quotation'
      fullPath: '/sales/create-quotation'
      preLoaderRoute: typeof LayoutSalesCreateQuotationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/create-order': {
      id: '/_layout/sales/create-order'
      path: '/sales/create-order'
      fullPath: '/sales/create-order'
      preLoaderRoute: typeof LayoutSalesCreateOrderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/create-incoming-payment': {
      id: '/_layout/sales/create-incoming-payment'
      path: '/sales/create-incoming-payment'
      fullPath: '/sales/create-incoming-payment'
      preLoaderRoute: typeof LayoutSalesCreateIncomingPaymentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/create-ar-invoice': {
      id: '/_layout/sales/create-ar-invoice'
      path: '/sales/create-ar-invoice'
      fullPath: '/sales/create-ar-invoice'
      preLoaderRoute: typeof LayoutSalesCreateArInvoiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/ar-invoice': {
      id: '/_layout/sales/ar-invoice'
      path: '/sales/ar-invoice'
      fullPath: '/sales/ar-invoice'
      preLoaderRoute: typeof LayoutSalesArInvoiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/ar-credit-memo': {
      id: '/_layout/sales/ar-credit-memo'
      path: '/sales/ar-credit-memo'
      fullPath: '/sales/ar-credit-memo'
      preLoaderRoute: typeof LayoutSalesArCreditMemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/quotations': {
      id: '/_layout/purchase/quotations'
      path: '/purchase/quotations'
      fullPath: '/purchase/quotations'
      preLoaderRoute: typeof LayoutPurchaseQuotationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/outgoing-payment': {
      id: '/_layout/purchase/outgoing-payment'
      path: '/purchase/outgoing-payment'
      fullPath: '/purchase/outgoing-payment'
      preLoaderRoute: typeof LayoutPurchaseOutgoingPaymentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/orders': {
      id: '/_layout/purchase/orders'
      path: '/purchase/orders'
      fullPath: '/purchase/orders'
      preLoaderRoute: typeof LayoutPurchaseOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/grpo': {
      id: '/_layout/purchase/grpo'
      path: '/purchase/grpo'
      fullPath: '/purchase/grpo'
      preLoaderRoute: typeof LayoutPurchaseGrpoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-quotation': {
      id: '/_layout/purchase/create-quotation'
      path: '/purchase/create-quotation'
      fullPath: '/purchase/create-quotation'
      preLoaderRoute: typeof LayoutPurchaseCreateQuotationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-outgoing-payment': {
      id: '/_layout/purchase/create-outgoing-payment'
      path: '/purchase/create-outgoing-payment'
      fullPath: '/purchase/create-outgoing-payment'
      preLoaderRoute: typeof LayoutPurchaseCreateOutgoingPaymentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-order': {
      id: '/_layout/purchase/create-order'
      path: '/purchase/create-order'
      fullPath: '/purchase/create-order'
      preLoaderRoute: typeof LayoutPurchaseCreateOrderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-grpo': {
      id: '/_layout/purchase/create-grpo'
      path: '/purchase/create-grpo'
      fullPath: '/purchase/create-grpo'
      preLoaderRoute: typeof LayoutPurchaseCreateGrpoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-ap-invoice': {
      id: '/_layout/purchase/create-ap-invoice'
      path: '/purchase/create-ap-invoice'
      fullPath: '/purchase/create-ap-invoice'
      preLoaderRoute: typeof LayoutPurchaseCreateApInvoiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/create-ap-credit-memo': {
      id: '/_layout/purchase/create-ap-credit-memo'
      path: '/purchase/create-ap-credit-memo'
      fullPath: '/purchase/create-ap-credit-memo'
      preLoaderRoute: typeof LayoutPurchaseCreateApCreditMemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/ap-invoice': {
      id: '/_layout/purchase/ap-invoice'
      path: '/purchase/ap-invoice'
      fullPath: '/purchase/ap-invoice'
      preLoaderRoute: typeof LayoutPurchaseApInvoiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase/ap-credit-memo': {
      id: '/_layout/purchase/ap-credit-memo'
      path: '/purchase/ap-credit-memo'
      fullPath: '/purchase/ap-credit-memo'
      preLoaderRoute: typeof LayoutPurchaseApCreditMemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/transfer-request': {
      id: '/_layout/inventory/transfer-request'
      path: '/inventory/transfer-request'
      fullPath: '/inventory/transfer-request'
      preLoaderRoute: typeof LayoutInventoryTransferRequestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/transfer': {
      id: '/_layout/inventory/transfer'
      path: '/inventory/transfer'
      fullPath: '/inventory/transfer'
      preLoaderRoute: typeof LayoutInventoryTransferRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/item-master': {
      id: '/_layout/inventory/item-master'
      path: '/inventory/item-master'
      fullPath: '/inventory/item-master'
      preLoaderRoute: typeof LayoutInventoryItemMasterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/goods-receipt': {
      id: '/_layout/inventory/goods-receipt'
      path: '/inventory/goods-receipt'
      fullPath: '/inventory/goods-receipt'
      preLoaderRoute: typeof LayoutInventoryGoodsReceiptRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inventory/goods-issue': {
      id: '/_layout/inventory/goods-issue'
      path: '/inventory/goods-issue'
      fullPath: '/inventory/goods-issue'
      preLoaderRoute: typeof LayoutInventoryGoodsIssueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/sales': {
      id: '/_layout/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof LayoutDashboardSalesRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/purchase': {
      id: '/_layout/dashboard/purchase'
      path: '/purchase'
      fullPath: '/dashboard/purchase'
      preLoaderRoute: typeof LayoutDashboardPurchaseRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/inventory': {
      id: '/_layout/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof LayoutDashboardInventoryRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/sales/ar-credit-memo/select-invoice': {
      id: '/_layout/sales/ar-credit-memo/select-invoice'
      path: '/select-invoice'
      fullPath: '/sales/ar-credit-memo/select-invoice'
      preLoaderRoute: typeof LayoutSalesArCreditMemoSelectInvoiceRouteImport
      parentRoute: typeof LayoutSalesArCreditMemoRoute
    }
    '/_layout/sales/ar-credit-memo/create': {
      id: '/_layout/sales/ar-credit-memo/create'
      path: '/create'
      fullPath: '/sales/ar-credit-memo/create'
      preLoaderRoute: typeof LayoutSalesArCreditMemoCreateRouteImport
      parentRoute: typeof LayoutSalesArCreditMemoRoute
    }
    '/_layout/inventory/transfer/create': {
      id: '/_layout/inventory/transfer/create'
      path: '/create'
      fullPath: '/inventory/transfer/create'
      preLoaderRoute: typeof LayoutInventoryTransferCreateRouteImport
      parentRoute: typeof LayoutInventoryTransferRoute
    }
    '/_layout/inventory/transfer-request/create': {
      id: '/_layout/inventory/transfer-request/create'
      path: '/create'
      fullPath: '/inventory/transfer-request/create'
      preLoaderRoute: typeof LayoutInventoryTransferRequestCreateRouteImport
      parentRoute: typeof LayoutInventoryTransferRequestRoute
    }
    '/_layout/inventory/item-master/create': {
      id: '/_layout/inventory/item-master/create'
      path: '/create'
      fullPath: '/inventory/item-master/create'
      preLoaderRoute: typeof LayoutInventoryItemMasterCreateRouteImport
      parentRoute: typeof LayoutInventoryItemMasterRoute
    }
    '/_layout/inventory/goods-receipt/create': {
      id: '/_layout/inventory/goods-receipt/create'
      path: '/create'
      fullPath: '/inventory/goods-receipt/create'
      preLoaderRoute: typeof LayoutInventoryGoodsReceiptCreateRouteImport
      parentRoute: typeof LayoutInventoryGoodsReceiptRoute
    }
    '/_layout/inventory/goods-issue/create': {
      id: '/_layout/inventory/goods-issue/create'
      path: '/create'
      fullPath: '/inventory/goods-issue/create'
      preLoaderRoute: typeof LayoutInventoryGoodsIssueCreateRouteImport
      parentRoute: typeof LayoutInventoryGoodsIssueRoute
    }
    '/_layout/sales/quotations/$docNum/edit': {
      id: '/_layout/sales/quotations/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/sales/quotations/$docNum/edit'
      preLoaderRoute: typeof LayoutSalesQuotationsDocNumEditRouteImport
      parentRoute: typeof LayoutSalesQuotationsRoute
    }
    '/_layout/sales/orders/$docNum/edit': {
      id: '/_layout/sales/orders/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/sales/orders/$docNum/edit'
      preLoaderRoute: typeof LayoutSalesOrdersDocNumEditRouteImport
      parentRoute: typeof LayoutSalesOrdersRoute
    }
    '/_layout/sales/incoming-payment/$docNum/edit': {
      id: '/_layout/sales/incoming-payment/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/sales/incoming-payment/$docNum/edit'
      preLoaderRoute: typeof LayoutSalesIncomingPaymentDocNumEditRouteImport
      parentRoute: typeof LayoutSalesIncomingPaymentRoute
    }
    '/_layout/sales/ar-invoice/$docNum/edit': {
      id: '/_layout/sales/ar-invoice/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/sales/ar-invoice/$docNum/edit'
      preLoaderRoute: typeof LayoutSalesArInvoiceDocNumEditRouteImport
      parentRoute: typeof LayoutSalesArInvoiceRoute
    }
    '/_layout/sales/ar-credit-memo/$docNum/edit': {
      id: '/_layout/sales/ar-credit-memo/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/sales/ar-credit-memo/$docNum/edit'
      preLoaderRoute: typeof LayoutSalesArCreditMemoDocNumEditRouteImport
      parentRoute: typeof LayoutSalesArCreditMemoRoute
    }
    '/_layout/purchase/quotations/$docNum/edit': {
      id: '/_layout/purchase/quotations/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/purchase/quotations/$docNum/edit'
      preLoaderRoute: typeof LayoutPurchaseQuotationsDocNumEditRouteImport
      parentRoute: typeof LayoutPurchaseQuotationsRoute
    }
    '/_layout/purchase/outgoing-payment/$docNum/edit': {
      id: '/_layout/purchase/outgoing-payment/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/purchase/outgoing-payment/$docNum/edit'
      preLoaderRoute: typeof LayoutPurchaseOutgoingPaymentDocNumEditRouteImport
      parentRoute: typeof LayoutPurchaseOutgoingPaymentRoute
    }
    '/_layout/purchase/orders/$docNum/edit': {
      id: '/_layout/purchase/orders/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/purchase/orders/$docNum/edit'
      preLoaderRoute: typeof LayoutPurchaseOrdersDocNumEditRouteImport
      parentRoute: typeof LayoutPurchaseOrdersRoute
    }
    '/_layout/purchase/grpo/$docNum/edit': {
      id: '/_layout/purchase/grpo/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/purchase/grpo/$docNum/edit'
      preLoaderRoute: typeof LayoutPurchaseGrpoDocNumEditRouteImport
      parentRoute: typeof LayoutPurchaseGrpoRoute
    }
    '/_layout/purchase/ap-invoice/$docNum/edit': {
      id: '/_layout/purchase/ap-invoice/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/purchase/ap-invoice/$docNum/edit'
      preLoaderRoute: typeof LayoutPurchaseApInvoiceDocNumEditRouteImport
      parentRoute: typeof LayoutPurchaseApInvoiceRoute
    }
    '/_layout/purchase/ap-credit-memo/$docNum/edit': {
      id: '/_layout/purchase/ap-credit-memo/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/purchase/ap-credit-memo/$docNum/edit'
      preLoaderRoute: typeof LayoutPurchaseApCreditMemoDocNumEditRouteImport
      parentRoute: typeof LayoutPurchaseApCreditMemoRoute
    }
    '/_layout/inventory/goods-receipt/$docNum/edit': {
      id: '/_layout/inventory/goods-receipt/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/inventory/goods-receipt/$docNum/edit'
      preLoaderRoute: typeof LayoutInventoryGoodsReceiptDocNumEditRouteImport
      parentRoute: typeof LayoutInventoryGoodsReceiptRoute
    }
    '/_layout/inventory/goods-issue/$docNum/edit': {
      id: '/_layout/inventory/goods-issue/$docNum/edit'
      path: '/$docNum/edit'
      fullPath: '/inventory/goods-issue/$docNum/edit'
      preLoaderRoute: typeof LayoutInventoryGoodsIssueDocNumEditRouteImport
      parentRoute: typeof LayoutInventoryGoodsIssueRoute
    }
  }
}

interface LayoutDashboardRouteChildren {
  LayoutDashboardInventoryRoute: typeof LayoutDashboardInventoryRoute
  LayoutDashboardPurchaseRoute: typeof LayoutDashboardPurchaseRoute
  LayoutDashboardSalesRoute: typeof LayoutDashboardSalesRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardInventoryRoute: LayoutDashboardInventoryRoute,
  LayoutDashboardPurchaseRoute: LayoutDashboardPurchaseRoute,
  LayoutDashboardSalesRoute: LayoutDashboardSalesRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutInventoryGoodsIssueRouteChildren {
  LayoutInventoryGoodsIssueCreateRoute: typeof LayoutInventoryGoodsIssueCreateRoute
  LayoutInventoryGoodsIssueDocNumEditRoute: typeof LayoutInventoryGoodsIssueDocNumEditRoute
}

const LayoutInventoryGoodsIssueRouteChildren: LayoutInventoryGoodsIssueRouteChildren =
  {
    LayoutInventoryGoodsIssueCreateRoute: LayoutInventoryGoodsIssueCreateRoute,
    LayoutInventoryGoodsIssueDocNumEditRoute:
      LayoutInventoryGoodsIssueDocNumEditRoute,
  }

const LayoutInventoryGoodsIssueRouteWithChildren =
  LayoutInventoryGoodsIssueRoute._addFileChildren(
    LayoutInventoryGoodsIssueRouteChildren,
  )

interface LayoutInventoryGoodsReceiptRouteChildren {
  LayoutInventoryGoodsReceiptCreateRoute: typeof LayoutInventoryGoodsReceiptCreateRoute
  LayoutInventoryGoodsReceiptDocNumEditRoute: typeof LayoutInventoryGoodsReceiptDocNumEditRoute
}

const LayoutInventoryGoodsReceiptRouteChildren: LayoutInventoryGoodsReceiptRouteChildren =
  {
    LayoutInventoryGoodsReceiptCreateRoute:
      LayoutInventoryGoodsReceiptCreateRoute,
    LayoutInventoryGoodsReceiptDocNumEditRoute:
      LayoutInventoryGoodsReceiptDocNumEditRoute,
  }

const LayoutInventoryGoodsReceiptRouteWithChildren =
  LayoutInventoryGoodsReceiptRoute._addFileChildren(
    LayoutInventoryGoodsReceiptRouteChildren,
  )

interface LayoutInventoryItemMasterRouteChildren {
  LayoutInventoryItemMasterCreateRoute: typeof LayoutInventoryItemMasterCreateRoute
}

const LayoutInventoryItemMasterRouteChildren: LayoutInventoryItemMasterRouteChildren =
  {
    LayoutInventoryItemMasterCreateRoute: LayoutInventoryItemMasterCreateRoute,
  }

const LayoutInventoryItemMasterRouteWithChildren =
  LayoutInventoryItemMasterRoute._addFileChildren(
    LayoutInventoryItemMasterRouteChildren,
  )

interface LayoutInventoryTransferRouteChildren {
  LayoutInventoryTransferCreateRoute: typeof LayoutInventoryTransferCreateRoute
}

const LayoutInventoryTransferRouteChildren: LayoutInventoryTransferRouteChildren =
  {
    LayoutInventoryTransferCreateRoute: LayoutInventoryTransferCreateRoute,
  }

const LayoutInventoryTransferRouteWithChildren =
  LayoutInventoryTransferRoute._addFileChildren(
    LayoutInventoryTransferRouteChildren,
  )

interface LayoutInventoryTransferRequestRouteChildren {
  LayoutInventoryTransferRequestCreateRoute: typeof LayoutInventoryTransferRequestCreateRoute
}

const LayoutInventoryTransferRequestRouteChildren: LayoutInventoryTransferRequestRouteChildren =
  {
    LayoutInventoryTransferRequestCreateRoute:
      LayoutInventoryTransferRequestCreateRoute,
  }

const LayoutInventoryTransferRequestRouteWithChildren =
  LayoutInventoryTransferRequestRoute._addFileChildren(
    LayoutInventoryTransferRequestRouteChildren,
  )

interface LayoutPurchaseApCreditMemoRouteChildren {
  LayoutPurchaseApCreditMemoDocNumEditRoute: typeof LayoutPurchaseApCreditMemoDocNumEditRoute
}

const LayoutPurchaseApCreditMemoRouteChildren: LayoutPurchaseApCreditMemoRouteChildren =
  {
    LayoutPurchaseApCreditMemoDocNumEditRoute:
      LayoutPurchaseApCreditMemoDocNumEditRoute,
  }

const LayoutPurchaseApCreditMemoRouteWithChildren =
  LayoutPurchaseApCreditMemoRoute._addFileChildren(
    LayoutPurchaseApCreditMemoRouteChildren,
  )

interface LayoutPurchaseApInvoiceRouteChildren {
  LayoutPurchaseApInvoiceDocNumEditRoute: typeof LayoutPurchaseApInvoiceDocNumEditRoute
}

const LayoutPurchaseApInvoiceRouteChildren: LayoutPurchaseApInvoiceRouteChildren =
  {
    LayoutPurchaseApInvoiceDocNumEditRoute:
      LayoutPurchaseApInvoiceDocNumEditRoute,
  }

const LayoutPurchaseApInvoiceRouteWithChildren =
  LayoutPurchaseApInvoiceRoute._addFileChildren(
    LayoutPurchaseApInvoiceRouteChildren,
  )

interface LayoutPurchaseGrpoRouteChildren {
  LayoutPurchaseGrpoDocNumEditRoute: typeof LayoutPurchaseGrpoDocNumEditRoute
}

const LayoutPurchaseGrpoRouteChildren: LayoutPurchaseGrpoRouteChildren = {
  LayoutPurchaseGrpoDocNumEditRoute: LayoutPurchaseGrpoDocNumEditRoute,
}

const LayoutPurchaseGrpoRouteWithChildren =
  LayoutPurchaseGrpoRoute._addFileChildren(LayoutPurchaseGrpoRouteChildren)

interface LayoutPurchaseOrdersRouteChildren {
  LayoutPurchaseOrdersDocNumEditRoute: typeof LayoutPurchaseOrdersDocNumEditRoute
}

const LayoutPurchaseOrdersRouteChildren: LayoutPurchaseOrdersRouteChildren = {
  LayoutPurchaseOrdersDocNumEditRoute: LayoutPurchaseOrdersDocNumEditRoute,
}

const LayoutPurchaseOrdersRouteWithChildren =
  LayoutPurchaseOrdersRoute._addFileChildren(LayoutPurchaseOrdersRouteChildren)

interface LayoutPurchaseOutgoingPaymentRouteChildren {
  LayoutPurchaseOutgoingPaymentDocNumEditRoute: typeof LayoutPurchaseOutgoingPaymentDocNumEditRoute
}

const LayoutPurchaseOutgoingPaymentRouteChildren: LayoutPurchaseOutgoingPaymentRouteChildren =
  {
    LayoutPurchaseOutgoingPaymentDocNumEditRoute:
      LayoutPurchaseOutgoingPaymentDocNumEditRoute,
  }

const LayoutPurchaseOutgoingPaymentRouteWithChildren =
  LayoutPurchaseOutgoingPaymentRoute._addFileChildren(
    LayoutPurchaseOutgoingPaymentRouteChildren,
  )

interface LayoutPurchaseQuotationsRouteChildren {
  LayoutPurchaseQuotationsDocNumEditRoute: typeof LayoutPurchaseQuotationsDocNumEditRoute
}

const LayoutPurchaseQuotationsRouteChildren: LayoutPurchaseQuotationsRouteChildren =
  {
    LayoutPurchaseQuotationsDocNumEditRoute:
      LayoutPurchaseQuotationsDocNumEditRoute,
  }

const LayoutPurchaseQuotationsRouteWithChildren =
  LayoutPurchaseQuotationsRoute._addFileChildren(
    LayoutPurchaseQuotationsRouteChildren,
  )

interface LayoutSalesArCreditMemoRouteChildren {
  LayoutSalesArCreditMemoCreateRoute: typeof LayoutSalesArCreditMemoCreateRoute
  LayoutSalesArCreditMemoSelectInvoiceRoute: typeof LayoutSalesArCreditMemoSelectInvoiceRoute
  LayoutSalesArCreditMemoDocNumEditRoute: typeof LayoutSalesArCreditMemoDocNumEditRoute
}

const LayoutSalesArCreditMemoRouteChildren: LayoutSalesArCreditMemoRouteChildren =
  {
    LayoutSalesArCreditMemoCreateRoute: LayoutSalesArCreditMemoCreateRoute,
    LayoutSalesArCreditMemoSelectInvoiceRoute:
      LayoutSalesArCreditMemoSelectInvoiceRoute,
    LayoutSalesArCreditMemoDocNumEditRoute:
      LayoutSalesArCreditMemoDocNumEditRoute,
  }

const LayoutSalesArCreditMemoRouteWithChildren =
  LayoutSalesArCreditMemoRoute._addFileChildren(
    LayoutSalesArCreditMemoRouteChildren,
  )

interface LayoutSalesArInvoiceRouteChildren {
  LayoutSalesArInvoiceDocNumEditRoute: typeof LayoutSalesArInvoiceDocNumEditRoute
}

const LayoutSalesArInvoiceRouteChildren: LayoutSalesArInvoiceRouteChildren = {
  LayoutSalesArInvoiceDocNumEditRoute: LayoutSalesArInvoiceDocNumEditRoute,
}

const LayoutSalesArInvoiceRouteWithChildren =
  LayoutSalesArInvoiceRoute._addFileChildren(LayoutSalesArInvoiceRouteChildren)

interface LayoutSalesIncomingPaymentRouteChildren {
  LayoutSalesIncomingPaymentDocNumEditRoute: typeof LayoutSalesIncomingPaymentDocNumEditRoute
}

const LayoutSalesIncomingPaymentRouteChildren: LayoutSalesIncomingPaymentRouteChildren =
  {
    LayoutSalesIncomingPaymentDocNumEditRoute:
      LayoutSalesIncomingPaymentDocNumEditRoute,
  }

const LayoutSalesIncomingPaymentRouteWithChildren =
  LayoutSalesIncomingPaymentRoute._addFileChildren(
    LayoutSalesIncomingPaymentRouteChildren,
  )

interface LayoutSalesOrdersRouteChildren {
  LayoutSalesOrdersDocNumEditRoute: typeof LayoutSalesOrdersDocNumEditRoute
}

const LayoutSalesOrdersRouteChildren: LayoutSalesOrdersRouteChildren = {
  LayoutSalesOrdersDocNumEditRoute: LayoutSalesOrdersDocNumEditRoute,
}

const LayoutSalesOrdersRouteWithChildren =
  LayoutSalesOrdersRoute._addFileChildren(LayoutSalesOrdersRouteChildren)

interface LayoutSalesQuotationsRouteChildren {
  LayoutSalesQuotationsDocNumEditRoute: typeof LayoutSalesQuotationsDocNumEditRoute
}

const LayoutSalesQuotationsRouteChildren: LayoutSalesQuotationsRouteChildren = {
  LayoutSalesQuotationsDocNumEditRoute: LayoutSalesQuotationsDocNumEditRoute,
}

const LayoutSalesQuotationsRouteWithChildren =
  LayoutSalesQuotationsRoute._addFileChildren(
    LayoutSalesQuotationsRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutInventoryGoodsIssueRoute: typeof LayoutInventoryGoodsIssueRouteWithChildren
  LayoutInventoryGoodsReceiptRoute: typeof LayoutInventoryGoodsReceiptRouteWithChildren
  LayoutInventoryItemMasterRoute: typeof LayoutInventoryItemMasterRouteWithChildren
  LayoutInventoryTransferRoute: typeof LayoutInventoryTransferRouteWithChildren
  LayoutInventoryTransferRequestRoute: typeof LayoutInventoryTransferRequestRouteWithChildren
  LayoutPurchaseApCreditMemoRoute: typeof LayoutPurchaseApCreditMemoRouteWithChildren
  LayoutPurchaseApInvoiceRoute: typeof LayoutPurchaseApInvoiceRouteWithChildren
  LayoutPurchaseCreateApCreditMemoRoute: typeof LayoutPurchaseCreateApCreditMemoRoute
  LayoutPurchaseCreateApInvoiceRoute: typeof LayoutPurchaseCreateApInvoiceRoute
  LayoutPurchaseCreateGrpoRoute: typeof LayoutPurchaseCreateGrpoRoute
  LayoutPurchaseCreateOrderRoute: typeof LayoutPurchaseCreateOrderRoute
  LayoutPurchaseCreateOutgoingPaymentRoute: typeof LayoutPurchaseCreateOutgoingPaymentRoute
  LayoutPurchaseCreateQuotationRoute: typeof LayoutPurchaseCreateQuotationRoute
  LayoutPurchaseGrpoRoute: typeof LayoutPurchaseGrpoRouteWithChildren
  LayoutPurchaseOrdersRoute: typeof LayoutPurchaseOrdersRouteWithChildren
  LayoutPurchaseOutgoingPaymentRoute: typeof LayoutPurchaseOutgoingPaymentRouteWithChildren
  LayoutPurchaseQuotationsRoute: typeof LayoutPurchaseQuotationsRouteWithChildren
  LayoutSalesArCreditMemoRoute: typeof LayoutSalesArCreditMemoRouteWithChildren
  LayoutSalesArInvoiceRoute: typeof LayoutSalesArInvoiceRouteWithChildren
  LayoutSalesCreateArInvoiceRoute: typeof LayoutSalesCreateArInvoiceRoute
  LayoutSalesCreateIncomingPaymentRoute: typeof LayoutSalesCreateIncomingPaymentRoute
  LayoutSalesCreateOrderRoute: typeof LayoutSalesCreateOrderRoute
  LayoutSalesCreateQuotationRoute: typeof LayoutSalesCreateQuotationRoute
  LayoutSalesIncomingPaymentRoute: typeof LayoutSalesIncomingPaymentRouteWithChildren
  LayoutSalesOrdersRoute: typeof LayoutSalesOrdersRouteWithChildren
  LayoutSalesQuotationsRoute: typeof LayoutSalesQuotationsRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutInventoryGoodsIssueRoute: LayoutInventoryGoodsIssueRouteWithChildren,
  LayoutInventoryGoodsReceiptRoute:
    LayoutInventoryGoodsReceiptRouteWithChildren,
  LayoutInventoryItemMasterRoute: LayoutInventoryItemMasterRouteWithChildren,
  LayoutInventoryTransferRoute: LayoutInventoryTransferRouteWithChildren,
  LayoutInventoryTransferRequestRoute:
    LayoutInventoryTransferRequestRouteWithChildren,
  LayoutPurchaseApCreditMemoRoute: LayoutPurchaseApCreditMemoRouteWithChildren,
  LayoutPurchaseApInvoiceRoute: LayoutPurchaseApInvoiceRouteWithChildren,
  LayoutPurchaseCreateApCreditMemoRoute: LayoutPurchaseCreateApCreditMemoRoute,
  LayoutPurchaseCreateApInvoiceRoute: LayoutPurchaseCreateApInvoiceRoute,
  LayoutPurchaseCreateGrpoRoute: LayoutPurchaseCreateGrpoRoute,
  LayoutPurchaseCreateOrderRoute: LayoutPurchaseCreateOrderRoute,
  LayoutPurchaseCreateOutgoingPaymentRoute:
    LayoutPurchaseCreateOutgoingPaymentRoute,
  LayoutPurchaseCreateQuotationRoute: LayoutPurchaseCreateQuotationRoute,
  LayoutPurchaseGrpoRoute: LayoutPurchaseGrpoRouteWithChildren,
  LayoutPurchaseOrdersRoute: LayoutPurchaseOrdersRouteWithChildren,
  LayoutPurchaseOutgoingPaymentRoute:
    LayoutPurchaseOutgoingPaymentRouteWithChildren,
  LayoutPurchaseQuotationsRoute: LayoutPurchaseQuotationsRouteWithChildren,
  LayoutSalesArCreditMemoRoute: LayoutSalesArCreditMemoRouteWithChildren,
  LayoutSalesArInvoiceRoute: LayoutSalesArInvoiceRouteWithChildren,
  LayoutSalesCreateArInvoiceRoute: LayoutSalesCreateArInvoiceRoute,
  LayoutSalesCreateIncomingPaymentRoute: LayoutSalesCreateIncomingPaymentRoute,
  LayoutSalesCreateOrderRoute: LayoutSalesCreateOrderRoute,
  LayoutSalesCreateQuotationRoute: LayoutSalesCreateQuotationRoute,
  LayoutSalesIncomingPaymentRoute: LayoutSalesIncomingPaymentRouteWithChildren,
  LayoutSalesOrdersRoute: LayoutSalesOrdersRouteWithChildren,
  LayoutSalesQuotationsRoute: LayoutSalesQuotationsRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
