import { useQuery, useQueryClient } from "@tanstack/react-query";
import { goeyToast } from "goey-toast";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import {
  createSharedKeys,
  createSharedQueries,
} from "@/features/create-pages/create-shared/api/create-shared.queries";
import type {
  LookupItem,
  ProductLookupItem,
} from "@/features/create-pages/create-shared/api/create-shared.types";
import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import type {
  ActiveDatePicker,
  PopupMode,
  ProductRowDraft,
  StockPreviewProduct,
} from "@/features/create-pages/create-shared/utils/create-order.types";
import { normalizeCreateOrderErrorMessage } from "@/features/create-pages/create-shared/utils/create-order.utils";
import { documentActionToast } from "@/features/create-pages/create-shared/utils/document-action-toast";
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from "@/features/create-pages/create-shared/utils/lookup-search-sync";
import { pageLoadingToast } from "@/features/create-pages/create-shared/utils/page-loading-toast";
import { resolveProductTaxRates } from "@/features/create-pages/create-shared/utils/product-tax-rate";
import { resolveDocumentLineDiscount } from "@/features/create-pages/create-shared/utils/resolve-document-line-discount";
import {
  useCreateGRPO,
  useUpdateGRPO,
} from "@/features/create-pages/grpo-create/api/grpo-create.mutations";
import { useGrpoLookups } from "@/features/create-pages/grpo-create/hooks/use-grpo-lookups";
import {
  filterAndRankLookups,
  getTodayISO,
  GRPO_FIELD_ERROR_TEXT,
  GRPO_FIELD_LABEL_TEXT,
  GRPO_MANDATORY_FIELDS,
} from "@/features/create-pages/grpo-create/utils/grpo-create.utils";
import type { GRPOMandatoryField } from "@/features/create-pages/grpo-create/utils/grpo-create.utils";
import { grpoQueries } from "@/features/table-pages/grpo/api/grpo.queries";
import {
  purchaseOrderKeys,
  purchaseOrderQueries,
} from "@/features/table-pages/purchase-orders/api/purchase-order.queries";
import {
  purchaseQuotationKeys,
  purchaseQuotationQueries,
} from "@/features/table-pages/purchase-quotations/api/purchase-quotation.queries";
import {
  useGRPOHeader,
  useGRPOLines,
  useResetGRPOCreateAction,
  useSetGRPOHeaderAction,
  useSetGRPOLinesAction,
} from "@/store/create/grpo-create.store";
import type { GRPOLineItemState } from "@/store/create/grpo-create.store";

import {
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from "../../create-shared/utils/auto-reference";

export interface GRPOCreateLine {
  id: string;
  productCode: string;
  productName: string;
  stock: number;
  currency: string;
  vatGroup: string;
  taxRate: number;
  uomCode?: string | undefined;
  uomEntry?: number | undefined;
  baseQuantity?: number | undefined;
  quantity: number;
  discountPercent: number;
  discountAmount: number;
  comment: string;
  price: number;
  warehouseCode: string;
  baseLine?: number | undefined;
  baseEntry?: number | undefined;
  baseType?: number | undefined;
}
type GRPOFieldErrors = Record<GRPOMandatoryField, string | undefined>;
const QUICK_PRODUCT_LIMIT = 10;
const FULL_PRODUCT_LIMIT = 100;

const EMPTY_GRPO_FIELD_ERRORS: GRPOFieldErrors = {
  vendorCode: undefined,
  vendorName: undefined,
  warehouseCode: undefined,
};

interface UseGRPOCreateOptions {
  mode?: "create" | "edit";
  docNum?: string;
  sourceDocNum?: string | undefined;
  sourceDocType?: "PurchaseOrder" | "PurchaseQuotation" | undefined;
  onCreateSuccess?: () => void;
}

export type UseGRPOCreateReturn = ReturnType<typeof useGRPOCreate>;

const normalizeCodeForCompare = (value: unknown) => {
  const raw = String(value ?? "").trim();
  if (!raw) {
    return "";
  }
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
};

export function useGRPOCreate({
  mode = "create",
  docNum,
  sourceDocNum,
  sourceDocType,
  onCreateSuccess,
}: UseGRPOCreateOptions) {
  const parseGRPOHeaderNotes = (detail: { Comments?: unknown; NumAtCard?: unknown }) => {
    const referenceNo = String(detail.NumAtCard ?? "").trim();
    const rawComments = String(detail.Comments ?? "").trim();

    if (referenceNo) {
      const legacyReferencePrefix = `${referenceNo} | `;
      return {
        comments: rawComments.startsWith(legacyReferencePrefix)
          ? rawComments.slice(legacyReferencePrefix.length).trim()
          : rawComments,
        referenceNo,
      };
    }

    const splitComments = rawComments.split(" | ").map((part) => part.trim());
    if (splitComments.length > 1) {
      return {
        comments: splitComments.slice(1).join(" | "),
        referenceNo: splitComments[0] ?? "",
      };
    }

    return {
      comments: rawComments,
      referenceNo,
    };
  };
  const isEditMode = mode === "edit";
  const editDocNum = (docNum ?? "").trim();
  const queryClient = useQueryClient();
  const header = useGRPOHeader();
  const setHeader = useSetGRPOHeaderAction();
  const rows = useGRPOLines();
  const setLines = useSetGRPOLinesAction();
  const resetGRPOCreate = useResetGRPOCreateAction();
  const createMutation = useCreateGRPO();
  const updateMutation = useUpdateGRPO();
  const hydratedDocNumRef = useRef<string | null>(null);
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null);
  const [sourceHydrationComplete, setSourceHydrationComplete] = useState(false);
  const lastRestrictedToastAtRef = useRef(0);
  const loadingToastRef = useRef<ReturnType<typeof pageLoadingToast> | null>(null);

  const [vendorNameInput, setVendorNameInput] = useState("");
  const [vendorCodeInput, setVendorCodeInput] = useState("");
  const [vendorNameFocused, setVendorNameFocused] = useState(false);
  const [vendorCodeFocused, setVendorCodeFocused] = useState(false);
  const [buyerInput, setBuyerInput] = useState("");
  const [buyerFocused, setBuyerFocused] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<PopupMode>("vendor-name");
  const [modalSearch, setModalSearch] = useState("");
  const [productPopupOpen, setProductPopupOpen] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [debouncedProductSearch, setDebouncedProductSearch] = useState("");
  const [productQueryLimit, setProductQueryLimit] = useState(QUICK_PRODUCT_LIMIT);
  const [activeProductRowId, setActiveProductRowId] = useState<string | null>(null);
  const [warehouseInput, setWarehouseInput] = useState("");
  const [warehouseFocused, setWarehouseFocused] = useState(false);

  const [billToAddress, setBillToAddressRaw] = useState("");
  const [shipToAddress, setShipToAddressRaw] = useState("");

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value));
  }, []);
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value));
  }, []);

  const [productRowDrafts, setProductRowDrafts] = useState<Record<string, ProductRowDraft>>({});
  const [stockPreviewProduct, setStockPreviewProduct] = useState<StockPreviewProduct | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<GRPOFieldErrors>(EMPTY_GRPO_FIELD_ERRORS);
  const [headerDiscountPercent, setHeaderDiscountPercent] = useState(0);

  /* ---------- vendor-change confirmation (copy-from guard) ---------- */
  const [pendingVendorChange, setPendingVendorChange] = useState<{
    vendor: LookupItem;
  } | null>(null);
  const hasCopiedRows = useMemo(
    () => rows.some((r) => r.baseEntry != null && r.baseType != null),
    [rows],
  );

  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);
  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null);
  const docDateContainerRef = useRef<HTMLDivElement>(null);
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null);

  const notifyRestricted = (fieldName: string) => {
    const now = Date.now();
    if (now - lastRestrictedToastAtRef.current < 2500) {
      return;
    }
    lastRestrictedToastAtRef.current = now;
    goeyToast.error(`${fieldName} is locked for edit`, {
      id: "restricted-edit-toast",
    });
  };

  const vendorsQuery = useQuery(createSharedQueries.vendors());
  const warehousesQuery = useQuery(createSharedQueries.warehouses());
  const salesEmployeesQuery = useQuery(createSharedQueries.salesEmployees());
  const financialPeriodQuery = useQuery(createSharedQueries.financialPeriod());
  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data]);
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data]);
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data]);
  const effectiveWarehouseCode = useMemo(() => {
    const normalized = warehouseInput.trim().toLowerCase();
    const matched = warehouses.find(
      (item) => item.name.toLowerCase() === normalized || item.code.toLowerCase() === normalized,
    );
    return matched?.code ?? warehouseInput.trim();
  }, [warehouseInput, warehouses]);

  const vendorSelected = Boolean(vendorCodeInput) || Boolean(vendorNameInput);
  const vendorLookupToken = `${vendorCodeInput.trim().toLowerCase()}::${vendorNameInput.trim().toLowerCase()}`;

  const productsQuery = useQuery({
    ...createSharedQueries.products(
      effectiveWarehouseCode || undefined,
      debouncedProductSearch.trim() || undefined,
      debouncedProductSearch.trim() ? undefined : productQueryLimit,
      "purchase",
    ),
    enabled: productPopupOpen && vendorSelected,
  });

  useEffect(() => {
    if (!productPopupOpen || !vendorSelected) {
      return;
    }
    void queryClient.invalidateQueries({
      queryKey: createSharedKeys.products(),
    });
  }, [productPopupOpen, queryClient, vendorLookupToken, vendorSelected]);
  const products = useMemo(
    () => filterAndRankLookups(productsQuery.data ?? [], debouncedProductSearch),
    [productsQuery.data, debouncedProductSearch],
  );

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDebouncedProductSearch(productSearch.trim());
    }, 180);
    return () => window.clearTimeout(timer);
  }, [productSearch]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setProductQueryLimit(QUICK_PRODUCT_LIMIT);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [debouncedProductSearch, vendorSelected, productPopupOpen]);

  const productWarehouseStocksQuery = useQuery({
    ...createSharedQueries.productWarehouseStocks(stockPreviewProduct?.code),
    enabled: Boolean(stockPreviewProduct?.code),
  });

  const editDetailQuery = useQuery({
    ...grpoQueries.detailByDocNum(editDocNum),
    enabled: isEditMode && Boolean(editDocNum),
  });

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === "Closed" ||
    editDetailQuery.data?.data?.DocStatus === "bost_Close" ||
    editDetailQuery.data?.data?.DocStatus === "C";
  const docStatus =
    editDetailQuery.data?.data?.DocStatus === "O" ||
    editDetailQuery.data?.data?.DocStatus === "bost_Open"
      ? "Open"
      : editDetailQuery.data?.data?.DocStatus === "C" ||
          editDetailQuery.data?.data?.DocStatus === "bost_Close"
        ? "Closed"
        : (editDetailQuery.data?.data?.DocStatus ?? "Open");

  useEffect(() => {
    if (isEditMode) {
      return;
    }
    resetGRPOCreate();
    hydratedDocNumRef.current = null;
  }, [isEditMode, resetGRPOCreate]);

  useEffect(() => {
    if (!isEditMode) {
      return;
    }
    const currentDocNum = editDocNum;
    if (!currentDocNum) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    if (hydratedDocNumRef.current === currentDocNum && isMetadataLoaded) {
      return;
    }

    // Show loading toast when starting edit hydration
    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast("GRPO", "edit");
    }
    void (async () => {
      try {
        setVendorCodeInput(String(detail.CardCode ?? "").trim());
        setVendorNameInput(String(detail.CardName ?? "").trim());
        const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
        const { comments: remarks, referenceNo } = parseGRPOHeaderNotes(detail);

        const matchedVendor = vendors.find(
          (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
        );
        const buyerFromDocCode =
          detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(detail.SalesPersonCode),
              )?.name
            : "";
        const buyerFromVendorCode =
          matchedVendor?.salesEmployeeCode !== undefined && matchedVendor.salesEmployeeCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(matchedVendor.salesEmployeeCode),
              )?.name
            : "";

        setBuyerInput(
          buyerFromDocCode || buyerFromVendorCode || matchedVendor?.salesEmployeeName?.trim() || "",
        );
        const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);

        setHeader({
          docDate: loadedDocDate,
          docDueDate,
          referenceNo,
          remarks,
        });
        // Set addresses from document: Address = Bill To, Address2 = Ship To
        const billAddr = String(detail.Address ?? "").trim();
        const shipAddr = String((detail as Record<string, unknown>).Address2 ?? "").trim();
        setBillToAddress(billAddr);
        setShipToAddress(shipAddr);
        const detailLines = detail.DocumentLines ?? [];
        const stockByItemCode = new Map<string, { code: string; stock: number }[]>();
        const uniqueItemCodes = [
          ...new Set(detailLines.map((line) => String(line.ItemCode ?? "").trim())),
        ].filter(Boolean);

        await Promise.all(
          uniqueItemCodes.map(async (itemCode) => {
            const warehouseStocks = await queryClient
              .fetchQuery(createSharedQueries.productWarehouseStocks(itemCode))
              .catch(() => []);
            stockByItemCode.set(
              itemCode,
              warehouseStocks.map((stock) => ({
                code: String(stock.code ?? "").trim(),
                stock: Number(stock.stock ?? 0),
              })),
            );
          }),
        );

        const taxRateByItemCode = await resolveProductTaxRates(
          queryClient,
          detailLines.map((line) => String(line.ItemCode ?? "").trim()),
          "purchase",
        );
        const resolvedHeaderDiscountPercent = Number(
          (detail as Record<string, unknown>).DiscountPercent ?? 0,
        );
        setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

        const mappedLines = (detail.DocumentLines ?? []).map((line, index) => {
          const quantity = Math.max(0, Number(line.Quantity ?? 0));
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const itemCode = String(line.ItemCode ?? "").trim();
          const lineWarehouseCode = String(line.WarehouseCode ?? "").trim();
          const warehouseStocks = stockByItemCode.get(itemCode) ?? [];
          const lineStock = lineWarehouseCode
            ? Number(warehouseStocks.find((stock) => stock.code === lineWarehouseCode)?.stock ?? 0)
            : warehouseStocks.reduce((sum, stock) => sum + Number(stock.stock ?? 0), 0);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line: line as unknown as Record<string, unknown>,
          });

          return {
            id: `${currentDocNum}-${index}`,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? line.ItemCode ?? "").trim(),
            stock: lineStock,
            currency: "",
            vatGroup: String(line.VatGroup ?? line.TaxCode ?? "").trim(),
            // SAP line tax is authoritative; fall back to product master only when missing
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? "").trim(),
            uomEntry:
              typeof line.UoMEntry === "number" && Number.isFinite(line.UoMEntry)
                ? line.UoMEntry
                : undefined,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: lineWarehouseCode,
            baseEntry:
              typeof line.BaseEntry === "number" && Number.isFinite(line.BaseEntry)
                ? line.BaseEntry
                : undefined,
            baseLine:
              typeof line.BaseLine === "number" && Number.isFinite(line.BaseLine)
                ? line.BaseLine
                : undefined,
            baseType:
              typeof line.BaseType === "number" && Number.isFinite(line.BaseType)
                ? line.BaseType
                : undefined,
            selected: false,
          };
        });
        setLines(mappedLines);
        setWarehouseInput(String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim());
        // Set addresses from document: Address = Bill To, Address2 = Ship To
        setBillToAddress(String(detail.Address ?? "").trim());
        setShipToAddress(String((detail as Record<string, unknown>).Address2 ?? "").trim());

        if (isMetadataLoaded) {
          hydratedDocNumRef.current = currentDocNum;
        }
        setHydratedDocNum(currentDocNum);
      } finally {
        // Dismiss loading toast when edit hydration is complete (success or error)
        loadingToastRef.current?.dismiss();
        loadingToastRef.current = null;
      }
    })();
  }, [
    editDocNum,
    editDetailQuery.data,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
  ]);

  useEffect(() => {
    if (mode !== "create") {
      return;
    }
    const currentSourceDocNum = sourceDocNum;
    const currentSourceDocType = sourceDocType;
    if (!currentSourceDocNum || !currentSourceDocType) {
      return;
    }

    // Parse comma-separated source docNums for multi-doc copy
    const sourceDocNums = currentSourceDocNum
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (sourceDocNums.length === 0) {
      return;
    }

    // Reset source hydration state when source changes
    setSourceHydrationComplete(false);
    hydratedDocNumRef.current = null;

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    const hydrKey = `${currentSourceDocType}-${currentSourceDocNum}`;
    if (hydratedDocNumRef.current === hydrKey && isMetadataLoaded) {
      return;
    }

    // Show loading toast when starting copy-from hydration
    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast("GRPO", "create");
    }

    // Fetch all source documents in parallel
    const fetchAllSources = async () => {
      const details = await Promise.all(
        sourceDocNums.map(async (num) => {
          if (currentSourceDocType === "PurchaseQuotation") {
            const res = await queryClient.fetchQuery(purchaseQuotationQueries.detailByDocNum(num));
            return res.data;
          }
          const res = await queryClient.fetchQuery(purchaseOrderQueries.detailByDocNum(num));
          return res.data;
        }),
      );

      // Use first source for header fields (vendor, buyer, addresses)
      const primaryDetail = details[0]!;
      const vendorCode = String(primaryDetail.CardCode ?? "").trim();
      const vendorName = String(primaryDetail.CardName ?? "").trim();
      const matchedVendor = vendors.find((v) => String(v.code).trim() === vendorCode);

      const buyerFromDocCode =
        primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(primaryDetail.SalesPersonCode),
            )?.name
          : "";
      const buyerFromVendorCode =
        matchedVendor?.salesEmployeeCode !== undefined && matchedVendor.salesEmployeeCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(matchedVendor.salesEmployeeCode),
            )?.name
          : "";
      const buyerName =
        buyerFromDocCode || buyerFromVendorCode || matchedVendor?.salesEmployeeName?.trim() || "";

      const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
      const sourceComments = String(primaryDetail.Comments ?? "").trim();

      // Build multi-source reference — put into remarks, not referenceNo
      const refs = sourceDocNums.map((num) =>
        generateSingleSourceReference(currentSourceDocType, num),
      );
      const autoReference = refs.length === 1 ? refs[0]! : refs.join("\n");

      // Extract existing "Based on" chain from source comments
      const commentLines = sourceComments
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean);
      const refLinesFromComments = commentLines.filter((line) => /^based on /i.test(line));

      // Build remarks: existing ref chain + new auto-ref + user remarks from source
      const userRemarks = commentLines
        .filter((line) => !/^based on /i.test(line))
        .join("\n")
        .trim();
      const remarksParts = [refLinesFromComments.join("\n"), autoReference, userRemarks]
        .filter(Boolean)
        .join("\n")
        .trim();

      const referenceWasAutoFilled = true;
      const docDueDate = String(primaryDetail.DocDueDate ?? "").slice(0, 10);

      // Merge all lines from all source documents
      const allDetailLines = details.flatMap((detail) => detail.DocumentLines ?? []);
      const uniqueItemCodes = [
        ...new Set(allDetailLines.map((line) => String(line.ItemCode ?? "").trim())),
      ].filter(Boolean);

      const stockByItemCode = new Map<string, { code: string; stock: number }[]>();
      await Promise.all(
        uniqueItemCodes.map(async (itemCode) => {
          const warehouseStocks = (await queryClient
            .fetchQuery(createSharedQueries.productWarehouseStocks(itemCode))
            .catch(() => [])) as { code: string; stock: number }[];
          stockByItemCode.set(
            itemCode,
            warehouseStocks.map((stock) => ({
              code: String(stock.code ?? "").trim(),
              stock: Number(stock.stock ?? 0),
            })),
          );
        }),
      );

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        allDetailLines.map((line) => String(line.ItemCode ?? "").trim()),
        "purchase",
      );
      const resolvedHeaderDiscountPercent = Number(
        (primaryDetail as Record<string, unknown>).DiscountPercent ?? 0,
      );
      setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

      let lineIndex = 0;
      const baseType = currentSourceDocType === "PurchaseQuotation" ? 540000006 : 22;
      const mappedLines = details.flatMap((detail, docIdx) => {
        const detailLines = detail.DocumentLines ?? [];
        return detailLines.map((line) => {
          const idx = lineIndex++;
          const itemCode = String(line.ItemCode ?? "").trim();
          const lineWarehouseCode = String(line.WarehouseCode ?? "").trim();
          const warehouseStocks = stockByItemCode.get(itemCode) ?? [];
          const lineStock = lineWarehouseCode
            ? Number(warehouseStocks.find((s) => s.code === lineWarehouseCode)?.stock ?? 0)
            : warehouseStocks.reduce((sum, s) => sum + Number(s.stock ?? 0), 0);

          const lineData = line as Record<string, unknown>;
          // For Purchase Quotation sources (baseType 540000006), the user-entered
          // quantity lives in PQT1.PQTReqQty (Service Layer: RequiredQuantity),
          // while PQT1.Quantity stays 0. Prefer RequiredQuantity as a fallback
          // so the copied-to GRPO receives the same quantity the user requested.
          const openQty = Number(
            lineData.OpenQty ??
              lineData.OpenQuantity ??
              lineData.RequiredQuantity ??
              lineData.requiredQuantity ??
              line.Quantity ??
              1,
          );
          const quantity = openQty;
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line: line as unknown as Record<string, unknown>,
          });

          return {
            id: `row-copy-${sourceDocNums[docIdx] ?? "unknown"}-${idx}`,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? line.ItemCode ?? "").trim(),
            stock: lineStock,
            currency: "",
            vatGroup: String(line.VatGroup ?? line.TaxCode ?? "").trim(),
            // SAP line tax is authoritative; fall back to product master only when missing
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? "").trim(),
            uomEntry:
              typeof line.UoMEntry === "number" && Number.isFinite(line.UoMEntry)
                ? line.UoMEntry
                : undefined,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: lineWarehouseCode,
            baseEntry: detail.DocEntry ?? detail.id,
            baseLine: line.LineNum ?? idx,
            baseType,
            selected: false,
          };
        });
      });

      const sourceNumAtCard = String(
        (primaryDetail as { NumAtCard?: string }).NumAtCard ?? "",
      ).trim();
      setVendorCodeInput(vendorCode);
      setVendorNameInput(vendorName);
      setBuyerInput(buyerName);
      setWarehouseInput(warehouseCode);
      setBillToAddress(
        String(primaryDetail.Address ?? "").trim() || matchedVendor?.billToAddress || "",
      );
      setShipToAddress(
        String((primaryDetail as Record<string, unknown>).Address2 ?? "").trim() ||
          matchedVendor?.shipToAddress ||
          matchedVendor?.billToAddress ||
          "",
      );
      setHeader({
        docDate: getTodayISO(),
        docDueDate,
        referenceAutoFilled: referenceWasAutoFilled,
        referenceNo: sourceNumAtCard,
        remarks: remarksParts,
      });
      setLines(mappedLines);
      if (isMetadataLoaded) {
        hydratedDocNumRef.current = hydrKey;
      }
      setSourceHydrationComplete(true);
      loadingToastRef.current?.dismiss();
      loadingToastRef.current = null;
    };

    void fetchAllSources();
  }, [
    mode,
    sourceDocNum,
    sourceDocType,
    vendors,
    salesEmployees,
    queryClient,
    setVendorCodeInput,
    setVendorNameInput,
    setBuyerInput,
    setWarehouseInput,
    setBillToAddress,
    setShipToAddress,
    setHeader,
    setLines,
  ]);

  const { vendorNameSuggestions, vendorCodeSuggestions, warehouseSuggestions, buyerSuggestions } =
    useGrpoLookups({
      buyerInput,
      buyers: salesEmployees,
      vendorCodeInput,
      vendorNameInput,
      vendors,
      warehouseInput,
      warehouses,
    });

  const popupResults = useMemo(() => {
    const term = modalSearch.trim().toLowerCase();
    const source = (
      modalMode === "vendor-name" || modalMode === "vendor-code"
        ? vendors
        : modalMode === "warehouse"
          ? warehouses
          : salesEmployees
    ) as ProductLookupItem[];
    if (!term) {
      return source;
    }
    const score = (item: ProductLookupItem) => {
      const code = (item.code || "").toLowerCase();
      const name = (item.name || "").toLowerCase();
      if (code === term || name === term) {
        return 0;
      }
      if (code.startsWith(term) || name.startsWith(term)) {
        return 1;
      }
      if (code.includes(term) || name.includes(term)) {
        return 2;
      }
      return 3;
    };
    return [...source].toSorted((a, b) => {
      const byScore = score(a) - score(b);
      if (byScore !== 0) {
        return byScore;
      }
      return a.code.localeCompare(b.code, undefined, {
        numeric: true,
        sensitivity: "base",
      });
    });
  }, [vendors, warehouses, salesEmployees, modalSearch, modalMode]);

  const openPopupByMode = (mode: PopupMode) => {
    const searchVal =
      mode === "vendor-name" || mode === "vendor-code"
        ? mode === "vendor-name"
          ? vendorNameInput
          : vendorCodeInput
        : mode === "warehouse"
          ? warehouseInput
          : buyerInput;

    setModalMode(mode);
    setModalSearch(searchVal);
    setModalOpen(true);
  };

  useEffect(() => {
    if (!modalOpen) {
      return;
    }
    const nextSearch = getLookupInlineSearchByMode(modalMode, {
      salesEmployee: buyerInput,
      vendorCode: vendorCodeInput,
      vendorName: vendorNameInput,
      warehouse: warehouseInput,
    });
    if (nextSearch !== modalSearch) {
      setModalSearch(nextSearch);
    }
  }, [
    buyerInput,
    modalMode,
    modalOpen,
    modalSearch,
    setModalSearch,
    vendorCodeInput,
    vendorNameInput,
    warehouseInput,
  ]);

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onSalesEmployee: handleBuyerChange,
      onVendorCode: handleVendorCodeChange,
      onVendorName: handleVendorNameChange,
      onWarehouse: handleWarehouseInputChange,
    });

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (!activeDatePicker) {
        return;
      }
      const target = event.target as Node;
      const insideDoc = docDateContainerRef.current?.contains(target);
      const insideDelivery = deliveryDateContainerRef.current?.contains(target);
      if (!insideDoc && !insideDelivery) {
        setActiveDatePicker(null);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [activeDatePicker]);

  const handleDocDueDateChange = (value: string) => {
    setHeader({ docDueDate: value });
    setFieldErrors((prev) => ({ ...prev, docDueDate: undefined }));
  };

  const handleDocDateChange = (value: string) => {
    setHeader({ docDate: value });
  };

  const filteredRows = useMemo(() => rows.filter((row) => row.quantity > 0), [rows]);

  const warehouseErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!submitAttempted) return errors;

    filteredRows.forEach((row) => {
      if (!row.warehouseCode.trim()) {
        errors[row.id] = "Warehouse is required.";
      }
    });
    return errors;
  }, [submitAttempted, filteredRows]);

  const selectVendor = (vendor: LookupItem) => {
    // If document has copied rows, confirm before breaking the link
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor });
      return;
    }
    applyVendorChange(vendor);
  };

  const applyVendorChange = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? vendor.billToAddress ?? "");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
    const buyerByCode =
      vendor.salesEmployeeCode !== undefined && vendor.salesEmployeeCode !== null
        ? salesEmployees.find(
            (item) =>
              normalizeCodeForCompare(item.code) ===
              normalizeCodeForCompare(vendor.salesEmployeeCode),
          )?.name
        : "";
    setBuyerInput(buyerByCode || vendor.salesEmployeeName?.trim() || "");
    setWarehouseInput("");
    setLines([]);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      billToAddress: undefined,
      salesEmployee: undefined,
      shipToAddress: undefined,
      vendorCode: undefined,
      vendorName: undefined,
    }));
  };

  const handleVendorNameChange = (value: string) => {
    setVendorNameInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined }));
    if (value.trim() === "") {
      setVendorNameFocused(true);
      setVendorCodeInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matchedByName = vendors.find(
      (item) => item.name.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matchedByName) {
      setVendorCodeInput(matchedByName.code);
      setBillToAddress(matchedByName.billToAddress ?? "");
      setShipToAddress(matchedByName.shipToAddress ?? matchedByName.billToAddress ?? "");
      const buyerByCode =
        matchedByName.salesEmployeeCode !== undefined && matchedByName.salesEmployeeCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(matchedByName.salesEmployeeCode),
            )?.name
          : "";
      setBuyerInput(buyerByCode || matchedByName.salesEmployeeName?.trim() || "");
      setVendorNameFocused(false);
      return;
    }
    // Typing a non-matching name — if copied rows exist, guard
    if (hasCopiedRows) {
      return;
    }
    setVendorCodeInput("");
    setBuyerInput("");
    setWarehouseInput("");
    setLines([]);
    setVendorNameFocused(true);
  };

  const handleVendorCodeChange = (value: string) => {
    setVendorCodeInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorCode: undefined }));
    if (value.trim() === "") {
      setVendorCodeFocused(true);
      setVendorNameInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matchedByCode = vendors.find(
      (item) => item.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matchedByCode) {
      // Switching to a different matched vendor with copied rows — confirm
      if (hasCopiedRows) {
        setPendingVendorChange({ vendor: matchedByCode });
        return;
      }
      setVendorNameInput(matchedByCode.name);
      setBillToAddress(matchedByCode.billToAddress ?? "");
      setShipToAddress(matchedByCode.shipToAddress ?? matchedByCode.billToAddress ?? "");
      const buyerByCode =
        matchedByCode.salesEmployeeCode !== undefined && matchedByCode.salesEmployeeCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(matchedByCode.salesEmployeeCode),
            )?.name
          : "";
      setBuyerInput(buyerByCode || matchedByCode.salesEmployeeName?.trim() || "");
      setVendorCodeFocused(false);
      return;
    }
    // Typing a non-matching code — if copied rows exist, guard
    if (hasCopiedRows) {
      return;
    }
    setVendorNameInput("");
    setBuyerInput("");
    setWarehouseInput("");
    setLines([]);
    setVendorCodeFocused(true);
  };

  /* ---------- vendor-change confirmation handlers ---------- */
  const confirmVendorChange = () => {
    const pending = pendingVendorChange;
    if (!pending) {
      return;
    }
    setPendingVendorChange(null);

    // Strip only auto-generated "Based on..." references from remarks, keep user remarks
    const cleanedRemarks = stripAutoGeneratedReferences(header.remarks);
    setHeader({ remarks: cleanedRemarks });

    // Clear base linkage from all rows (break copy-from link) but keep row data
    setLines((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row;
        return rest;
      }),
    );

    // Apply the new vendor (without clearing lines/warehouse)
    applyVendorChangeForConfirmation(pending.vendor);
  };

  const cancelVendorChange = () => {
    setPendingVendorChange(null);
  };

  /** Apply vendor without clearing lines/warehouse — used only during vendor-change confirmation. */
  const applyVendorChangeForConfirmation = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? vendor.billToAddress ?? "");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
    const buyerByCode =
      vendor.salesEmployeeCode !== undefined && vendor.salesEmployeeCode !== null
        ? salesEmployees.find(
            (item) =>
              normalizeCodeForCompare(item.code) ===
              normalizeCodeForCompare(vendor.salesEmployeeCode),
          )?.name
        : "";
    setBuyerInput(buyerByCode || vendor.salesEmployeeName?.trim() || "");
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      billToAddress: undefined,
      salesEmployee: undefined,
      shipToAddress: undefined,
      vendorCode: undefined,
      vendorName: undefined,
    }));
  };

  const handleWarehouseInputChange = (value: string) => {
    setWarehouseInput(value);
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }));
  };

  const handleBuyerChange = (value: string) => {
    setBuyerInput(value);
    setFieldErrors((prev) => ({ ...prev, salesEmployee: undefined }));
    if (!value.trim()) {
      setBuyerFocused(true);
      return;
    }
    const byName = salesEmployees.find(
      (item) => item.name.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    const byCode = salesEmployees.find(
      (item) => normalizeCodeForCompare(item.code) === normalizeCodeForCompare(value),
    );
    const matched = byName ?? byCode;
    if (matched) {
      selectBuyer(matched);
      return;
    }
    setBuyerFocused(true);
  };

  const prefetchProducts = () => {
    if (!effectiveWarehouseCode) {
      return;
    }
    void queryClient.prefetchQuery(
      createSharedQueries.products(
        effectiveWarehouseCode || undefined,
        productSearch.trim() || undefined,
        QUICK_PRODUCT_LIMIT,
        "purchase",
      ),
    );
  };

  const openProductPopup = (rowId: string | null = null) => {
    setActiveProductRowId(rowId);
    if (!vendorNameInput.trim() || !vendorCodeInput.trim() || !buyerInput.trim()) {
      const nextErrors = { ...EMPTY_GRPO_FIELD_ERRORS };
      if (!vendorNameInput.trim()) {
        nextErrors.vendorName = GRPO_FIELD_ERROR_TEXT.vendorName;
      }
      if (!vendorCodeInput.trim()) {
        nextErrors.vendorCode = GRPO_FIELD_ERROR_TEXT.vendorCode;
      }
      setFieldErrors(nextErrors);
      return;
    }

    setProductQueryLimit(QUICK_PRODUCT_LIMIT);
    setProductPopupOpen(true);
  };

  const loadMoreProducts = () => {
    if (!productPopupOpen) {
      return;
    }
    if (productsQuery.isFetching) {
      return;
    }
    const currentCount = productsQuery.data?.length ?? 0;
    if (currentCount < productQueryLimit) {
      return;
    }
    const isSearchMode = debouncedProductSearch.trim().length > 0;
    if (!isSearchMode && productQueryLimit >= FULL_PRODUCT_LIMIT) {
      return;
    }
    setProductQueryLimit((prev) => Math.min(prev + 10, FULL_PRODUCT_LIMIT));
  };

  const selectBuyer = (item: LookupItem) => {
    setBuyerInput(item.name);
    setBuyerFocused(false);
    setFieldErrors((prev) => ({ ...prev, salesEmployee: undefined }));
  };

  const selectWarehouse = (warehouse: LookupItem) => {
    setWarehouseInput(warehouse.name);
    setProductQueryLimit(QUICK_PRODUCT_LIMIT);
    void queryClient.prefetchQuery(
      createSharedQueries.products(
        warehouse.code || undefined,
        undefined,
        QUICK_PRODUCT_LIMIT,
        "purchase",
      ),
    );
    setLines((prev) =>
      prev.map((row) => ({
        ...row,
        warehouseCode: warehouse.code,
      })),
    );
    setWarehouseFocused(false);
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }));
  };

  const applyProductToRow = (product: ProductLookupItem) => {
    setLines((prev) => {
      if (activeProductRowId) {
        // Updating an existing row: leave the user-chosen warehouse untouched.
        return prev.map((row) =>
          row.id === activeProductRowId
            ? {
                ...row,
                baseEntry: undefined,
                baseLine: undefined,
                baseType: undefined,
                comment: "",
                currency: String(product.currency ?? ""),
                discountAmount: 0,
                discountPercent: 0,
                price: Number(product.price ?? 0),
                productCode: product.code,
                productName: product.name,
                quantity: 1,
                stock: Number(product.stock ?? 0),
                taxRate: Number(product.taxRate ?? 0),
                uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
                uomEntry: product.purchaseUomEntry ?? product.uomEntry,
                vatGroup: String(product.vatGroup ?? ""),
              }
            : row,
        );
      }
      // New row: force user to pick a warehouse explicitly.
      return [
        ...prev,
        {
          baseEntry: undefined,
          baseLine: undefined,
          baseType: undefined,
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: Number(product.stock ?? 0),
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: "",
        },
      ];
    });
    setProductPopupOpen(false);
    setProductSearch("");
    setActiveProductRowId(null);
  };

  const applyProductsToRows = (products: ProductLookupItem[]) => {
    setLines((prev) => {
      const nextRows = products.map((product) => ({
        baseEntry: undefined,
        baseLine: undefined,
        baseType: undefined,
        comment: "",
        currency: String(product.currency ?? ""),
        discountAmount: 0,
        discountPercent: 0,
        id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        price: Number(product.price ?? 0),
        productCode: product.code,
        productName: product.name,
        quantity: 1,
        selected: false,
        stock: Number(product.stock ?? 0),
        taxRate: Number(product.taxRate ?? 0),
        uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
        uomEntry: product.purchaseUomEntry ?? product.uomEntry,
        vatGroup: String(product.vatGroup ?? ""),
        warehouseCode: "",
      }));
      return [...prev, ...nextRows];
    });
    setProductPopupOpen(false);
    setProductSearch("");
    setActiveProductRowId(null);
  };

  const handleReferenceNoChange = (value: string) => {
    setHeader({ referenceNo: value });
    setFieldErrors((prev) => ({ ...prev, referenceNo: undefined }));
  };

  const handleRemarksChange = (value: string) => {
    setHeader({ remarks: value });
    setFieldErrors((prev) => ({ ...prev, comments: undefined }));
  };

  const handleBillToAddressChange = (value: string) => {
    setBillToAddress(value);
    setFieldErrors((prev) => ({ ...prev, billToAddress: undefined }));
  };

  const handleShipToAddressChange = (value: string) => {
    setShipToAddress(value);
    setFieldErrors((prev) => ({ ...prev, shipToAddress: undefined }));
  };

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) {
      return [];
    }
    const requiredFields = GRPO_MANDATORY_FIELDS;

    return requiredFields.filter((field) => {
      if (field === "vendorName") {
        return !vendorNameInput.trim();
      }
      if (field === "vendorCode") {
        return !vendorCodeInput.trim();
      }
      if (field === "warehouseCode") {
        // Check if ANY row has a warehouseCode selected
        return !rows.some((row) => row.warehouseCode?.trim());
      }
      return false;
    });
  }, [isEditMode, vendorNameInput, vendorCodeInput, rows]);

  const searchMandatoryFields = useMemo(() => ["vendorName", "vendorCode"] as const, []);
  const missingSearchMandatoryFields = useMemo(
    () =>
      searchMandatoryFields.filter((field) => {
        if (field === "vendorName") {
          return !vendorNameInput.trim();
        }
        if (field === "vendorCode") {
          return !vendorCodeInput.trim();
        }
        return false;
      }),
    [searchMandatoryFields, vendorNameInput, vendorCodeInput],
  );
  const searchRequiredCompletionPercent = useMemo(() => {
    const completed = searchMandatoryFields.length - missingSearchMandatoryFields.length;
    return (completed / searchMandatoryFields.length) * 100;
  }, [searchMandatoryFields.length, missingSearchMandatoryFields.length]);

  const requiredCompletionPercent = useMemo(() => {
    const requiredFields = GRPO_MANDATORY_FIELDS;
    const completed = requiredFields.length - missingMandatoryFields.length;
    return (completed / requiredFields.length) * 100;
  }, [missingMandatoryFields.length]);

  const requiredFieldsTotal = GRPO_MANDATORY_FIELDS.length;
  const isEditHydrated = !isEditMode || !editDocNum || hydratedDocNum === editDocNum;
  const isSourceHydrating = mode === "create" && Boolean(sourceDocNum) && !sourceHydrationComplete;

  const createDisabledReason = useMemo(() => {
    if (missingMandatoryFields.length > 0) {
      return `Complete required fields: ${missingMandatoryFields.map((field) => GRPO_FIELD_LABEL_TEXT[field]).join(", ")}.`;
    }
    if (!rows.some((row) => row.quantity > 0)) {
      return "Set at least one product quantity greater than 0.";
    }
    return null;
  }, [missingMandatoryFields, rows]);

  const updateProductRow = (id: string, patch: Partial<GRPOCreateLine>) => {
    setLines((prev) =>
      prev.map((row) => {
        if (row.id !== id) {
          return row;
        }
        const next: GRPOLineItemState = { ...row, ...patch };
        next.quantity = Math.max(0, Number(next.quantity) || 0);
        return next;
      }),
    );
  };

  const removeProductRow = (id: string) => {
    setLines((prev) => prev.filter((row) => row.id !== id));
    setProductRowDrafts((prev) => {
      if (!prev[id]) {
        return prev;
      }
      const next = { ...prev };
      delete next[id];
      return next;
    });
  };

  const setProductRowDraft = (id: string, field: keyof ProductRowDraft, value: string) => {
    setProductRowDrafts((prev) => ({
      ...prev,
      [id]: {
        ...prev[id],
        [field]: value,
      },
    }));
  };

  const clearProductRowDraft = (id: string, field: keyof ProductRowDraft) => {
    setProductRowDrafts((prev) => {
      const rowDraft = prev[id];
      if (!rowDraft || rowDraft[field] === undefined) {
        return prev;
      }
      const nextRowDraft = { ...rowDraft };
      delete nextRowDraft[field];
      if (Object.keys(nextRowDraft).length === 0) {
        const next = { ...prev };
        delete next[id];
        return next;
      }
      return { ...prev, [id]: nextRowDraft };
    });
  };

  const openStockPreview = (product: StockPreviewProduct) => {
    setStockPreviewProduct(product);
  };

  const resolvedSalesEmployeeCode = useMemo(() => {
    const byName = salesEmployees.find(
      (item) => item.name.trim().toLowerCase() === buyerInput.trim().toLowerCase(),
    );
    if (byName) {
      return Number(normalizeCodeForCompare(byName.code));
    }

    const byCode = salesEmployees.find(
      (item) => normalizeCodeForCompare(item.code) === normalizeCodeForCompare(buyerInput),
    );
    if (byCode) {
      return Number(normalizeCodeForCompare(byCode.code));
    }

    return;
  }, [buyerInput, salesEmployees]);

  const handleCreateGRPO = async () => {
    setSubmitAttempted(true);
    if (!isEditMode && missingMandatoryFields.length > 0) {
      const nextErrors = { ...EMPTY_GRPO_FIELD_ERRORS };
      missingMandatoryFields.forEach((field) => {
        nextErrors[field] = GRPO_FIELD_ERROR_TEXT[field];
      });
      setFieldErrors(nextErrors);
      setCreateError("Fill required fields before creating GRPO.");
      return;
    }

    if (filteredRows.length === 0) {
      setCreateError("Set at least one line quantity greater than 0.");
      return;
    }

    // Validate warehouse is selected for all lines
    const linesMissingWarehouse = filteredRows.filter((row) => !row.warehouseCode.trim());
    if (linesMissingWarehouse.length > 0) {
      return;
    }

    // Validate dates against active financial period
    if (financialPeriodQuery.data) {
      const fRefDateStr = financialPeriodQuery.data.F_RefDate
        ? String(financialPeriodQuery.data.F_RefDate).slice(0, 10)
        : "";
      const tRefDateStr = financialPeriodQuery.data.T_RefDate
        ? String(financialPeriodQuery.data.T_RefDate).slice(0, 10)
        : "";

      if (fRefDateStr && tRefDateStr) {
        const docDateVal = String(header.docDate ?? "").slice(0, 10);
        if (docDateVal && (docDateVal < fRefDateStr || docDateVal > tRefDateStr)) {
          const errorMsg = `Document Date (${docDateVal}) deviates from permissible range. Must fall within active period ${fRefDateStr} to ${tRefDateStr}.`;
          setCreateError(errorMsg);
          goeyToast.error(errorMsg, { id: "date-range-error-toast" });
          return;
        }

        const docDueDateVal = String(header.docDueDate ?? "").slice(0, 10);
        if (docDueDateVal && (docDueDateVal < fRefDateStr || docDueDateVal > tRefDateStr)) {
          const errorMsg = `Due Date (${docDueDateVal}) deviates from permissible range. Must fall within active period ${fRefDateStr} to ${tRefDateStr}.`;
          setCreateError(errorMsg);
          goeyToast.error(errorMsg, { id: "due-date-range-error-toast" });
          return;
        }
      }
    }

    if (isEditMode) {
      const detail = editDetailQuery.data?.data;
      const existingDocDueDate = String(detail?.DocDueDate ?? "")
        .slice(0, 10)
        .trim();
      const currentDocDueDate = String(header.docDueDate ?? "").trim();
      const currentReferenceNo = String(header.referenceNo ?? "").trim();
      const { comments: existingComments, referenceNo: existingReferenceNo } = detail
        ? parseGRPOHeaderNotes(detail)
        : { comments: "", referenceNo: "" };
      const currentComments = String(header.remarks ?? "").trim();

      if (
        currentDocDueDate === existingDocDueDate &&
        currentReferenceNo === existingReferenceNo &&
        currentComments === existingComments.trim()
      ) {
        const noChangeMessage = "Change at least one field before update.";
        setCreateError(noChangeMessage);
        goeyToast.error(noChangeMessage, { id: "no-change-update-toast" });
        return;
      }
    }

    setCreateError(null);
    const payload = isEditMode
      ? {
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          Comments: header.remarks.trim() || undefined,
          DocDueDate: header.docDueDate || undefined,
          NumAtCard: header.referenceNo.trim() || undefined,
        }
      : {
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          CardCode: vendorCodeInput.trim(),
          Comments: header.remarks.trim() || undefined,
          DocDate: header.docDate || undefined,
          DocDueDate: header.docDueDate || undefined,
          DocumentLines: (() => {
            const lines: Record<string, unknown>[] = [];
            for (const row of filteredRows) {
              // Guard: never send zero-quantity lines
              if (row.quantity <= 0) {
                continue;
              }

              const hasCompleteBaseLink =
                Number.isFinite(row.baseEntry) &&
                Number.isFinite(row.baseLine) &&
                Number.isFinite(row.baseType);

              // Manual rows (no base link): send single line with actual quantity
              if (!hasCompleteBaseLink) {
                lines.push({
                  DiscountPercent: row.discountPercent,
                  ItemCode: row.productCode,
                  Quantity: row.quantity,
                  UnitPrice: row.price,
                  UoMCode: row.uomCode || undefined,
                  UoMEntry: row.uomEntry ?? undefined,
                  VatGroup: row.vatGroup || undefined,
                  WarehouseCode: row.warehouseCode || undefined,
                });
                continue;
              }

              // Base-linked rows: split into base qty and excess portions
              const baseQty = row.baseQuantity ?? 0;
              const linkedQty = Math.min(row.quantity, baseQty);

              // Only push base-linked portion if quantity is positive
              if (linkedQty > 0) {
                lines.push({
                  BaseEntry: row.baseEntry,
                  BaseLine: row.baseLine,
                  BaseType: row.baseType,
                  DiscountPercent: row.discountPercent,
                  ItemCode: row.productCode,
                  Quantity: linkedQty,
                  UnitPrice: row.price,
                  UoMCode: row.uomCode || undefined,
                  UoMEntry: row.uomEntry ?? undefined,
                  VatGroup: row.vatGroup || undefined,
                  WarehouseCode: row.warehouseCode || undefined,
                });
              }

              // Excess portion: manual line without base linkage
              const excessQty = row.quantity - baseQty;
              if (excessQty > 0) {
                lines.push({
                  DiscountPercent: row.discountPercent,
                  ItemCode: row.productCode,
                  Quantity: excessQty,
                  UnitPrice: row.price,
                  UoMCode: row.uomCode || undefined,
                  UoMEntry: row.uomEntry ?? undefined,
                  VatGroup: row.vatGroup || undefined,
                  WarehouseCode: row.warehouseCode || undefined,
                });
              }
            }
            return lines;
          })(),
          SalesPersonCode: resolvedSalesEmployeeCode,
        };

    const toastHandle = documentActionToast("GRPO", isEditMode ? "update" : "create");
    try {
      let createdDocNum: number | undefined;
      if (isEditMode) {
        const detail = editDetailQuery.data?.data;
        const id = detail?.id ?? detail?.DocEntry;
        if (id === undefined || id === null) {
          setCreateError("Unable to update GRPO. Document id is missing.");
          toastHandle.error();
          return;
        }
        await updateMutation.mutateAsync({
          id,
          payload,
        });
      } else {
        const result = await createMutation.mutateAsync({ payload });
        createdDocNum = result?.data?.DocNum;
      }
      toastHandle.success(createdDocNum);

      if (isEditMode) {
        const currentDocNum = (docNum ?? "").trim();
        if (currentDocNum) {
          void queryClient.prefetchQuery(grpoQueries.detailByDocNum(currentDocNum));
        }
        window.scrollTo({ behavior: "smooth", top: 0 });
        setSubmitAttempted(false);
        return;
      }

      resetGRPOCreate();
      setSubmitAttempted(false);
      setVendorNameInput("");
      setVendorCodeInput("");
      setBuyerInput("");
      setProductRowDrafts({});
      setWarehouseInput("");
      setBillToAddress("");
      setShipToAddress("");
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      setBuyerFocused(false);
      setWarehouseFocused(false);
      setActiveDatePicker(null);
      setProductPopupOpen(false);
      setProductSearch("");
      setDebouncedProductSearch("");
      setActiveProductRowId(null);
      setStockPreviewProduct(null);
      setFieldErrors(EMPTY_GRPO_FIELD_ERRORS);
      setCreateError(null);
      hydratedDocNumRef.current = null;
      setHydratedDocNum(null);

      // Invalidate the specific source document detail queries used by copy-from hydration
      // so the next GRPO copy reads fresh OpenQty / status from the backend
      if (sourceDocNum) {
        if (sourceDocType === "PurchaseOrder") {
          sourceDocNum.split(",").forEach((num) => {
            const trimmed = num.trim();
            if (trimmed) {
              void queryClient.invalidateQueries({
                queryKey: purchaseOrderQueries.detailByDocNum(trimmed).queryKey,
              });
            }
          });
          void queryClient.invalidateQueries({ queryKey: purchaseOrderKeys.all });
        } else if (sourceDocType === "PurchaseQuotation") {
          sourceDocNum.split(",").forEach((num) => {
            const trimmed = num.trim();
            if (trimmed) {
              void queryClient.invalidateQueries({
                queryKey: purchaseQuotationQueries.detailByDocNum(trimmed).queryKey,
              });
            }
          });
          void queryClient.invalidateQueries({ queryKey: purchaseQuotationKeys.all });
        }
      }

      void Promise.allSettled([
        queryClient.invalidateQueries({
          queryKey: grpoQueries.list({ limit: 10, page: 1 }).queryKey,
        }),
        queryClient.prefetchQuery(grpoQueries.docNumSuggestions(undefined, 10)),
        queryClient.prefetchQuery(grpoQueries.docNumSuggestions(undefined, 100)),
      ]);

      // Scroll to top after successful save
      window.scrollTo({ behavior: "smooth", top: 0 });

      // Notify parent to navigate away after successful create
      if (!isEditMode) {
        onCreateSuccess?.();
      }
    } catch (error) {
      toastHandle.error();
      const errorMsg = normalizeCreateOrderErrorMessage(
        error,
        `Failed to ${isEditMode ? "update" : "create"} GRPO. Try again.`,
      );
      setCreateError(errorMsg);
    }
  };

  return {
    isEditMode,
    isEditHydrated,
    isSourceHydrating,
    today,
    activeDatePicker,
    setActiveDatePicker,
    docDateContainerRef,
    deliveryDateContainerRef,
    handleDocDateChange,
    handleDocDueDateChange,
    showEditRestrictedToast: (fieldName = "Field") => notifyRestricted(fieldName),

    vendorsQuery,
    warehousesQuery,
    salesEmployeesQuery,
    financialPeriodQuery,
    productsQuery,
    productWarehouseStocksQuery,
    editDetailQuery,
    createMutation,
    updateMutation,

    vendorNameSuggestions,
    vendorCodeSuggestions,
    warehouseSuggestions,
    buyerSuggestions,
    vendors,
    warehouses,
    salesEmployees,
    products,
    effectiveWarehouseCode,

    vendorNameInput,
    vendorCodeInput,
    warehouseInput,
    buyerInput,
    vendorNameFocused,
    setVendorNameFocused,
    vendorCodeFocused,
    setVendorCodeFocused,
    buyerFocused,
    setBuyerFocused,
    warehouseFocused,
    setWarehouseFocused,
    docDate: header.docDate,
    docDueDate: header.docDueDate,
    referenceNo: header.referenceNo,
    referenceAutoFilled: header.referenceAutoFilled,
    remarks: header.remarks,
    headerDiscountPercent,
    billToAddress,
    shipToAddress,
    isClosed,
    docStatus,

    modalOpen,
    modalMode,
    modalSearch,
    setModalOpen,
    setModalSearch,
    openPopup: openPopupByMode,
    handleLookupModalSearchSync,
    popupResults,

    productPopupOpen,
    productSearch,
    setProductPopupOpen,
    setProductSearch,
    activeProductRowId,
    openProductPopup,
    loadMoreProducts,
    applyProductToRow,
    applyProductsToRows,
    prefetchProducts: () => (isEditMode ? null : prefetchProducts()),
    // Derive the product code of the currently active row for seeding modal selection
    activeRowProductCode: (() => {
      if (!activeProductRowId) {
        return null;
      }
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      return activeRow?.productCode ?? null;
    })(),

    rows,
    productRowDrafts,
    setProductRowDraft,
    clearProductRowDraft,
    updateProductRow,
    removeProductRow,

    stockPreviewProduct,
    setStockPreviewProduct,
    openStockPreview,

    fieldErrors,
    createError,
    createDisabledReason,
    missingSearchMandatoryFields,
    searchRequiredCompletionPercent,
    searchMandatoryFields,
    missingMandatoryFields,
    requiredCompletionPercent,
    requiredFieldsTotal,
    requiredFieldLabelText: GRPO_FIELD_LABEL_TEXT,
    handleCreateOrder: handleCreateGRPO,
    submitAttempted,
    warehouseErrors,

    setDocDate: (val: string) =>
      isEditMode ? notifyRestricted("Document Date") : setHeader({ docDate: val }),
    setDocDueDate: (val: string) => setHeader({ docDueDate: val }),
    setBuyerInput: (val: string) =>
      isEditMode ? notifyRestricted("Buyer") : handleBuyerChange(val),
    setSalesEmployeeInput: (val: string) =>
      isEditMode ? notifyRestricted("Sales Employee") : handleBuyerChange(val),
    setWarehouseInput: (val: string) =>
      isEditMode ? notifyRestricted("Warehouse") : handleWarehouseInputChange(val),
    setReferenceNo: handleReferenceNoChange,
    setRemarks: handleRemarksChange,
    setBillToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Bill To Address") : handleBillToAddressChange(val),
    setShipToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Ship To Address") : handleShipToAddressChange(val),
    selectVendor: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Vendor") : selectVendor(val),
    selectWarehouse: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Warehouse") : selectWarehouse(val),
    selectSalesEmployee: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Sales Employee") : selectBuyer(val),
    selectBuyer: (val: LookupItem) => (isEditMode ? notifyRestricted("Buyer") : selectBuyer(val)),
    handleVendorNameChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Name") : handleVendorNameChange(val),
    handleVendorCodeChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Code") : handleVendorCodeChange(val),

    // Vendor-change confirmation (copy-from guard)
    pendingVendorChange,
    hasCopiedRows,
    confirmVendorChange,
    cancelVendorChange,
  };
}
