import { describe, expect, it } from "vitest";

import {
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from "@/features/create-pages/create-shared/utils/auto-reference";

describe("generateSingleSourceReference", () => {
  it("prefixes Auto Generated and includes company/BP code", () => {
    expect(generateSingleSourceReference("PurchaseQuotation", "132424", "C1105")).toBe(
      "Auto Generated Based on C1105 Purchase Quotation 132424",
    );
  });

  it("prefixes Auto Generated when company code is empty", () => {
    expect(generateSingleSourceReference("PurchaseOrder", "5001", "")).toBe(
      "Auto Generated Based on Purchase Order 5001",
    );
    expect(generateSingleSourceReference("PurchaseOrder", "5001")).toBe(
      "Auto Generated Based on Purchase Order 5001",
    );
  });

  it("stripAutoGeneratedReferences removes Auto Generated and legacy Based on lines", () => {
    const remarks = [
      "Urgent for plant B",
      "Auto Generated Based on C1105 Purchase Quotation 132424",
      "Based on Purchase Order 188",
    ].join("\n");
    expect(stripAutoGeneratedReferences(remarks)).toBe("Urgent for plant B");
  });
});
