import { describe, expect, it } from "vitest";

import {
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from "@/features/create-pages/create-shared/utils/auto-reference";

describe("generateSingleSourceReference", () => {
  it("writes short PQ / PO lines without company or Auto Generated", () => {
    expect(generateSingleSourceReference("PurchaseQuotation", "132424", "C1105")).toBe("PQ 132424");
    expect(generateSingleSourceReference("PurchaseOrder", "5001", "")).toBe("PO 5001");
    expect(generateSingleSourceReference("PurchaseOrder", "5001")).toBe("PO 5001");
  });

  it("stripAutoGeneratedReferences removes short and legacy Based on lines", () => {
    const remarks = [
      "Urgent for plant B",
      "PQ 132424",
      "Auto Generated Based on C1105 Purchase Quotation 132424",
      "Based on Purchase Order 188",
    ].join("\n");
    expect(stripAutoGeneratedReferences(remarks)).toBe("Urgent for plant B");
  });
});
