#!/bin/sh
echo "🔍 Running pre-commit checks..."

cd backend
echo "📦 Formatting backend..."
pnpm format

echo "📦 Linting backend..."
pnpm lint

echo "📦 Building backend..."
pnpm build
cd ..

cd frontend
echo "📦 Formatting frontend..."
pnpm format

echo "📦 Linting frontend..."
pnpm lint

echo "📦 Building frontend..."
pnpm build

echo "✅ All checks passed!"