import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { AttachmentItem } from "@/features/create-pages/create-shared/components/grids/upload-grid";

import {
  useCreateAPCreditMemo,
  useUpdateAPCreditMemo,
} from "@/features/create-pages/ap-credit-memo-create/api/ap-credit-memo-create.mutations";
import type {
  CreateAPCreditMemoInput,
  UpdateAPCreditMemoInput,
} from "@/features/create-pages/ap-credit-memo-create/api/ap-credit-memo-create.mutations";
import { useAPCreditMemoLookups } from "@/features/create-pages/ap-credit-memo-create/hooks/use-ap-credit-memo-lookups";
import {
  useAPCreditMemoHeader,
  useAPCreditMemoLines,
  useResetAPCreditMemoCreateAction,
  useSetAPCreditMemoHeaderAction,
  useSetAPCreditMemoLinesAction,
} from "@/features/create-pages/ap-credit-memo-create/store/ap-credit-memo-create.store";
import {
  AP_CREDIT_MEMO_FIELD_ERROR_TEXT,
  AP_CREDIT_MEMO_FIELD_LABEL_TEXT,
  AP_CREDIT_MEMO_MANDATORY_FIELDS,
  EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS,
  filterAndRankLookups,
  getTodayISO,
} from "@/features/create-pages/ap-credit-memo-create/utils/ap-credit-memo-create.utils";
import type { APCreditMemoFieldErrors } from "@/features/create-pages/ap-credit-memo-create/utils/ap-credit-memo-create.utils";
import { createSharedQueries } from "@/features/create-pages/create-shared/api/create-shared.queries";
import { parseDocumentHeaderNotes } from "@/features/create-pages/create-shared/utils/parse-header-notes";
import {
  clipSapText,
  SAP_FIELD_MAX,
  sapCommentsField,
} from "@/features/create-pages/create-shared/utils/sap-document-fields";
import type {
  LookupItem,
  ProductLookupItem,
  ProductWarehouseStockItem,
} from "@/features/create-pages/create-shared/api/create-shared.types";
import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import type {
  ActiveDatePicker,
  PopupMode,
  ProductRowDraft,
  StockPreviewProduct,
} from "@/features/create-pages/create-shared/utils/create-order.types";
import {
  formatWarehouseDisplay,
  normalizeCreateOrderErrorMessage,
} from "@/features/create-pages/create-shared/utils/create-order.utils";
import {
  notifyCreateApiError,
  notifyEditRestrictedField,
} from "@/features/create-pages/create-shared/utils/create-feedback-toast";
import { useDocumentSaveActions } from "@/features/create-pages/create-shared/hooks/use-document-save-actions";
import { useDocumentSeriesField } from "@/features/create-pages/create-shared/hooks/use-document-series-field";
import {
  documentSeriesPayload,
  SAP_SERIES_OBJECT,
  toPositiveSeries,
} from "@/features/create-pages/create-shared/utils/document-series";
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from "@/features/create-pages/create-shared/utils/lookup-search-sync";
import {
  resolveHydrateProductMeta,
  taxRatesFromProductMeta,
} from "@/features/create-pages/create-shared/utils/hydrate-product-meta";
import { resolveDocumentLineDiscount } from "@/features/create-pages/create-shared/utils/resolve-document-line-discount";
import { apCreditMemoQueries } from "@/features/table-pages/ap-credit-memo/api/ap-credit-memo.queries";
import { apInvoiceQueries } from "@/features/table-pages/ap-invoices/api/ap-invoice.queries";
import { apInvoiceAPI } from "@/features/table-pages/ap-invoices/api/ap-invoice.service";

import {
  composeCopySourceRemarks,
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from "../../create-shared/utils/auto-reference";

export interface APCreditMemoCreateLine {
  id: string;
  productCode: string;
  productName: string;
  stock: number;
  currency: string;
  vatGroup: string;
  taxRate: number;
  uomCode?: string | undefined;
  uomEntry?: number | undefined;
  baseQuantity?: number | undefined;
  quantity: number;
  discountPercent: number;
  discountAmount: number;
  comment: string;
  returnReason?: string | undefined;
  price: number;
  warehouseCode: string;
  baseLine?: number | undefined;
  baseEntry?: number | undefined;
  baseType?: number | undefined;
  selected?: boolean | undefined;
}
const BROWSE_PRODUCT_LIMIT = 50;

interface UseAPCreditMemoCreateOptions {
  mode?: "create" | "edit";
  docNum?: string;
  sourceDocNum?: string | undefined;
  sourceDocType?: "APInvoice" | undefined;
  draftDocNum?: string | undefined;
  draftDocEntry?: string | undefined;
  onCreateSuccess?: () => void;
}

const normalizeCodeForCompare = (value: unknown) => {
  const raw = String(value ?? "").trim();
  if (!raw) {
    return "";
  }
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
};

export function useAPCreditMemoCreate({
  mode = "create",
  docNum,
  sourceDocNum,
  sourceDocType,
  draftDocNum = "",
  draftDocEntry = "",
  onCreateSuccess,
}: UseAPCreditMemoCreateOptions) {
  const parseAPCreditMemoHeaderNotes = parseDocumentHeaderNotes;
  const isEditMode = mode === "edit";
  const editDocNum = (docNum ?? "").trim();
  const queryClient = useQueryClient();
  const header = useAPCreditMemoHeader();
  const setHeader = useSetAPCreditMemoHeaderAction();
  const rows = useAPCreditMemoLines();
  const filteredRows = useMemo(() => rows.filter((r) => r.selected && r.quantity > 0), [rows]);
  const setLines = useSetAPCreditMemoLinesAction();
  const resetAPCreditMemoCreate = useResetAPCreditMemoCreateAction();
  const createMutation = useCreateAPCreditMemo();
  const updateMutation = useUpdateAPCreditMemo();
  const hydratedDocNumRef = useRef<string | null>(null);
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null);
  const [formSnapshot, setFormSnapshot] = useState<any>(null);

  const [vendorNameInput, setVendorNameInput] = useState("");
  const [vendorCodeInput, setVendorCodeInput] = useState("");
  const [vendorNameFocused, setVendorNameFocused] = useState(false);
  const [vendorCodeFocused, setVendorCodeFocused] = useState(false);
  const [buyerInput, setBuyerInput] = useState("");
  const [buyerFocused, setBuyerFocused] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<PopupMode>("vendor-name");
  const [modalSearch, setModalSearch] = useState("");
  const [productPopupOpen, setProductPopupOpen] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [debouncedProductSearch, setDebouncedProductSearch] = useState("");

  const [activeProductRowId, setActiveProductRowId] = useState<string | null>(null);
  const [warehouseInput, setWarehouseInput] = useState("");
  const [warehouseFocused, setWarehouseFocused] = useState(false);

  const setSeries = useCallback(
    (series: number | null) => {
      setHeader({ series });
    },
    [setHeader],
  );

  const seriesField = useDocumentSeriesField({
    objectCode: SAP_SERIES_OBJECT.apCreditMemo,
    branchId: header.branchId,
    series: header.series,
    setSeries,
    disabled: isEditMode,
    lockSuggestion: isEditMode,
    documentNumber: isEditMode ? editDocNum : null,
  });

  const resetWarehouse = useCallback(() => {
    setWarehouseInput("");
    setHeader({ warehouseCode: "" });
    setWarehouseFocused(false);
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }));
  }, [setHeader]);

  const [billToAddress, setBillToAddressRaw] = useState("");
  const [shipToAddress, setShipToAddressRaw] = useState("");

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value));
  }, []);
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value));
  }, []);

  const [productRowDrafts, setProductRowDrafts] = useState<Record<string, ProductRowDraft>>({});
  const [stockPreviewProduct, setStockPreviewProduct] = useState<StockPreviewProduct | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<APCreditMemoFieldErrors>(
    EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS,
  );
  const [headerDiscountPercent, setHeaderDiscountPercent] = useState(0);
  const [attachments, setAttachments] = useState<AttachmentItem[]>([]);

  const resetForm = useCallback(() => {
    resetAPCreditMemoCreate();
    setVendorNameInput("");
    setVendorCodeInput("");
    setBuyerInput("");
    resetWarehouse();
    setBillToAddress("");
    setShipToAddress("");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
    setBuyerFocused(false);
    setActiveDatePicker(null);
    setModalOpen(false);
    setModalMode("vendor-name");
    setModalSearch("");
    setProductSearch("");
    setDebouncedProductSearch("");
    setActiveProductRowId(null);
    setProductPopupOpen(false);
    setProductRowDrafts({});
    setStockPreviewProduct(null);
    setFieldErrors(EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS);
    setCreateError(null);
    setHydratedDocNum(null);
    setFormSnapshot(null);
    setAttachments([]);
  }, [resetAPCreditMemoCreate, resetWarehouse, setBillToAddress, setShipToAddress]);

  const [pendingVendorChange, setPendingVendorChange] = useState<{
    vendor: LookupItem;
  } | null>(null);
  const hasCopiedRows = useMemo(
    () => rows.some((r) => r.baseEntry != null && r.baseType != null),
    [rows],
  );

  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);

  const warehouseErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!submitAttempted) return errors;

    filteredRows.forEach((row) => {
      if (!row.warehouseCode.trim()) {
        errors[row.id] = "Warehouse is required.";
      }
    });
    return errors;
  }, [submitAttempted, filteredRows]);

  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null);
  const docDateContainerRef = useRef<HTMLDivElement>(null);
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null);

  const notifyRestricted = (fieldName = "Field") => {
    notifyEditRestrictedField(fieldName);
  };

  const vendorsQuery = useQuery(createSharedQueries.vendors());
  const warehousesQuery = useQuery(createSharedQueries.warehouses());
  const salesEmployeesQuery = useQuery(createSharedQueries.salesEmployees());
  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data]);
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data]);
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data]);
  const effectiveWarehouseCode = useMemo(() => {
    const lookup = warehouseInput.trim().toLowerCase();
    const match = lookup.match(/\[([^\]]+)\]$/) || lookup.match(/^\[([^\]]+)\]/);
    const codeOrName = match ? match[1]!.trim() : lookup;
    const matched = warehouses.find(
      (item) => item.name.toLowerCase() === codeOrName || item.code.toLowerCase() === codeOrName,
    );
    return matched?.code ?? lookup;
  }, [warehouseInput, warehouses]);

  const searchWarehouseCode = useMemo(() => {
    if (activeProductRowId) {
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      if (activeRow?.warehouseCode) {
        return activeRow.warehouseCode;
      }
    }
    return effectiveWarehouseCode || undefined;
  }, [activeProductRowId, rows, effectiveWarehouseCode]);

  const vendorSelected = Boolean(vendorCodeInput) || Boolean(vendorNameInput);
  const vendorLookupToken = `${vendorCodeInput.trim().toLowerCase()}::${vendorNameInput.trim().toLowerCase()}`;
  const partnerCardCode = vendorCodeInput.trim() || undefined;

  const productsQuery = useQuery({
    ...createSharedQueries.products(
      undefined, // Pass undefined to keep search warehouse-agnostic
      debouncedProductSearch.trim() || undefined,
      BROWSE_PRODUCT_LIMIT,
      "purchase",
      undefined,
      partnerCardCode,
      "ap-credit-memo",
    ),
    enabled: productPopupOpen && vendorSelected && Boolean(partnerCardCode),
  });

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDebouncedProductSearch(productSearch.trim());
    }, 180);
    return () => window.clearTimeout(timer);
  }, [productSearch]);

  const prefetchProducts = useCallback(() => {
    if (!vendorSelected || !partnerCardCode) {
      return;
    }
    void queryClient.prefetchQuery(
      createSharedQueries.products(
        undefined,
        undefined,
        BROWSE_PRODUCT_LIMIT,
        "purchase",
        undefined,
        partnerCardCode,
        "ap-credit-memo",
      ),
    );
  }, [vendorSelected, partnerCardCode, queryClient]);

  useEffect(() => {
    if (!vendorSelected) {
      return;
    }
    prefetchProducts();
  }, [vendorLookupToken, vendorSelected, prefetchProducts]);

  const productWarehouseStocksQuery = useQuery({
    ...createSharedQueries.productWarehouseStocks(stockPreviewProduct?.code),
    enabled: Boolean(stockPreviewProduct?.code),
  });

  const fetchDocNum = isEditMode ? editDocNum : draftDocNum;
  const editDetailQuery = useQuery({
    ...apCreditMemoQueries.detailByDocNum(fetchDocNum, isEditMode ? undefined : draftDocEntry),
    enabled: (isEditMode && Boolean(editDocNum)) || Boolean(draftDocNum),
  });

  const sourceInvoiceQuery = useQuery({
    ...apInvoiceQueries.detailByDocNum(sourceDocNum || ""),
    enabled: !isEditMode && !!sourceDocNum && sourceDocType === "APInvoice",
  });

  const sourceInvoiceData = sourceInvoiceQuery.data?.data as Record<string, unknown> | undefined;
  const isSourceClosed =
    sourceInvoiceData?.DocStatus === "Closed" || sourceInvoiceData?.DocStatus === "C";

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === "Closed" ||
    editDetailQuery.data?.data?.DocStatus === "C";

  const isDirty = useMemo(() => {
    if ((!isEditMode && !draftDocNum) || !formSnapshot) {
      return false;
    }
    const current = {
      remarks: (header.remarks || "").trim(),
      referenceNo: (header.referenceNo || "").trim(),
      docDueDate: header.docDueDate,
      billToAddress: formatAddressForDisplay(billToAddress).trim(),
      shipToAddress: formatAddressForDisplay(shipToAddress).trim(),
      attachments: attachments.map((att) => ({
        fileName: att.fileName,
        freeText: att.freeText || "",
      })),
      productRows: filteredRows.map((row) => ({
        productCode: row.productCode,
        quantity: row.quantity,
        price: row.price,
        discountPercent: row.discountPercent,
        warehouseCode: row.warehouseCode,
        uomCode: row.uomCode,
        uomEntry: row.uomEntry,
      })),
    };
    return JSON.stringify(current) !== JSON.stringify(formSnapshot);
  }, [
    isEditMode,
    draftDocNum,
    formSnapshot,
    header.remarks,
    header.referenceNo,
    header.docDueDate,
    billToAddress,
    shipToAddress,
    attachments,
    filteredRows,
  ]);

  const submitDisabled = isEditMode || Boolean(draftDocNum) ? !isDirty : false;
  const docStatus =
    editDetailQuery.data?.data?.DocStatus === "O"
      ? "Open"
      : editDetailQuery.data?.data?.DocStatus === "C"
        ? "Closed"
        : (editDetailQuery.data?.data?.DocStatus ?? "Open");

  useEffect(() => {
    if (header.warehouseCode && warehouses.length > 0) {
      const matched = warehouses.find(
        (w) => String(w.code).trim() === String(header.warehouseCode).trim(),
      );
      if (matched && warehouseInput !== formatWarehouseDisplay(matched.name, matched.code)) {
        setWarehouseInput(formatWarehouseDisplay(matched.name, matched.code));
      }
    }
  }, [header.warehouseCode, warehouses, warehouseInput]);

  useEffect(() => {
    if (!isEditMode) {
      resetAPCreditMemoCreate();
      hydratedDocNumRef.current = null;
    }
    return () => {
      resetAPCreditMemoCreate();
      resetWarehouse();
    };
  }, [isEditMode, resetAPCreditMemoCreate, resetWarehouse]);

  useEffect(() => {
    if (!isEditMode) {
      return;
    }
    const currentDocNum = editDocNum;
    if (!currentDocNum) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    if (hydratedDocNumRef.current === currentDocNum) {
      return;
    }
    void (async () => {
      try {
        setVendorCodeInput(String(detail.CardCode ?? "").trim());
        setVendorNameInput(String(detail.CardName ?? "").trim());
        const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
        const { comments: remarks, referenceNo } = parseAPCreditMemoHeaderNotes(detail);

        const matchedVendor = vendors.find(
          (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
        );
        const buyerFromDocCode =
          detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(detail.SalesPersonCode),
              )?.name
            : "";

        setBuyerInput(buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "");
        const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);

        setHeader({
          docDate: loadedDocDate,
          docDueDate,
          referenceNo,
          remarks,
          series: toPositiveSeries((detail as Record<string, unknown>).Series),
        });
        setBillToAddress(String(detail.Address ?? "").trim());
        setShipToAddress(String((detail as Record<string, unknown>).Address2 ?? "").trim());
        const detailLines = detail.DocumentLines ?? [];
        const uniqueItemCodes = [
          ...new Set(detailLines.map((line) => String(line.ItemCode ?? "").trim())),
        ].filter(Boolean);

        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          uniqueItemCodes,
          "purchase",
          { cardCode: String(detail.CardCode ?? "").trim() || undefined },
        );
        const taxRateByItemCode = taxRatesFromProductMeta(productByCode);
        const resolvedHeaderDiscountPercent = Number(
          (detail as Record<string, unknown>).DiscountPercent ?? 0,
        );
        setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

        const mappedLines = (detail.DocumentLines ?? []).map(
          (line: Record<string, unknown>, index: number) => {
            const lineData = line as Record<string, unknown>;
            const quantity = Math.max(0, Number(line.Quantity ?? 0));
            const price = Number(line.Price ?? line.UnitPrice ?? 0);
            const grossAmount = Math.max(0, price * quantity);
            const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
              grossAmount,
              headerDiscountPercent: resolvedHeaderDiscountPercent,
              line,
            });
            const itemCode = String(line.ItemCode ?? "").trim();
            const productMeta = productByCode.get(itemCode);

            return {
              baseEntry: typeof line.BaseEntry === "number" ? line.BaseEntry : undefined,
              baseLine: typeof line.BaseLine === "number" ? line.BaseLine : undefined,
              baseQuantity: quantity,
              baseType: typeof line.BaseType === "number" ? line.BaseType : undefined,
              comment: "",
              currency: String(detail.DocCurr ?? productMeta?.currency ?? "").trim(),
              discountAmount,
              discountPercent,
              id: `${currentDocNum}-${index}`,
              price,
              productCode: itemCode,
              productName: String(
                line.ItemDescription ?? productMeta?.name ?? line.ItemCode ?? "",
              ).trim(),
              quantity,
              returnReason: String((line as Record<string, unknown>).U_ReturnReason ?? "").trim(),
              selected: true,
              stock: 0,
              taxRate:
                (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
                taxRateByItemCode.get(itemCode) ||
                0,
              uomCode: (() => {
                const code = String(
                  lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
                ).trim();
                if (code) return code;
                const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
                if (Number.isFinite(entry) && entry > 0) {
                  const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                  if (match?.code) return match.code;
                }
                return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
              })(),
              uomEntry: (() => {
                const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
                if (Number.isFinite(entry) && entry > 0) return entry;
                const code = String(
                  lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
                ).trim();
                if (code) {
                  const match = productMeta?.uomList?.find((u) => u.code === code);
                  if (match?.uomEntry !== undefined) return match.uomEntry;
                }
                return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
              })(),
              purchaseUomCode: productMeta?.purchaseUomCode,
              purchaseUomEntry: productMeta?.purchaseUomEntry,
              salesUomCode: productMeta?.uomCode,
              salesUomEntry: productMeta?.uomEntry,
              uomList: productMeta?.uomList,
              vatGroup: String(
                (line as { VatGroup?: string; TaxCode?: string }).VatGroup ??
                  (line as { TaxCode?: string }).TaxCode ??
                  "",
              ).trim(),
              warehouseCode: String(line.WarehouseCode ?? "").trim(),
            };
          },
        );
        setLines(mappedLines);
        setProductRowDrafts({});

        const rawAttachments = detail.attachments || [];
        setAttachments(
          rawAttachments.map((item: any, idx: number) => ({
            id: `loaded-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );

        // Populate header warehouseCode so the reactive useEffect resolves the display name.
        const editWarehouseCode = String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
        if (editWarehouseCode) {
          setHeader({ warehouseCode: editWarehouseCode });
          const matchedWarehouse = warehouses.find(
            (w) => String(w.code).trim() === editWarehouseCode,
          );
          setWarehouseInput(
            formatWarehouseDisplay(matchedWarehouse?.name ?? editWarehouseCode, editWarehouseCode),
          );
        }

        hydratedDocNumRef.current = currentDocNum;
        setFormSnapshot({
          remarks: (remarks || "").trim(),
          referenceNo: (referenceNo || "").trim(),
          docDueDate: docDueDate,
          billToAddress: formatAddressForDisplay(String(detail.Address ?? "")).trim(),
          shipToAddress: formatAddressForDisplay(
            String((detail as Record<string, unknown>).Address2 ?? ""),
          ).trim(),
          attachments: rawAttachments.map((item: any) => ({
            fileName: item.fileName,
            freeText: item.freeText || item.remarks || "",
          })),
          productRows: mappedLines
            .filter((row) => row.productCode.trim() && row.quantity > 0)
            .map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
        });
        setHydratedDocNum(currentDocNum);
      } finally {
      }
    })();
  }, [
    editDocNum,
    editDetailQuery.data,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
    effectiveWarehouseCode,
    warehouses,
  ]);
  // Draft Hydration — loads existing draft data into form when draftDocNum is present
  useEffect(() => {
    if (!draftDocNum) {
      return;
    }
    if (isEditMode) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    const hydrationKey = `${draftDocNum}_${draftDocEntry}`;
    if (hydratedDocNumRef.current === hydrationKey) {
      return;
    }
    void (async () => {
      try {
        setVendorCodeInput(String(detail.CardCode ?? "").trim());
        setVendorNameInput(String(detail.CardName ?? "").trim());
        const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
        const { comments: remarks, referenceNo } = parseAPCreditMemoHeaderNotes(detail);

        const matchedVendor = vendors.find(
          (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
        );
        const buyerFromDocCode =
          detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(detail.SalesPersonCode),
              )?.name
            : "";

        setBuyerInput(buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "");
        const docDueDate = String(detail.DocDueDate ?? "").slice(0, 10);

        setBillToAddress(String(detail.Address ?? "").trim() || matchedVendor?.billToAddress || "");
        setShipToAddress(
          String(detail.Address2 ?? "").trim() || matchedVendor?.shipToAddress || "",
        );
        setHeader({
          docDate: loadedDocDate,
          docDueDate,
          referenceNo,
          remarks,
          series: toPositiveSeries((detail as Record<string, unknown>).Series),
        });

        const productCodes = (detail.DocumentLines ?? [])
          .map((line) => String(line.ItemCode ?? "").trim())
          .filter(Boolean);
        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          productCodes,
          "purchase",
          { cardCode: String(detail.CardCode ?? "").trim() || undefined },
        );
        const taxRateByItemCode = taxRatesFromProductMeta(productByCode);

        const warehousesRes = await queryClient.fetchQuery(createSharedQueries.warehouses());
        const warehousesData = Array.isArray(warehousesRes) ? warehousesRes : [];
        const warehouseCode = String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
        const matchedWarehouse = warehousesData.find(
          (w: any) => String(w.code).trim() === warehouseCode,
        );
        setWarehouseInput(
          formatWarehouseDisplay(matchedWarehouse?.name ?? warehouseCode, warehouseCode),
        );

        let lineIndex = 0;
        const mappedLines = (detail.DocumentLines ?? []).map((line) => {
          const idx = lineIndex++;
          const lineData = line as Record<string, unknown>;
          const quantity = Math.max(0, Number(line.Quantity ?? 0));
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: 0,
            line: line as unknown as Record<string, unknown>,
          });
          const itemCode = String(line.ItemCode ?? "").trim();
          const productMeta = productByCode.get(itemCode);

          return {
            id: `row-draft-${idx}`,
            productCode: itemCode,
            foreignName: productMeta?.foreignName,
            productName: String(line.ItemDescription ?? productMeta?.name ?? itemCode).trim(),
            stock: 0,
            currency: String(productMeta?.currency ?? "").trim(),
            vatGroup: String(
              (line as { VatGroup?: string; TaxCode?: string }).VatGroup ??
                (line as { TaxCode?: string }).TaxCode ??
                "",
            ).trim(),
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: (() => {
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) return code;
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) {
                const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                if (match?.code) return match.code;
              }
              return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
            })(),
            uomEntry: (() => {
              const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
              if (Number.isFinite(entry) && entry > 0) return entry;
              const code = String(
                lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
              ).trim();
              if (code) {
                const match = productMeta?.uomList?.find((u) => u.code === code);
                if (match?.uomEntry !== undefined) return match.uomEntry;
              }
              return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
            })(),
            purchaseUomCode: productMeta?.purchaseUomCode,
            purchaseUomEntry: productMeta?.purchaseUomEntry,
            salesUomCode: productMeta?.uomCode,
            salesUomEntry: productMeta?.uomEntry,
            uomList: productMeta?.uomList,
            baseQuantity: undefined,
            quantity,
            discountPercent,
            discountAmount,
            comment: "",
            price,
            warehouseCode: String(line.WarehouseCode ?? "").trim(),
            baseEntry: undefined,
            baseLine: undefined,
            baseType: undefined,
            selected: true,
            returnReason: String(line.U_ReturnReason ?? "").trim(),
          };
        });
        setLines(mappedLines);

        const rawAttachments = detail.attachments || [];
        setAttachments(
          rawAttachments.map((item: any, idx: number) => ({
            id: `draft-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );

        hydratedDocNumRef.current = hydrationKey;
        setHydratedDocNum(hydrationKey);
        setFormSnapshot({
          remarks: (remarks || "").trim(),
          referenceNo: (referenceNo || "").trim(),
          docDueDate: docDueDate,
          billToAddress: formatAddressForDisplay(
            String(detail.Address ?? "").trim() || matchedVendor?.billToAddress || "",
          ).trim(),
          shipToAddress: formatAddressForDisplay(
            String(detail.Address2 ?? "").trim() || matchedVendor?.shipToAddress || "",
          ).trim(),
          attachments: rawAttachments.map((item: any) => ({
            fileName: item.fileName,
            freeText: item.freeText || item.remarks || "",
          })),
          productRows: mappedLines
            .filter((row) => row.productCode.trim() && row.quantity > 0)
            .map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
        });
      } finally {
      }
    })();
  }, [
    draftDocNum,
    draftDocEntry,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
    editDetailQuery.data,
    effectiveWarehouseCode,
  ]);
  useEffect(() => {
    if (isEditMode || draftDocNum) {
      return;
    }
    const currentSourceDocNum = sourceDocNum;
    const currentSourceDocType = sourceDocType;
    if (!currentSourceDocNum || !currentSourceDocType) {
      hydratedDocNumRef.current = null;
      return;
    }

    const sourceDocNums = currentSourceDocNum
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (sourceDocNums.length === 0) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    const hydrationKey = `${currentSourceDocType}-${currentSourceDocNum}`;
    if (hydratedDocNumRef.current === hydrationKey && isMetadataLoaded) {
      return;
    }
    if (isMetadataLoaded) {
      hydratedDocNumRef.current = hydrationKey;
    }
    const fetchAllSources = async () => {
      try {
        interface APInvoiceDetailType {
          CardCode?: string;
          CardName?: string;
          Comments?: string;
          DocCurr?: string;
          DocDueDate?: string;
          DocEntry?: number;
          id?: number;
          SalesPersonCode?: number;
          Address?: string;
          Address2?: string;
          DocumentLines?: Record<string, unknown>[];
          attachments?: any[];
        }

        const details = await Promise.all(
          sourceDocNums.map(async (num) => {
            const res = await queryClient.fetchQuery(apInvoiceQueries.detailByDocNum(num));
            return res.data as APInvoiceDetailType;
          }),
        );

        const primaryDetail = details[0]!;
        const vendorCode = String(primaryDetail.CardCode ?? "").trim();
        const vendorName = String(primaryDetail.CardName ?? "").trim();
        const matchedVendor = vendors.find((v) => String(v.code).trim() === vendorCode);

        const buyerFromDocCode =
          primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
            ? salesEmployees.find(
                (item) =>
                  normalizeCodeForCompare(item.code) ===
                  normalizeCodeForCompare(primaryDetail.SalesPersonCode),
              )?.name
            : "";
        const buyerName = buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "";

        const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
        const sourceComments = String(primaryDetail.Comments ?? "").trim();
        const refs = sourceDocNums.map((num) =>
          generateSingleSourceReference(currentSourceDocType, num, vendorCode),
        );
        const remarksParts = composeCopySourceRemarks(sourceComments, refs);

        const docDueDate = String(primaryDetail.DocDueDate ?? "").slice(0, 10);

        const allDetailLines = details.flatMap(
          (d) => (d.DocumentLines ?? []) as { ItemCode?: string }[],
        );
        const uniqueItemCodes = [
          ...new Set(allDetailLines.map((line) => String(line.ItemCode ?? "").trim())),
        ].filter(Boolean);

        const productByCode = await resolveHydrateProductMeta(
          queryClient,
          uniqueItemCodes,
          "purchase",
          {
            cardCode: String(primaryDetail.CardCode ?? "").trim() || undefined,
          },
        );

        const baseType = 18; // AP Invoice BaseType
        const currency = String(primaryDetail.DocCurr ?? "").trim();

        const taxRateByItemCode = taxRatesFromProductMeta(productByCode);
        const resolvedHeaderDiscountPercent = Number(
          (primaryDetail as Record<string, unknown>).DiscountPercent ?? 0,
        );
        setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

        let lineIndex = 0;
        const mappedLines = details.flatMap((detail) => {
          const detailLines = (detail.DocumentLines ?? []) as Record<string, unknown>[];
          return detailLines.map((line) => {
            const idx = lineIndex++;
            const lineData = line as Record<string, unknown>;
            const quantity = Math.max(
              0,
              Number(line.OpenQty ?? line.OpenQuantity ?? line.Quantity ?? 0),
            );
            const price = Number(line.Price ?? line.UnitPrice ?? 0);
            const grossAmount = Math.max(0, price * quantity);
            const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
              grossAmount,
              headerDiscountPercent: resolvedHeaderDiscountPercent,
              line: line as unknown as Record<string, unknown>,
            });
            const itemCode = String(line.ItemCode ?? "").trim();
            const productMeta = productByCode.get(itemCode);

            return {
              baseEntry: detail.DocEntry ?? (detail as { id?: number }).id ?? undefined,
              baseLine: (line.LineNum as number | undefined) ?? idx,
              baseQuantity: quantity,
              baseType,
              comment: "",
              currency: currency || String(productMeta?.currency ?? "").trim(),
              discountAmount,
              discountPercent,
              id: `row-copy-${detail.DocEntry ?? detail.id ?? "unknown"}-${idx}`,
              price,
              productCode: itemCode,
              productName: String(
                line.ItemDescription ?? productMeta?.name ?? line.ItemCode ?? "",
              ).trim(),
              quantity,
              returnReason: String((line as Record<string, unknown>).U_ReturnReason ?? "").trim(),
              selected: false,
              stock: 0,
              taxRate:
                (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
                taxRateByItemCode.get(itemCode) ||
                0,
              uomCode: (() => {
                const code = String(
                  lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
                ).trim();
                if (code) return code;
                const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
                if (Number.isFinite(entry) && entry > 0) {
                  const match = productMeta?.uomList?.find((u) => u.uomEntry === entry);
                  if (match?.code) return match.code;
                }
                return String(productMeta?.purchaseUomCode ?? productMeta?.uomCode ?? "").trim();
              })(),
              uomEntry: (() => {
                const entry = Number(lineData.UoMEntry ?? lineData.uomEntry ?? lineData.UomEntry);
                if (Number.isFinite(entry) && entry > 0) return entry;
                const code = String(
                  lineData.UoMCode ?? lineData.uomCode ?? lineData.UomCode ?? "",
                ).trim();
                if (code) {
                  const match = productMeta?.uomList?.find((u) => u.code === code);
                  if (match?.uomEntry !== undefined) return match.uomEntry;
                }
                return productMeta?.purchaseUomEntry ?? productMeta?.uomEntry;
              })(),
              purchaseUomCode: productMeta?.purchaseUomCode,
              purchaseUomEntry: productMeta?.purchaseUomEntry,
              salesUomCode: productMeta?.uomCode,
              salesUomEntry: productMeta?.uomEntry,
              uomList: productMeta?.uomList,
              vatGroup: String(
                (line as { VatGroup?: string; TaxCode?: string }).VatGroup ??
                  (line as { TaxCode?: string }).TaxCode ??
                  "",
              ).trim(),
              warehouseCode: String(line.WarehouseCode ?? warehouseCode).trim(),
            };
          });
        });

        const sourceNumAtCard = String(
          (primaryDetail as { NumAtCard?: string }).NumAtCard ?? "",
        ).trim();
        setVendorCodeInput(vendorCode);
        setVendorNameInput(vendorName);
        setBuyerInput(buyerName);
        const matchedWarehouseCopy = warehouses.find(
          (w) => String(w.code).trim() === warehouseCode,
        );
        setWarehouseInput(
          formatWarehouseDisplay(matchedWarehouseCopy?.name ?? warehouseCode, warehouseCode),
        );
        setBillToAddress(String(primaryDetail.Address ?? "").trim());
        setShipToAddress(String(primaryDetail.Address2 ?? "").trim());
        setHeader({
          docDate: getTodayISO(),
          docDueDate,
          referenceAutoFilled: true,
          referenceNo: sourceNumAtCard,
          remarks: clipSapText(remarksParts, SAP_FIELD_MAX.comments),
          warehouseCode, // ← required so the reactive useEffect can resolve the display name
        });
        setLines(mappedLines);
        setProductRowDrafts({});

        const sourceAttachments = primaryDetail.attachments || [];
        setAttachments(
          sourceAttachments.map((item: any, idx: number) => ({
            id: `copy-${idx}-${item.fileName}`,
            fileName: item.fileName,
            fileExtension: item.fileExtension,
            sourcePath: item.sourcePath,
            attachmentDate: item.attachmentDate,
            freeText: item.freeText || "",
            targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
          })),
        );
        if (isMetadataLoaded) {
          hydratedDocNumRef.current = hydrationKey;
        }
      } catch {
        // Error resilience – ensure toast is dismissed even on failure
      } finally {
      }
    };

    void fetchAllSources();
  }, [
    isEditMode,
    draftDocNum,
    sourceDocNum,
    sourceDocType,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setVendorCodeInput,
    setVendorNameInput,
    setBuyerInput,
    setWarehouseInput,
    setBillToAddress,
    setShipToAddress,
    setProductRowDrafts,
    vendors,
  ]);

  const { vendorNameSuggestions, vendorCodeSuggestions, warehouseSuggestions, buyerSuggestions } =
    useAPCreditMemoLookups({
      buyerInput,
      buyers: salesEmployees,
      vendorCodeInput,
      vendorNameInput,
      vendors,
      warehouseInput,
      warehouses,
    });

  const openPopupByMode = (mode: PopupMode) => {
    const searchVal =
      mode === "vendor-name" || mode === "vendor-code"
        ? mode === "vendor-name"
          ? vendorNameInput
          : vendorCodeInput
        : mode === "warehouse"
          ? warehouseInput
          : mode === "series"
            ? seriesField.seriesInput
            : buyerInput;

    setModalMode(mode);
    setModalSearch(searchVal);
    setModalOpen(true);
  };

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onSalesEmployee: handleBuyerChange,
      onSeries: seriesField.handleSeriesChange,
      onVendorCode: handleVendorCodeChange,
      onVendorName: handleVendorNameChange,
      onWarehouse: handleWarehouseInputChange,
    });

  useEffect(() => {
    if (!modalOpen) {
      return;
    }
    const nextSearch = getLookupInlineSearchByMode(modalMode, {
      salesEmployee: buyerInput,
      series: seriesField.seriesInput,
      vendorCode: vendorCodeInput,
      vendorName: vendorNameInput,
      warehouse: warehouseInput,
    });
    if (nextSearch !== modalSearch) {
      setModalSearch(nextSearch);
    }
  }, [
    buyerInput,
    modalMode,
    modalOpen,
    modalSearch,
    setModalSearch,
    vendorCodeInput,
    vendorNameInput,
    warehouseInput,
  ]);

  const selectVendor = (vendor: LookupItem) => {
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor });
      return;
    }
    applyVendorChange(vendor);
  };

  const applyVendorChange = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);

    setWarehouseInput("");
    setLines([]);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
  };

  const handleVendorNameChange = (value: string) => {
    setVendorNameInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined }));
    if (value.trim() === "") {
      setVendorNameFocused(true);
      setVendorCodeInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.name.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      setVendorCodeInput(matched.code);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorCodeInput("");
    setBuyerInput("");
    setLines([]);
    setVendorNameFocused(true);
  };

  const handleVendorCodeChange = (value: string) => {
    setVendorCodeInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorCode: undefined }));
    if (value.trim() === "") {
      setVendorCodeFocused(true);
      setVendorNameInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.code.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      if (hasCopiedRows) {
        setPendingVendorChange({ vendor: matched });
        return;
      }
      setVendorNameInput(matched.name);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorNameInput("");
    setBuyerInput("");
    setLines([]);
    setVendorCodeFocused(true);
  };

  const confirmVendorChange = () => {
    const pending = pendingVendorChange;
    if (!pending) {
      return;
    }
    setPendingVendorChange(null);

    const cleanedRemarks = stripAutoGeneratedReferences(header.remarks);
    setHeader({ remarks: cleanedRemarks });

    setLines((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row;
        return rest;
      }),
    );

    applyVendorChangeForConfirmation(pending.vendor);
  };

  const cancelVendorChange = () => {
    setPendingVendorChange(null);
  };

  const applyVendorChangeForConfirmation = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
  };

  const handleWarehouseInputChange = (value: string) => {
    setWarehouseInput(value);
    if (value.trim() === "") {
      setWarehouseFocused(true);
      setHeader({ warehouseCode: "" });
      return;
    }
    const matched = warehouses.find(
      (w) =>
        w.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        w.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      selectWarehouse(matched);
      return;
    }
    setHeader({ warehouseCode: "" });
  };

  const handleBuyerChange = (value: string) => {
    setBuyerInput(value);
    const matched = salesEmployees.find(
      (s) =>
        s.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        s.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      setBuyerFocused(false);
    }
  };

  const openProductPopup = (rowId: string | null = null) => {
    setActiveProductRowId(rowId);
    if (!vendorNameInput.trim() || !vendorCodeInput.trim()) {
      setFieldErrors((prev) => ({
        ...prev,
        vendorCode: !vendorCodeInput.trim()
          ? AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorCode
          : undefined,
        vendorName: !vendorNameInput.trim()
          ? AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorName
          : undefined,
      }));
      return;
    }

    setProductPopupOpen(true);
  };

  const selectWarehouse = (warehouse: LookupItem) => {
    setWarehouseInput(formatWarehouseDisplay(warehouse.name, warehouse.code));
    setHeader({ warehouseCode: warehouse.code });
    setLines((prev) => prev.map((row) => ({ ...row, warehouseCode: warehouse.code })));
    setWarehouseFocused(false);
  };

  const resolvedBuyerCode = useMemo(() => {
    const normalize = (val: unknown) =>
      String(val ?? "")
        .trim()
        .toLowerCase();
    const input = normalize(buyerInput);
    if (!input) return undefined;

    const byName = salesEmployees.find((item) => normalize(item.name) === input);
    if (byName) return Number(byName.code);

    const byCode = salesEmployees.find((item) => normalize(item.code) === input);
    if (byCode) return Number(byCode.code);

    return undefined;
  }, [buyerInput, salesEmployees]);

  const saveActions = useDocumentSaveActions({
    documentName: "AP Credit Memo",
    moduleType: "purchase",
    defaultUrl: "/purchase/create-ap-credit-memo",
    tableUrl: "/purchase/ap-credit-memo",
    resetForm,
    getPayloadString: () => {
      const buildDocumentLines = (): CreateAPCreditMemoInput["DocumentLines"] => {
        const lines: CreateAPCreditMemoInput["DocumentLines"] = [];
        for (const row of filteredRows) {
          if (row.quantity <= 0) {
            continue;
          }

          const hasCompleteBaseLink =
            Number.isFinite(row.baseEntry) &&
            Number.isFinite(row.baseLine) &&
            Number.isFinite(row.baseType);

          const baseLine: CreateAPCreditMemoInput["DocumentLines"][0] = {
            DiscountPercent: row.discountPercent,
            ItemCode: row.productCode,
            Quantity: row.quantity,
            UnitPrice: row.price,
            ...(row.uomEntry !== undefined ? { UoMEntry: row.uomEntry } : {}),
            ...(row.uomCode ? { UoMCode: row.uomCode } : {}),
            ...(row.warehouseCode ? { WarehouseCode: row.warehouseCode } : {}),
            ...(row.vatGroup ? { VatGroup: row.vatGroup } : {}),
            ...(row.returnReason ? { U_ReturnReason: row.returnReason } : {}),
          };

          if (!hasCompleteBaseLink) {
            lines.push(baseLine);
            continue;
          }

          const baseQty = row.baseQuantity ?? 0;
          const linkedQty = Math.min(row.quantity, baseQty);

          if (linkedQty > 0) {
            lines.push({
              ...baseLine,
              Quantity: linkedQty,
              ...(row.baseType !== undefined ? { BaseType: row.baseType } : {}),
              ...(row.baseEntry !== undefined ? { BaseEntry: row.baseEntry } : {}),
              ...(row.baseLine !== undefined ? { BaseLine: row.baseLine } : {}),
            });
          }

          const excessQty = row.quantity - baseQty;
          if (excessQty > 0) {
            lines.push({
              ...baseLine,
              Quantity: excessQty,
            });
          }
        }
        return lines;
      };

      if (isEditMode || draftDocNum) {
        const updatePayload: UpdateAPCreditMemoInput = {
          ...sapCommentsField(header.remarks),
          DocDueDate: header.docDueDate || undefined,
          NumAtCard: header.referenceNo.trim() || undefined,
          SalesPersonCode: resolvedBuyerCode,
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          ...(draftDocNum
            ? {
                DocumentLines: buildDocumentLines(),
              }
            : {}),
        };
        return JSON.stringify(updatePayload);
      }

      const createPayload: CreateAPCreditMemoInput = {
        CardCode: vendorCodeInput.trim(),
        ...(header.docDate ? { DocDate: header.docDate } : {}),
        ...(header.docDueDate ? { DocDueDate: header.docDueDate } : {}),
        ...sapCommentsField(header.remarks),
        ...(header.referenceNo.trim() ? { NumAtCard: header.referenceNo.trim() } : {}),
        Address: billToAddress.trim() || undefined,
        Address2: shipToAddress.trim() || undefined,
        ...documentSeriesPayload(header.series ?? seriesField.effectiveSeries),
        DocumentLines: buildDocumentLines(),
        SalesPersonCode: resolvedBuyerCode,
        attachments: attachments.map((att) => ({
          sourcePath: att.sourcePath || "",
          fileName: att.fileName,
          fileExtension: att.fileExtension || "",
          freeText: att.freeText || "",
          attachmentDate: att.attachmentDate || "",
        })),
      };
      return JSON.stringify(createPayload);
    },
    isEditMode,
  });

  const selectBuyer = (item: LookupItem) => {
    setBuyerInput(item.name);
    setBuyerFocused(false);
  };

  const applyProductToRow = (product: ProductLookupItem) => {
    void queryClient.prefetchQuery(createSharedQueries.productWarehouseStocks(product.code));
    setLines((prev) => {
      if (activeProductRowId) {
        const activeRow = prev.find((r) => r.id === activeProductRowId);
        const targetWhs = activeRow?.warehouseCode || effectiveWarehouseCode || "";
        const stocksData = queryClient.getQueryData<ProductWarehouseStockItem[]>(
          createSharedQueries.productWarehouseStocks(product.code).queryKey,
        );
        const matchedStock = stocksData?.find(
          (s) => String(s.code).trim() === String(targetWhs).trim(),
        );
        const resolvedStock = matchedStock ? Number(matchedStock.stock ?? 0) : 0;

        return prev.map((row) =>
          row.id === activeProductRowId
            ? {
                ...row,
                price: Number(product.price ?? 0),
                productCode: product.code,
                foreignName: product.foreignName,
                productName: product.name,
                quantity: 1,
                stock: resolvedStock,
                uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
                uomEntry: product.purchaseUomEntry ?? product.uomEntry,
                warehouseCode: targetWhs,
              }
            : row,
        );
      }
      const targetWhs = effectiveWarehouseCode || "";
      const stocksData = queryClient.getQueryData<ProductWarehouseStockItem[]>(
        createSharedQueries.productWarehouseStocks(product.code).queryKey,
      );
      const matchedStock = stocksData?.find(
        (s) => String(s.code).trim() === String(targetWhs).trim(),
      );
      const resolvedStock = matchedStock ? Number(matchedStock.stock ?? 0) : 0;

      return [
        ...prev,
        {
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          foreignName: product.foreignName,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: resolvedStock,
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: targetWhs,
        },
      ];
    });
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const applyProductsToRows = (products: ProductLookupItem[]) => {
    products.forEach((product) => {
      void queryClient.prefetchQuery(createSharedQueries.productWarehouseStocks(product.code));
    });

    setLines((prev) => [
      ...prev,
      ...products.map((product) => {
        const targetWhs = effectiveWarehouseCode || "";
        const stocksData = queryClient.getQueryData<ProductWarehouseStockItem[]>(
          createSharedQueries.productWarehouseStocks(product.code).queryKey,
        );
        const matchedStock = stocksData?.find(
          (s) => String(s.code).trim() === String(targetWhs).trim(),
        );
        const resolvedStock = matchedStock ? Number(matchedStock.stock ?? 0) : 0;

        return {
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          foreignName: product.foreignName,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: resolvedStock,
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: targetWhs,
        };
      }),
    ]);
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const handleCreateAPCreditMemo = async (
    action: "save-new" | "view" | "close" | "draft" = "save-new",
  ) => {
    const draftCardCode = String(header.vendorCode || vendorCodeInput || "").trim();
    const isDraftAction = action === "draft";
    const isDraftUpdate = isDraftAction && Boolean(draftDocNum);
    const isUpdating = isEditMode || isDraftUpdate;

    if (isDraftAction) {
      if (!draftCardCode) {
        setSubmitAttempted(true);
        const nextErrors = { ...EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS };
        nextErrors.vendorCode = AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorCode;
        nextErrors.vendorName = AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorName;
        setFieldErrors(nextErrors);
        setCreateError("Vendor is required to save as draft.");
        return;
      }
    }

    setSubmitAttempted(true);

    if (!isDraftAction && !isEditMode) {
      const missing = AP_CREDIT_MEMO_MANDATORY_FIELDS.filter((field) => {
        if (field === "vendorName") {
          return !vendorNameInput.trim();
        }
        if (field === "vendorCode") {
          return !vendorCodeInput.trim();
        }
        return false;
      });

      if (missing.length > 0) {
        const nextErrors = { ...EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS };
        missing.forEach((field) => {
          nextErrors[field] = AP_CREDIT_MEMO_FIELD_ERROR_TEXT[field];
        });
        setFieldErrors(nextErrors);
        setCreateError("Fill required fields before creating A/P Credit Memo.");
        return;
      }
    }

    if (filteredRows.length === 0) {
      setCreateError("Select at least one row and set a quantity greater than 0.");
      return;
    }

    const buildDocumentLines = (): CreateAPCreditMemoInput["DocumentLines"] => {
      const lines: CreateAPCreditMemoInput["DocumentLines"] = [];
      for (const row of filteredRows) {
        if (row.quantity <= 0) {
          continue;
        }

        const hasCompleteBaseLink =
          Number.isFinite(row.baseEntry) &&
          Number.isFinite(row.baseLine) &&
          Number.isFinite(row.baseType);

        const baseLine: CreateAPCreditMemoInput["DocumentLines"][0] = {
          DiscountPercent: row.discountPercent,
          ItemCode: row.productCode,
          Quantity: row.quantity,
          UnitPrice: row.price,
          ...(row.uomEntry !== undefined ? { UoMEntry: row.uomEntry } : {}),
          ...(row.uomCode ? { UoMCode: row.uomCode } : {}),
          ...(row.warehouseCode ? { WarehouseCode: row.warehouseCode } : {}),
          ...(row.vatGroup ? { VatGroup: row.vatGroup } : {}),
          ...(row.returnReason ? { U_ReturnReason: row.returnReason } : {}),
        };

        if (!hasCompleteBaseLink) {
          lines.push(baseLine);
          continue;
        }

        const baseQty = row.baseQuantity ?? 0;
        const linkedQty = Math.min(row.quantity, baseQty);

        if (linkedQty > 0) {
          lines.push({
            ...baseLine,
            Quantity: linkedQty,
            ...(row.baseType !== undefined ? { BaseType: row.baseType } : {}),
            ...(row.baseEntry !== undefined ? { BaseEntry: row.baseEntry } : {}),
            ...(row.baseLine !== undefined ? { BaseLine: row.baseLine } : {}),
          });
        }

        const excessQty = row.quantity - baseQty;
        if (excessQty > 0) {
          lines.push({
            ...baseLine,
            Quantity: excessQty,
          });
        }
      }
      return lines;
    };

    const trackingAction = isDraftAction
      ? isDraftUpdate
        ? "draft-update"
        : "draft"
      : isEditMode
        ? "update"
        : action;

    saveActions.startSaveTracking(trackingAction);
    try {
      let createdDocNum: string | number | undefined;
      if (isUpdating) {
        const currentSalesPersonCode = resolvedBuyerCode;

        if (isEditMode && !isDirty) {
          const noChangeMessage = "Change at least one field before update.";
          setCreateError(noChangeMessage);
          return;
        }

        const id =
          editDetailQuery.data?.data?.id ?? editDetailQuery.data?.data?.DocEntry ?? draftDocEntry;
        const updatePayload: UpdateAPCreditMemoInput = {
          ...sapCommentsField(header.remarks),
          DocDate: header.docDate || undefined,
          DocDueDate: header.docDueDate || undefined,
          NumAtCard: header.referenceNo.trim() || undefined,
          SalesPersonCode: currentSalesPersonCode,
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          ...(draftDocNum || isDraftUpdate
            ? {
                DocumentLines: buildDocumentLines(),
              }
            : {}),
          attachments: attachments.map((att) => ({
            sourcePath: att.sourcePath || "",
            fileName: att.fileName,
            fileExtension: att.fileExtension || "",
            freeText: att.freeText || "",
            attachmentDate: att.attachmentDate || "",
          })),
        };

        if (isDraftUpdate) {
          updatePayload.isDraft = true;
          if (draftDocEntry) {
            updatePayload.draftDocEntry = Number(draftDocEntry);
          }
        }

        await updateMutation.mutateAsync({ id: id!, payload: updatePayload });

        createdDocNum = editDetailQuery.data?.data?.DocNum ?? draftDocNum;

        // Fetch the updated detail from the API/cache to sync the local states (like attachments) immediately without page refresh
        const fetchNum = isEditMode ? editDocNum : draftDocNum;
        const updatedDetailRes = await queryClient.fetchQuery(
          apCreditMemoQueries.detailByDocNum(fetchNum, isEditMode ? undefined : draftDocEntry),
        );
        const updatedDetail = updatedDetailRes?.data;
        if (updatedDetail) {
          const rawAttachments = updatedDetail.attachments || [];
          setAttachments(
            rawAttachments.map((item: any, idx: number) => ({
              id: `loaded-${idx}-${item.fileName}`,
              fileName: item.fileName,
              fileExtension: item.fileExtension,
              sourcePath: item.sourcePath,
              attachmentDate: item.attachmentDate,
              freeText: item.freeText || "",
              targetPath: `${item.sourcePath}\\${item.fileName}.${item.fileExtension}`,
            })),
          );

          const { comments: remarks, referenceNo } = parseAPCreditMemoHeaderNotes(updatedDetail);
          const docDueDate = String(updatedDetail.DocDueDate ?? updatedDetail.DocDate ?? "").slice(
            0,
            10,
          );

          setFormSnapshot({
            remarks: (remarks || "").trim(),
            referenceNo: (referenceNo || "").trim(),
            docDueDate: docDueDate,
            billToAddress: formatAddressForDisplay(
              String(updatedDetail.Address ?? "").trim() || billToAddress || "",
            ).trim(),
            shipToAddress: formatAddressForDisplay(
              String(updatedDetail.Address2 ?? "").trim() || shipToAddress || "",
            ).trim(),
            attachments: rawAttachments.map((item: any) => ({
              fileName: item.fileName,
              freeText: item.freeText || item.remarks || "",
            })),
            productRows: filteredRows.map((row) => ({
              productCode: row.productCode,
              quantity: row.quantity,
              price: row.price,
              discountPercent: row.discountPercent,
              warehouseCode: row.warehouseCode,
              uomCode: row.uomCode,
              uomEntry: row.uomEntry,
            })),
          });
        }
      } else {
        const createPayload: CreateAPCreditMemoInput = {
          CardCode: vendorCodeInput.trim(),
          ...(header.docDate ? { DocDate: header.docDate } : {}),
          ...(header.docDueDate ? { DocDueDate: header.docDueDate } : {}),
          ...sapCommentsField(header.remarks),
          ...(header.referenceNo.trim() ? { NumAtCard: header.referenceNo.trim() } : {}),
          Address: billToAddress.trim() || undefined,
          Address2: shipToAddress.trim() || undefined,
          ...documentSeriesPayload(header.series ?? seriesField.effectiveSeries),
          DocumentLines: buildDocumentLines(),
          SalesPersonCode: resolvedBuyerCode,
          attachments: attachments.map((att) => ({
            sourcePath: att.sourcePath || "",
            fileName: att.fileName,
            fileExtension: att.fileExtension || "",
            freeText: att.freeText || "",
            attachmentDate: att.attachmentDate || "",
          })),
        };

        if (isDraftAction) {
          createPayload.isDraft = true;
          if (draftDocEntry) {
            createPayload.draftDocEntry = Number(draftDocEntry);
          }
        } else if (draftDocNum && draftDocEntry) {
          createPayload.draftDocEntry = Number(draftDocEntry);
        }

        // Try to reopen the base A/P Invoice if it's closed, as requested.
        // We catch and swallow the error if SAP doesn't support reopening this specific invoice,
        // so we can still attempt to create the linked Credit Memo!
        if (isSourceClosed) {
          try {
            const entry = Number(sourceInvoiceData?.DocEntry ?? sourceInvoiceData?.id);
            if (entry) {
              await apInvoiceAPI.reopenAPInvoice(entry);
            }
          } catch (err) {
            console.warn(
              `SAP Reopen failed (continuing to Credit Memo creation): ${(err as Error).message}`,
            );
          }
        }

        const result = await createMutation.mutateAsync({
          payload: createPayload,
        });
        createdDocNum = result?.data?.DocNum;

        if (sourceDocNum && sourceDocType) {
          void queryClient.invalidateQueries({
            queryKey: apInvoiceQueries.list({ limit: 10, page: 1 }).queryKey,
          });

          if (sourceDocType === "APInvoice") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: apInvoiceQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
          }
        }
      }

      saveActions.trackMutationSuccess();

      if (isEditMode) {
        resetWarehouse();
      }

      if (isEditMode) {
        void queryClient.invalidateQueries(apCreditMemoQueries.detailByDocNum(editDocNum));
      }

      await saveActions.handleActionSuccess(isEditMode ? "update" : action, createdDocNum);

      setSubmitAttempted(false);

      if (!isEditMode && action === "save-new") {
        onCreateSuccess?.();
      }
    } catch (error) {
      const errorMsg = normalizeCreateOrderErrorMessage(
        error,
        `Failed to ${trackingAction} A/P Credit Memo.`,
      );
      setCreateError(errorMsg);
      notifyCreateApiError(errorMsg, "ap-credit-memo");
    }
  };

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) {
      return [];
    }
    return AP_CREDIT_MEMO_MANDATORY_FIELDS.filter((field) => {
      if (field === "vendorName") {
        return !vendorNameInput.trim();
      }
      if (field === "vendorCode") {
        return !vendorCodeInput.trim();
      }
      return false;
    });
  }, [isEditMode, vendorNameInput, vendorCodeInput, rows]);

  const requiredCompletionPercent = useMemo(
    () =>
      ((AP_CREDIT_MEMO_MANDATORY_FIELDS.length - missingMandatoryFields.length) /
        AP_CREDIT_MEMO_MANDATORY_FIELDS.length) *
      100,
    [missingMandatoryFields],
  );

  return {
    activeDatePicker,
    activeProductRowId,
    activeRowProductCode: (() => {
      if (!activeProductRowId) {
        return null;
      }
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      return activeRow?.productCode ?? null;
    })(),
    applyProductToRow,
    applyProductsToRows,
    isSourceClosed,
    billToAddress,
    buyerFocused,
    buyerInput,
    buyerSuggestions,
    cancelVendorChange,
    clearProductRowDraft: (id: string, field: string) =>
      setProductRowDrafts((prev) => {
        const next = { ...prev[id] };
        delete next[field as keyof typeof next];
        return { ...prev, [id]: next };
      }),
    confirmVendorChange,
    submitDisabled,
    createDisabledReason:
      missingMandatoryFields.length > 0
        ? "Mandatory fields missing"
        : rows.length === 0
          ? "No lines"
          : null,
    createError,
    createMutation,
    deliveryDateContainerRef,
    docDate: header.docDate,
    docDateContainerRef,
    docDueDate: header.docDueDate,
    docStatus,
    editDetailQuery,
    fieldErrors,
    handleCreateOrder: handleCreateAPCreditMemo,
    handleDocDateChange: (val: string) => setHeader({ docDate: val }),
    handleDocDueDateChange: (val: string) => setHeader({ docDueDate: val }),
    ...seriesField,
    selectSeries: (item: LookupItem) => {
      if (isEditMode) {
        notifyRestricted("Series");
        return;
      }
      seriesField.selectSeries(item);
      setModalOpen(false);
    },
    handleLookupModalSearchSync,
    handleVendorCodeChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Code") : handleVendorCodeChange(val),
    handleVendorNameChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Name") : handleVendorNameChange(val),
    hasCopiedRows,
    isClosed,
    isEditHydrated: !isEditMode || hydratedDocNum === editDocNum,
    isEditMode,
    isDirty,
    isLookupLoading: modalMode.includes("vendor")
      ? vendorsQuery.isLoading
      : modalMode === "warehouse"
        ? warehousesQuery.isLoading
        : salesEmployeesQuery.isLoading,
    isProductsLoading: productsQuery.isLoading,
    isSourceHydrating:
      mode === "create" && !draftDocNum && Boolean(sourceDocNum) && !hydratedDocNumRef.current,
    loadMoreProducts: () => {
      // Browse is a single cached page (BROWSE_PRODUCT_LIMIT). Virtual scroll only windows it.
    },
    lookupError:
      (modalMode.includes("vendor")
        ? vendorsQuery.error
        : modalMode === "warehouse"
          ? warehousesQuery.error
          : salesEmployeesQuery.error
      )?.message ?? null,
    missingMandatoryFields,
    missingSearchMandatoryFields: useMemo(
      () =>
        ["vendorName", "vendorCode"].filter(
          (field) =>
            !String(field === "vendorName" ? vendorNameInput : (vendorCodeInput ?? "")).trim(),
        ),
      [vendorNameInput, vendorCodeInput],
    ),
    modalMode,
    modalOpen,
    modalSearch,
    openPopup: openPopupByMode,
    openProductPopup,
    openStockPreview: setStockPreviewProduct,
    pendingVendorChange,
    popupResults: useMemo(
      () =>
        filterAndRankLookups(
          modalMode.includes("vendor")
            ? vendors
            : modalMode === "warehouse"
              ? warehouses
              : modalMode === "series"
                ? (seriesField.seriesList as LookupItem[])
                : salesEmployees,
          modalSearch,
        ),
      [vendors, warehouses, salesEmployees, seriesField.seriesList, modalSearch, modalMode],
    ),
    prefetchProducts: isEditMode ? () => {} : prefetchProducts,
    productPopupOpen,
    productRowDrafts,
    productSearch,
    productWarehouseStocksQuery,
    products: productsQuery.data ?? [],
    productsError: productsQuery.error?.message ?? null,
    productsQuery,
    headerDiscountPercent,
    referenceAutoFilled: header.referenceAutoFilled,
    referenceNo: header.referenceNo,
    remarks: header.remarks,
    removeProductRow: (id: string) => setLines((prev) => prev.filter((r) => r.id !== id)),
    requiredCompletionPercent,
    requiredFieldLabelText: AP_CREDIT_MEMO_FIELD_LABEL_TEXT,
    requiredFieldsTotal: AP_CREDIT_MEMO_MANDATORY_FIELDS.length,
    rows,
    submitAttempted,
    warehouseErrors,
    salesEmployees,
    salesEmployeesQuery,
    searchMandatoryFields: useMemo(() => ["vendorName", "vendorCode"] as const, []),
    searchRequiredCompletionPercent: useMemo(() => {
      const filled = (vendorNameInput.trim() ? 1 : 0) + (vendorCodeInput.trim() ? 1 : 0);
      return (filled / 2) * 100;
    }, [vendorNameInput, vendorCodeInput]),
    selectSalesEmployee: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Sales Employee") : selectBuyer(val),
    selectVendor: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Vendor") : selectVendor(val),
    selectWarehouse: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Warehouse") : selectWarehouse(val),
    setActiveDatePicker,
    setBillToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Pay To Address") : setBillToAddress(val),
    setBuyerFocused,
    setBuyerInput: (val: string) =>
      isEditMode ? notifyRestricted("Buyer") : handleBuyerChange(val),
    setDocDate: (val: string) => setHeader({ docDate: val }),
    setDocDueDate: (val: string) => setHeader({ docDueDate: val }),
    setModalOpen,
    setModalSearch,
    setProductPopupOpen,
    setProductRowDraft: (id: string, field: string, value: string) =>
      setProductRowDrafts((prev) => ({
        ...prev,
        [id]: { ...prev[id], [field]: value },
      })),
    setProductSearch,
    setReferenceNo: (val: string) => {
      setHeader({ referenceNo: val });
      setFieldErrors((prev) => ({ ...prev, referenceNo: undefined }));
    },
    setRemarks: (val: string) => {
      setHeader({ remarks: val });
      setFieldErrors((prev) => ({ ...prev, comments: undefined }));
    },
    setShipToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Ship To Address") : setShipToAddress(val),
    setStockPreviewProduct,
    setVendorCodeFocused,
    setVendorNameFocused,
    setWarehouseFocused,
    setWarehouseInput: (val: string) =>
      isEditMode ? notifyRestricted("Warehouse") : handleWarehouseInputChange(val),
    shipToAddress,
    showEditRestrictedToast: notifyRestricted,
    stockPreviewProduct,
    today,
    updateMutation,
    updateProductRow: (id: string, patch: Partial<APCreditMemoCreateLine>) =>
      setLines((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r))),
    setProductRows: setLines,
    vendorCodeFocused,
    vendorCodeInput,
    vendorCodeSuggestions,
    vendorNameFocused,
    vendorNameInput,
    vendorNameSuggestions,
    vendors,
    vendorsQuery,
    warehouseCode: effectiveWarehouseCode,
    searchWarehouseCode,
    warehouseFocused,
    resetWarehouse,
    clearLines: () => setLines([]),
    clearProductRowDrafts: () => setProductRowDrafts({}),
    warehouseInput,
    warehouseSuggestions,
    warehouses,
    warehousesQuery,
    trackerDocType: isEditMode ? ("ap-credit-memo" as const) : null,
    trackerDocEntry: isEditMode
      ? (editDetailQuery.data?.data?.DocEntry ?? editDetailQuery.data?.data?.id)
      : null,
    attachments,
    setAttachments,
    isSaved: saveActions.isSaved,
    savedDocNum: saveActions.savedDocNum,
    resetForm: saveActions.handleReset,
  };
}
