import { useQuery, useQueryClient } from "@tanstack/react-query";
import { goeyToast } from "goey-toast";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import {
  useCreateAPCreditMemo,
  useUpdateAPCreditMemo,
} from "@/features/create-pages/ap-credit-memo-create/api/ap-credit-memo-create.mutations";
import type {
  CreateAPCreditMemoInput,
  UpdateAPCreditMemoInput,
} from "@/features/create-pages/ap-credit-memo-create/api/ap-credit-memo-create.mutations";
import { useAPCreditMemoLookups } from "@/features/create-pages/ap-credit-memo-create/hooks/use-ap-credit-memo-lookups";
import {
  useAPCreditMemoHeader,
  useAPCreditMemoLines,
  useResetAPCreditMemoCreateAction,
  useSetAPCreditMemoHeaderAction,
  useSetAPCreditMemoLinesAction,
} from "@/features/create-pages/ap-credit-memo-create/store/ap-credit-memo-create.store";
import {
  AP_CREDIT_MEMO_FIELD_ERROR_TEXT,
  AP_CREDIT_MEMO_FIELD_LABEL_TEXT,
  AP_CREDIT_MEMO_MANDATORY_FIELDS,
  filterAndRankLookups,
  getTodayISO,
} from "@/features/create-pages/ap-credit-memo-create/utils/ap-credit-memo-create.utils";
import type { APCreditMemoMandatoryField } from "@/features/create-pages/ap-credit-memo-create/utils/ap-credit-memo-create.utils";
import { createSharedQueries } from "@/features/create-pages/create-shared/api/create-shared.queries";
import type {
  LookupItem,
  ProductLookupItem,
} from "@/features/create-pages/create-shared/api/create-shared.types";
import { formatAddressForDisplay } from "@/features/create-pages/create-shared/utils/address.utils";
import type {
  ActiveDatePicker,
  PopupMode,
  ProductRowDraft,
  StockPreviewProduct,
} from "@/features/create-pages/create-shared/utils/create-order.types";
import { normalizeCreateOrderErrorMessage } from "@/features/create-pages/create-shared/utils/create-order.utils";
import { documentActionToast } from "@/features/create-pages/create-shared/utils/document-action-toast";
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from "@/features/create-pages/create-shared/utils/lookup-search-sync";
import { pageLoadingToast } from "@/features/create-pages/create-shared/utils/page-loading-toast";
import { resolveProductTaxRates } from "@/features/create-pages/create-shared/utils/product-tax-rate";
import { resolveDocumentLineDiscount } from "@/features/create-pages/create-shared/utils/resolve-document-line-discount";
import { apCreditMemoQueries } from "@/features/table-pages/ap-credit-memo/api/ap-credit-memo.queries";
import { apInvoiceQueries } from "@/features/table-pages/ap-invoices/api/ap-invoice.queries";
import { apInvoiceAPI } from "@/features/table-pages/ap-invoices/api/ap-invoice.service";

import {
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from "../../create-shared/utils/auto-reference";

export interface APCreditMemoCreateLine {
  id: string;
  productCode: string;
  productName: string;
  stock: number;
  currency: string;
  vatGroup: string;
  taxRate: number;
  uomCode?: string | undefined;
  uomEntry?: number | undefined;
  baseQuantity?: number | undefined;
  quantity: number;
  discountPercent: number;
  discountAmount: number;
  comment: string;
  returnReason?: string | undefined;
  price: number;
  warehouseCode: string;
  baseLine?: number | undefined;
  baseEntry?: number | undefined;
  baseType?: number | undefined;
  selected?: boolean | undefined;
}
type APCreditMemoFieldErrors = Record<APCreditMemoMandatoryField, string | undefined> & {
  warehouseCode?: string | undefined;
};
const QUICK_PRODUCT_LIMIT = 10;

const EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS: APCreditMemoFieldErrors = {
  returnReason: undefined,
  vendorCode: undefined,
  vendorName: undefined,
};

interface UseAPCreditMemoCreateOptions {
  mode?: "create" | "edit";
  docNum?: string;
  sourceDocNum?: string | undefined;
  sourceDocType?: "APInvoice" | undefined;
  onCreateSuccess?: () => void;
}

const normalizeCodeForCompare = (value: unknown) => {
  const raw = String(value ?? "").trim();
  if (!raw) {
    return "";
  }
  const parsed = Number(raw);
  return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase();
};

export function useAPCreditMemoCreate({
  mode = "create",
  docNum,
  sourceDocNum,
  sourceDocType,
  onCreateSuccess,
}: UseAPCreditMemoCreateOptions) {
  const parseAPCreditMemoHeaderNotes = (detail: { Comments?: unknown; NumAtCard?: unknown }) => {
    const referenceNo = String(detail.NumAtCard ?? "").trim();
    const rawComments = String(detail.Comments ?? "").trim();

    if (referenceNo) {
      const legacyReferencePrefix = `${referenceNo} | `;
      return {
        comments: rawComments.startsWith(legacyReferencePrefix)
          ? rawComments.slice(legacyReferencePrefix.length).trim()
          : rawComments,
        referenceNo,
      };
    }

    const splitComments = rawComments.split(" | ").map((part) => part.trim());
    if (splitComments.length > 1) {
      return {
        comments: splitComments.slice(1).join(" | "),
        referenceNo: splitComments[0] ?? "",
      };
    }

    return {
      comments: rawComments,
      referenceNo,
    };
  };
  const isEditMode = mode === "edit";
  const editDocNum = (docNum ?? "").trim();
  const queryClient = useQueryClient();
  const header = useAPCreditMemoHeader();
  const setHeader = useSetAPCreditMemoHeaderAction();
  const rows = useAPCreditMemoLines();
  const filteredRows = useMemo(() => rows.filter((r) => r.selected && r.quantity > 0), [rows]);
  const setLines = useSetAPCreditMemoLinesAction();
  const resetAPCreditMemoCreate = useResetAPCreditMemoCreateAction();
  const createMutation = useCreateAPCreditMemo();
  const updateMutation = useUpdateAPCreditMemo();
  const hydratedDocNumRef = useRef<string | null>(null);
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null);
  const lastRestrictedToastAtRef = useRef(0);
  const loadingToastRef = useRef<ReturnType<typeof pageLoadingToast> | null>(null);

  const [vendorNameInput, setVendorNameInput] = useState("");
  const [vendorCodeInput, setVendorCodeInput] = useState("");
  const [vendorNameFocused, setVendorNameFocused] = useState(false);
  const [vendorCodeFocused, setVendorCodeFocused] = useState(false);
  const [buyerInput, setBuyerInput] = useState("");
  const [buyerFocused, setBuyerFocused] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<PopupMode>("vendor-name");
  const [modalSearch, setModalSearch] = useState("");
  const [productPopupOpen, setProductPopupOpen] = useState(false);
  const [productSearch, setProductSearch] = useState("");
  const [debouncedProductSearch, setDebouncedProductSearch] = useState("");
  const [productQueryLimit, setProductQueryLimit] = useState(QUICK_PRODUCT_LIMIT);
  const [activeProductRowId, setActiveProductRowId] = useState<string | null>(null);
  const [warehouseInput, setWarehouseInput] = useState("");
  const [warehouseFocused, setWarehouseFocused] = useState(false);

  const [billToAddress, setBillToAddressRaw] = useState("");
  const [shipToAddress, setShipToAddressRaw] = useState("");

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value));
  }, []);
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value));
  }, []);

  const [productRowDrafts, setProductRowDrafts] = useState<Record<string, ProductRowDraft>>({});
  const [stockPreviewProduct, setStockPreviewProduct] = useState<StockPreviewProduct | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [fieldErrors, setFieldErrors] = useState<APCreditMemoFieldErrors>(
    EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS,
  );
  const [headerDiscountPercent, setHeaderDiscountPercent] = useState(0);

  const [pendingVendorChange, setPendingVendorChange] = useState<{
    vendor: LookupItem;
  } | null>(null);
  const hasCopiedRows = useMemo(
    () => rows.some((r) => r.baseEntry != null && r.baseType != null),
    [rows],
  );

  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);

  const warehouseErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!submitAttempted) return errors;

    filteredRows.forEach((row) => {
      if (!row.warehouseCode.trim()) {
        errors[row.id] = "Warehouse is required.";
      }
    });
    return errors;
  }, [submitAttempted, filteredRows]);

  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null);
  const docDateContainerRef = useRef<HTMLDivElement>(null);
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null);

  const notifyRestricted = (fieldName: string) => {
    const now = Date.now();
    if (now - lastRestrictedToastAtRef.current < 2500) {
      return;
    }
    lastRestrictedToastAtRef.current = now;
    goeyToast.error(`${fieldName} is locked for edit`, {
      id: "restricted-edit-toast",
    });
  };

  const vendorsQuery = useQuery(createSharedQueries.vendors());
  const warehousesQuery = useQuery(createSharedQueries.warehouses());
  const salesEmployeesQuery = useQuery(createSharedQueries.salesEmployees());
  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data]);
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data]);
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data]);
  const effectiveWarehouseCode = useMemo(() => {
    const lookup = warehouseInput.trim().toLowerCase();
    const match = lookup.match(/^\[(.*?)\]/);
    const codeOrName = match ? match[1]!.trim() : lookup;
    const matched = warehouses.find(
      (item) => item.name.toLowerCase() === codeOrName || item.code.toLowerCase() === codeOrName,
    );
    return matched?.code ?? lookup;
  }, [warehouseInput, warehouses]);

  const vendorSelected = Boolean(vendorCodeInput) || Boolean(vendorNameInput);
  const vendorLookupToken = `${vendorCodeInput.trim().toLowerCase()}::${vendorNameInput.trim().toLowerCase()}`;

  const productsQuery = useQuery({
    ...createSharedQueries.products(
      effectiveWarehouseCode || undefined,
      debouncedProductSearch.trim() || undefined,
      debouncedProductSearch.trim() ? undefined : productQueryLimit,
      "purchase",
    ),
    enabled: productPopupOpen && vendorSelected,
  });

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDebouncedProductSearch(productSearch.trim());
    }, 180);
    return () => window.clearTimeout(timer);
  }, [productSearch]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setProductQueryLimit(QUICK_PRODUCT_LIMIT);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [debouncedProductSearch, vendorSelected, productPopupOpen]);

  const prefetchProducts = useCallback(() => {
    if (!vendorSelected) {
      return;
    }
    void queryClient.prefetchQuery(
      createSharedQueries.products(
        effectiveWarehouseCode || undefined,
        productSearch.trim() || undefined,
        QUICK_PRODUCT_LIMIT,
        "purchase",
      ),
    );
  }, [vendorSelected, effectiveWarehouseCode, productSearch, queryClient]);

  useEffect(() => {
    if (!vendorSelected) {
      return;
    }
    prefetchProducts();
  }, [vendorLookupToken, vendorSelected, prefetchProducts]);

  const productWarehouseStocksQuery = useQuery({
    ...createSharedQueries.productWarehouseStocks(stockPreviewProduct?.code),
    enabled: Boolean(stockPreviewProduct?.code),
  });

  const editDetailQuery = useQuery({
    ...apCreditMemoQueries.detailByDocNum(editDocNum),
    enabled: isEditMode && Boolean(editDocNum),
  });

  const sourceInvoiceQuery = useQuery({
    ...apInvoiceQueries.detailByDocNum(sourceDocNum || ""),
    enabled: !isEditMode && !!sourceDocNum && sourceDocType === "APInvoice",
  });

  const sourceInvoiceData = sourceInvoiceQuery.data?.data as Record<string, unknown> | undefined;
  const isSourceClosed =
    sourceInvoiceData?.DocStatus === "Closed" || sourceInvoiceData?.DocStatus === "C";

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === "Closed" ||
    editDetailQuery.data?.data?.DocStatus === "C";
  const docStatus =
    editDetailQuery.data?.data?.DocStatus === "O"
      ? "Open"
      : editDetailQuery.data?.data?.DocStatus === "C"
        ? "Closed"
        : (editDetailQuery.data?.data?.DocStatus ?? "Open");

  useEffect(() => {
    if (header.warehouseCode && warehouses.length > 0) {
      const matched = warehouses.find(
        (w) => String(w.code).trim() === String(header.warehouseCode).trim(),
      );
      if (matched && warehouseInput !== `[${matched.code}] ${matched.name}`) {
        setWarehouseInput(`[${matched.code}] ${matched.name}`);
      }
    }
  }, [header.warehouseCode, warehouses, warehouseInput]);

  useEffect(() => {
    if (isEditMode) {
      return;
    }
    resetAPCreditMemoCreate();
    hydratedDocNumRef.current = null;
  }, [isEditMode, resetAPCreditMemoCreate]);

  useEffect(() => {
    if (!isEditMode) {
      return;
    }
    const currentDocNum = editDocNum;
    if (!currentDocNum) {
      return;
    }
    const detail = editDetailQuery.data?.data;
    if (!detail) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    if (hydratedDocNumRef.current === currentDocNum && isMetadataLoaded) {
      return;
    }

    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast("A/P Credit Memo", "edit");
    }

    void (async () => {
      setVendorCodeInput(String(detail.CardCode ?? "").trim());
      setVendorNameInput(String(detail.CardName ?? "").trim());
      const loadedDocDate = String(detail.DocDate ?? "").slice(0, 10) || getTodayISO();
      const { comments: remarks, referenceNo } = parseAPCreditMemoHeaderNotes(detail);

      const matchedVendor = vendors.find(
        (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? "").trim(),
      );
      const buyerFromDocCode =
        detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(detail.SalesPersonCode),
            )?.name
          : "";

      setBuyerInput(buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "");

      setHeader({
        docDate: loadedDocDate,
        docDueDate: loadedDocDate,
        referenceNo,
        remarks,
      });
      setBillToAddress(String(detail.Address ?? "").trim());
      setShipToAddress(String((detail as Record<string, unknown>).Address2 ?? "").trim());

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        (detail.DocumentLines ?? []).map((line: { ItemCode?: string }) =>
          String(line.ItemCode ?? "").trim(),
        ),
        "purchase",
      );
      const resolvedHeaderDiscountPercent = Number(
        (detail as Record<string, unknown>).DiscountPercent ?? 0,
      );
      setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

      const mappedLines = (detail.DocumentLines ?? []).map(
        (line: Record<string, unknown>, index: number) => {
          const quantity = Math.max(0, Number(line.Quantity ?? 0));
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line,
          });
          const itemCode = String(line.ItemCode ?? "").trim();

          return {
            baseEntry: typeof line.BaseEntry === "number" ? line.BaseEntry : undefined,
            baseLine: typeof line.BaseLine === "number" ? line.BaseLine : undefined,
            baseQuantity: quantity,
            baseType: typeof line.BaseType === "number" ? line.BaseType : undefined,
            comment: "",
            currency: String(detail.DocCurr ?? "").trim(),
            discountAmount,
            discountPercent,
            id: `${currentDocNum}-${index}`,
            price,
            productCode: String(line.ItemCode ?? "").trim(),
            productName: String(line.ItemDescription ?? line.ItemCode ?? "").trim(),
            quantity,
            returnReason: String((line as Record<string, unknown>).U_ReturnReason ?? "").trim(),
            selected: true,
            stock: 0,
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? "").trim(),
            uomEntry: typeof line.UoMEntry === "number" ? line.UoMEntry : undefined,
            vatGroup: String(line.TaxCode ?? "").trim(),
            warehouseCode: String(line.WarehouseCode ?? "").trim(),
          };
        },
      );
      setLines(mappedLines);
      setProductRowDrafts({});
      setWarehouseInput(String(detail.DocumentLines?.[0]?.WarehouseCode ?? "").trim());

      if (isMetadataLoaded) {
        hydratedDocNumRef.current = currentDocNum;
      }
      setHydratedDocNum(currentDocNum);
      loadingToastRef.current?.dismiss();
      loadingToastRef.current = null;
    })();
  }, [
    editDocNum,
    editDetailQuery.data,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
  ]);

  useEffect(() => {
    if (mode !== "create") {
      return;
    }
    const currentSourceDocNum = sourceDocNum;
    const currentSourceDocType = sourceDocType;
    if (!currentSourceDocNum || !currentSourceDocType) {
      return;
    }

    const sourceDocNums = currentSourceDocNum
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    if (sourceDocNums.length === 0) {
      return;
    }

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0;
    const hydrationKey = `${currentSourceDocType}-${currentSourceDocNum}`;
    if (hydratedDocNumRef.current === hydrationKey && isMetadataLoaded) {
      return;
    }

    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast("A/P Credit Memo", "create");
    }

    const fetchAllSources = async () => {
      interface APInvoiceDetailType {
        CardCode?: string;
        CardName?: string;
        Comments?: string;
        DocCurr?: string;
        DocDueDate?: string;
        DocEntry?: number;
        id?: number;
        SalesPersonCode?: number;
        Address?: string;
        Address2?: string;
        DocumentLines?: Record<string, unknown>[];
      }

      const details = await Promise.all(
        sourceDocNums.map(async (num) => {
          const res = await queryClient.fetchQuery(apInvoiceQueries.detailByDocNum(num));
          return res.data as APInvoiceDetailType;
        }),
      );

      const primaryDetail = details[0]!;
      const vendorCode = String(primaryDetail.CardCode ?? "").trim();
      const vendorName = String(primaryDetail.CardName ?? "").trim();
      const matchedVendor = vendors.find((v) => String(v.code).trim() === vendorCode);

      const buyerFromDocCode =
        primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(primaryDetail.SalesPersonCode),
            )?.name
          : "";
      const buyerName = buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || "";

      const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? "").trim();
      const sourceComments = String(primaryDetail.Comments ?? "").trim();

      const refs = sourceDocNums.map((num) =>
        generateSingleSourceReference(currentSourceDocType, num),
      );
      const autoReference = refs.length === 1 ? refs[0]! : refs.join("\n");

      const commentLines = sourceComments
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean);
      const refLinesFromComments = commentLines.filter((line) => /^based on /i.test(line));

      const userRemarks = commentLines
        .filter((line) => !/^based on /i.test(line))
        .join("\n")
        .trim();
      const remarksParts = [refLinesFromComments.join("\n"), autoReference, userRemarks]
        .filter(Boolean)
        .join("\n")
        .trim();

      const docDueDate = String(primaryDetail.DocDueDate ?? "").slice(0, 10);

      const allDetailLines = details.flatMap(
        (d) => (d.DocumentLines ?? []) as { ItemCode?: string }[],
      );

      const baseType = 18; // AP Invoice BaseType

      const currency = String(primaryDetail.DocCurr ?? "").trim();

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        allDetailLines.map((line) => String(line.ItemCode ?? "").trim()),
        "purchase",
      );
      const resolvedHeaderDiscountPercent = Number(
        (primaryDetail as Record<string, unknown>).DiscountPercent ?? 0,
      );
      setHeaderDiscountPercent(resolvedHeaderDiscountPercent);

      let lineIndex = 0;
      const mappedLines = details.flatMap((detail) => {
        const detailLines = (detail.DocumentLines ?? []) as Record<string, unknown>[];
        return detailLines.map((line) => {
          const idx = lineIndex++;
          const lineData = line as Record<string, unknown>;
          const openQty = Number(lineData.OpenQty ?? lineData.OpenQuantity ?? line.Quantity ?? 1);
          const quantity = openQty;
          const price = Number(line.Price ?? line.UnitPrice ?? 0);
          const grossAmount = Math.max(0, price * quantity);
          const { discountPercent, discountAmount } = resolveDocumentLineDiscount({
            grossAmount,
            headerDiscountPercent: resolvedHeaderDiscountPercent,
            line,
          });
          const itemCode = String(line.ItemCode ?? "").trim();

          return {
            baseEntry: detail.DocEntry ?? (detail as { id?: number }).id ?? undefined,
            baseLine: (line.LineNum as number | undefined) ?? idx,
            baseQuantity: quantity,
            baseType,
            comment: "",
            currency,
            discountAmount,
            discountPercent,
            id: `row-copy-${detail.DocEntry ?? detail.id ?? "unknown"}-${idx}`,
            price,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? line.ItemCode ?? "").trim(),
            quantity,
            returnReason: String((line as Record<string, unknown>).U_ReturnReason ?? "").trim(),
            selected: false,
            stock: 0,
            taxRate:
              (typeof line.VatPrcnt === "number" ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? "").trim(),
            uomEntry: typeof line.UoMEntry === "number" ? (line.UoMEntry as number) : undefined,
            vatGroup: String(line.TaxCode ?? "").trim(),
            warehouseCode: String(line.WarehouseCode ?? warehouseCode).trim(),
          };
        });
      });

      const sourceNumAtCard = String(
        (primaryDetail as { NumAtCard?: string }).NumAtCard ?? "",
      ).trim();
      setVendorCodeInput(vendorCode);
      setVendorNameInput(vendorName);
      setBuyerInput(buyerName);
      setWarehouseInput(warehouseCode);
      setBillToAddress(String(primaryDetail.Address ?? "").trim());
      setShipToAddress(String(primaryDetail.Address2 ?? "").trim());
      setHeader({
        docDate: getTodayISO(),
        docDueDate,
        referenceAutoFilled: true,
        referenceNo: sourceNumAtCard,
        remarks: remarksParts,
      });
      setLines(mappedLines);
      setProductRowDrafts({});
      if (isMetadataLoaded) {
        hydratedDocNumRef.current = hydrationKey;
      }
      loadingToastRef.current?.dismiss();
      loadingToastRef.current = null;
    };

    void fetchAllSources();
  }, [
    mode,
    sourceDocNum,
    sourceDocType,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setVendorCodeInput,
    setVendorNameInput,
    setBuyerInput,
    setWarehouseInput,
    setBillToAddress,
    setShipToAddress,
    setProductRowDrafts,
    vendors,
  ]);

  const { vendorNameSuggestions, vendorCodeSuggestions, warehouseSuggestions, buyerSuggestions } =
    useAPCreditMemoLookups({
      buyerInput,
      buyers: salesEmployees,
      vendorCodeInput,
      vendorNameInput,
      vendors,
      warehouseInput,
      warehouses,
    });

  const openPopupByMode = (mode: PopupMode) => {
    const searchVal =
      mode === "vendor-name" || mode === "vendor-code"
        ? mode === "vendor-name"
          ? vendorNameInput
          : vendorCodeInput
        : mode === "warehouse"
          ? warehouseInput
          : buyerInput;

    setModalMode(mode);
    setModalSearch(searchVal);
    setModalOpen(true);
  };

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onSalesEmployee: handleBuyerChange,
      onVendorCode: handleVendorCodeChange,
      onVendorName: handleVendorNameChange,
      onWarehouse: handleWarehouseInputChange,
    });

  useEffect(() => {
    if (!modalOpen) {
      return;
    }
    const nextSearch = getLookupInlineSearchByMode(modalMode, {
      salesEmployee: buyerInput,
      vendorCode: vendorCodeInput,
      vendorName: vendorNameInput,
      warehouse: warehouseInput,
    });
    if (nextSearch !== modalSearch) {
      setModalSearch(nextSearch);
    }
  }, [
    buyerInput,
    modalMode,
    modalOpen,
    modalSearch,
    setModalSearch,
    vendorCodeInput,
    vendorNameInput,
    warehouseInput,
  ]);

  const selectVendor = (vendor: LookupItem) => {
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor });
      return;
    }
    applyVendorChange(vendor);
  };

  const applyVendorChange = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);

    setWarehouseInput("");
    setLines([]);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
    setVendorNameFocused(false);
    setVendorCodeFocused(false);
  };

  const handleVendorNameChange = (value: string) => {
    setVendorNameInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined }));
    if (value.trim() === "") {
      setVendorNameFocused(true);
      setVendorCodeInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.name.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      setVendorCodeInput(matched.code);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorCodeInput("");
    setBuyerInput("");
    setLines([]);
    setVendorNameFocused(true);
  };

  const handleVendorCodeChange = (value: string) => {
    setVendorCodeInput(value);
    setFieldErrors((prev) => ({ ...prev, vendorCode: undefined }));
    if (value.trim() === "") {
      setVendorCodeFocused(true);
      setVendorNameInput("");
      setBuyerInput("");
      setBillToAddress("");
      setShipToAddress("");
      return;
    }
    const matched = vendors.find((v) => v.code.trim().toLowerCase() === value.trim().toLowerCase());
    if (matched) {
      if (hasCopiedRows) {
        setPendingVendorChange({ vendor: matched });
        return;
      }
      setVendorNameInput(matched.name);
      setBillToAddress(matched.billToAddress ?? "");
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? "");

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ""
          : "");
      setBuyerInput(buyerName);
      setVendorNameFocused(false);
      setVendorCodeFocused(false);
      return;
    }
    if (hasCopiedRows) {
      return;
    }
    setVendorNameInput("");
    setBuyerInput("");
    setLines([]);
    setVendorCodeFocused(true);
  };

  const confirmVendorChange = () => {
    const pending = pendingVendorChange;
    if (!pending) {
      return;
    }
    setPendingVendorChange(null);

    const cleanedRemarks = stripAutoGeneratedReferences(header.remarks);
    setHeader({ remarks: cleanedRemarks });

    setLines((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row;
        return rest;
      }),
    );

    applyVendorChangeForConfirmation(pending.vendor);
  };

  const cancelVendorChange = () => {
    setPendingVendorChange(null);
  };

  const applyVendorChangeForConfirmation = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name);
    setVendorCodeInput(vendor.code);
    setBillToAddress(vendor.billToAddress ?? "");
    setShipToAddress(vendor.shipToAddress ?? "");
    setVendorNameFocused(false);
    setVendorCodeFocused(false);

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ""
        : "");
    setBuyerInput(buyerName);
    setCreateError(null);
    setFieldErrors((prev) => ({
      ...prev,
      vendorCode: undefined,
      vendorName: undefined,
    }));
  };

  const handleWarehouseInputChange = (value: string) => {
    setWarehouseInput(value);
    if (value.trim() === "") {
      setWarehouseFocused(true);
      setHeader({ warehouseCode: "" });
      return;
    }
    const matched = warehouses.find(
      (w) =>
        w.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        w.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      selectWarehouse(matched);
      return;
    }
    setHeader({ warehouseCode: "" });
  };

  const handleBuyerChange = (value: string) => {
    setBuyerInput(value);
    const matched = salesEmployees.find(
      (s) =>
        s.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        s.code.trim().toLowerCase() === value.trim().toLowerCase(),
    );
    if (matched) {
      setBuyerFocused(false);
    }
  };

  const openProductPopup = (rowId: string | null = null) => {
    setActiveProductRowId(rowId);
    if (!vendorNameInput.trim() || !vendorCodeInput.trim()) {
      setFieldErrors((prev) => ({
        ...prev,
        vendorCode: !vendorCodeInput.trim()
          ? AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorCode
          : undefined,
        vendorName: !vendorNameInput.trim()
          ? AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorName
          : undefined,
      }));
      return;
    }

    setProductPopupOpen(true);
  };

  const selectWarehouse = (warehouse: LookupItem) => {
    setWarehouseInput(`[${warehouse.code}] ${warehouse.name}`);
    setHeader({ warehouseCode: warehouse.code });
    setLines((prev) => prev.map((row) => ({ ...row, warehouseCode: warehouse.code })));
    setWarehouseFocused(false);
  };

  const selectBuyer = (item: LookupItem) => {
    setBuyerInput(item.name);
    setBuyerFocused(false);
  };

  const applyProductToRow = (product: ProductLookupItem) => {
    setLines((prev) => {
      if (activeProductRowId) {
        return prev.map((row) =>
          row.id === activeProductRowId
            ? {
                ...row,
                price: Number(product.price ?? 0),
                productCode: product.code,
                productName: product.name,
                quantity: 1,
                stock: Number(product.stock ?? 0),
                uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
                uomEntry: product.purchaseUomEntry ?? product.uomEntry,
                warehouseCode: effectiveWarehouseCode || "",
              }
            : row,
        );
      }
      return [
        ...prev,
        {
          comment: "",
          currency: String(product.currency ?? ""),
          discountAmount: 0,
          discountPercent: 0,
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          price: Number(product.price ?? 0),
          productCode: product.code,
          productName: product.name,
          quantity: 1,
          selected: false,
          stock: Number(product.stock ?? 0),
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          vatGroup: String(product.vatGroup ?? ""),
          warehouseCode: effectiveWarehouseCode || "",
        },
      ];
    });
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const applyProductsToRows = (products: ProductLookupItem[]) => {
    setLines((prev) => [
      ...prev,
      ...products.map((product) => ({
        comment: "",
        currency: String(product.currency ?? ""),
        discountAmount: 0,
        discountPercent: 0,
        id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        price: Number(product.price ?? 0),
        productCode: product.code,
        productName: product.name,
        quantity: 1,
        selected: false,
        stock: Number(product.stock ?? 0),
        taxRate: Number(product.taxRate ?? 0),
        uomCode: String(product.purchaseUomCode ?? product.uomCode ?? "").trim(),
        uomEntry: product.purchaseUomEntry ?? product.uomEntry,
        vatGroup: String(product.vatGroup ?? ""),
        warehouseCode: effectiveWarehouseCode || "",
      })),
    ]);
    setProductPopupOpen(false);
    setProductSearch("");
  };

  const handleCreateAPCreditMemo = async () => {
    setSubmitAttempted(true);

    if (!isEditMode) {
      const missing = AP_CREDIT_MEMO_MANDATORY_FIELDS.filter((field) => {
        if (field === "vendorName") {
          return !vendorNameInput.trim();
        }
        if (field === "vendorCode") {
          return !vendorCodeInput.trim();
        }
        if (field === "returnReason") {
          return false;
        }
        return false;
      });

      if (missing.length > 0) {
        const nextErrors = { ...EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS };
        missing.forEach((field) => {
          nextErrors[field] = AP_CREDIT_MEMO_FIELD_ERROR_TEXT[field];
        });
        setFieldErrors(nextErrors);
        setCreateError("Fill required fields before creating A/P Credit Memo.");
        return;
      }
    }

    if (filteredRows.length === 0) {
      setCreateError("Select at least one row and set a quantity greater than 0.");
      return;
    }

    const toastHandle = documentActionToast("A/P Credit Memo", isEditMode ? "update" : "create");
    try {
      if (isEditMode) {
        const detail = editDetailQuery.data?.data;
        const existingDocDueDate = String(detail?.DocDueDate ?? "")
          .slice(0, 10)
          .trim();
        const { comments: existingComments, referenceNo: existingReferenceNo } = detail
          ? parseAPCreditMemoHeaderNotes(detail)
          : { comments: "", referenceNo: "" };
        const currentDocDueDate = String(header.docDueDate ?? "").trim();
        const currentComments = String(header.remarks ?? "").trim();
        const currentReferenceNo = String(header.referenceNo ?? "").trim();

        if (
          currentDocDueDate === existingDocDueDate &&
          currentComments === existingComments.trim() &&
          currentReferenceNo === existingReferenceNo
        ) {
          const noChangeMessage = "Change at least one field before update.";
          setCreateError(noChangeMessage);
          goeyToast.error(noChangeMessage, { id: "no-change-update-toast" });
          return;
        }

        const id = editDetailQuery.data?.data?.id ?? editDetailQuery.data?.data?.DocEntry;
        const updatePayload: UpdateAPCreditMemoInput = {
          Comments: header.remarks.trim() || undefined,
          DocDueDate: header.docDueDate || undefined,
          NumAtCard: header.referenceNo.trim() || undefined,
        };

        await updateMutation.mutateAsync({ id: id!, payload: updatePayload });

        toastHandle.success(editDetailQuery.data?.data?.DocNum);
      } else {
        const buildDocumentLines = (): CreateAPCreditMemoInput["DocumentLines"] => {
          const lines: CreateAPCreditMemoInput["DocumentLines"] = [];
          for (const row of filteredRows) {
            if (row.quantity <= 0) {
              continue;
            }

            const hasCompleteBaseLink =
              Number.isFinite(row.baseEntry) &&
              Number.isFinite(row.baseLine) &&
              Number.isFinite(row.baseType);

            const baseLine: CreateAPCreditMemoInput["DocumentLines"][0] = {
              DiscountPercent: row.discountPercent,
              ItemCode: row.productCode,
              Quantity: row.quantity,
              UnitPrice: row.price,
              ...(row.uomCode ? { UoMCode: row.uomCode } : {}),
              ...(row.warehouseCode ? { WarehouseCode: row.warehouseCode } : {}),
              ...(row.vatGroup ? { VatGroup: row.vatGroup } : {}),
              ...(row.returnReason ? { U_ReturnReason: row.returnReason } : {}),
            };

            if (!hasCompleteBaseLink) {
              lines.push(baseLine);
              continue;
            }

            const baseQty = row.baseQuantity ?? 0;
            const linkedQty = Math.min(row.quantity, baseQty);

            if (linkedQty > 0) {
              lines.push({
                ...baseLine,
                Quantity: linkedQty,
                ...(row.baseType !== undefined ? { BaseType: row.baseType } : {}),
                ...(row.baseEntry !== undefined ? { BaseEntry: row.baseEntry } : {}),
                ...(row.baseLine !== undefined ? { BaseLine: row.baseLine } : {}),
              });
            }

            const excessQty = row.quantity - baseQty;
            if (excessQty > 0) {
              lines.push({
                ...baseLine,
                Quantity: excessQty,
              });
            }
          }
          return lines;
        };

        const createPayload: CreateAPCreditMemoInput = {
          CardCode: vendorCodeInput.trim(),
          ...(header.docDate ? { DocDate: header.docDate } : {}),
          ...(header.docDueDate ? { DocDueDate: header.docDueDate } : {}),
          ...(header.remarks.trim() ? { Comments: header.remarks.trim() } : {}),
          ...(header.referenceNo.trim() ? { NumAtCard: header.referenceNo.trim() } : {}),
          DocumentLines: buildDocumentLines(),
        };

        // Try to reopen the base A/P Invoice if it's closed, as requested.
        // We catch and swallow the error if SAP doesn't support reopening this specific invoice,
        // so we can still attempt to create the linked Credit Memo!
        if (isSourceClosed) {
          try {
            const entry = Number(sourceInvoiceData?.DocEntry ?? sourceInvoiceData?.id);
            if (entry) {
              await apInvoiceAPI.reopenAPInvoice(entry);
            }
          } catch (err) {
            console.warn(
              `SAP Reopen failed (continuing to Credit Memo creation): ${(err as Error).message}`,
            );
          }
        }

        const result = await createMutation.mutateAsync({
          payload: createPayload,
        });
        const createdDocNum = result?.data?.DocNum;

        if (sourceDocNum && sourceDocType) {
          void queryClient.invalidateQueries({
            queryKey: apInvoiceQueries.list({ limit: 10, page: 1 }).queryKey,
          });

          if (sourceDocType === "APInvoice") {
            sourceDocNum.split(",").forEach((num) => {
              const trimmed = num.trim();
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: apInvoiceQueries.detailByDocNum(trimmed).queryKey,
                });
              }
            });
          }
        }

        toastHandle.success(createdDocNum);
      }

      if (!isEditMode) {
        resetAPCreditMemoCreate();
        setVendorNameInput("");
        setVendorCodeInput("");
        setBuyerInput("");
        setWarehouseInput("");
        setBillToAddress("");
        setShipToAddress("");
        setVendorNameFocused(false);
        setVendorCodeFocused(false);
        setBuyerFocused(false);
        setWarehouseFocused(false);
        setActiveDatePicker(null);
        setModalOpen(false);
        setModalMode("vendor-name");
        setModalSearch("");
        setProductSearch("");
        setDebouncedProductSearch("");
        setActiveProductRowId(null);
        setProductPopupOpen(false);
        setProductRowDrafts({});
        setStockPreviewProduct(null);
        setFieldErrors(EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS);
        setCreateError(null);
        hydratedDocNumRef.current = null;
        setHydratedDocNum(null);
      }

      setSubmitAttempted(false);
      window.scrollTo({ behavior: "smooth", top: 0 });

      if (!isEditMode) {
        onCreateSuccess?.();
      }
    } catch (error) {
      toastHandle.error();
      const errorMsg = normalizeCreateOrderErrorMessage(
        error,
        "Failed to process A/P Credit Memo.",
      );
      setCreateError(errorMsg);
    }
  };

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) {
      return [];
    }
    return AP_CREDIT_MEMO_MANDATORY_FIELDS.filter((field) => {
      if (field === "vendorName") {
        return !vendorNameInput.trim();
      }
      if (field === "vendorCode") {
        return !vendorCodeInput.trim();
      }
      if (field === "returnReason") {
        return false;
      }
      return false;
    });
  }, [isEditMode, vendorNameInput, vendorCodeInput, rows]);

  const requiredCompletionPercent = useMemo(
    () =>
      ((AP_CREDIT_MEMO_MANDATORY_FIELDS.length - missingMandatoryFields.length) /
        AP_CREDIT_MEMO_MANDATORY_FIELDS.length) *
      100,
    [missingMandatoryFields],
  );

  return {
    activeDatePicker,
    activeProductRowId,
    activeRowProductCode: (() => {
      if (!activeProductRowId) {
        return null;
      }
      const activeRow = rows.find((r) => r.id === activeProductRowId);
      return activeRow?.productCode ?? null;
    })(),
    applyProductToRow,
    applyProductsToRows,
    isSourceClosed,
    billToAddress,
    buyerFocused,
    buyerInput,
    buyerSuggestions,
    cancelVendorChange,
    clearProductRowDraft: (id: string, field: string) =>
      setProductRowDrafts((prev) => {
        const next = { ...prev[id] };
        delete next[field as keyof typeof next];
        return { ...prev, [id]: next };
      }),
    confirmVendorChange,
    createDisabledReason:
      missingMandatoryFields.length > 0
        ? "Mandatory fields missing"
        : rows.length === 0
          ? "No lines"
          : null,
    createError,
    createMutation,
    deliveryDateContainerRef,
    docDate: header.docDate,
    docDateContainerRef,
    docDueDate: header.docDueDate,
    docStatus,
    editDetailQuery,
    fieldErrors,
    handleCreateOrder: handleCreateAPCreditMemo,
    handleDocDateChange: (val: string) => setHeader({ docDate: val }),
    handleDocDueDateChange: (val: string) => setHeader({ docDueDate: val }),
    handleLookupModalSearchSync,
    handleVendorCodeChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Code") : handleVendorCodeChange(val),
    handleVendorNameChange: (val: string) =>
      isEditMode ? notifyRestricted("Vendor Name") : handleVendorNameChange(val),
    hasCopiedRows,
    isClosed,
    isEditHydrated: !isEditMode || hydratedDocNum === editDocNum,
    isEditMode,
    isLookupLoading: modalMode.includes("vendor")
      ? vendorsQuery.isLoading
      : modalMode === "warehouse"
        ? warehousesQuery.isLoading
        : salesEmployeesQuery.isLoading,
    isProductsLoading: productsQuery.isLoading,
    isSourceHydrating: mode === "create" && Boolean(sourceDocNum) && !hydratedDocNumRef.current,
    loadMoreProducts: () => {
      if (!productPopupOpen) {
        return;
      }
      if (productsQuery.isFetching) {
        return;
      }
      const currentCount = productsQuery.data?.length ?? 0;
      if (currentCount < productQueryLimit) {
        return;
      }
      if (debouncedProductSearch.trim().length > 0) {
        return;
      }
      if (productQueryLimit >= 50) {
        return;
      }
      setProductQueryLimit((prev) => Math.min(prev + 10, 50));
    },
    lookupError:
      (modalMode.includes("vendor")
        ? vendorsQuery.error
        : modalMode === "warehouse"
          ? warehousesQuery.error
          : salesEmployeesQuery.error
      )?.message ?? null,
    missingMandatoryFields,
    missingSearchMandatoryFields: useMemo(
      () =>
        ["vendorName", "vendorCode"].filter(
          (field) =>
            !String(field === "vendorName" ? vendorNameInput : (vendorCodeInput ?? "")).trim(),
        ),
      [vendorNameInput, vendorCodeInput],
    ),
    modalMode,
    modalOpen,
    modalSearch,
    openPopup: openPopupByMode,
    openProductPopup,
    openStockPreview: setStockPreviewProduct,
    pendingVendorChange,
    popupResults: useMemo(
      () =>
        filterAndRankLookups(
          modalMode.includes("vendor")
            ? vendors
            : modalMode === "warehouse"
              ? warehouses
              : salesEmployees,
          modalSearch,
        ),
      [vendors, warehouses, salesEmployees, modalSearch, modalMode],
    ),
    prefetchProducts: isEditMode ? () => {} : prefetchProducts,
    productPopupOpen,
    productRowDrafts,
    productSearch,
    productWarehouseStocksQuery,
    products: productsQuery.data ?? [],
    productsError: productsQuery.error?.message ?? null,
    productsQuery,
    headerDiscountPercent,
    referenceAutoFilled: header.referenceAutoFilled,
    referenceNo: header.referenceNo,
    remarks: header.remarks,
    removeProductRow: (id: string) => setLines((prev) => prev.filter((r) => r.id !== id)),
    requiredCompletionPercent,
    requiredFieldLabelText: AP_CREDIT_MEMO_FIELD_LABEL_TEXT,
    requiredFieldsTotal: AP_CREDIT_MEMO_MANDATORY_FIELDS.length,
    rows,
    submitAttempted,
    warehouseErrors,
    salesEmployees,
    salesEmployeesQuery,
    searchMandatoryFields: useMemo(() => ["vendorName", "vendorCode"] as const, []),
    searchRequiredCompletionPercent: useMemo(() => {
      const filled = (vendorNameInput.trim() ? 1 : 0) + (vendorCodeInput.trim() ? 1 : 0);
      return (filled / 2) * 100;
    }, [vendorNameInput, vendorCodeInput]),
    selectSalesEmployee: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Sales Employee") : selectBuyer(val),
    selectVendor: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Vendor") : selectVendor(val),
    selectWarehouse: (val: LookupItem) =>
      isEditMode ? notifyRestricted("Warehouse") : selectWarehouse(val),
    setActiveDatePicker,
    setBillToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Bill To Address") : setBillToAddress(val),
    setBuyerFocused,
    setBuyerInput: (val: string) =>
      isEditMode ? notifyRestricted("Buyer") : handleBuyerChange(val),
    setDocDate: (val: string) => setHeader({ docDate: val }),
    setDocDueDate: (val: string) => setHeader({ docDueDate: val }),
    setModalOpen,
    setModalSearch,
    setProductPopupOpen,
    setProductRowDraft: (id: string, field: string, value: string) =>
      setProductRowDrafts((prev) => ({
        ...prev,
        [id]: { ...prev[id], [field]: value },
      })),
    setProductSearch,
    setReferenceNo: (val: string) => setHeader({ referenceNo: val }),
    setRemarks: (val: string) => setHeader({ remarks: val }),
    setShipToAddress: (val: string) =>
      isEditMode ? notifyRestricted("Ship To Address") : setShipToAddress(val),
    setStockPreviewProduct,
    setVendorCodeFocused,
    setVendorNameFocused,
    setWarehouseFocused,
    setWarehouseInput: (val: string) =>
      isEditMode ? notifyRestricted("Warehouse") : handleWarehouseInputChange(val),
    shipToAddress,
    showEditRestrictedToast: notifyRestricted,
    stockPreviewProduct,
    today,
    updateMutation,
    updateProductRow: (id: string, patch: Partial<APCreditMemoCreateLine>) =>
      setLines((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r))),
    vendorCodeFocused,
    vendorCodeInput,
    vendorCodeSuggestions,
    vendorNameFocused,
    vendorNameInput,
    vendorNameSuggestions,
    vendors,
    vendorsQuery,
    warehouseCode: effectiveWarehouseCode,
    warehouseFocused,
    warehouseInput,
    warehouseSuggestions,
    warehouses,
    warehousesQuery,
  };
}
