import { useQuery, useQueryClient } from '@tanstack/react-query'
import { goeyToast } from 'goey-toast'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import {
  type CreateAPCreditMemoInput,
  type UpdateAPCreditMemoInput,
  useCreateAPCreditMemo,
  useUpdateAPCreditMemo,
} from '@/features/create-pages/ap-credit-memo-create/api/ap-credit-memo-create.mutations'
import { useAPCreditMemoLookups } from '@/features/create-pages/ap-credit-memo-create/hooks/use-ap-credit-memo-lookups'
import {
  useAPCreditMemoHeader,
  useAPCreditMemoLines,
  useResetAPCreditMemoCreateAction,
  useSetAPCreditMemoHeaderAction,
  useSetAPCreditMemoLinesAction,
} from '@/features/create-pages/ap-credit-memo-create/store/ap-credit-memo-create.store'
import {
  AP_CREDIT_MEMO_FIELD_ERROR_TEXT,
  AP_CREDIT_MEMO_FIELD_LABEL_TEXT,
  AP_CREDIT_MEMO_MANDATORY_FIELDS,
  type APCreditMemoMandatoryField,
  filterAndRankLookups,
  getTodayISO,
} from '@/features/create-pages/ap-credit-memo-create/utils/ap-credit-memo-create.utils'
import { createSharedQueries } from '@/features/create-pages/create-shared/api/create-shared.queries'
import {
  type LookupItem,
  type ProductLookupItem,
} from '@/features/create-pages/create-shared/api/create-shared.types'
import { formatAddressForDisplay } from '@/features/create-pages/create-shared/utils/address.utils'
import {
  type ActiveDatePicker,
  type PopupMode,
  type ProductRowDraft,
  type StockPreviewProduct,
} from '@/features/create-pages/create-shared/utils/create-order.types'
import { normalizeCreateOrderErrorMessage } from '@/features/create-pages/create-shared/utils/create-order.utils'
import { documentActionToast } from '@/features/create-pages/create-shared/utils/document-action-toast'
import {
  getLookupInlineSearchByMode,
  syncLookupSearchByMode,
} from '@/features/create-pages/create-shared/utils/lookup-search-sync'
import { pageLoadingToast } from '@/features/create-pages/create-shared/utils/page-loading-toast'
import { resolveProductTaxRates } from '@/features/create-pages/create-shared/utils/product-tax-rate'
import { apCreditMemoQueries } from '@/features/table-pages/ap-credit-memo/api/ap-credit-memo.queries'
import { apInvoiceQueries } from '@/features/table-pages/ap-invoices/api/ap-invoice.queries'

import {
  generateSingleSourceReference,
  stripAutoGeneratedReferences,
} from '../../create-shared/utils/auto-reference'

export type APCreditMemoCreateLine = {
  id: string
  productCode: string
  productName: string
  stock: number
  currency: string
  vatGroup: string
  taxRate: number
  uomCode?: string | undefined
  uomEntry?: number | undefined
  baseQuantity?: number | undefined
  quantity: number
  discountPercent: number
  discountAmount: number
  comment: string
  returnReason?: string | undefined
  price: number
  warehouseCode: string
  baseLine?: number | undefined
  baseEntry?: number | undefined
  baseType?: number | undefined
}
type APCreditMemoFieldErrors = Record<APCreditMemoMandatoryField, string | undefined>
const QUICK_PRODUCT_LIMIT = 10
const FULL_PRODUCT_LIMIT = 100

const EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS: APCreditMemoFieldErrors = {
  vendorName: undefined,
  vendorCode: undefined,
  warehouseCode: undefined,
  returnReason: undefined,
}

interface UseAPCreditMemoCreateOptions {
  mode?: 'create' | 'edit'
  docNum?: string
  sourceDocNum?: string | undefined
  sourceDocType?: 'APInvoice' | undefined
  onCreateSuccess?: () => void
}

const normalizeCodeForCompare = (value: unknown) => {
  const raw = String(value ?? '').trim()
  if (!raw) return ''
  const parsed = Number(raw)
  return Number.isFinite(parsed) ? String(Math.trunc(parsed)) : raw.toLowerCase()
}

export function useAPCreditMemoCreate({
  mode = 'create',
  docNum,
  sourceDocNum,
  sourceDocType,
  onCreateSuccess,
}: UseAPCreditMemoCreateOptions) {
  const isEditMode = mode === 'edit'
  const editDocNum = (docNum ?? '').trim()
  const queryClient = useQueryClient()
  const header = useAPCreditMemoHeader()
  const setHeader = useSetAPCreditMemoHeaderAction()
  const rows = useAPCreditMemoLines()
  const setLines = useSetAPCreditMemoLinesAction()
  const resetAPCreditMemoCreate = useResetAPCreditMemoCreateAction()
  const createMutation = useCreateAPCreditMemo()
  const updateMutation = useUpdateAPCreditMemo()
  const hydratedDocNumRef = useRef<string | null>(null)
  const [hydratedDocNum, setHydratedDocNum] = useState<string | null>(null)
  const lastRestrictedToastAtRef = useRef(0)
  const loadingToastRef = useRef<ReturnType<typeof pageLoadingToast> | null>(null)

  const [vendorNameInput, setVendorNameInput] = useState('')
  const [vendorCodeInput, setVendorCodeInput] = useState('')
  const [vendorNameFocused, setVendorNameFocused] = useState(false)
  const [vendorCodeFocused, setVendorCodeFocused] = useState(false)
  const [buyerInput, setBuyerInput] = useState('')
  const [buyerFocused, setBuyerFocused] = useState(false)
  const [modalOpen, setModalOpen] = useState(false)
  const [modalMode, setModalMode] = useState<PopupMode>('vendor-name')
  const [modalSearch, setModalSearch] = useState('')
  const [productPopupOpen, setProductPopupOpen] = useState(false)
  const [productSearch, setProductSearch] = useState('')
  const [debouncedProductSearch, setDebouncedProductSearch] = useState('')
  const [productQueryLimit, setProductQueryLimit] = useState(QUICK_PRODUCT_LIMIT)
  const [activeProductRowId, setActiveProductRowId] = useState<string | null>(null)
  const [warehouseInput, setWarehouseInput] = useState('')
  const [warehouseFocused, setWarehouseFocused] = useState(false)

  const [billToAddress, setBillToAddressRaw] = useState('')
  const [shipToAddress, setShipToAddressRaw] = useState('')

  const setBillToAddress = useCallback((value: string) => {
    setBillToAddressRaw(formatAddressForDisplay(value))
  }, [])
  const setShipToAddress = useCallback((value: string) => {
    setShipToAddressRaw(formatAddressForDisplay(value))
  }, [])

  const [productRowDrafts, setProductRowDrafts] = useState<Record<string, ProductRowDraft>>({})
  const [stockPreviewProduct, setStockPreviewProduct] = useState<StockPreviewProduct | null>(null)
  const [createError, setCreateError] = useState<string | null>(null)
  const [fieldErrors, setFieldErrors] = useState<APCreditMemoFieldErrors>(
    EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS,
  )

  const [pendingVendorChange, setPendingVendorChange] = useState<{
    vendor: LookupItem
  } | null>(null)
  const hasCopiedRows = useMemo(
    () => rows.some((r) => r.baseEntry != null && r.baseType != null),
    [rows],
  )

  const today = useMemo(() => {
    const now = new Date()
    return new Date(now.getFullYear(), now.getMonth(), now.getDate())
  }, [])
  const [activeDatePicker, setActiveDatePicker] = useState<ActiveDatePicker>(null)
  const docDateContainerRef = useRef<HTMLDivElement>(null)
  const deliveryDateContainerRef = useRef<HTMLDivElement>(null)

  const notifyRestricted = (fieldName: string) => {
    const now = Date.now()
    if (now - lastRestrictedToastAtRef.current < 2500) return
    lastRestrictedToastAtRef.current = now
    goeyToast.error(`${fieldName} is locked for edit`, {
      id: 'restricted-edit-toast',
    })
  }

  const vendorsQuery = useQuery(createSharedQueries.vendors())
  const warehousesQuery = useQuery(createSharedQueries.warehouses())
  const salesEmployeesQuery = useQuery(createSharedQueries.salesEmployees())
  const vendors = useMemo(() => vendorsQuery.data ?? [], [vendorsQuery.data])
  const warehouses = useMemo(() => warehousesQuery.data ?? [], [warehousesQuery.data])
  const salesEmployees = useMemo(() => salesEmployeesQuery.data ?? [], [salesEmployeesQuery.data])
  const effectiveWarehouseCode = useMemo(() => {
    const normalized = warehouseInput.trim().toLowerCase()
    const matched = warehouses.find(
      (item) => item.name.toLowerCase() === normalized || item.code.toLowerCase() === normalized,
    )
    return matched?.code ?? warehouseInput.trim()
  }, [warehouseInput, warehouses])

  const vendorSelected = Boolean(vendorCodeInput) || Boolean(vendorNameInput)

  const productsQuery = useQuery({
    ...createSharedQueries.products(
      effectiveWarehouseCode || undefined,
      debouncedProductSearch.trim() || undefined,
      productQueryLimit,
      'purchase',
    ),
    enabled: productPopupOpen && vendorSelected,
  })

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setDebouncedProductSearch(productSearch.trim())
    }, 180)
    return () => window.clearTimeout(timer)
  }, [productSearch])

  const productWarehouseStocksQuery = useQuery({
    ...createSharedQueries.productWarehouseStocks(stockPreviewProduct?.code),
    enabled: Boolean(stockPreviewProduct?.code),
  })

  const editDetailQuery = useQuery({
    ...apCreditMemoQueries.detailByDocNum(editDocNum),
    enabled: isEditMode && Boolean(editDocNum),
  })

  const isClosed =
    editDetailQuery.data?.data?.DocStatus === 'Closed' ||
    editDetailQuery.data?.data?.DocStatus === 'C'
  const docStatus =
    editDetailQuery.data?.data?.DocStatus === 'O'
      ? 'Open'
      : editDetailQuery.data?.data?.DocStatus === 'C'
        ? 'Closed'
        : (editDetailQuery.data?.data?.DocStatus ?? 'Open')

  useEffect(() => {
    if (isEditMode) return
    resetAPCreditMemoCreate()
    hydratedDocNumRef.current = null
  }, [isEditMode, resetAPCreditMemoCreate])

  useEffect(() => {
    if (!isEditMode) return
    const currentDocNum = editDocNum
    if (!currentDocNum) return
    const detail = editDetailQuery.data?.data
    if (!detail) return

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0
    if (hydratedDocNumRef.current === currentDocNum && isMetadataLoaded) return

    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast('A/P Credit Memo', 'edit')
    }

    void (async () => {
      setVendorCodeInput(String(detail.CardCode ?? '').trim())
      setVendorNameInput(String(detail.CardName ?? '').trim())
      const loadedDocDate = String(detail.DocDate ?? '').slice(0, 10) || getTodayISO()
      const referenceNo = String((detail as { NumAtCard?: string }).NumAtCard ?? '').trim()
      const rawComments = String(detail.Comments ?? '').trim()

      const remarks = rawComments

      const matchedVendor = vendors.find(
        (vendor) => String(vendor.code).trim() === String(detail.CardCode ?? '').trim(),
      )
      const buyerFromDocCode =
        detail.SalesPersonCode !== undefined && detail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(detail.SalesPersonCode),
            )?.name
          : ''

      setBuyerInput(buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || '')
      setHeader({
        docDate: loadedDocDate,
        docDueDate: String(detail.DocDueDate ?? '').slice(0, 10) || loadedDocDate,
        referenceNo,
        remarks,
      })
      setBillToAddress(String(detail.Address ?? '').trim())
      setShipToAddress(String((detail as Record<string, unknown>).Address2 ?? '').trim())

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        (detail.DocumentLines ?? []).map((line: { ItemCode?: string }) =>
          String(line.ItemCode ?? '').trim(),
        ),
        'purchase',
      )

      const mappedLines = (detail.DocumentLines ?? []).map(
        (line: Record<string, unknown>, index: number) => {
          const quantity = Math.max(0, Number(line.Quantity ?? 0))
          const price = Number(line.Price ?? line.UnitPrice ?? 0)
          const grossAmount = Math.max(0, price * quantity)
          const discountPercent = Number(line.DiscountPercent ?? 0)
          const discountAmount = Math.max(0, (grossAmount * discountPercent) / 100)
          const itemCode = String(line.ItemCode ?? '').trim()

          return {
            id: `${currentDocNum}-${index}`,
            productCode: String(line.ItemCode ?? '').trim(),
            productName: String(line.ItemDescription ?? line.ItemCode ?? '').trim(),
            stock: 0,
            currency: String(detail.DocCurr ?? '').trim(),
            vatGroup: String(line.TaxCode ?? '').trim(),
            taxRate:
              (typeof line.VatPrcnt === 'number' ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? '').trim(),
            uomEntry: typeof line.UoMEntry === 'number' ? line.UoMEntry : undefined,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: '',
            returnReason: String((line as Record<string, unknown>).U_ReturnReason ?? '').trim(),
            price,
            warehouseCode: String(line.WarehouseCode ?? '').trim(),
            baseEntry: typeof line.BaseEntry === 'number' ? line.BaseEntry : undefined,
            baseLine: typeof line.BaseLine === 'number' ? line.BaseLine : undefined,
            baseType: typeof line.BaseType === 'number' ? line.BaseType : undefined,
          }
        },
      )
      setLines(mappedLines)
      setProductRowDrafts({})
      setWarehouseInput(String(detail.DocumentLines?.[0]?.WarehouseCode ?? '').trim())

      if (isMetadataLoaded) {
        hydratedDocNumRef.current = currentDocNum
      }
      setHydratedDocNum(currentDocNum)
      loadingToastRef.current?.dismiss()
      loadingToastRef.current = null
    })()
  }, [
    editDocNum,
    editDetailQuery.data,
    isEditMode,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setBillToAddress,
    setShipToAddress,
    vendors,
  ])

  useEffect(() => {
    if (mode !== 'create') return
    const currentSourceDocNum = sourceDocNum
    const currentSourceDocType = sourceDocType
    if (!currentSourceDocNum || !currentSourceDocType) return

    const sourceDocNums = currentSourceDocNum
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
    if (sourceDocNums.length === 0) return

    const isMetadataLoaded = vendors.length > 0 && salesEmployees.length > 0
    const hydrationKey = `${currentSourceDocType}-${currentSourceDocNum}`
    if (hydratedDocNumRef.current === hydrationKey && isMetadataLoaded) return

    if (!loadingToastRef.current) {
      loadingToastRef.current = pageLoadingToast('A/P Credit Memo', 'create')
    }

    const fetchAllSources = async () => {
      type APInvoiceDetailType = {
        CardCode?: string
        CardName?: string
        Comments?: string
        DocCurr?: string
        DocDueDate?: string
        DocEntry?: number
        id?: number
        SalesPersonCode?: number
        Address?: string
        Address2?: string
        DocumentLines?: Array<Record<string, unknown>>
      }

      const details = await Promise.all(
        sourceDocNums.map(async (num) => {
          const res = await queryClient.fetchQuery(apInvoiceQueries.detailByDocNum(num))
          return res.data as APInvoiceDetailType
        }),
      )

      const primaryDetail = details[0]!
      const vendorCode = String(primaryDetail.CardCode ?? '').trim()
      const vendorName = String(primaryDetail.CardName ?? '').trim()
      const matchedVendor = vendors.find((v) => String(v.code).trim() === vendorCode)

      const buyerFromDocCode =
        primaryDetail.SalesPersonCode !== undefined && primaryDetail.SalesPersonCode !== null
          ? salesEmployees.find(
              (item) =>
                normalizeCodeForCompare(item.code) ===
                normalizeCodeForCompare(primaryDetail.SalesPersonCode),
            )?.name
          : ''
      const buyerName = buyerFromDocCode || matchedVendor?.salesEmployeeName?.trim() || ''

      const warehouseCode = String(primaryDetail.DocumentLines?.[0]?.WarehouseCode ?? '').trim()
      const sourceComments = String(primaryDetail.Comments ?? '').trim()

      const refs = sourceDocNums.map((num) =>
        generateSingleSourceReference(currentSourceDocType, num),
      )
      const autoReference = refs.length === 1 ? refs[0]! : refs.join('\n')

      const commentLines = sourceComments
        .split('\n')
        .map((l) => l.trim())
        .filter(Boolean)
      const refLinesFromComments = commentLines.filter((line) => /^based on /i.test(line))

      const userRemarks = commentLines
        .filter((line) => !/^based on /i.test(line))
        .join('\n')
        .trim()
      const remarksParts = [refLinesFromComments.join('\n'), autoReference, userRemarks]
        .filter(Boolean)
        .join('\n')
        .trim()

      const docDueDate = String(primaryDetail.DocDueDate ?? '').slice(0, 10)

      const allDetailLines = details.flatMap(
        (d) => (d.DocumentLines ?? []) as Array<{ ItemCode?: string }>,
      )

      const baseType = 18 // AP Invoice BaseType

      const currency = String(primaryDetail.DocCurr ?? '').trim()

      const taxRateByItemCode = await resolveProductTaxRates(
        queryClient,
        allDetailLines.map((line) => String(line.ItemCode ?? '').trim()),
        'purchase',
      )

      let lineIndex = 0
      const mappedLines = details.flatMap((detail) => {
        const detailLines = (detail.DocumentLines ?? []) as Array<Record<string, unknown>>
        return detailLines.map((line) => {
          const idx = lineIndex++
          const lineData = line as Record<string, unknown>
          const openQty = Number(lineData.OpenQty ?? lineData.OpenQuantity ?? line.Quantity ?? 1)
          const quantity = openQty
          const price = Number(line.Price ?? line.UnitPrice ?? 0)
          const grossAmount = Math.max(0, price * quantity)
          const discountPercent = Number(line.DiscountPercent ?? 0)
          const discountAmount = Math.max(0, (grossAmount * discountPercent) / 100)
          const itemCode = String(line.ItemCode ?? '').trim()

          return {
            id: `row-copy-${detail.DocEntry ?? detail.id ?? 'unknown'}-${idx}`,
            productCode: itemCode,
            productName: String(line.ItemDescription ?? line.ItemCode ?? '').trim(),
            stock: 0,
            currency,
            vatGroup: String(line.TaxCode ?? '').trim(),
            taxRate:
              (typeof line.VatPrcnt === 'number' ? line.VatPrcnt : Number(line.VatPrcnt) || 0) ||
              taxRateByItemCode.get(itemCode) ||
              0,
            uomCode: String(line.UoMCode ?? '').trim(),
            uomEntry: typeof line.UoMEntry === 'number' ? (line.UoMEntry as number) : undefined,
            baseQuantity: quantity,
            quantity,
            discountPercent,
            discountAmount,
            comment: '',
            returnReason: String((line as Record<string, unknown>).U_ReturnReason ?? '').trim(),
            price,
            warehouseCode: String(line.WarehouseCode ?? warehouseCode).trim(),
            baseEntry: detail.DocEntry ?? (detail as { id?: number }).id ?? undefined,
            baseLine: (line.LineNum as number | undefined) ?? idx,
            baseType,
          }
        })
      })

      setVendorCodeInput(vendorCode)
      setVendorNameInput(vendorName)
      setBuyerInput(buyerName)
      setWarehouseInput(warehouseCode)
      setBillToAddress(String(primaryDetail.Address ?? '').trim())
      setShipToAddress(String(primaryDetail.Address2 ?? '').trim())

      setHeader({
        docDate: getTodayISO(),
        docDueDate,
        referenceNo: '',
        remarks: remarksParts,
        referenceAutoFilled: true,
      })
      setLines(mappedLines)
      setProductRowDrafts({})
      if (isMetadataLoaded) {
        hydratedDocNumRef.current = hydrationKey
      }
      loadingToastRef.current?.dismiss()
      loadingToastRef.current = null
    }

    void fetchAllSources()
  }, [
    mode,
    sourceDocNum,
    sourceDocType,
    queryClient,
    salesEmployees,
    setHeader,
    setLines,
    setVendorCodeInput,
    setVendorNameInput,
    setBuyerInput,
    setWarehouseInput,
    setBillToAddress,
    setShipToAddress,
    setProductRowDrafts,
    vendors,
  ])

  const { vendorNameSuggestions, vendorCodeSuggestions, warehouseSuggestions, buyerSuggestions } =
    useAPCreditMemoLookups({
      vendors,
      warehouses,
      buyers: salesEmployees,
      vendorNameInput,
      vendorCodeInput,
      warehouseInput,
      buyerInput,
    })

  const openPopupByMode = (mode: PopupMode) => {
    const searchVal =
      mode === 'vendor-name' || mode === 'vendor-code'
        ? mode === 'vendor-name'
          ? vendorNameInput
          : vendorCodeInput
        : mode === 'warehouse'
          ? warehouseInput
          : buyerInput

    setModalMode(mode)
    setModalSearch(searchVal)
    setModalOpen(true)
  }

  const handleLookupModalSearchSync = (mode: PopupMode, value: string) =>
    syncLookupSearchByMode(mode, value, {
      onVendorName: handleVendorNameChange,
      onVendorCode: handleVendorCodeChange,
      onWarehouse: handleWarehouseInputChange,
      onSalesEmployee: handleBuyerChange,
    })

  useEffect(() => {
    if (!modalOpen) return
    const nextSearch = getLookupInlineSearchByMode(modalMode, {
      vendorName: vendorNameInput,
      vendorCode: vendorCodeInput,
      warehouse: warehouseInput,
      salesEmployee: buyerInput,
    })
    if (nextSearch !== modalSearch) {
      setModalSearch(nextSearch)
    }
  }, [
    buyerInput,
    modalMode,
    modalOpen,
    modalSearch,
    setModalSearch,
    vendorCodeInput,
    vendorNameInput,
    warehouseInput,
  ])

  const selectVendor = (vendor: LookupItem) => {
    if (hasCopiedRows) {
      setPendingVendorChange({ vendor })
      return
    }
    applyVendorChange(vendor)
  }

  const applyVendorChange = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name)
    setVendorCodeInput(vendor.code)
    setBillToAddress(vendor.billToAddress ?? '')
    setShipToAddress(vendor.shipToAddress ?? '')

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ''
        : '')
    setBuyerInput(buyerName)

    setWarehouseInput('')
    setLines([])
    setCreateError(null)
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined, vendorCode: undefined }))
    setVendorNameFocused(false)
    setVendorCodeFocused(false)
  }

  const handleVendorNameChange = (value: string) => {
    setVendorNameInput(value)
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined }))
    if (value.trim() === '') {
      setVendorNameFocused(true)
      setVendorCodeInput('')
      setBuyerInput('')
      setBillToAddress('')
      setShipToAddress('')
      return
    }
    const matched = vendors.find((v) => v.name.trim().toLowerCase() === value.trim().toLowerCase())
    if (matched) {
      setVendorCodeInput(matched.code)
      setBillToAddress(matched.billToAddress ?? '')
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? '')

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ''
          : '')
      setBuyerInput(buyerName)
      setVendorNameFocused(false)
      setVendorCodeFocused(false)
      return
    }
    if (hasCopiedRows) return
    setVendorCodeInput('')
    setBuyerInput('')
    setLines([])
    setVendorNameFocused(true)
  }

  const handleVendorCodeChange = (value: string) => {
    setVendorCodeInput(value)
    setFieldErrors((prev) => ({ ...prev, vendorCode: undefined }))
    if (value.trim() === '') {
      setVendorCodeFocused(true)
      setVendorNameInput('')
      setBuyerInput('')
      setBillToAddress('')
      setShipToAddress('')
      return
    }
    const matched = vendors.find((v) => v.code.trim().toLowerCase() === value.trim().toLowerCase())
    if (matched) {
      if (hasCopiedRows) {
        setPendingVendorChange({ vendor: matched })
        return
      }
      setVendorNameInput(matched.name)
      setBillToAddress(matched.billToAddress ?? '')
      setShipToAddress(matched.shipToAddress ?? matched.billToAddress ?? '')

      const buyerName =
        matched.salesEmployeeName?.trim() ||
        (matched.salesEmployeeCode
          ? salesEmployees
              .find(
                (s) =>
                  normalizeCodeForCompare(s.code) ===
                  normalizeCodeForCompare(matched.salesEmployeeCode),
              )
              ?.name?.trim() || ''
          : '')
      setBuyerInput(buyerName)
      setVendorNameFocused(false)
      setVendorCodeFocused(false)
      return
    }
    if (hasCopiedRows) return
    setVendorNameInput('')
    setBuyerInput('')
    setLines([])
    setVendorCodeFocused(true)
  }

  const confirmVendorChange = () => {
    const pending = pendingVendorChange
    if (!pending) return
    setPendingVendorChange(null)

    const cleanedRemarks = stripAutoGeneratedReferences(header.remarks)
    setHeader({ remarks: cleanedRemarks })

    setLines((prev) =>
      prev.map((row) => {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        const { baseEntry, baseLine, baseType, baseQuantity, ...rest } = row
        return rest
      }),
    )

    applyVendorChangeForConfirmation(pending.vendor)
  }

  const cancelVendorChange = () => {
    setPendingVendorChange(null)
  }

  const applyVendorChangeForConfirmation = (vendor: LookupItem) => {
    setVendorNameInput(vendor.name)
    setVendorCodeInput(vendor.code)
    setBillToAddress(vendor.billToAddress ?? '')
    setShipToAddress(vendor.shipToAddress ?? '')
    setVendorNameFocused(false)
    setVendorCodeFocused(false)

    const buyerName =
      vendor.salesEmployeeName?.trim() ||
      (vendor.salesEmployeeCode
        ? salesEmployees
            .find(
              (s) =>
                normalizeCodeForCompare(s.code) ===
                normalizeCodeForCompare(vendor.salesEmployeeCode),
            )
            ?.name?.trim() || ''
        : '')
    setBuyerInput(buyerName)
    setCreateError(null)
    setFieldErrors((prev) => ({ ...prev, vendorName: undefined, vendorCode: undefined }))
  }

  const handleWarehouseInputChange = (value: string) => {
    setWarehouseInput(value)
    setFieldErrors((prev) => ({ ...prev, warehouseCode: undefined }))
    const matched = warehouses.find(
      (w) =>
        w.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        w.code.trim().toLowerCase() === value.trim().toLowerCase(),
    )
    if (matched) {
      setLines((prev) => prev.map((row) => ({ ...row, warehouseCode: matched.code })))
      setWarehouseFocused(false)
    }
  }

  const handleBuyerChange = (value: string) => {
    setBuyerInput(value)
    setFieldErrors((prev) => ({ ...prev, salesEmployee: undefined }))
    const matched = salesEmployees.find(
      (s) =>
        s.name.trim().toLowerCase() === value.trim().toLowerCase() ||
        s.code.trim().toLowerCase() === value.trim().toLowerCase(),
    )
    if (matched) {
      setBuyerFocused(false)
    }
  }

  const openProductPopup = (rowId: string | null = null) => {
    setActiveProductRowId(rowId)
    if (!vendorNameInput.trim() || !vendorCodeInput.trim()) {
      setFieldErrors((prev) => ({
        ...prev,
        vendorName: !vendorNameInput.trim()
          ? AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorName
          : undefined,
        vendorCode: !vendorCodeInput.trim()
          ? AP_CREDIT_MEMO_FIELD_ERROR_TEXT.vendorCode
          : undefined,
      }))
      return
    }

    setProductPopupOpen(true)
  }

  const selectWarehouse = (warehouse: LookupItem) => {
    setWarehouseInput(warehouse.name)
    setLines((prev) => prev.map((row) => ({ ...row, warehouseCode: warehouse.code })))
    setWarehouseFocused(false)
  }

  const selectBuyer = (item: LookupItem) => {
    setBuyerInput(item.name)
    setBuyerFocused(false)
  }

  const applyProductToRow = (product: ProductLookupItem) => {
    const existingCodes = new Set(rows.map((r) => r.productCode))

    if (activeProductRowId) {
      const duplicateRow = rows.find(
        (r) => r.id !== activeProductRowId && r.productCode === product.code,
      )
      if (duplicateRow) {
        goeyToast.error('Duplicate product already exists', {
          id: 'ap-credit-memo-duplicate-product',
        })
        return
      }
    } else {
      if (existingCodes.has(product.code)) {
        goeyToast.error('Duplicate product already exists', {
          id: 'ap-credit-memo-duplicate-product',
        })
        return
      }
    }

    setLines((prev) => {
      if (activeProductRowId) {
        return prev.map((row) =>
          row.id === activeProductRowId
            ? {
                ...row,
                productCode: product.code,
                productName: product.name,
                stock: Number(product.stock ?? 0),
                price: Number(product.price ?? 0),
                warehouseCode: effectiveWarehouseCode || '',
                uomCode: String(product.purchaseUomCode ?? product.uomCode ?? '').trim(),
                uomEntry: product.purchaseUomEntry ?? product.uomEntry,
                quantity: 1,
              }
            : row,
        )
      }
      return [
        ...prev,
        {
          id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          productCode: product.code,
          productName: product.name,
          stock: Number(product.stock ?? 0),
          currency: String(product.currency ?? ''),
          vatGroup: String(product.vatGroup ?? ''),
          taxRate: Number(product.taxRate ?? 0),
          uomCode: String(product.purchaseUomCode ?? product.uomCode ?? '').trim(),
          uomEntry: product.purchaseUomEntry ?? product.uomEntry,
          quantity: 1,
          discountPercent: 0,
          discountAmount: 0,
          comment: '',
          price: Number(product.price ?? 0),
          warehouseCode: effectiveWarehouseCode || '',
        },
      ]
    })
    setProductPopupOpen(false)
    setProductSearch('')
  }

  const applyProductsToRows = (products: ProductLookupItem[]) => {
    const existingCodes = new Set(rows.map((r) => r.productCode))

    const freshProducts = products.filter((p) => {
      if (existingCodes.has(p.code)) {
        goeyToast.error('Duplicate product already exists', {
          id: 'ap-credit-memo-duplicate-product',
        })
        return false
      }
      existingCodes.add(p.code)
      return true
    })

    if (freshProducts.length === 0) {
      setProductPopupOpen(false)
      setProductSearch('')
      return
    }

    setLines((prev) => [
      ...prev,
      ...freshProducts.map((product) => ({
        id: `row-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        productCode: product.code,
        productName: product.name,
        stock: Number(product.stock ?? 0),
        currency: String(product.currency ?? ''),
        vatGroup: String(product.vatGroup ?? ''),
        taxRate: Number(product.taxRate ?? 0),
        uomCode: String(product.purchaseUomCode ?? product.uomCode ?? '').trim(),
        uomEntry: product.purchaseUomEntry ?? product.uomEntry,
        quantity: 1,
        discountPercent: 0,
        discountAmount: 0,
        comment: '',
        price: Number(product.price ?? 0),
        warehouseCode: effectiveWarehouseCode || '',
      })),
    ])
    setProductPopupOpen(false)
    setProductSearch('')
  }

  const handleCreateAPCreditMemo = async () => {
    const filteredRows = rows.filter((r) => r.quantity > 0)

    if (!isEditMode) {
      const rowsMissingReturnReason = filteredRows.filter((r) => !r.returnReason?.trim())
      if (rowsMissingReturnReason.length > 0) {
        const nextErrors = { ...EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS }
        nextErrors.returnReason = AP_CREDIT_MEMO_FIELD_ERROR_TEXT.returnReason
        setFieldErrors(nextErrors)
        const missingItemCodes = rowsMissingReturnReason.map((r) => r.productCode || '<unknown>')
        setCreateError(`Return reason is required for: ${missingItemCodes.join(', ')}`)
        return
      }

      const missing = AP_CREDIT_MEMO_MANDATORY_FIELDS.filter((field) => {
        if (field === 'vendorName') return !vendorNameInput.trim()
        if (field === 'vendorCode') return !vendorCodeInput.trim()
        if (field === 'warehouseCode') {
          return !rows.some((row) => row.warehouseCode?.trim())
        }
        if (field === 'returnReason') {
          const filteredRows = rows.filter((r) => r.quantity > 0)
          return filteredRows.some((r) => !r.returnReason?.trim())
        }
        return false
      })

      if (missing.length > 0) {
        const nextErrors = { ...EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS }
        missing.forEach((field) => {
          nextErrors[field] = AP_CREDIT_MEMO_FIELD_ERROR_TEXT[field]
        })
        setFieldErrors(nextErrors)
        setCreateError('Fill required fields before creating A/P Credit Memo.')
        return
      }
    }

    if (filteredRows.length === 0) {
      setCreateError('Set at least one line quantity greater than 0.')
      return
    }

    const linesMissingWarehouse = filteredRows.filter((row) => !row.warehouseCode.trim())
    if (linesMissingWarehouse.length > 0) {
      const missingItemCodes = linesMissingWarehouse.map((row) => row.productCode || '<unknown>')
      setCreateError(`Warehouse is required for: ${missingItemCodes.join(', ')}`)
      return
    }

    const toastHandle = documentActionToast('A/P Credit Memo', isEditMode ? 'update' : 'create')
    try {
      if (isEditMode) {
        const id = editDetailQuery.data?.data?.id ?? editDetailQuery.data?.data?.DocEntry
        const updatePayload: UpdateAPCreditMemoInput = {
          DocDueDate: header.docDueDate || undefined,
          Comments: header.remarks.trim() || undefined,
          NumAtCard: header.referenceNo.trim() || undefined,
        }

        await updateMutation.mutateAsync({ id: id!, payload: updatePayload })

        toastHandle.success(editDetailQuery.data?.data?.DocNum)
      } else {
        const buildDocumentLines = (): CreateAPCreditMemoInput['DocumentLines'] => {
          const lines: CreateAPCreditMemoInput['DocumentLines'] = []
          for (const row of filteredRows) {
            if (row.quantity <= 0) continue

            const hasCompleteBaseLink =
              Number.isFinite(row.baseEntry) &&
              Number.isFinite(row.baseLine) &&
              Number.isFinite(row.baseType)

            const baseLine: CreateAPCreditMemoInput['DocumentLines'][0] = {
              ItemCode: row.productCode,
              Quantity: row.quantity,
              UnitPrice: row.price,
              DiscountPercent: row.discountPercent,
              ...(row.uomCode ? { UoMCode: row.uomCode } : {}),
              ...(row.warehouseCode ? { WarehouseCode: row.warehouseCode } : {}),
              ...(row.vatGroup ? { VatGroup: row.vatGroup } : {}),
              ...(row.returnReason ? { U_ReturnReason: row.returnReason } : {}),
            }

            if (!hasCompleteBaseLink) {
              lines.push(baseLine)
              continue
            }

            const baseQty = row.baseQuantity ?? 0
            const linkedQty = Math.min(row.quantity, baseQty)

            if (linkedQty > 0) {
              lines.push({
                ...baseLine,
                Quantity: linkedQty,
                ...(row.baseType !== undefined ? { BaseType: row.baseType } : {}),
                ...(row.baseEntry !== undefined ? { BaseEntry: row.baseEntry } : {}),
                ...(row.baseLine !== undefined ? { BaseLine: row.baseLine } : {}),
              })
            }

            const excessQty = row.quantity - baseQty
            if (excessQty > 0) {
              lines.push({
                ...baseLine,
                Quantity: excessQty,
              })
            }
          }
          return lines
        }

        const createPayload: CreateAPCreditMemoInput = {
          CardCode: vendorCodeInput.trim(),
          ...(header.docDate ? { DocDate: header.docDate } : {}),
          ...(header.docDueDate ? { DocDueDate: header.docDueDate } : {}),
          ...(header.remarks.trim() ? { Comments: header.remarks.trim() } : {}),
          DocumentLines: buildDocumentLines(),
        }
        const result = await createMutation.mutateAsync({ payload: createPayload })
        const createdDocNum = result?.data?.DocNum

        if (sourceDocNum && sourceDocType) {
          void queryClient.invalidateQueries({
            queryKey: apInvoiceQueries.list({ page: 1, limit: 10 }).queryKey,
          })

          if (sourceDocType === 'APInvoice') {
            sourceDocNum.split(',').forEach((num) => {
              const trimmed = num.trim()
              if (trimmed) {
                void queryClient.invalidateQueries({
                  queryKey: apInvoiceQueries.detailByDocNum(trimmed).queryKey,
                })
              }
            })
          }
        }

        toastHandle.success(createdDocNum)
      }

      if (!isEditMode) {
        resetAPCreditMemoCreate()
        setVendorNameInput('')
        setVendorCodeInput('')
        setBuyerInput('')
        setWarehouseInput('')
        setBillToAddress('')
        setShipToAddress('')
        setVendorNameFocused(false)
        setVendorCodeFocused(false)
        setBuyerFocused(false)
        setWarehouseFocused(false)
        setActiveDatePicker(null)
        setModalOpen(false)
        setModalMode('vendor-name')
        setModalSearch('')
        setProductSearch('')
        setDebouncedProductSearch('')
        setActiveProductRowId(null)
        setProductPopupOpen(false)
        setProductRowDrafts({})
        setStockPreviewProduct(null)
        setFieldErrors(EMPTY_AP_CREDIT_MEMO_FIELD_ERRORS)
        setCreateError(null)
        hydratedDocNumRef.current = null
        setHydratedDocNum(null)
      }

      window.scrollTo({ top: 0, behavior: 'smooth' })

      if (!isEditMode) {
        onCreateSuccess?.()
      }
    } catch (error) {
      toastHandle.error()
      const errorMsg = normalizeCreateOrderErrorMessage(error, 'Failed to process A/P Credit Memo.')
      setCreateError(errorMsg)
    }
  }

  const missingMandatoryFields = useMemo(() => {
    if (isEditMode) return []
    return AP_CREDIT_MEMO_MANDATORY_FIELDS.filter((field) => {
      if (field === 'vendorName') return !vendorNameInput.trim()
      if (field === 'vendorCode') return !vendorCodeInput.trim()
      if (field === 'warehouseCode') {
        return !rows.some((row) => row.warehouseCode?.trim())
      }
      if (field === 'returnReason') {
        const filteredRows = rows.filter((r) => r.quantity > 0)
        return filteredRows.length === 0 || filteredRows.some((r) => !r.returnReason?.trim())
      }
      return false
    })
  }, [isEditMode, vendorNameInput, vendorCodeInput, rows])

  const requiredCompletionPercent = useMemo(
    () =>
      ((AP_CREDIT_MEMO_MANDATORY_FIELDS.length - missingMandatoryFields.length) /
        AP_CREDIT_MEMO_MANDATORY_FIELDS.length) *
      100,
    [missingMandatoryFields],
  )

  return {
    isEditMode,
    isEditHydrated: !isEditMode || hydratedDocNum === editDocNum,
    isSourceHydrating: mode === 'create' && Boolean(sourceDocNum) && !hydratedDocNumRef.current,
    today,
    activeDatePicker,
    setActiveDatePicker,
    docDateContainerRef,
    deliveryDateContainerRef,
    handleDocDateChange: (val: string) => setHeader({ docDate: val }),
    handleDocDueDateChange: (val: string) => setHeader({ docDueDate: val }),
    showEditRestrictedToast: notifyRestricted,

    vendorsQuery,
    warehousesQuery,
    salesEmployeesQuery,
    productsQuery,
    productWarehouseStocksQuery,
    editDetailQuery,
    createMutation,
    updateMutation,

    vendorNameSuggestions,
    vendorCodeSuggestions,
    warehouseSuggestions,
    buyerSuggestions,
    vendors,
    warehouses,
    salesEmployees,

    vendorNameInput,
    vendorCodeInput,
    warehouseInput,
    buyerInput,
    vendorNameFocused,
    setVendorNameFocused,
    vendorCodeFocused,
    setVendorCodeFocused,
    buyerFocused,
    setBuyerFocused,
    warehouseFocused,
    setWarehouseFocused,
    docDate: header.docDate,
    docDueDate: header.docDueDate,
    referenceNo: header.referenceNo,
    referenceAutoFilled: header.referenceAutoFilled,
    remarks: header.remarks,
    billToAddress,
    shipToAddress,
    isClosed,
    docStatus,
    products: productsQuery.data ?? [],

    modalOpen,
    modalMode,
    modalSearch,
    setModalOpen,
    setModalSearch,
    openPopup: openPopupByMode,
    handleLookupModalSearchSync,
    popupResults: useMemo(
      () =>
        filterAndRankLookups(
          modalMode.includes('vendor')
            ? vendors
            : modalMode === 'warehouse'
              ? warehouses
              : salesEmployees,
          modalSearch,
        ),
      [vendors, warehouses, salesEmployees, modalSearch, modalMode],
    ),

    productPopupOpen,
    productSearch,
    setProductPopupOpen,
    setProductSearch,
    activeProductRowId,
    openProductPopup,
    loadMoreProducts: () => setProductQueryLimit((prev) => Math.min(prev + 10, FULL_PRODUCT_LIMIT)),
    applyProductToRow,
    applyProductsToRows,
    existingProductCodes: useMemo(() => new Set(rows.map((r) => r.productCode)), [rows]),
    onBlockDuplicate: () => {
      goeyToast.error('Duplicate product already exists', {
        id: 'ap-credit-memo-duplicate-product',
      })
    },
    prefetchProducts: () => {},
    activeRowProductCode: (() => {
      if (!activeProductRowId) return null
      const activeRow = rows.find((r) => r.id === activeProductRowId)
      return activeRow?.productCode ?? null
    })(),
    isLookupLoading: modalMode.includes('vendor')
      ? vendorsQuery.isLoading
      : modalMode === 'warehouse'
        ? warehousesQuery.isLoading
        : salesEmployeesQuery.isLoading,
    lookupError:
      (modalMode.includes('vendor')
        ? vendorsQuery.error
        : modalMode === 'warehouse'
          ? warehousesQuery.error
          : salesEmployeesQuery.error
      )?.message ?? null,
    isProductsLoading: productsQuery.isLoading,
    productsError: productsQuery.error?.message ?? null,
    warehouseCode: effectiveWarehouseCode,

    rows,
    productRowDrafts,
    setProductRowDraft: (id: string, field: string, value: string) =>
      setProductRowDrafts((prev) => ({ ...prev, [id]: { ...prev[id], [field]: value } })),
    clearProductRowDraft: (id: string, field: string) =>
      setProductRowDrafts((prev) => {
        const next = { ...prev[id] }
        delete next[field as keyof typeof next]
        return { ...prev, [id]: next }
      }),
    updateProductRow: (id: string, patch: Partial<APCreditMemoCreateLine>) =>
      setLines((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r))),
    removeProductRow: (id: string) => setLines((prev) => prev.filter((r) => r.id !== id)),

    stockPreviewProduct,
    setStockPreviewProduct,
    openStockPreview: setStockPreviewProduct,

    fieldErrors,
    createError,
    createDisabledReason:
      missingMandatoryFields.length > 0
        ? 'Mandatory fields missing'
        : rows.length === 0
          ? 'No lines'
          : null,
    searchMandatoryFields: useMemo(() => ['vendorName', 'vendorCode'] as const, []),
    missingSearchMandatoryFields: useMemo(
      () =>
        ['vendorName', 'vendorCode'].filter(
          (field) =>
            !String(field === 'vendorName' ? vendorNameInput : (vendorCodeInput ?? '')).trim(),
        ),
      [vendorNameInput, vendorCodeInput],
    ),
    searchRequiredCompletionPercent: useMemo(() => {
      const filled = (vendorNameInput.trim() ? 1 : 0) + (vendorCodeInput.trim() ? 1 : 0)
      return (filled / 2) * 100
    }, [vendorNameInput, vendorCodeInput]),
    missingMandatoryFields,
    requiredCompletionPercent,
    requiredFieldsTotal: AP_CREDIT_MEMO_MANDATORY_FIELDS.length,
    requiredFieldLabelText: AP_CREDIT_MEMO_FIELD_LABEL_TEXT,
    handleCreateOrder: handleCreateAPCreditMemo,

    setDocDate: (val: string) => setHeader({ docDate: val }),
    setDocDueDate: (val: string) => setHeader({ docDueDate: val }),
    setBuyerInput: (val: string) =>
      isEditMode ? notifyRestricted('Buyer') : handleBuyerChange(val),
    setWarehouseInput: (val: string) =>
      isEditMode ? notifyRestricted('Warehouse') : handleWarehouseInputChange(val),
    setReferenceNo: (val: string) => setHeader({ referenceNo: val }),
    setRemarks: (val: string) => setHeader({ remarks: val }),
    setBillToAddress: (val: string) =>
      isEditMode ? notifyRestricted('Bill To Address') : setBillToAddress(val),
    setShipToAddress: (val: string) =>
      isEditMode ? notifyRestricted('Ship To Address') : setShipToAddress(val),
    selectVendor: (val: LookupItem) =>
      isEditMode ? notifyRestricted('Vendor') : selectVendor(val),
    selectWarehouse: (val: LookupItem) =>
      isEditMode ? notifyRestricted('Warehouse') : selectWarehouse(val),
    selectSalesEmployee: (val: LookupItem) =>
      isEditMode ? notifyRestricted('Sales Employee') : selectBuyer(val),
    handleVendorNameChange: (val: string) =>
      isEditMode ? notifyRestricted('Vendor Name') : handleVendorNameChange(val),
    handleVendorCodeChange: (val: string) =>
      isEditMode ? notifyRestricted('Vendor Code') : handleVendorCodeChange(val),

    pendingVendorChange,
    hasCopiedRows,
    confirmVendorChange,
    cancelVendorChange,
  }
}
