// PDF generator: Styled A4 .pdf with brand header, address, table, totals, and attachments.

import PDFDocument from "pdfkit";
import type { ExportDocumentData } from "./types";

const ACCENT = "#1F4E79";
const LIGHT_GRAY = "#F2F7FB";
const DARK = "#333333";

export const generatePdf = async (data: ExportDocumentData): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Brand header bar
    doc.rect(0, 0, doc.page.width, 50).fill(ACCENT);
    doc
      .fillColor("#FFFFFF")
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("VENDOR PORTAL", 50, 14, { align: "center", width: doc.page.width - 100 });

    // Title
    doc
      .fillColor(DARK)
      .fontSize(16)
      .font("Helvetica-Bold")
      .text(`${data.title} #${data.docNum}`, 50, 70, { align: "center" });

    // Status badge
    const statusY = 95;
    doc
      .rect(450, statusY, 100, 18)
      .fill(data.docStatus === "Open" ? "#E8F5E9" : "#FFF3E0")
      .stroke("#D0D0D0");
    doc
      .fillColor(DARK)
      .fontSize(10)
      .font("Helvetica")
      .text(`Status: ${data.docStatus}`, 455, statusY + 3, { width: 90, align: "center" });

    // Address block
    const addrY = 80;
    doc.fontSize(10).font("Helvetica-Bold").text("Vendor:", 50, addrY);
    doc.font("Helvetica").text(`${data.cardCode} - ${data.cardName}`, 50, addrY + 14);
    if (data.address) doc.text(data.address, 50, addrY + 28);

    doc.fontSize(10).font("Helvetica-Bold").text("Date:", 350, addrY);
    doc.font("Helvetica").text(data.docDate, 350, addrY + 14);
    if (data.docDueDate) {
      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text("Due:", 350, addrY + 28);
      doc.font("Helvetica").text(data.docDueDate, 350, addrY + 42);
    }

    // Table header
    const tableTop = 180;
    const colWidths = [30, 70, 140, 50, 40, 60, 70, 50];
    const headers = ["#", "Item Code", "Description", "Qty", "UOM", "Price", "Total", "Whs"];
    let x = 50;
    doc.rect(50, tableTop, 495, 20).fill(ACCENT);
    doc.fillColor("#FFFFFF").fontSize(9).font("Helvetica-Bold");
    headers.forEach((h, i) => {
      doc.text(h, x + 2, tableTop + 4, {
        width: colWidths[i] - 4,
        align: i >= 3 ? "right" : "left",
      });
      x += colWidths[i];
    });

    // Table rows
    const rowHeight = 18;
    let y = tableTop + 20;
    data.lines.forEach((line, i) => {
      if (y + rowHeight > doc.page.height - 80) {
        doc.addPage();
        y = 50;
        // Repeat header on new page
        doc.rect(50, y, 495, 20).fill(ACCENT);
        doc.fillColor("#FFFFFF").fontSize(9).font("Helvetica-Bold");
        x = 50;
        headers.forEach((h, j) => {
          doc.text(h, x + 2, y + 4, { width: colWidths[j] - 4, align: j >= 3 ? "right" : "left" });
          x += colWidths[j];
        });
        y += 20;
      }

      if (i % 2 === 1) doc.rect(50, y, 495, rowHeight).fill(LIGHT_GRAY);
      doc.fillColor(DARK).fontSize(8).font("Helvetica");
      const vals = [
        line.lineNum,
        line.itemCode,
        line.itemDescription,
        line.quantity,
        line.uom,
        line.price,
        line.total,
        line.warehouse,
      ];
      x = 50;
      vals.forEach((v, j) => {
        doc.text(String(v), x + 2, y + 3, {
          width: colWidths[j] - 4,
          align: j >= 3 ? "right" : "left",
        });
        x += colWidths[j];
      });
      y += rowHeight;
    });

    // Totals
    y += 6;
    doc.rect(300, y, 245, 22).fill("#E8EEF4");
    doc.fillColor(DARK).fontSize(11).font("Helvetica-Bold");
    doc.text(`Total (${data.docCurrency}):`, 305, y + 4, { width: 160, align: "right" });
    doc.text(String(data.docTotal), 470, y + 4, { width: 70, align: "right" });
    y += 30;

    // Comments
    if (data.comments) {
      doc.fontSize(10).font("Helvetica-Bold").text("Comments:", 50, y);
      doc
        .font("Helvetica")
        .fontSize(9)
        .fillColor("#666666")
        .text(data.comments, 50, y + 14);
      y += 36;
    }

    // Attachments
    if (data.attachments.length > 0) {
      y += 6;
      doc.fontSize(10).font("Helvetica-Bold").fillColor(DARK).text("Attachments:", 50, y);
      y += 14;
      data.attachments.forEach((a) => {
        doc
          .fontSize(9)
          .font("Helvetica")
          .fillColor("#333333")
          .text(
            `  • ${a.fileName}.${a.fileExtension}${a.freeText ? ` — ${a.freeText}` : ""}`,
            50,
            y,
          );
        y += 14;
      });
    }

    // Footer
    const footerY = doc.page.height - 30;
    doc
      .fontSize(8)
      .font("Helvetica")
      .fillColor("#999999")
      .text(
        `Generated by Vendor Portal | ${new Date().toLocaleDateString()} | Page 1`,
        50,
        footerY,
        { align: "center", width: doc.page.width - 100 },
      );

    doc.end();
  });
};
